import * as XLSX from 'xlsx';
import type { ExpenseVarianceRow } from './expense-variance-data';
import type { DigestAttachment } from './portal-digest-attachments';
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money = (n: number | null) => n == null ? 'Pending' : '₹'+n.toLocaleString('en-IN',{maximumFractionDigits:2});
export function adHocCostMail(rows: ExpenseVarianceRow[], date: string) {
 const valid=rows.filter(r=>!r.excluded),day=valid.filter(r=>r.date===date);
 const summarize=(items:ExpenseVarianceRow[])=>{const matched=items.filter(r=>r.estimated!=null&&r.actual!=null);return {count:items.length,compared:matched.length,estimate:matched.length?matched.reduce((s,r)=>s+r.estimated!,0):null,actual:matched.length?matched.reduce((s,r)=>s+r.actual!,0):null,difference:matched.length?matched.reduce((s,r)=>s+(r.delta??0),0):null,pending:items.filter(r=>r.actual==null).length,over:items.filter(r=>r.overrun).length};};
 const daily=summarize(day),mtd=summarize(valid);
 const periods=[{label:'Report day',...daily},{label:'MTD',...mtd}];
 const html=`<h3 style="font-size:16px;margin:22px 0 8px;color:#173b45">Estimated vs actual</h3><table width="100%" style="border-collapse:collapse;font-size:12px"><tr>${['Period','Compared','Estimate','Actual','Difference','Actual pending'].map(h=>`<th style="padding:7px;text-align:left;background:#e9f7f4;color:#173b45">${h}</th>`).join('')}</tr>${periods.map(p=>`<tr>${[p.label,`${p.compared}/${p.count}`,p.estimate==null?'—':money(p.estimate),p.actual==null?'—':money(p.actual),p.difference==null?'—':money(p.difference),String(p.pending)].map(v=>`<td style="padding:8px 7px;border-bottom:1px solid #e5e7eb">${escape(v)}</td>`).join('')}</tr>`).join('')}</table><p style="font-size:12px;color:${mtd.over?'#b4233e':'#52656d'};margin:8px 0"><b>${daily.over} report-day / ${mtd.over} MTD requests over estimate</b></p><p style="font-size:11px;color:#64748b;margin:6px 0">Compared = requests with both amounts; pending actuals are excluded from comparison. Latest saved MTD values include late updates. Excel has station-wise, day-level detail. Actual means submitted, not paid.</p>`;
 const workbook=XLSX.utils.book_new();
 const exported=valid.map(r=>({Date:r.date,Station:r.station,Reference:r.reference,'Payment head':r.head,Status:r.status,'Estimate INR':r.estimated,'Actual submitted INR':r.actual,'Variance INR':r.delta,'Variance %':r.percent==null?null:Number(r.percent.toFixed(2)),Attention:r.state,'Estimated shipments':r.shipments,'Estimated CPS':r.cps==null?null:Number(r.cps.toFixed(2))}));
 XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(exported.length?exported:[{Information:'No expense request comparisons in scope.'}]),'Estimated vs Actual');
 const dailyGroups=new Map<string,ExpenseVarianceRow[]>();
 for(const row of valid){const key=JSON.stringify([row.date,row.station,row.head]);dailyGroups.set(key,[...(dailyGroups.get(key)||[]),row]);}
 const dayRows=[...dailyGroups.values()].map(items=>{const totals=summarize(items);return {Date:items[0].date,Station:items[0].station,'Payment head':items[0].head,Requests:totals.count,'Actuals pending':totals.pending,'Compared requests':totals.compared,'Comparable estimate INR':totals.estimate,'Actual submitted INR':totals.actual,'Difference INR':totals.difference,'Over estimate requests':totals.over};});
 XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet(dayRows.length?dayRows:[{Information:'No daily comparisons.'}]),'Station daily summary');
 XLSX.utils.book_append_sheet(workbook,XLSX.utils.json_to_sheet([{ReportDate:date,Basis:'Deployment/work date; monthly through report date.',Actual:'Submitted cost, not bank settlement. Blank means pending.',Estimate:'Saved expense estimate; legacy edits may have changed historical estimates.',CPS:'Request amount / entered request shipments, not station inbound.'}]),'Read me');
 const attachments: DigestAttachment[]=[{filename:`DropX-Adhoc-Comparison-${date}.xlsx`,contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',encoding:'base64',content:XLSX.write(workbook,{type:'buffer',bookType:'xlsx'}).toString('base64')}];
 return {html,text:`Estimated vs actual · ${date}\n${periods.map(p=>`${p.label}: ${p.compared}/${p.count} compared; estimate ${money(p.estimate)}, actual ${money(p.actual)}, difference ${money(p.difference)}; ${p.pending} actuals pending; ${p.over} over estimate`).join("\n")}\nLatest MTD includes late updates. Station-wise daily comparisons attached.`,attachments};
}
