export const allPeopleExportColumns = [
  { key: "dropxId", label: "DropX ID" },
  { key: "biometricId", label: "Biometric ID" },
  { key: "fullName", label: "Full name" },
  { key: "category", label: "Category" },
  { key: "mobileCountryCode", label: "Mobile country code" },
  { key: "mobileNumber", label: "Mobile number" },
  { key: "email", label: "Email" },
  { key: "dateOfJoin", label: "Date of join" },
  { key: "location", label: "Location" },
  { key: "model", label: "Model" },
  { key: "provider", label: "Provider" },
  { key: "designation", label: "Designation" },
  { key: "status", label: "Status" },
  { key: "active", label: "Active" },
  { key: "statutoryApplicability", label: "Statutory applicability" },
  { key: "gender", label: "Gender" },
  { key: "dateOfBirth", label: "Date of birth" },
  { key: "aadhaarNumber", label: "Aadhaar number" },
  { key: "panNumber", label: "PAN number" },
  { key: "eshramUan", label: "eShram UAN" },
  { key: "fatherName", label: "Father name" },
  { key: "bloodGroup", label: "Blood group" },
  { key: "handicapped", label: "Handicapped" },
  { key: "address", label: "Address" },
  { key: "stateCode", label: "State code" },
  { key: "pincode", label: "Pincode" },
  { key: "landmark", label: "Landmark" },
  { key: "bankAccountNumber", label: "Bank account number" },
  { key: "ifsc", label: "IFSC" },
  { key: "pfUan", label: "PF UAN" },
  { key: "pfAccountNumber", label: "PF account number" },
  { key: "esiNumber", label: "ESI number" },
  { key: "emergencyContactNumber", label: "Emergency contact number" },
  { key: "emergencyContactName", label: "Emergency contact name" },
  { key: "emergencyContactRelation", label: "Emergency contact relation" },
  { key: "drivingLicenseNumber", label: "Driving license number" },
  { key: "drivingLicenseExpiry", label: "Driving license expiry" },
  { key: "vehicleRegistrationNumber", label: "Vehicle registration number" },
  { key: "vehicleRegistrationExpiry", label: "Vehicle registration expiry" },
  { key: "vehicleInsuranceExpiry", label: "Vehicle insurance expiry" },
  { key: "pollutionExpiry", label: "Pollution expiry" },
  { key: "aadhaarFrontFile", label: "Aadhaar front file" },
  { key: "aadhaarBackFile", label: "Aadhaar back file" },
  { key: "panFile", label: "PAN file" },
  { key: "drivingLicenseFrontFile", label: "Driving license front file" },
  { key: "drivingLicenseBackFile", label: "Driving license back file" },
  { key: "profilePhotoFile", label: "Profile photo file" },
  { key: "returnRemarks", label: "Return remarks" },
  { key: "createdAt", label: "Created at" },
  { key: "updatedAt", label: "Updated at" }
] as const;

export type AllPeopleExportKey = (typeof allPeopleExportColumns)[number]["key"];
export type AllPeopleExportValues = Record<AllPeopleExportKey, string>;
