import type {DigestBuilder,DigestMessage} from './portal-digest-delivery';
import {loadCodPendingReport} from './ops-pulse/cod-pending-data';
import {loadCodAgeing} from './ops-pulse/cod-ageing-data';
import {ageingBands,type CodAgeingSnapshot} from './ops-pulse/cod-ageing';
import type {CodPendingRow} from './ops-pulse/cod-pending';
import {loadCodMailRecipients,type CodMailRecipient} from './cod-pending-mail-scope';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number|null)=>v===null?'Not available':new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
export function buildCodDigestMessages(rows:CodPendingRow[],source:CodAgeingSnapshot,recipients:CodMailRecipient[],date:string,slot:string,subjectTemplate:string):DigestMessage[]{
 const month=new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'long',timeZone:'Asia/Kolkata'});
 const subject=subjectTemplate.replace(/\{\{month\}\}/g,month).replace(/\{\{year\}\}/g,date.slice(0,4));
 if(!subject||/[\r\n]/.test(subject))throw new Error('Invalid COD reminder subject.');
 return recipients.flatMap(recipient=>{
  const allowed=rows.filter(r=>recipient.stationIds.includes(r.station.id));const pending=allowed.filter(r=>r.pending);const includeAgeing=allowed.some(r=>r.client==='amazon');
  const ageing=source.stations.filter(s=>allowed.some(r=>r.station.station_code===s.stationCode)&&s.total>0);
  if(!pending.length&&!ageing.some(s=>s.overTwo>0)&&!(source.error&&includeAgeing))return [];
  const headers=['Station','Slip status','Deposited ₹','Short ₹'];
  const body=pending.map(r=>[r.station.station_code,r.status,money(r.amount),r.short?money(r.short):r.status==='Short'?'Amount unavailable':'—']);
  const table=(columns:string[],data:(string|number)[][])=>`<table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr>${columns.map(c=>`<th style="padding:9px;border:1px solid #d1d9df;background:#e5efd9;text-align:left">${esc(c)}</th>`).join('')}</tr></thead><tbody>${data.map(cells=>`<tr>${cells.map((c,i)=>`<td style="padding:8px;border:1px solid #d1d9df;${i>1?'text-align:right;':''}">${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const totals=Object.fromEntries(ageingBands.map(b=>[b,ageing.reduce((n,r)=>n+(r.bands[b]||0),0)]));
  const ageingTable=!includeAgeing?'<p>EDSP outstanding cash applies to Amazon stations; none are in this recipient’s scope.</p>':source.error?`<p style="color:#b45309">${esc(source.error)}</p>`:`<table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr>${['Station',...ageingBands,'Grand total'].map(c=>`<th style="padding:7px;border:1px solid #b9cbb0;background:#d6e8c1">${esc(c)}</th>`).join('')}</tr></thead><tbody>${ageing.map(s=>`<tr><td style="padding:7px;border:1px solid #ddd">${esc(s.stationCode)}${s.overTwo>0?' ⚑':''}</td>${ageingBands.map(b=>`<td style="padding:7px;border:1px solid #ddd;text-align:right;color:${b!=='2 DAYS'&&s.bands[b]>0?'#c11c1c':'#17202a'}">${s.bands[b]?money(s.bands[b]):'—'}</td>`).join('')}<td style="padding:7px;border:1px solid #ddd;background:${s.overTwo>0?'#fff0ed':'#edf4fa'};text-align:right;font-weight:bold">${money(s.total)}</td></tr>`).join('')}<tr style="background:#d6e8c1;font-weight:bold"><td>Grand total</td>${ageingBands.map(b=>`<td style="padding:7px;text-align:right">${money(totals[b])}</td>`).join('')}<td style="padding:7px;text-align:right">${money(ageing.reduce((n,s)=>n+s.total,0))}</td></tr></tbody></table>`;
  const sourceLabel=`EDSP upload date: ${source.uploadDate} · Outstanding data as of: ${source.dataDate} (D−1).`;
  const headline=slot==='morning'?'9:00 AM follow-up':'8:30 PM deadline reminder';
  const url='https://ops.dropxlogistics.com/cod/pending?date='+date;
  const text=`${headline}\nDeposit/slip date: ${date}. Deadline: ${date} 8:30 PM IST.\n${sourceLabel}\nSlip status checked at send preparation; morning reuses the evening report source.\n\n${pending.length} stations need attention.\n${headers.join(' | ')}\n${body.map(r=>r.join(' | ')).join('\n')}\n\nOutstanding cash (2 days and above)\n${(includeAgeing?source.error:null)||ageing.map(s=>`${s.stationCode} | ${ageingBands.map(b=>b+': '+money(s.bands[b])).join(' | ')} | Total: ${money(s.total)}`).join('\n')}\nAmounts greater than 2 days are highlighted. 0–1 days are excluded from this ageing table. Other / older preserves source bands such as year-labelled balances.\nView details and download: ${url}`;
  return [{email:recipient.email,name:recipient.name,subject,text,html:`<!doctype html><html><body style="margin:0;background:#f4f6f8;font-family:Arial,sans-serif;color:#17202a"><div style="max-width:1000px;margin:24px auto;background:white;padding:28px;border-top:5px solid #ed4824"><p style="color:#ed4824;font-weight:bold">DROPX · OPSPULSE</p><h1 style="font-size:24px">COD report · ${esc(date)}</h1><h2 style="font-size:18px">${headline}</h2><p>All stations must upload their daily deposit slips by <strong>8:30 PM IST</strong>.</p><p><strong>Deposit / slip date: ${esc(date)}</strong><br>${esc(sourceLabel)}<br>Slip status is refreshed for this reminder. Both reminders use the same source cutoff of ${esc(date)}, 8:30 PM IST.</p><h2 style="font-size:18px">${pending.length} stations need slip action</h2>${pending.length?table(headers,body):'<p>All mapped stations have completed slips.</p>'}<h2 style="font-size:18px">Outstanding cash · ${esc(source.dataDate)}</h2><p><strong style="color:#c11c1c">${ageing.filter(s=>s.overTwo>0).length} stations have cash pending more than 2 days.</strong></p>${ageingTable}<p style="font-size:12px;color:#627082">Exactly 2 days is shown separately. Red amounts need ageing attention. 0–1 days is excluded from this table. Other / older preserves source labels including old-year balances. Outstanding cash is separate from a confirmed deposit shortage.</p><p><a style="display:inline-block;padding:12px 18px;background:#ed4824;color:#fff;text-decoration:none;border-radius:6px" href="${url}">View station details &amp; download report</a></p><p style="font-size:12px;color:#627082">Only your permitted stations are included. This conversation is grouped by report month; a new thread starts next month.</p></div></body></html>`,scope:{stationIds:allowed.map(r=>r.station.id),reportDate:date,slot,sourceBatchId:source.batchId,sourceDataDate:source.dataDate,sourceUploadDate:date}}];
 });
}
export const buildCodPendingDigest:DigestBuilder=async(db,control,date)=>{
 const rows=await loadCodPendingReport(db,control.company_id,[],true,date);
 const [source,recipients]=await Promise.all([loadCodAgeing(db,control.company_id,date,rows.filter(r=>r.client==='amazon').map(r=>r.station.station_code)),loadCodMailRecipients(db,control.company_id,rows.map(r=>r.station),String(control.config.email_domain||''))]);
 if(!control.subject_template)throw new Error('COD subject is not configured.');
 return {checkedAt:new Date().toISOString(),messages:buildCodDigestMessages(rows,source,recipients,date,String(control.config.slot),control.subject_template)};
};
