import {compactCodReason} from './ops-pulse/cod-return-policy';
import type {DigestBuilder,DigestMessage} from './portal-digest-delivery';
import {loadCodNoUpdateStreaks,loadCodPendingReport} from './ops-pulse/cod-pending-data';
import {loadCodAgeing} from './ops-pulse/cod-ageing-data';
import {ageingBands,type CodAgeingSnapshot} from './ops-pulse/cod-ageing';
import type {CodPendingRow} from './ops-pulse/cod-pending';
import {codNoUpdateBands,type CodNoUpdateStreak} from './ops-pulse/cod-no-update-streak';
import {loadCodMailRecipients,type CodMailRecipient} from './cod-pending-mail-scope';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number|null)=>v===null?'Not available':new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
export function buildCodDigestMessages(rows:CodPendingRow[],source:CodAgeingSnapshot,recipients:CodMailRecipient[],date:string,slot:string,subjectTemplate:string,noUpdateStreaks:CodNoUpdateStreak[]=[]):DigestMessage[]{
 const month=new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'long',timeZone:'Asia/Kolkata'});
 const subject=subjectTemplate.replace(/\{\{month\}\}/g,month).replace(/\{\{year\}\}/g,date.slice(0,4));
 if(!subject||/[\r\n]/.test(subject))throw new Error('Invalid COD reminder subject.');
 return recipients.flatMap(recipient=>{
  const allowed=rows.filter(r=>recipient.stationIds.includes(r.station.id));const pending=allowed.filter(r=>r.pending);const includeAgeing=allowed.some(r=>r.client==='amazon');
  const ageing=source.stations.filter(s=>allowed.some(r=>r.station.station_code===s.stationCode)&&s.total>0);
  if(!allowed.length)return [];
  const uploaded=allowed.filter(r=>r.slipUploaded).length;
  const updatesRecorded=allowed.filter(r=>r.updateRecorded).length;
  const notUploaded=allowed.filter(r=>!r.updateRecorded).length;
  const exceptions=allowed.filter(r=>!r.entries.length&&r.exception).length;
  const allowedIds=new Set(allowed.map(row=>row.station.id));
  const scopedStreaks=(noUpdateStreaks.length?noUpdateStreaks:allowed.filter(row=>!row.updateRecorded).map(row=>({stationId:row.station.id,stationCode:row.station.station_code,days:1}))).filter(row=>allowedIds.has(row.stationId));
  const streakGroups=codNoUpdateBands.map(band=>({...band,stations:scopedStreaks.filter(row=>row.days>=band.min&&row.days<=band.max)}));
  const headers=['Station','COD slip uploaded','Daily update','Slip validation','Reason / follow-up','Deposited ₹','Short ₹'];
  const body=[...allowed].sort((a,b)=>Number(a.slipUploaded)-Number(b.slipUploaded)||a.station.station_code.localeCompare(b.station.station_code)).map(r=>[r.station.station_code,r.slipUploaded?'YES — uploaded':r.exception&&!r.entries.length?'Exception recorded':'NO — pending',r.status==='Review pending'?'Recorded':r.status,r.slipUploaded?(r.validation==='Review pending'?'Review pending':r.validation):r.exception?'Not applicable':'Awaiting upload',[r.slipUploaded&&r.validation==='Review pending'?'Upload recorded; manual review pending':compactCodReason(r.validationReason),r.exception?.email_subject?`${r.entries.length?'Earlier exception email':'Email'}: ${r.exception.email_subject}`:'',r.exception?.email_check_status&&r.exception.email_check_status!=='Not applicable'?r.exception.email_check_status:''].filter(Boolean).join(' · '),money(r.amount),r.short?money(r.short):r.status==='Short'?'Amount unavailable':'—']);
  const table=(columns:string[],data:(string|number)[][])=>`<table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr>${columns.map((c,i)=>`<th style="padding:8px;border:1px solid #263850;background:#172b45;color:#ffffff;text-align:${i>=5?'right':'left'}">${esc(c)}</th>`).join('')}</tr></thead><tbody>${data.map((cells,row)=>`<tr style="background:${row%2?'#f8fafc':'#ffffff'}">${cells.map((c,i)=>{const badge=i===1||i===2||i===3;const good=i===1?String(c).startsWith('YES'):['Complete','Valid','No Cash','Not applicable'].includes(String(c));const bad=(i===1&&c==='NO — pending')||['Missing slip','Slip missing proof','Rejected','Short','Returned','Not valid','Awaiting upload'].includes(String(c));const color=good?'#166534':bad?'#b91c1c':'#92400e';const bg=good?'#dcfce7':bad?'#fee2e2':'#fef3c7';return `<td style="padding:7px 8px;border:1px solid #e2e8f0;vertical-align:top;text-align:${i>=5?'right':'left'};${i===0?'font-weight:bold;':''}${(i===6&&c!=='—'||i===4&&(['Returned','Not valid'].includes(String(cells[3]))||/Email not found|Email check unavailable/.test(String(c))))?'color:#b91c1c;font-weight:bold;':''}">${badge?`<span style="display:inline-block;padding:3px 6px;border-radius:4px;background:${bg};color:${color};font-weight:bold">${esc(c)}</span>`:esc(c)}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`;
  const cards=`<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:20px 0"><tr>${[['Total stations',allowed.length,'#172b45','#eff4fa'],['Slip uploaded',uploaded,'#166534','#dcfce7'],['Banker / No Cash',exceptions,'#1d4ed8','#dbeafe'],['No daily update',notUploaded,'#b91c1c','#fee2e2']].map(([label,value,color,bg])=>`<td style="width:25%;padding:14px 10px;background:${bg};border:3px solid white;vertical-align:top;color:${color}"><div style="font-size:11px;font-weight:bold">${label}</div><div style="font-size:28px;font-weight:bold;margin-top:6px">${value}</div></td>`).join('')}</tr></table>`;
  const streakTable=scopedStreaks.length?`<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;table-layout:fixed;margin:8px 0 20px"><tr>${streakGroups.map(group=>`<th style="padding:10px 6px;border:3px solid #ffffff;background:${group.background};color:${group.color};font-size:12px;text-align:left">${group.label}<br><span style="font-size:23px">${group.stations.length}</span></th>`).join('')}</tr><tr>${streakGroups.map(group=>`<td style="padding:9px 6px;border:1px solid #e2e8f0;vertical-align:top;font-size:12px;line-height:1.55;color:${group.color};font-weight:${group.stations.length?'bold':'normal'}">${group.stations.length?group.stations.map(row=>esc(row.stationCode)).join(', '):'—'}</td>`).join('')}</tr></table>`:'<p style="padding:12px;background:#dcfce7;color:#166534;font-weight:bold">Every permitted station has recorded today’s COD update.</p>';
  const totals=Object.fromEntries(ageingBands.map(b=>[b,ageing.reduce((n,r)=>n+(r.bands[b]||0),0)]));
  const ageingTable=!includeAgeing?'<p>EDSP outstanding cash applies to Amazon stations; none are in this recipient’s scope.</p>':source.error?`<p style="color:#b45309">${esc(source.error)}</p>`:`<table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr>${['Station',...ageingBands,'Grand total'].map(c=>`<th style="padding:7px;border:1px solid #b9cbb0;background:#d6e8c1">${esc(c)}</th>`).join('')}</tr></thead><tbody>${ageing.map(s=>`<tr><td style="padding:7px;border:1px solid #ddd">${esc(s.stationCode)}${s.overTwo>0?' ⚑':''}</td>${ageingBands.map(b=>`<td style="padding:7px;border:1px solid #ddd;text-align:right;color:${b!=='2 DAYS'&&s.bands[b]>0?'#c11c1c':'#17202a'}">${s.bands[b]?money(s.bands[b]):'—'}</td>`).join('')}<td style="padding:7px;border:1px solid #ddd;background:${s.overTwo>0?'#fff0ed':'#edf4fa'};text-align:right;font-weight:bold">${money(s.total)}</td></tr>`).join('')}<tr style="background:#d6e8c1;font-weight:bold"><td>Grand total</td>${ageingBands.map(b=>`<td style="padding:7px;text-align:right">${money(totals[b])}</td>`).join('')}<td style="padding:7px;text-align:right">${money(ageing.reduce((n,s)=>n+s.total,0))}</td></tr></tbody></table>`;
  const sourceLabel=`EDSP upload date: ${source.uploadDate} · Outstanding data as of: ${source.dataDate} (D−1).`;
  const headline=slot==='morning'?'9:00 AM follow-up':'8:30 PM deadline reminder';
  const url=recipient.canViewPendingReport===false?'https://ops.dropxlogistics.com/cod/submission?deposit_date='+date:'https://ops.dropxlogistics.com/cod/pending?date='+date;
  const cta=recipient.canViewPendingReport===false?'Upload / correct COD slip':'View station details & download report';
  const streakText=streakGroups.map(group=>`${group.label}: ${group.stations.length} (${group.stations.map(row=>row.stationCode).join(', ')||'—'})`).join('\n');
  const text=`${headline}\nDeposit/slip date: ${date}. Deadline: ${date} 8:30 PM IST.\n${sourceLabel}\nSlip status checked at send preparation; morning reuses the evening report source.\n\n${updatesRecorded} of ${allowed.length} stations recorded a daily update: ${uploaded} slip uploads and ${exceptions} Banker Not Reported / No Cash statuses. ${notUploaded} have no daily update. ${pending.length} require station action.\n\nConsecutive days without a COD update\n${streakText}\nNo Cash and Banker Not Reported count as a recorded daily update.\n\n${headers.join(' | ')}\n${body.map(r=>r.join(' | ')).join('\n')}\n\nOutstanding cash (2 days and above)\n${(includeAgeing?source.error:null)||ageing.map(s=>`${s.stationCode} | ${ageingBands.map(b=>b+': '+money(s.bands[b])).join(' | ')} | Total: ${money(s.total)}`).join('\n')}\nAmounts greater than 2 days are highlighted. 0–1 days are excluded from this ageing table. Other / older preserves source bands such as year-labelled balances.\n${cta}: ${url}`;
  return [{email:recipient.email,name:recipient.name,subject,text,html:`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;background:#f4f6f8;font-family:Arial,sans-serif;color:#17202a"><div style="max-width:1000px;margin:24px auto;background:white;padding:28px;border-top:5px solid #ed4824"><p style="color:#ed4824;font-weight:bold">DROPX · OPSPULSE</p><h1 style="font-size:24px">COD report · ${esc(date)}</h1><h2 style="font-size:18px">${headline}</h2><p>All stations must record their daily COD update by <strong>8:30 PM IST</strong>.</p><p><strong>Deposit / slip date: ${esc(date)}</strong><br>${esc(sourceLabel)}<br>Upload, manual review and exception status are refreshed for this reminder. Both reminders use the same source cutoff of ${esc(date)}, 8:30 PM IST.</p>${cards}<h2 style="font-size:18px;margin-bottom:4px">Consecutive days without a COD update</h2><p style="font-size:13px;color:#627082;margin-top:0">Escalation view through ${esc(date)}. No Cash and Banker Not Reported count as a recorded daily update.</p>${streakTable}<h2 style="font-size:20px">COD daily update: ${updatesRecorded} / ${allowed.length} recorded</h2><p><strong style="color:${notUploaded?'#b91c1c':'#167347'}">${uploaded} slips uploaded. ${exceptions} Banker Not Reported / No Cash statuses. ${notUploaded} stations have no daily update.</strong> ${pending.length} stations require action.</p>${table(headers,body)}<p style="font-size:12px;color:#627082">Red: failed manual review, missing daily update or shortage. The reason column explains the required follow-up. A slip awaiting review is already a recorded upload and is not a station miss. No Cash and Banker Not Reported are completed daily status updates; a deposit slip is not required for these cases.</p><h2 style="font-size:18px">Outstanding cash · ${esc(source.dataDate)}</h2><p><strong style="color:#c11c1c">${ageing.filter(s=>s.overTwo>0).length} stations have cash pending more than 2 days.</strong></p>${ageingTable}<p style="font-size:12px;color:#627082">Exactly 2 days is shown separately. Red amounts need ageing attention. 0–1 days is excluded from this table. Other / older preserves source labels including old-year balances. Outstanding cash is separate from a confirmed deposit shortage.</p><p><a style="display:inline-block;padding:12px 18px;background:#ed4824;color:#fff;text-decoration:none;border-radius:6px" href="${url}">${esc(cta)}</a></p><p style="font-size:12px;color:#627082">Only your permitted stations are included. This conversation is grouped by report month; a new thread starts next month.</p></div></body></html>`,scope:{stationIds:allowed.map(r=>r.station.id),reportDate:date,slot,sourceBatchId:source.batchId,sourceDataDate:source.dataDate,sourceUploadDate:date}}];
 });
}
export const buildCodPendingDigest:DigestBuilder=async(db,control,date)=>{
 const rows=await loadCodPendingReport(db,control.company_id,[],true,date);
 const [source,recipients,noUpdateStreaks]=await Promise.all([loadCodAgeing(db,control.company_id,date,rows.filter(r=>r.client==='amazon').map(r=>r.station.station_code)),loadCodMailRecipients(db,control.company_id,rows.map(r=>r.station),String(control.config.email_domain||'')),loadCodNoUpdateStreaks(db,control.company_id,rows.map(row=>row.station),date)]);
 if(!control.subject_template)throw new Error('COD subject is not configured.');
 return {checkedAt:new Date().toISOString(),messages:buildCodDigestMessages(rows,source,recipients,date,String(control.config.slot),control.subject_template,noUpdateStreaks)};
};
