import type {DigestBuilder,DigestMessage} from './portal-digest-delivery';
import {loadCodPendingReport} from './ops-pulse/cod-pending-data';
import {loadCodAgeing} from './ops-pulse/cod-ageing-data';
import {ageingBands,type CodAgeingSnapshot} from './ops-pulse/cod-ageing';
import type {CodPendingRow} from './ops-pulse/cod-pending';
import {loadCodMailRecipients,type CodMailRecipient} from './cod-pending-mail-scope';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const money=(v:number|null)=>v===null?'Not available':new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
export function buildCodDigestMessages(rows:CodPendingRow[],source:CodAgeingSnapshot,recipients:CodMailRecipient[],date:string,slot:string,subjectTemplate:string):DigestMessage[]{
 const month=new Date(date+'T12:00:00Z').toLocaleDateString('en-GB',{month:'long',timeZone:'Asia/Kolkata'});
 const subject=subjectTemplate.replace(/\{\{month\}\}/g,month).replace(/\{\{year\}\}/g,date.slice(0,4));
 if(!subject||/[\r\n]/.test(subject))throw new Error('Invalid COD reminder subject.');
 return recipients.flatMap(recipient=>{
  const allowed=rows.filter(r=>recipient.stationIds.includes(r.station.id));const pending=allowed.filter(r=>r.pending);const includeAgeing=allowed.some(r=>r.client==='amazon');
  const ageing=source.stations.filter(s=>allowed.some(r=>r.station.station_code===s.stationCode)&&s.total>0);
  if(!allowed.length)return [];
  const uploaded=allowed.filter(r=>r.slipUploaded).length;
  const notUploaded=allowed.length-uploaded;
  const headers=['Station','COD slip uploaded','Review status','Deposited ₹','Short ₹'];
  const body=[...allowed].sort((a,b)=>Number(a.slipUploaded)-Number(b.slipUploaded)||a.station.station_code.localeCompare(b.station.station_code)).map(r=>[r.station.station_code,r.slipUploaded?'YES — uploaded':'NO — pending',r.status,money(r.amount),r.short?money(r.short):r.status==='Short'?'Amount unavailable':'—']);
  const table=(columns:string[],data:(string|number)[][])=>`<table cellpadding="0" cellspacing="0" style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr>${columns.map((c,i)=>`<th style="padding:12px 10px;border:1px solid #263850;background:#172b45;color:#ffffff;text-align:${i>=3?'right':'left'}">${esc(c)}</th>`).join('')}</tr></thead><tbody>${data.map((cells,row)=>`<tr style="background:${row%2?'#f8fafc':'#ffffff'}">${cells.map((c,i)=>{const badge=i===1||i===2;const good=i===1?String(c).startsWith('YES'):c==='Complete';const bad=i===1||['Missing slip','Slip missing proof','Rejected','Short'].includes(String(c));const color=good?'#166534':bad?'#b91c1c':'#92400e';const bg=good?'#dcfce7':bad?'#fee2e2':'#fef3c7';return `<td style="padding:11px 10px;border:1px solid #e2e8f0;vertical-align:top;text-align:${i>=3?'right':'left'};${i===0?'font-weight:bold;':''}${i===4&&c!=='—'?'color:#b91c1c;font-weight:bold;':''}">${badge?`<span style="display:inline-block;padding:5px 8px;border-radius:4px;background:${bg};color:${color};font-weight:bold">${esc(c)}</span>`:esc(c)}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`;
  const cards=`<table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;margin:20px 0"><tr>${[['Total stations',allowed.length,'#172b45','#eff4fa'],['Slip uploaded',uploaded,'#166534','#dcfce7'],['Not uploaded',notUploaded,'#b91c1c','#fee2e2'],['Uploaded · review needed',allowed.filter(r=>r.slipUploaded&&r.pending).length,'#92400e','#fef3c7']].map(([label,value,color,bg])=>`<td style="width:25%;padding:14px 10px;background:${bg};border:3px solid white;vertical-align:top;color:${color}"><div style="font-size:11px;font-weight:bold">${label}</div><div style="font-size:28px;font-weight:bold;margin-top:6px">${value}</div></td>`).join('')}</tr></table>`;
  const totals=Object.fromEntries(ageingBands.map(b=>[b,ageing.reduce((n,r)=>n+(r.bands[b]||0),0)]));
  const ageingTable=!includeAgeing?'<p>EDSP outstanding cash applies to Amazon stations; none are in this recipient’s scope.</p>':source.error?`<p style="color:#b45309">${esc(source.error)}</p>`:`<table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr>${['Station',...ageingBands,'Grand total'].map(c=>`<th style="padding:7px;border:1px solid #b9cbb0;background:#d6e8c1">${esc(c)}</th>`).join('')}</tr></thead><tbody>${ageing.map(s=>`<tr><td style="padding:7px;border:1px solid #ddd">${esc(s.stationCode)}${s.overTwo>0?' ⚑':''}</td>${ageingBands.map(b=>`<td style="padding:7px;border:1px solid #ddd;text-align:right;color:${b!=='2 DAYS'&&s.bands[b]>0?'#c11c1c':'#17202a'}">${s.bands[b]?money(s.bands[b]):'—'}</td>`).join('')}<td style="padding:7px;border:1px solid #ddd;background:${s.overTwo>0?'#fff0ed':'#edf4fa'};text-align:right;font-weight:bold">${money(s.total)}</td></tr>`).join('')}<tr style="background:#d6e8c1;font-weight:bold"><td>Grand total</td>${ageingBands.map(b=>`<td style="padding:7px;text-align:right">${money(totals[b])}</td>`).join('')}<td style="padding:7px;text-align:right">${money(ageing.reduce((n,s)=>n+s.total,0))}</td></tr></tbody></table>`;
  const sourceLabel=`EDSP upload date: ${source.uploadDate} · Outstanding data as of: ${source.dataDate} (D−1).`;
  const headline=slot==='morning'?'9:00 AM follow-up':'8:30 PM deadline reminder';
  const url=recipient.canViewPendingReport===false?'https://ops.dropxlogistics.com/cod/submission?deposit_date='+date:'https://ops.dropxlogistics.com/cod/pending?date='+date;
  const cta=recipient.canViewPendingReport===false?'Upload / correct COD slip':'View station details & download report';
  const text=`${headline}\nDeposit/slip date: ${date}. Deadline: ${date} 8:30 PM IST.\n${sourceLabel}\nSlip status checked at send preparation; morning reuses the evening report source.\n\n${uploaded} of ${allowed.length} stations uploaded; ${notUploaded} not uploaded. ${pending.length} require review or upload action.\n${headers.join(' | ')}\n${body.map(r=>r.join(' | ')).join('\n')}\n\nOutstanding cash (2 days and above)\n${(includeAgeing?source.error:null)||ageing.map(s=>`${s.stationCode} | ${ageingBands.map(b=>b+': '+money(s.bands[b])).join(' | ')} | Total: ${money(s.total)}`).join('\n')}\nAmounts greater than 2 days are highlighted. 0–1 days are excluded from this ageing table. Other / older preserves source bands such as year-labelled balances.\n${cta}: ${url}`;
  return [{email:recipient.email,name:recipient.name,subject,text,html:`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"></head><body style="margin:0;background:#f4f6f8;font-family:Arial,sans-serif;color:#17202a"><div style="max-width:1000px;margin:24px auto;background:white;padding:28px;border-top:5px solid #ed4824"><p style="color:#ed4824;font-weight:bold">DROPX · OPSPULSE</p><h1 style="font-size:24px">COD report · ${esc(date)}</h1><h2 style="font-size:18px">${headline}</h2><p>All stations must upload their daily deposit slips by <strong>8:30 PM IST</strong>.</p><p><strong>Deposit / slip date: ${esc(date)}</strong><br>${esc(sourceLabel)}<br>Slip status is refreshed for this reminder. Both reminders use the same source cutoff of ${esc(date)}, 8:30 PM IST.</p>${cards}<h2 style="font-size:20px">COD slip update: ${uploaded} / ${allowed.length} uploaded</h2><p><strong style="color:${notUploaded?'#b91c1c':'#167347'}">${notUploaded} stations have not uploaded their COD slip.</strong> ${pending.length} stations require upload or review action.</p>${table(headers,body)}<p style="font-size:12px;color:#627082">Green: uploaded / complete · Red: missing slip or shortage · Amber: verification or review required.</p><h2 style="font-size:18px">Outstanding cash · ${esc(source.dataDate)}</h2><p><strong style="color:#c11c1c">${ageing.filter(s=>s.overTwo>0).length} stations have cash pending more than 2 days.</strong></p>${ageingTable}<p style="font-size:12px;color:#627082">Exactly 2 days is shown separately. Red amounts need ageing attention. 0–1 days is excluded from this table. Other / older preserves source labels including old-year balances. Outstanding cash is separate from a confirmed deposit shortage.</p><p><a style="display:inline-block;padding:12px 18px;background:#ed4824;color:#fff;text-decoration:none;border-radius:6px" href="${url}">${esc(cta)}</a></p><p style="font-size:12px;color:#627082">Only your permitted stations are included. This conversation is grouped by report month; a new thread starts next month.</p></div></body></html>`,scope:{stationIds:allowed.map(r=>r.station.id),reportDate:date,slot,sourceBatchId:source.batchId,sourceDataDate:source.dataDate,sourceUploadDate:date}}];
 });
}
export const buildCodPendingDigest:DigestBuilder=async(db,control,date)=>{
 const rows=await loadCodPendingReport(db,control.company_id,[],true,date);
 const [source,recipients]=await Promise.all([loadCodAgeing(db,control.company_id,date,rows.filter(r=>r.client==='amazon').map(r=>r.station.station_code)),loadCodMailRecipients(db,control.company_id,rows.map(r=>r.station),String(control.config.email_domain||''))]);
 if(!control.subject_template)throw new Error('COD subject is not configured.');
 return {checkedAt:new Date().toISOString(),messages:buildCodDigestMessages(rows,source,recipients,date,String(control.config.slot),control.subject_template)};
};
