import type { GpsExceptionReview } from '@/lib/fleet/gps-exceptions';
import "server-only";
import { normalizeAuditConfig, type AuditConfig } from "@/lib/fleet/audit-rules";

import type { AuthorizationContext } from "@/lib/authorization";
import { hasPermission } from "@/lib/authorization";
import { loadAdHocActivity, isAdHocActivityLocation } from "@/lib/ops-pulse/adhoc-activity";
import { loadCodLocations, todayKolkata } from "@/lib/ops-pulse/cod";
import { getPaymentApprovalEligibility } from "@/lib/payment-approval-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { isFleetManagerPaymentHead } from "@/lib/fleet-control-payment-scope";
import { fleetAdHocRequestType } from "@/lib/fleet-control-adhoc-scope";
import { defaultFleetDailyStatusEmailConfig, normalizeFleetDailyStatusEmailConfig, type FleetDailyStatusEmailConfig } from "@/lib/fleet/daily-status-email";
import { loadFleetDailyStatusRecipients, resolveFleetDailyStatusDeliveryRecipients, type FleetMailDeliveryRecipient } from "@/lib/fleet/daily-status-recipients";
import { auditProgrammeFromRiskWeights, defaultFleetAuditProgrammeConfig, type FleetAuditProgrammeConfig } from "@/lib/fleet/audit-programme-config";

export type FleetControlVehicle = {
  id: string; vehicleNo: string; stationCode: string; model: string; fuelType: string; status: string; statusLabel: string;
  ownershipType: "own" | "odcd" | "rented"; nonOperationalSince: string | null; expectedOperationalDate: string | null; statusComment: string; statusReasonId: string | null; statusReasonKey: string; statusReasonLabel: string;
  deploymentStatus: "deployed" | "not_deployed"; currentLocationType: "station" | "ho" | "workshop" | "in_transit" | "other"; currentLocationCode: string; currentLocationLabel: string; currentLocationUpdatedAt: string | null;
  createdAt: string | null;
  registrationExpiry: string | null; insuranceExpiry: string | null; pucExpiry: string | null; fitnessExpiry: string | null; taxExpiry: string | null;
  nextDocument: string | null; nextDocumentDate: string | null; nextDocumentDays: number | null;
  lastServiceDate: string | null; nextServiceDate: string | null; nextServiceOdometerKm: number | null; lastAuditDate: string | null;
};
export type FleetVehicleStatusReason = { id: string; key: string; label: string; helper: string; sortOrder: number; isActive: boolean };
export type FleetVehicleStatusDefinition = { id: string; key: string; label: string; helper: string; tone: "good" | "info" | "warn" | "bad" | "neutral"; isOperational: boolean; isTerminal: boolean; requiresReason: boolean; requiresExpectedDate: boolean; sortOrder: number; isActive: boolean; reasons: FleetVehicleStatusReason[] };
export type FleetDocumentDefinition = { id: string; value: string; label: string; description: string; requiresExpiry: boolean; expiryMode: "required" | "optional" | "linked_fitness"; reminderDays: number; sortOrder: number };
export type FleetVehicleDocument = { id: string; vehicleNo: string; documentType: string; fileName: string; contentType: string; fileSize: number | null; expiryDate: string | null; uploadedAt: string | null; viewUrl: string; downloadUrl: string };
export type FleetVehicleMovement = { id: string; vehicleId: string; vehicleNo: string; fromStation: string; toStation: string; reason: string; movedAt: string; movedBy: string };
export type FleetVehicleStatusHistory = { id: string; vehicleId: string; vehicleNo: string; status: string; statusLabel: string; statusReasonKey: string; statusReasonLabel: string; comment: string; expectedOperationalDate: string | null; startedAt: string; endedAt: string | null };
export type FleetVehicleDailyKm = { vehicleNo: string; date: string; km: number; source: string; confidencePercent: number | null; maxSpeed: number | null; movingMinutes: number | null; lateNight: boolean; firstMovingAt: string | null; lastMovingAt: string | null; firstMovingLatitude: number | null; firstMovingLongitude: number | null };
export type FleetControlPayment = { id: string; requestNo: string; stationCode: string; head: string; amount: number; requestedBy: string; requestedAt: string; workDate: string | null; status: string; statusLabel: string; remarks: string; canApprove: boolean };
export type FleetControlAdHocRow = { id: string; date: string; stationCode: string; stationName: string; cluster: string; region: string; requestType: "Van" | "Driver"; paymentHeadCode: string; paymentHeadName: string; reference: string; source: string; reason: string; remark: string; amount: number; approvalStatus: string };
export type FleetServiceRecord = { id: string; vehicleId: string; vehicleNo: string; stationCode: string; serviceDate: string; serviceType: string; odometerKm: number | null; vendorName: string; vendorContact: string; amount: number; status: string; description: string; invoiceUrl: string; nextServiceDate: string | null; nextServiceOdometerKm: number | null; downtimeHours: number | null };
export type FleetAuditMode = "video" | "physical";
export type FleetAuditEvidence = { id: string; checklistItemId: string | null; mediaType: "photo" | "video" | "document"; mediaUrl: string; caption: string; createdAt: string | null };
export type FleetAudit = { responses?: {label:string;answer:string;comments:string;action:string;days:number|null}[]; draft: Record<string,string>; id: string; vehicleId: string; vehicleNo: string; stationCode: string; templateId: string | null; auditMode: FleetAuditMode; scheduledFor: string; scheduledReason: string; riskScore: number; status: string; score: number | null; summary: string; completedAt: string | null; emailStatus: string; evidenceCount: number; evidence: FleetAuditEvidence[] };
export type FleetAuditSuggestion = { vehicleId: string; vehicleNo: string; stationCode: string; riskScore: number; reasons: string[]; recommendedFor: string };
export type FleetEvidenceType = "none" | "photo" | "video" | "document" | "any";
export type FleetChecklistItem = { responseConfig: AuditConfig | null; id: string; templateId: string; auditMode: "both" | "video" | "physical"; category: string; label: string; guidance: string; responseType: string; isRequired: boolean; failureSeverity: string; sortOrder: number; passEvidenceType: FleetEvidenceType; passMinEvidence: number; failEvidenceType: FleetEvidenceType; failMinEvidence: number; failRemarksRequired: boolean };
export type FleetAuditTemplate = { id: string; name: string; description: string; cadenceDays: number; isDefault: boolean; itemCount: number };
export type FleetPortalMember = { id: string; userId: string; name: string; email: string; accessLevel: string; scope: string; isActive: boolean };
export type FleetStatusRecipient = { id: string; name: string; email: string; stationCodes: string[]; source: "people" | "manual"; isActive: boolean };
export type FleetDesignationAccess = { id: string; code: string; name: string; enabled: boolean; roleId: string | null; locationAccessMode: "all_locations" | "role_based" | "none" | null };
export type FleetControlSettings = { defaultAuditCadenceDays: number; documentWarningDays: number; serviceWarningDays: number; autoSuggestAudits: boolean; breakdownVehicleLinkRequired: boolean; auditEmailEnabled: boolean; auditVideoRequired: boolean; auditProgramme: FleetAuditProgrammeConfig; dailyStatusEmailEnabled: boolean; dailyStatusSendTime: string; dailyStatusOnlyAffected: boolean; dailyStatusEmailConfig: FleetDailyStatusEmailConfig };
export type FleetIntegration = { key: "paytap" | "wheelseye"; name: string; purpose: string; status: "connected" | "in_progress" | "not_configured"; detail: string; lastSyncAt: string | null };
export type FleetFinding = { id: string; auditId: string; vehicleId: string; vehicleNo: string; stationCode: string; category: string; finding: string; severity: string; actionRequired: string; dueDate: string | null; status: string; resolutionNote: string };
export type FleetControlData = { gpsExceptionReviews?: GpsExceptionReview[]; findings: FleetFinding[];
  generatedAt: string; today: string; operator: { name: string; role: string; company: string };
  capabilities: { canApprovePayments: boolean; canAddVehicles: boolean; canEditVehicles: boolean; canManageDocuments: boolean; canReviewGps?: boolean; canManageAudits?: boolean; canManageFleet: boolean; canManageSettings: boolean; canAccessUsers: boolean; visibleSections: string[] };
  counts: { vehicles: number; active: number; underService: number; unavailable: number; documentAttention: number; pendingPayments: number; pendingAmount: number; adHocToday: number; adHocTodayAmount: number; serviceDue: number; auditsDue: number };
  vehicles: FleetControlVehicle[]; vehicleStatuses: FleetVehicleStatusDefinition[]; statusHistory: FleetVehicleStatusHistory[]; dailyKm: FleetVehicleDailyKm[]; documents: FleetVehicleDocument[]; documentTypes: FleetDocumentDefinition[]; movements: FleetVehicleMovement[]; payments: FleetControlPayment[]; adHocRows: FleetControlAdHocRow[]; serviceHistory: FleetServiceRecord[]; audits: FleetAudit[]; auditSuggestions: FleetAuditSuggestion[]; auditTemplates: FleetAuditTemplate[]; checklistItems: FleetChecklistItem[]; members: FleetPortalMember[]; statusRecipients: FleetStatusRecipient[]; resolvedStatusRecipients: FleetMailDeliveryRecipient[]; designationAccess: FleetDesignationAccess[]; settings: FleetControlSettings; integrations: FleetIntegration[];
  featureReady: boolean; stationOptions: Array<{ code: string; name: string; cluster: string; region: string }>; errors: string[];
};

type VehicleRow = { id: string; vehicle_no: string; station_code: string; model: string; fuel_type: string; status: string | null; ownership_type: string | null; non_operational_since: string | null; expected_operational_date: string | null; status_comment: string | null; status_reason_id: string | null; status_reason_key: string | null; deployment_status: string | null; current_location_type: string | null; current_location_code: string | null; current_location_label: string | null; current_location_updated_at: string | null; created_at: string | null; registration_expiry: string | null; insurance_expiry: string | null; puc_expiry: string | null; fitness_expiry: string | null; tax_expiry: string | null };
type PaymentHeadRow = { id: string; code: string | null; name: string | null };
type PaymentRow = { id: string; request_no: string | null; location_id: string | null; location_code: string | null; station_code: string | null; payment_head_id: string; amount: number | string | null; amount_approved: number | string | null; amount_requested: number | string | null; status: string | null; approval_status: string | null; current_approver_user_id: string | null; current_approver_role_id: string | null; current_approver_role_ids: string[] | null; requested_by: string | null; created_at: string; work_date: string | null; remarks: string | null; notes: string | null; details: Record<string, unknown> | null; profiles?: { full_name: string | null; email: string | null } | Array<{ full_name: string | null; email: string | null }> | null };

const expiryFields = [["Registration", "registration_expiry"], ["Insurance", "insurance_expiry"], ["PUC", "puc_expiry"], ["Fitness", "fitness_expiry"], ["Tax", "tax_expiry"]] as const;
const defaultDocumentTypes: FleetDocumentDefinition[] = [
  { id: "", value: "FLEET_REGISTRATION", label: "Registration certificate", description: "Vehicle registration record", requiresExpiry: false, expiryMode: "linked_fitness", reminderDays: 30, sortOrder: 10 },
  { id: "", value: "FLEET_INSURANCE", label: "Insurance", description: "Current vehicle insurance policy", requiresExpiry: true, expiryMode: "required", reminderDays: 30, sortOrder: 20 },
  { id: "", value: "FLEET_PUC", label: "Pollution certificate (PUC)", description: "Pollution under control certificate", requiresExpiry: true, expiryMode: "required", reminderDays: 15, sortOrder: 30 },
  { id: "", value: "FLEET_FITNESS", label: "Fitness certificate", description: "Commercial vehicle fitness certificate", requiresExpiry: true, expiryMode: "required", reminderDays: 30, sortOrder: 40 },
  { id: "", value: "FLEET_TAX", label: "Road tax", description: "Road tax payment or exemption", requiresExpiry: true, expiryMode: "required", reminderDays: 30, sortOrder: 50 }
];
function text(value: unknown) { return String(value ?? "").trim(); }
function normalized(value: unknown) { return text(value).toUpperCase().replace(/[^A-Z0-9]+/g, "_"); }
function numberValue(value: unknown) { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed : 0; }
function nullableNumber(value: unknown) { const parsed = Number(value); return value == null || value === "" || !Number.isFinite(parsed) ? null : parsed; }
function firstRelation<T>(value: T | T[] | null | undefined) { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function isFeatureSetupError(message: string) { return /does not exist|schema cache|could not find the table/i.test(message); }
export function fleetVehicleStatus(value: unknown) { const status = normalized(value || "active"); if (["REPAIR", "UNDER_SERVICE", "SERVICE"].includes(status)) return { key: "under_service", label: "Under service" }; const labels: Record<string, string> = { ACTIVE: "Active", BREAKDOWN: "Breakdown", INACTIVE: "Inactive", RETURNED: "Returned", SOLD: "Sold", DISPOSED: "Disposed" }; const customLabel = status.toLowerCase().split("_").filter(Boolean).map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join(" "); return { key: status.toLowerCase(), label: (labels[status] ?? customLabel) || "Inactive" }; }
function isPendingPayment(row: PaymentRow) { const state = normalized(row.approval_status || row.status); if (["FINAL_APPROVED", "APPROVED", "REJECTED", "RETURNED", "CANCELLED", "PROCESSING", "PROCESSED", "PAID"].includes(state)) return false; return Boolean(row.current_approver_user_id || row.current_approver_role_id || row.current_approver_role_ids?.length) || ["PENDING", "RE_PENDING", "RESUBMITTED", "SUBMITTED"].includes(state) || state.endsWith("_APPROVED"); }
function paymentStatus(row: PaymentRow) { const state = normalized(row.approval_status || row.status); if (state === "FINAL_APPROVED" || state === "APPROVED") return "Approved"; if (state === "PROCESSING") return "Processing"; if (state === "PROCESSED" || state === "PAID") return "Paid"; if (state === "RETURNED") return "Returned"; if (state === "REJECTED") return "Rejected"; if (state.endsWith("_APPROVED")) return "In approval"; return "Pending"; }
function dayDifference(date: string, today: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null; return Math.round((Date.parse(`${date}T00:00:00Z`) - Date.parse(`${today}T00:00:00Z`)) / 86_400_000); }
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }
function mapVehicle(row: VehicleRow, today: string): FleetControlVehicle { const documents = expiryFields.flatMap(([label, field]) => { const value = text(row[field]); const days = dayDifference(value, today); return days == null ? [] : [{ label, date: value, days }]; }).sort((a, b) => a.days - b.days); const next = documents[0] ?? null; const status = fleetVehicleStatus(row.status); const ownership = normalized(row.ownership_type); const ownershipType = ownership === "ODCD" ? "odcd" : ownership === "RENTED" || ownership === "LEASED" ? "rented" : "own"; const deploymentStatus = row.deployment_status === "not_deployed" ? "not_deployed" as const : "deployed" as const; const locationType = ["station", "ho", "workshop", "in_transit", "other"].includes(text(row.current_location_type)) ? text(row.current_location_type) as FleetControlVehicle["currentLocationType"] : "station"; const stationCode = text(row.station_code).toUpperCase(); return { id: row.id, vehicleNo: text(row.vehicle_no).toUpperCase(), stationCode, model: text(row.model) || "Model not recorded", fuelType: text(row.fuel_type) || "-", status: status.key, statusLabel: status.label, ownershipType, deploymentStatus, currentLocationType: locationType, currentLocationCode: text(row.current_location_code).toUpperCase(), currentLocationLabel: text(row.current_location_label) || text(row.current_location_code).toUpperCase() || stationCode, currentLocationUpdatedAt: row.current_location_updated_at, nonOperationalSince: row.non_operational_since, expectedOperationalDate: row.expected_operational_date, statusComment: text(row.status_comment), statusReasonId: row.status_reason_id, statusReasonKey: text(row.status_reason_key), statusReasonLabel: "", createdAt: row.created_at, registrationExpiry: row.registration_expiry, insuranceExpiry: row.insurance_expiry, pucExpiry: row.puc_expiry, fitnessExpiry: row.fitness_expiry, taxExpiry: row.tax_expiry, nextDocument: next?.label ?? null, nextDocumentDate: next?.date ?? null, nextDocumentDays: next?.days ?? null, lastServiceDate: null, nextServiceDate: null, nextServiceOdometerKm: null, lastAuditDate: null }; }
function defaultSettings(): FleetControlSettings { return { defaultAuditCadenceDays: 30, documentWarningDays: 30, serviceWarningDays: 14, autoSuggestAudits: true, breakdownVehicleLinkRequired: false, auditEmailEnabled: true, auditVideoRequired: true, auditProgramme: defaultFleetAuditProgrammeConfig, dailyStatusEmailEnabled: false, dailyStatusSendTime: "20:00", dailyStatusOnlyAffected: true, dailyStatusEmailConfig: defaultFleetDailyStatusEmailConfig }; }
function auditReason(value: unknown) {
  const raw = text(value);
  const mode: FleetAuditMode = /^\[mode:video\]/i.test(raw) ? "video" : "physical";
  return { mode, reason: raw.replace(/^\[mode:(?:video|physical)\]\s*/i, "").replace(/\s*\[moved:[^\]]+\]\s*$/i, "") || "Routine monthly audit" };
}
function checklistEvidence(responseType: string, guidanceValue: unknown) {
  const raw = text(guidanceValue);
  const remarksMarker = raw.match(/^\[remarks-fail:(required|optional)\]\s*/i);
  const failRemarksRequired = remarksMarker ? remarksMarker[1].toLowerCase() === "required" : ["pass_fail", "yes_no"].includes(responseType);
  const withoutRemarks = raw.replace(/^\[remarks-fail:(?:required|optional)\]\s*/i, "");
  const passMarker = withoutRemarks.match(/^\[evidence-pass:(none|photo|video|document|any):(\d+)\]\s*/i);
  const withoutPass = withoutRemarks.replace(/^\[evidence-pass:(?:none|photo|video|document|any):\d+\]\s*/i, "");
  const failMarker = withoutPass.match(/^\[evidence-fail:(none|photo|video|document|any):(\d+)\]\s*/i);
  const legacyMarker = raw.match(/^\[evidence:(none|photo|video|document|any):(\d+)\]\s*/i);
  const defaultType = responseType === "photo" ? "photo" : responseType === "video" ? "video" : "none";
  const fallbackType = (legacyMarker?.[1]?.toLowerCase() || defaultType) as FleetEvidenceType;
  const fallbackMin = legacyMarker ? Math.max(0, Math.min(10, Number(legacyMarker[2]) || 0)) : defaultType === "none" ? 0 : 1;
  const rule = (marker: RegExpMatchArray | null, type: FleetEvidenceType, minimum: number) => ({ type: (marker?.[1]?.toLowerCase() || type) as FleetEvidenceType, minimum: marker ? Math.max(0, Math.min(10, Number(marker[2]) || 0)) : minimum });
  const pass = rule(passMarker, legacyMarker ? fallbackType : "none", legacyMarker ? fallbackMin : 0);
  const fail = rule(failMarker, fallbackType, fallbackMin);
  return { passEvidenceType: pass.type, passMinEvidence: pass.minimum, failEvidenceType: fail.type, failMinEvidence: fail.minimum, failRemarksRequired, guidance: withoutRemarks.replace(/^\[evidence-pass:(?:none|photo|video|document|any):\d+\]\s*/i, "").replace(/^\[evidence-fail:(?:none|photo|video|document|any):\d+\]\s*/i, "").replace(/^\[evidence:(?:none|photo|video|document|any):\d+\]\s*/i, "") };
}

export async function hasActiveFleetMembership(companyId: string | null, userId: string) {
  if (!supabaseAdmin || !companyId) return false;
  const product = await supabaseAdmin.from("company_product_memberships").select("id,role_id").eq("company_id", companyId).eq("product_code", "fleet").eq("user_id", userId).eq("is_active", true).maybeSingle();
  if (product.error && !isFeatureSetupError(product.error.message)) return false;
  return Boolean(product.data?.id && product.data.role_id);
}

export async function loadFleetControlData(companyId: string, authorization: AuthorizationContext): Promise<FleetControlData> {
  const today = todayKolkata(); const activityStart = addDays(today, -92); const errors: string[] = [];
  const locationsResult = await loadCodLocations(companyId, authorization.locationScopeIds, authorization.hasAllLocationAccess); if (locationsResult.error) errors.push(locationsResult.error);
  const locations = locationsResult.locations.filter(isAdHocActivityLocation); const stationCodes = locations.map((location) => normalized(location.station_code));
  const canManageFleet = authorization.isMasterOwner || hasPermission(authorization, "fleet_audits", "edit") || hasPermission(authorization, "fleet_maintenance", "edit") || hasPermission(authorization, "fleet_vehicle_view", "edit");
  const canManageDocuments = authorization.isMasterOwner || hasPermission(authorization, "fleet_date_view", "edit") || hasPermission(authorization, "fleet_vehicle_view", "edit");
  const canManageSettings = authorization.isMasterOwner || hasPermission(authorization, "fleet_settings", "edit") || hasPermission(authorization, "fleet_masters", "edit");
  const visibleSections = [
    ["overview", "fleet_action_center"],
    ["attention", "fleet_action_center"],
    ["vehicles", "fleet_vehicle_view"],
    ["documents", "fleet_date_view"],
    ["tracking", "fleet_tracking"],
    ["fuel", "fleet_tracking"],
    ["service", "fleet_maintenance"],
    ["audits", "fleet_audits"],
    ["approvals", "payment_approvals"],
    ["adhoc", "fleet_reports"],
    ["reports", "fleet_reports"],
    ["settings", "fleet_settings"],
    ["masters", "fleet_masters"]
  ].filter(([, code]) => hasPermission(authorization, code, "access")).map(([section]) => section);
  const base: FleetControlData = { findings: [], generatedAt: new Date().toISOString(), today, operator: { name: authorization.fullName || authorization.email || "Fleet controller", role: authorization.roleName || authorization.designationName || "Fleet controller", company: authorization.companyName || "DropX Logistics" }, capabilities: { canReviewGps: authorization.isMasterOwner || (hasPermission(authorization,"fleet_tracking","access") && (hasPermission(authorization,"fleet_tracking","edit") || hasPermission(authorization,"fleet_action_center","edit"))), canApprovePayments: hasPermission(authorization, "payment_approvals", "edit"), canAddVehicles: hasPermission(authorization, "fleet_vehicle_view", "add"), canEditVehicles: hasPermission(authorization, "fleet_date_view", "edit") || hasPermission(authorization, "fleet_vehicle_view", "edit"), canManageDocuments, canManageAudits: authorization.isMasterOwner || hasPermission(authorization,"fleet_audits","edit"), canManageFleet, canManageSettings, canAccessUsers: hasPermission(authorization, "users", "access"), visibleSections }, counts: { vehicles: 0, active: 0, underService: 0, unavailable: 0, documentAttention: 0, pendingPayments: 0, pendingAmount: 0, adHocToday: 0, adHocTodayAmount: 0, serviceDue: 0, auditsDue: 0 }, vehicles: [], vehicleStatuses: [], statusHistory: [], dailyKm: [], documents: [], documentTypes: defaultDocumentTypes, movements: [], payments: [], adHocRows: [], serviceHistory: [], audits: [], auditSuggestions: [], auditTemplates: [], checklistItems: [], members: [], statusRecipients: [], resolvedStatusRecipients: [], designationAccess: [], settings: defaultSettings(), integrations: [{ key: "paytap", name: "Paytap", purpose: "Fuel cards and fuel transaction reconciliation", status: "in_progress", detail: "Integration workspace prepared", lastSyncAt: null }, { key: "wheelseye", name: "WheelsEye", purpose: "GPS location, daily kilometres and route visibility", status: "not_configured", detail: "Access token required", lastSyncAt: null }], featureReady: false, stationOptions: locations.map((location) => ({ code: normalized(location.station_code), name: text(location.station_name || location.city || location.station_code), cluster: text(location.cluster || location.cluster_manager) || "Unassigned cluster", region: text(location.region) || "Unassigned region" })), errors };
  if (!supabaseAdmin) return { ...base, errors: [...errors, "Database service is unavailable."] };

  let vehicleQuery = supabaseAdmin.from("fleet_vehicles").select("id,vehicle_no,station_code,model,fuel_type,status,ownership_type,deployment_status,current_location_type,current_location_code,current_location_label,current_location_updated_at,non_operational_since,expected_operational_date,status_comment,status_reason_id,status_reason_key,created_at,registration_expiry,insurance_expiry,puc_expiry,fitness_expiry,tax_expiry").eq("company_id", companyId).order("vehicle_no");
  if (!authorization.hasAllLocationAccess) vehicleQuery = vehicleQuery.in("station_code", stationCodes.length ? stationCodes : ["__NO_STATION__"]);
  let paymentQuery = supabaseAdmin.from("payment_requests").select("id,request_no,location_id,location_code,station_code,payment_head_id,amount,amount_approved,amount_requested,status,approval_status,current_approver_user_id,current_approver_role_id,current_approver_role_ids,requested_by,created_at,work_date,remarks,notes,details,profiles:requested_by(full_name,email)").eq("company_id", companyId).order("created_at", { ascending: false }).limit(1000);
  if (!authorization.hasAllLocationAccess) paymentQuery = paymentQuery.in("location_id", authorization.locationScopeIds.length ? authorization.locationScopeIds : ["00000000-0000-0000-0000-000000000000"]);
  const [vehiclesResult, headsResult, paymentsResult, adHocResult] = await Promise.all([vehicleQuery, supabaseAdmin.from("payment_heads").select("id,code,name").eq("company_id", companyId).eq("is_active", true), paymentQuery, loadAdHocActivity(companyId, locations, activityStart, today)]);
  if (vehiclesResult.error) errors.push(vehiclesResult.error.message); if (headsResult.error) errors.push(headsResult.error.message); if (paymentsResult.error) errors.push(paymentsResult.error.message); if (adHocResult.error) errors.push(adHocResult.error);
  let vehicles = ((vehiclesResult.data ?? []) as VehicleRow[]).map((row) => mapVehicle(row, today)); const vehicleById = new Map(vehicles.map((vehicle) => [vehicle.id, vehicle]));
  const heads = (headsResult.data ?? []) as PaymentHeadRow[]; const vehicleHeadIds = new Set(heads.filter(isFleetManagerPaymentHead).map((head) => head.id)); const headById = new Map(heads.map((head) => [head.id, head]));
  const paymentRows = ((paymentsResult.data ?? []) as unknown as PaymentRow[]).filter((row) => vehicleHeadIds.has(row.payment_head_id)); const pendingRows = paymentRows.filter(isPendingPayment); const eligibleIds = await getPaymentApprovalEligibility(companyId, authorization, pendingRows); const canEditApprovals = hasPermission(authorization, "payment_approvals", "edit");
  const payments = paymentRows.map((row): FleetControlPayment => { const head = headById.get(row.payment_head_id); const profile = firstRelation(row.profiles); return { id: row.id, requestNo: text(row.request_no) || row.id, stationCode: normalized(row.station_code || row.location_code) || "UNASSIGNED", head: text(head?.name || head?.code) || "Vehicle expense", amount: numberValue(row.amount_approved ?? row.amount ?? row.amount_requested), requestedBy: text(profile?.full_name || profile?.email) || "Station team", requestedAt: row.created_at, workDate: row.work_date, status: normalized(row.approval_status || row.status).toLowerCase(), statusLabel: paymentStatus(row), remarks: text(row.remarks || row.notes) || "No remarks recorded", canApprove: canEditApprovals && eligibleIds.has(row.id) }; });
  const adHocRows = adHocResult.stations.flatMap((station) => station.days.flatMap((day) => day.entries.flatMap((entry): FleetControlAdHocRow[] => {
    const requestType = fleetAdHocRequestType(entry);
    return requestType ? [{ id: entry.id, date: day.date, stationCode: station.code, stationName: station.name, cluster: station.cluster || "Unassigned cluster", region: station.region || "Unassigned region", requestType, paymentHeadCode: entry.paymentHeadCode || (requestType === "Van" ? "ADHOC_VAN" : "ADHOC_DRIVER"), paymentHeadName: entry.paymentHeadName || `Ad-hoc ${requestType}`, reference: entry.reference, source: entry.source, reason: entry.reason, remark: entry.remark, amount: entry.amount, approvalStatus: entry.approvalStatus || (entry.source === "Cashbook" ? "paid" : "submitted") }] : [];
  })))
    .sort((a, b) => b.date.localeCompare(a.date) || a.stationCode.localeCompare(b.stationCode) || a.requestType.localeCompare(b.requestType));

  const scopeVehicleIds = vehicles.map((vehicle) => vehicle.id); const scoped = scopeVehicleIds.length ? scopeVehicleIds : ["00000000-0000-0000-0000-000000000000"];
  const scopeVehicleNos = vehicles.map((vehicle) => vehicle.vehicleNo); const scopedNos = scopeVehicleNos.length ? scopeVehicleNos : ["__NO_VEHICLE__"];
  const [serviceResult, auditResult, templateResult, checklistResult, settingsResult, membershipResult, recipientResult, wheelseyeResult, gpsSyncResult, fuelSyncResult, evidenceResult, designationResult, designationPolicyResult, documentTypesResult, documentsResult, movementsResult, statusMasterResult, statusReasonResult, statusHistoryResult, dailyKmResult, findingsResult, responsesResult, gpsReviewsResult] = await Promise.all([
    supabaseAdmin.from("fleet_service_history").select("id,vehicle_id,service_date,service_type,odometer_km,vendor_name,vendor_contact,amount,status,description,invoice_url,next_service_date,next_service_odometer_km,downtime_hours").eq("company_id", companyId).in("vehicle_id", scoped).order("service_date", { ascending: false }).limit(500),
    supabaseAdmin.from("fleet_audits").select("id,vehicle_id,template_id,scheduled_for,scheduled_reason,risk_score,status,score,summary,completed_at,email_status,draft").eq("company_id", companyId).in("vehicle_id", scoped).order("scheduled_for", { ascending: false }).limit(500),
    supabaseAdmin.from("fleet_audit_templates").select("id,name,description,cadence_days,is_default").eq("company_id", companyId).eq("is_active", true).order("name"),
    supabaseAdmin.from("fleet_audit_checklist_items").select("id,template_id,audit_mode,category,label,guidance,response_type,response_config,is_required,failure_severity,sort_order").eq("company_id", companyId).eq("is_active", true).order("sort_order"),
    supabaseAdmin.from("fleet_control_settings").select("default_audit_cadence_days,document_warning_days,service_warning_days,auto_suggest_audits,breakdown_vehicle_link_required,audit_email_enabled,audit_video_required,risk_weights,daily_status_email_enabled,daily_status_send_time,daily_status_only_affected,daily_status_email_config").eq("company_id", companyId).maybeSingle(),
    supabaseAdmin.from("fleet_portal_memberships").select("id,user_id,access_level,has_all_location_access,location_scope_ids,is_active,profiles:user_id(full_name,email)").eq("company_id", companyId).order("created_at"),
    supabaseAdmin.from("fleet_status_report_recipients").select("id,name,email,station_codes,source,is_active").eq("company_id", companyId).order("name"),
    supabaseAdmin.from("wheelseye_settings").select("is_enabled,token_secret_id").eq("company_id", companyId).eq("id", true).maybeSingle(),
    supabaseAdmin.from("fleet_daily_km").select("calculated_at").eq("company_id", companyId).order("calculated_at", { ascending: false }).limit(1),
    supabaseAdmin.from("fleet_fuel_transactions").select("uploaded_at,provider").eq("company_id", companyId).order("uploaded_at", { ascending: false }).limit(1),
    supabaseAdmin.from("fleet_audit_evidence").select("id,audit_id,checklist_item_id,media_type,media_url,caption,created_at").eq("company_id", companyId).order("created_at", { ascending: false }).limit(2000),
    supabaseAdmin.from("designations").select("id,code,name").eq("company_id", companyId).eq("is_active", true).order("name"),
    supabaseAdmin.from("designation_product_access_policies").select("designation_id,default_role_id,location_access_mode,is_enabled").eq("company_id", companyId).eq("product_code", "fleet"),
    supabaseAdmin.from("document_types").select("id,code,name,description,requires_expiry,reminder_days,sort_order").eq("company_id", companyId).eq("document_module", "fleet").eq("is_active", true).order("sort_order"),
    supabaseAdmin.from("fleet_vehicle_documents").select("id,vehicle_no,document_type,file_name,content_type,file_size,expiry_date,uploaded_at").eq("company_id", companyId).eq("is_active", true).in("vehicle_no", scopedNos).order("uploaded_at", { ascending: false }),
    supabaseAdmin.from("dashboard_app_event_logs").select("id,subject_id,subject_code,actor_label,event_code,metadata,created_at").eq("company_id", companyId).eq("module", "fleet").in("event_code", ["fleet_vehicle_transferred", "fleet_vehicle_location_updated"]).in("subject_id", scoped).order("created_at", { ascending: false }).limit(1000),
    supabaseAdmin.from("fleet_vehicle_status_master").select("id,status_key,label,helper_text,tone,is_operational,is_terminal,requires_reason,requires_expected_date,sort_order,is_active").eq("company_id", companyId).order("sort_order"),
    supabaseAdmin.from("fleet_vehicle_status_reason_master").select("id,status_id,reason_key,label,helper_text,sort_order,is_active").eq("company_id", companyId).order("sort_order"),
    supabaseAdmin.from("fleet_vehicle_status_history").select("id,vehicle_id,vehicle_no,status_key,status_label,status_reason_key,status_reason_label,comment,expected_operational_date,started_at,ended_at").eq("company_id", companyId).in("vehicle_id", scoped).order("started_at", { ascending: false }).limit(5000),
    supabaseAdmin.from("fleet_daily_km").select("vehicle_no,movement_date,km,source,confidence_percent,max_speed,moving_minutes,late_night,first_moving_at,last_moving_at,first_moving_latitude,first_moving_longitude").eq("company_id", companyId).in("vehicle_no", scopedNos).neq("review_status", "needs_review").order("movement_date", { ascending: false }).limit(20000),
    supabaseAdmin.from("fleet_audit_findings").select("id,audit_id,category,finding,severity,action_required,expected_completion_date,status,resolution_note,fleet_audits!inner(vehicle_id)").eq("company_id", companyId).in("fleet_audits.vehicle_id", scoped).order("created_at", { ascending: false }).limit(2000)
    ,supabaseAdmin.from("fleet_audit_responses").select("audit_id,checklist_item_id,response_value,comments,fleet_audits!inner(vehicle_id)").eq("company_id",companyId).in("fleet_audits.vehicle_id",scoped).order("responded_at",{ascending:false}).limit(10000)
    ,supabaseAdmin.from("fleet_gps_exception_reviews").select("vehicle_no,movement_date,reason,remarks,reviewed_by_name,reviewed_at").eq("company_id",companyId).in("vehicle_no",scopedNos).order("reviewed_at",{ascending:false}).limit(20000)
  ]);
  const featureErrors = [serviceResult, auditResult, templateResult, checklistResult, settingsResult, membershipResult, recipientResult, evidenceResult, findingsResult, responsesResult, gpsReviewsResult].flatMap((result) => result.error ? [result.error.message] : []); const featureReady = !featureErrors.some(isFeatureSetupError); featureErrors.filter((message) => !isFeatureSetupError(message)).forEach((message) => errors.push(message));
  const documentTypes: FleetDocumentDefinition[] = documentTypesResult.error || !(documentTypesResult.data?.length) ? defaultDocumentTypes : documentTypesResult.data.map((row: any) => { const value = text(row.code).toUpperCase(); const expiryMode = value === "FLEET_REGISTRATION" ? "linked_fitness" as const : row.requires_expiry !== false ? "required" as const : "optional" as const; return { id: text(row.id), value, label: text(row.name) || text(row.code), description: text(row.description), requiresExpiry: expiryMode === "required", expiryMode, reminderDays: numberValue(row.reminder_days) || 30, sortOrder: numberValue(row.sort_order) }; });
  if (documentTypesResult.error && !isFeatureSetupError(documentTypesResult.error.message)) errors.push(documentTypesResult.error.message);
  const documents: FleetVehicleDocument[] = (documentsResult.data ?? []).map((row: any) => { const vehicleNo = text(row.vehicle_no).toUpperCase(); const documentType = text(row.document_type).toUpperCase(); const fileUrl = `/api/fleet/documents/download?vehicle_no=${encodeURIComponent(vehicleNo)}&document_type=${encodeURIComponent(documentType)}`; return { id: row.id, vehicleNo, documentType, fileName: text(row.file_name), contentType: text(row.content_type), fileSize: nullableNumber(row.file_size), expiryDate: row.expiry_date, uploadedAt: row.uploaded_at, viewUrl: fileUrl, downloadUrl: `${fileUrl}&download=1` }; });
  if (documentsResult.error && !isFeatureSetupError(documentsResult.error.message)) errors.push(documentsResult.error.message);
  const movements: FleetVehicleMovement[] = (movementsResult.data ?? []).map((row: any) => { const metadata = row.metadata && typeof row.metadata === "object" ? row.metadata : {}; const physical = row.event_code === "fleet_vehicle_location_updated"; return { id: row.id, vehicleId: text(row.subject_id), vehicleNo: text(row.subject_code).toUpperCase(), fromStation: physical ? text(metadata.from_location) || "Not recorded" : normalized(metadata.from_station) || "UNASSIGNED", toStation: physical ? text(metadata.to_location) || "Not recorded" : normalized(metadata.to_station) || "UNASSIGNED", reason: text(metadata.reason) || (physical ? "Deployment or physical location updated" : "Placement updated"), movedAt: row.created_at, movedBy: text(row.actor_label) || "Fleet team" }; });
  if (movementsResult.error && !isFeatureSetupError(movementsResult.error.message)) errors.push(movementsResult.error.message);
  const reasonsByStatus = new Map<string, FleetVehicleStatusReason[]>();
  (statusReasonResult.data ?? []).forEach((row: any) => { const list = reasonsByStatus.get(row.status_id) ?? []; list.push({ id: row.id, key: text(row.reason_key), label: text(row.label), helper: text(row.helper_text), sortOrder: numberValue(row.sort_order), isActive: Boolean(row.is_active) }); reasonsByStatus.set(row.status_id, list); });
  const vehicleStatuses: FleetVehicleStatusDefinition[] = (statusMasterResult.data ?? []).map((row: any) => ({ id: row.id, key: text(row.status_key), label: text(row.label), helper: text(row.helper_text), tone: (["good", "info", "warn", "bad", "neutral"].includes(row.tone) ? row.tone : "neutral") as FleetVehicleStatusDefinition["tone"], isOperational: Boolean(row.is_operational), isTerminal: Boolean(row.is_terminal), requiresReason: Boolean(row.requires_reason), requiresExpectedDate: Boolean(row.requires_expected_date), sortOrder: numberValue(row.sort_order), isActive: Boolean(row.is_active), reasons: reasonsByStatus.get(row.id) ?? [] }));
  if (statusMasterResult.error && !isFeatureSetupError(statusMasterResult.error.message)) errors.push(statusMasterResult.error.message);
  if (statusReasonResult.error && !isFeatureSetupError(statusReasonResult.error.message)) errors.push(statusReasonResult.error.message);
  const statusByKey = new Map(vehicleStatuses.map((status) => [status.key, status]));
  const reasonById = new Map(vehicleStatuses.flatMap((status) => status.reasons.map((reason) => [reason.id, reason] as const)));
  vehicles = vehicles.map((vehicle) => { const definition = statusByKey.get(vehicle.status); const reason = vehicle.statusReasonId ? reasonById.get(vehicle.statusReasonId) : definition?.reasons.find((item) => item.key === vehicle.statusReasonKey); return { ...vehicle, statusLabel: definition?.label ?? vehicle.statusLabel, statusReasonLabel: reason?.label ?? vehicle.statusReasonKey.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }; });
  const statusHistory: FleetVehicleStatusHistory[] = (statusHistoryResult.data ?? []).map((row: any) => ({ id: row.id, vehicleId: row.vehicle_id, vehicleNo: text(row.vehicle_no).toUpperCase(), status: text(row.status_key), statusLabel: text(row.status_label), statusReasonKey: text(row.status_reason_key), statusReasonLabel: text(row.status_reason_label), comment: text(row.comment), expectedOperationalDate: row.expected_operational_date, startedAt: row.started_at, endedAt: row.ended_at }));
  const dailyKm: FleetVehicleDailyKm[] = (dailyKmResult.data ?? []).map((row: any) => ({ vehicleNo: text(row.vehicle_no).toUpperCase(), date: row.movement_date, km: numberValue(row.km), source: text(row.source), confidencePercent: nullableNumber(row.confidence_percent), maxSpeed: nullableNumber(row.max_speed), movingMinutes: nullableNumber(row.moving_minutes), lateNight: Boolean(row.late_night), firstMovingAt: row.first_moving_at, lastMovingAt: row.last_moving_at, firstMovingLatitude: nullableNumber(row.first_moving_latitude), firstMovingLongitude: nullableNumber(row.first_moving_longitude) }));
  if (statusHistoryResult.error && !isFeatureSetupError(statusHistoryResult.error.message)) errors.push(statusHistoryResult.error.message);
  if (dailyKmResult.error && !isFeatureSetupError(dailyKmResult.error.message)) errors.push(dailyKmResult.error.message);
  const serviceHistory: FleetServiceRecord[] = (serviceResult.data ?? []).map((row: any) => { const vehicle = vehicleById.get(row.vehicle_id); return { responses:(responsesResult.data ?? []).filter((r:any)=>r.audit_id===row.id).map((r:any)=>{const value=r.response_value||{};return {label:value.label || checklistResult.data?.find((i:any)=>i.id===r.checklist_item_id)?.label || 'Checklist response',answer:value.config?.options?.find((o:any)=>o.value===value.value)?.label || String(value.value ?? value.response ?? ''),comments:text(r.comments),action:text(value.action),days:value.days?Number(value.days):null};}), draft: row.draft || {}, id: row.id, vehicleId: row.vehicle_id, vehicleNo: vehicle?.vehicleNo ?? "Unknown", stationCode: vehicle?.stationCode ?? "—", serviceDate: row.service_date, serviceType: text(row.service_type), odometerKm: nullableNumber(row.odometer_km), vendorName: text(row.vendor_name), vendorContact: text(row.vendor_contact), amount: numberValue(row.amount), status: text(row.status), description: text(row.description), invoiceUrl: text(row.invoice_url), nextServiceDate: row.next_service_date, nextServiceOdometerKm: nullableNumber(row.next_service_odometer_km), downtimeHours: nullableNumber(row.downtime_hours) }; });
  const latestServiceByVehicle = new Map<string, FleetServiceRecord>(); serviceHistory.filter((record) => record.status !== "scheduled").forEach((record) => { if (!latestServiceByVehicle.has(record.vehicleId)) latestServiceByVehicle.set(record.vehicleId, record); });
  const plannedServiceByVehicle = new Map<string, FleetServiceRecord>(); serviceHistory.filter((record) => record.status === "scheduled").sort((a, b) => a.serviceDate.localeCompare(b.serviceDate)).forEach((record) => plannedServiceByVehicle.set(record.vehicleId, record));
  const evidenceByAudit = new Map<string, FleetAuditEvidence[]>(); (evidenceResult.data ?? []).forEach((row: any) => { const current = evidenceByAudit.get(row.audit_id) ?? []; current.push({ id: row.id, checklistItemId: row.checklist_item_id, mediaType: row.media_type, mediaUrl: text(row.media_url), caption: text(row.caption), createdAt: row.created_at }); evidenceByAudit.set(row.audit_id, current); });
  const audits: FleetAudit[] = (auditResult.data ?? []).map((row: any) => { const vehicle = vehicleById.get(row.vehicle_id); const parsed = auditReason(row.scheduled_reason); const evidence = evidenceByAudit.get(row.id) ?? []; return { responses:(responsesResult.data ?? []).filter((r:any)=>r.audit_id===row.id).map((r:any)=>{const value=r.response_value||{};return {label:value.label || checklistResult.data?.find((i:any)=>i.id===r.checklist_item_id)?.label || 'Checklist response',answer:value.config?.options?.find((o:any)=>o.value===value.value)?.label || String(value.value ?? value.response ?? ''),comments:text(r.comments),action:text(value.action),days:value.days?Number(value.days):null};}), draft: row.draft || {}, id: row.id, vehicleId: row.vehicle_id, vehicleNo: vehicle?.vehicleNo ?? "Unknown", stationCode: vehicle?.stationCode ?? "—", templateId: row.template_id, auditMode: parsed.mode, scheduledFor: row.scheduled_for, scheduledReason: parsed.reason, riskScore: numberValue(row.risk_score), status: text(row.status), score: nullableNumber(row.score), summary: text(row.summary), completedAt: row.completed_at, emailStatus: text(row.email_status || "not_sent"), evidenceCount: evidence.length, evidence }; });
  const latestAuditByVehicle = new Map<string, FleetAudit>(); audits.filter((audit) => ["passed", "failed"].includes(audit.status)).forEach((audit) => { if (!latestAuditByVehicle.has(audit.vehicleId)) latestAuditByVehicle.set(audit.vehicleId, audit); });
  vehicles = vehicles.map((vehicle) => { const service = latestServiceByVehicle.get(vehicle.id); const plan = plannedServiceByVehicle.get(vehicle.id); const audit = latestAuditByVehicle.get(vehicle.id); return { ...vehicle, lastServiceDate: service?.serviceDate ?? null, nextServiceDate: plan?.serviceDate ?? service?.nextServiceDate ?? null, nextServiceOdometerKm: plan?.nextServiceOdometerKm ?? service?.nextServiceOdometerKm ?? null, lastAuditDate: audit?.completedAt?.slice(0, 10) ?? null }; });
  const settingsRow = settingsResult.data as any; const settings: FleetControlSettings = settingsRow ? { defaultAuditCadenceDays: numberValue(settingsRow.default_audit_cadence_days) || 30, documentWarningDays: numberValue(settingsRow.document_warning_days) || 30, serviceWarningDays: numberValue(settingsRow.service_warning_days) || 14, autoSuggestAudits: Boolean(settingsRow.auto_suggest_audits), breakdownVehicleLinkRequired: Boolean(settingsRow.breakdown_vehicle_link_required), auditEmailEnabled: settingsRow.audit_email_enabled !== false, auditVideoRequired: settingsRow.audit_video_required !== false, auditProgramme: auditProgrammeFromRiskWeights(settingsRow.risk_weights), dailyStatusEmailEnabled: Boolean(settingsRow.daily_status_email_enabled), dailyStatusSendTime: text(settingsRow.daily_status_send_time).slice(0, 5) || "20:00", dailyStatusOnlyAffected: settingsRow.daily_status_only_affected !== false, dailyStatusEmailConfig: normalizeFleetDailyStatusEmailConfig(settingsRow.daily_status_email_config) } : defaultSettings();
  const checklistItems: FleetChecklistItem[] = (checklistResult.data ?? []).map((row: any) => { const responseType = text(row.response_type); const evidence = checklistEvidence(responseType, row.guidance); return { responseConfig: normalizeAuditConfig(row.response_config), id: row.id, templateId: row.template_id, auditMode: (["video", "physical"].includes(row.audit_mode) ? row.audit_mode : "both") as FleetChecklistItem["auditMode"], category: text(row.category), label: text(row.label), responseType, isRequired: Boolean(row.is_required), failureSeverity: text(row.failure_severity), sortOrder: numberValue(row.sort_order), ...evidence }; });
  const auditTemplates: FleetAuditTemplate[] = (templateResult.data ?? []).map((row: any) => ({ id: row.id, name: text(row.name), description: text(row.description), cadenceDays: numberValue(row.cadence_days), isDefault: Boolean(row.is_default), itemCount: checklistItems.filter((item) => item.templateId === row.id).length }));
  const activeAuditVehicleIds = new Set(audits.filter((audit) => ["scheduled", "in_progress"].includes(audit.status)).map((audit) => audit.vehicleId));
  const auditSuggestions: FleetAuditSuggestion[] = settings.autoSuggestAudits ? vehicles.flatMap((vehicle) => { if (activeAuditVehicleIds.has(vehicle.id) || ["sold", "disposed", "returned"].includes(vehicle.status)) return []; let score = 0; const reasons: string[] = []; if (vehicle.status === "breakdown") { score += 40; reasons.push("vehicle is in breakdown"); } if (vehicle.status === "under_service") { score += 25; reasons.push("vehicle is under service"); } if (vehicle.nextDocumentDays != null && vehicle.nextDocumentDays < 0) { score += 25; reasons.push(`${vehicle.nextDocument} has expired`); } else if (vehicle.nextDocumentDays != null && vehicle.nextDocumentDays <= settings.documentWarningDays) { score += 12; reasons.push(`${vehicle.nextDocument} expires soon`); } const lastAudit = latestAuditByVehicle.get(vehicle.id); if (!lastAudit) { score += 20; reasons.push("no completed audit in Fleet"); } else { const auditDate = lastAudit.completedAt?.slice(0, 10) ?? lastAudit.scheduledFor; const age = dayDifference(today, auditDate) ?? 0; if (age >= settings.defaultAuditCadenceDays) { score += 25; reasons.push(`last audit was ${age} days ago`); } if (lastAudit.status === "failed") { score += 20; reasons.push("last audit failed"); } } const service = plannedServiceByVehicle.get(vehicle.id) ?? latestServiceByVehicle.get(vehicle.id); const dueDate = service?.status === "scheduled" ? service.serviceDate : service?.nextServiceDate; if (vehicle.ownershipType === "own" && dueDate && (dayDifference(dueDate, today) ?? 999) <= settings.serviceWarningDays) { score += 20; reasons.push("service is due soon"); } if (score < 20) return []; return [{ vehicleId: vehicle.id, vehicleNo: vehicle.vehicleNo, stationCode: vehicle.stationCode, riskScore: Math.min(score, 100), reasons, recommendedFor: score >= 50 ? today : addDays(today, 7) }]; }).sort((a, b) => b.riskScore - a.riskScore) : [];
  const members: FleetPortalMember[] = (membershipResult.data ?? []).map((row: any) => { const profile = firstRelation(row.profiles as any) as any; return { id: row.id, userId: row.user_id, name: text(profile?.full_name) || text(profile?.email) || "User", email: text(profile?.email), accessLevel: text(row.access_level), scope: row.has_all_location_access ? "All stations" : `${Array.isArray(row.location_scope_ids) ? row.location_scope_ids.length : 0} stations`, isActive: Boolean(row.is_active) }; });
  const statusRecipients: FleetStatusRecipient[] = (recipientResult.data ?? []).map((row: any) => ({ id: row.id, name: text(row.name) || text(row.email), email: text(row.email), stationCodes: Array.isArray(row.station_codes) ? row.station_codes.map(normalized).filter(Boolean) : [], source: row.source === "people" ? "people" : "manual", isActive: Boolean(row.is_active) }));
  let resolvedStatusRecipients: FleetMailDeliveryRecipient[] = [];
  if (canManageSettings) {
    const config = settings.dailyStatusEmailConfig;
    const excludedCodes = new Set(config.excludedStationCodes.map(normalized));
    const isAmazonNow = (location: any) => (Array.isArray(location.location_models) ? location.location_models : [location.location_models]).some((model: any) => /(?:^|\s)(?:AMAZON\s+)?NOW(?:\s|$)/i.test(`${text(model?.code)} ${text(model?.name)}`));
    const reportLocations = locations.filter((location) => { const code = normalized(location.station_code); return code && !excludedCodes.has(code) && !(config.excludeAmazonNow && isAmazonNow(location)); });
    const reportStationCodes = [...new Set([...vehicles.map((vehicle) => vehicle.stationCode), ...adHocRows.map((row) => row.stationCode)].map(normalized).filter((code) => code && reportLocations.some((location) => normalized(location.station_code) === code)))].sort();
    try {
      const automatic = await loadFleetDailyStatusRecipients(supabaseAdmin, companyId, reportLocations, config);
      resolvedStatusRecipients = resolveFleetDailyStatusDeliveryRecipients(automatic, statusRecipients.filter((recipient) => recipient.isActive), reportStationCodes, reportStationCodes, false);
    } catch (error) {
      errors.push(error instanceof Error ? `Unable to resolve Fleet email audience: ${error.message}` : "Unable to resolve Fleet email audience.");
    }
  }
  const policyByDesignation = new Map((designationPolicyResult.data ?? []).map((row: any) => [row.designation_id, row]));
  const designationAccess: FleetDesignationAccess[] = (designationResult.data ?? []).map((row: any) => { const policy = policyByDesignation.get(row.id) as any; return { id: row.id, code: text(row.code), name: text(row.name), enabled: Boolean(policy?.is_enabled), roleId: policy?.default_role_id ?? null, locationAccessMode: policy?.location_access_mode ?? null }; }).filter((row) => row.enabled);
  const gpsLast = (gpsSyncResult.data?.[0] as any)?.calculated_at ?? null; const fuelLast = (fuelSyncResult.data?.[0] as any)?.uploaded_at ?? null; const fuelProvider = text((fuelSyncResult.data?.[0] as any)?.provider);
  const integrations: FleetIntegration[] = [{ key: "paytap", name: "Paytap", purpose: "Fuel cards and fuel transaction reconciliation", status: fuelProvider.toLowerCase() === "paytap" ? "connected" : "in_progress", detail: fuelProvider ? `Latest fuel source: ${fuelProvider}` : "Connector and vehicle mapping are being prepared", lastSyncAt: fuelLast }, { key: "wheelseye", name: "WheelsEye", purpose: "GPS location, daily kilometres and route visibility", status: (wheelseyeResult.data as any)?.is_enabled && (wheelseyeResult.data as any)?.token_secret_id ? "connected" : "not_configured", detail: (wheelseyeResult.data as any)?.is_enabled ? "GPS access token configured" : "GPS connection is not enabled", lastSyncAt: gpsLast }];
  const actionablePayments = payments.filter((payment) => payment.canApprove); const underService = vehicles.filter((vehicle) => ["under_service", "breakdown"].includes(vehicle.status));
  const documentAttentionVehicles = new Set<string>();
  vehicles.forEach((vehicle) => {
    const vehicleDocuments = documents.filter((document) => document.vehicleNo === vehicle.vehicleNo);
    if (documentTypes.some((type) => {
      const document = vehicleDocuments.find((item) => item.documentType === type.value);
      if (!document) return true;
      const days = document.expiryDate ? dayDifference(document.expiryDate, today) : null;
      return type.requiresExpiry && (days == null || days <= type.reminderDays);
    })) documentAttentionVehicles.add(vehicle.id);
  });
  const adHocToday = adHocRows.filter((row) => row.date === today); const serviceDue = vehicles.filter((vehicle) => vehicle.ownershipType === "own" && vehicle.nextServiceDate && (dayDifference(vehicle.nextServiceDate, today) ?? 999) <= settings.serviceWarningDays);
  const findings: FleetFinding[] = (findingsResult.data ?? []).flatMap((row: any) => { const a = firstRelation(row.fleet_audits) as any; const v = vehicleById.get(a?.vehicle_id); return v ? [{ id: row.id, auditId: row.audit_id, vehicleId: v.id, vehicleNo: v.vehicleNo, stationCode: v.stationCode, category: row.category, finding: row.finding, severity: row.severity, actionRequired: row.action_required || "", dueDate: row.expected_completion_date, status: row.status, resolutionNote: row.resolution_note || "" }] : []; });
  if (findingsResult.error) errors.push(findingsResult.error.message);
  return { ...base, gpsExceptionReviews:(gpsReviewsResult.data||[]).map(r=>({vehicleNo:r.vehicle_no,date:r.movement_date,reason:r.reason,remarks:r.remarks,reviewedBy:r.reviewed_by_name,reviewedAt:r.reviewed_at})), findings, vehicles, vehicleStatuses, statusHistory, dailyKm, documents, documentTypes, movements, payments, adHocRows, serviceHistory, audits, auditSuggestions, auditTemplates, checklistItems, members, statusRecipients, resolvedStatusRecipients, designationAccess, settings, integrations, featureReady, counts: { vehicles: vehicles.length, active: vehicles.filter((vehicle) => vehicle.status === "active").length, underService: underService.length, unavailable: vehicles.filter((vehicle) => vehicle.status !== "active").length, documentAttention: documentAttentionVehicles.size, pendingPayments: actionablePayments.length, pendingAmount: actionablePayments.reduce((sum, payment) => sum + payment.amount, 0), adHocToday: adHocToday.length, adHocTodayAmount: adHocToday.reduce((sum, row) => sum + row.amount, 0), serviceDue: serviceDue.length, auditsDue: auditSuggestions.length + audits.filter((audit) => audit.status === "scheduled" && audit.scheduledFor <= today).length }, errors: [...new Set(errors)] };
}
