import "server-only";

import type { AuthorizationContext } from "@/lib/authorization";
import { hasPermission } from "@/lib/authorization";
import { loadAdHocActivity, isAdHocActivityLocation } from "@/lib/ops-pulse/adhoc-activity";
import { loadCodLocations, todayKolkata } from "@/lib/ops-pulse/cod";
import { getPaymentApprovalEligibility } from "@/lib/payment-approval-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { isFleetManagerPaymentHead } from "@/lib/fleet-control-payment-scope";

export type FleetControlVehicle = {
  id: string; vehicleNo: string; stationCode: string; model: string; fuelType: string; status: string; statusLabel: string;
  registrationExpiry: string | null; insuranceExpiry: string | null; pucExpiry: string | null; fitnessExpiry: string | null; taxExpiry: string | null;
  nextDocument: string | null; nextDocumentDate: string | null; nextDocumentDays: number | null;
  lastServiceDate: string | null; nextServiceDate: string | null; nextServiceOdometerKm: number | null; lastAuditDate: string | null;
};
export type FleetControlPayment = { id: string; requestNo: string; stationCode: string; head: string; amount: number; requestedBy: string; requestedAt: string; workDate: string | null; status: string; statusLabel: string; remarks: string; canApprove: boolean };
export type FleetControlAdHocRow = { id: string; date: string; stationCode: string; stationName: string; reference: string; source: string; reason: string; remark: string; amount: number };
export type FleetServiceRecord = { id: string; vehicleId: string; vehicleNo: string; stationCode: string; serviceDate: string; serviceType: string; odometerKm: number | null; vendorName: string; vendorContact: string; amount: number; status: string; description: string; invoiceUrl: string; nextServiceDate: string | null; nextServiceOdometerKm: number | null; downtimeHours: number | null };
export type FleetAudit = { id: string; vehicleId: string; vehicleNo: string; stationCode: string; templateId: string | null; scheduledFor: string; scheduledReason: string; riskScore: number; status: string; score: number | null; summary: string; completedAt: string | null; emailStatus: string; evidenceCount: number };
export type FleetAuditSuggestion = { vehicleId: string; vehicleNo: string; stationCode: string; riskScore: number; reasons: string[]; recommendedFor: string };
export type FleetChecklistItem = { id: string; templateId: string; category: string; label: string; guidance: string; responseType: string; isRequired: boolean; failureSeverity: string; sortOrder: number };
export type FleetAuditTemplate = { id: string; name: string; description: string; cadenceDays: number; isDefault: boolean; itemCount: number };
export type FleetPortalMember = { id: string; userId: string; name: string; email: string; accessLevel: string; scope: string; isActive: boolean };
export type FleetControlSettings = { defaultAuditCadenceDays: number; documentWarningDays: number; serviceWarningDays: number; autoSuggestAudits: boolean; breakdownVehicleLinkRequired: boolean; auditEmailEnabled: boolean; auditVideoRequired: boolean };
export type FleetIntegration = { key: "paytap" | "wheelseye"; name: string; purpose: string; status: "connected" | "in_progress" | "not_configured"; detail: string; lastSyncAt: string | null };
export type FleetControlData = {
  generatedAt: string; today: string; operator: { name: string; role: string; company: string };
  capabilities: { canApprovePayments: boolean; canAddVehicles: boolean; canEditVehicles: boolean; canManageFleet: boolean; canManageSettings: boolean };
  counts: { vehicles: number; active: number; underService: number; unavailable: number; documentAttention: number; pendingPayments: number; pendingAmount: number; adHocToday: number; adHocTodayAmount: number; serviceDue: number; auditsDue: number };
  vehicles: FleetControlVehicle[]; payments: FleetControlPayment[]; adHocRows: FleetControlAdHocRow[]; serviceHistory: FleetServiceRecord[]; audits: FleetAudit[]; auditSuggestions: FleetAuditSuggestion[]; auditTemplates: FleetAuditTemplate[]; checklistItems: FleetChecklistItem[]; members: FleetPortalMember[]; settings: FleetControlSettings; integrations: FleetIntegration[];
  featureReady: boolean; stationOptions: Array<{ code: string; name: string }>; errors: string[];
};

type VehicleRow = { id: string; vehicle_no: string; station_code: string; model: string; fuel_type: string; status: string | null; registration_expiry: string | null; insurance_expiry: string | null; puc_expiry: string | null; fitness_expiry: string | null; tax_expiry: string | null };
type PaymentHeadRow = { id: string; code: string | null; name: string | null };
type PaymentRow = { id: string; request_no: string | null; location_id: string | null; location_code: string | null; station_code: string | null; payment_head_id: string; amount: number | string | null; amount_approved: number | string | null; amount_requested: number | string | null; status: string | null; approval_status: string | null; current_approver_user_id: string | null; current_approver_role_id: string | null; current_approver_role_ids: string[] | null; requested_by: string | null; created_at: string; work_date: string | null; remarks: string | null; notes: string | null; details: Record<string, unknown> | null; profiles?: { full_name: string | null; email: string | null } | Array<{ full_name: string | null; email: string | null }> | null };

const expiryFields = [["Registration", "registration_expiry"], ["Insurance", "insurance_expiry"], ["PUC", "puc_expiry"], ["Fitness", "fitness_expiry"], ["Tax", "tax_expiry"]] as const;
function text(value: unknown) { return String(value ?? "").trim(); }
function normalized(value: unknown) { return text(value).toUpperCase().replace(/[^A-Z0-9]+/g, "_"); }
function numberValue(value: unknown) { const parsed = Number(value ?? 0); return Number.isFinite(parsed) ? parsed : 0; }
function nullableNumber(value: unknown) { const parsed = Number(value); return value == null || value === "" || !Number.isFinite(parsed) ? null : parsed; }
function firstRelation<T>(value: T | T[] | null | undefined) { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function isFeatureSetupError(message: string) { return /does not exist|schema cache|could not find the table/i.test(message); }
export function fleetVehicleStatus(value: unknown) { const status = normalized(value || "active"); if (["REPAIR", "UNDER_SERVICE", "SERVICE"].includes(status)) return { key: "under_service", label: "Under service" }; if (status === "BREAKDOWN") return { key: "breakdown", label: "Breakdown" }; if (status === "ACTIVE") return { key: "active", label: "Active" }; if (status === "SOLD") return { key: "sold", label: "Sold" }; if (status === "RETURNED") return { key: "returned", label: "Returned" }; if (status === "DISPOSED") return { key: "disposed", label: "Disposed" }; return { key: "inactive", label: "Inactive" }; }
function isPendingPayment(row: PaymentRow) { const state = normalized(row.approval_status || row.status); if (["FINAL_APPROVED", "APPROVED", "REJECTED", "RETURNED", "CANCELLED", "PROCESSING", "PROCESSED", "PAID"].includes(state)) return false; return Boolean(row.current_approver_user_id || row.current_approver_role_id || row.current_approver_role_ids?.length) || ["PENDING", "RE_PENDING", "RESUBMITTED", "SUBMITTED"].includes(state) || state.endsWith("_APPROVED"); }
function paymentStatus(row: PaymentRow) { const state = normalized(row.approval_status || row.status); if (state === "FINAL_APPROVED" || state === "APPROVED") return "Approved"; if (state === "PROCESSING") return "Processing"; if (state === "PROCESSED" || state === "PAID") return "Paid"; if (state === "RETURNED") return "Returned"; if (state === "REJECTED") return "Rejected"; if (state.endsWith("_APPROVED")) return "In approval"; return "Pending"; }
function dayDifference(date: string, today: string) { if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null; return Math.round((Date.parse(`${date}T00:00:00Z`) - Date.parse(`${today}T00:00:00Z`)) / 86_400_000); }
function addDays(date: string, days: number) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }
function mapVehicle(row: VehicleRow, today: string): FleetControlVehicle { const documents = expiryFields.flatMap(([label, field]) => { const value = text(row[field]); const days = dayDifference(value, today); return days == null ? [] : [{ label, date: value, days }]; }).sort((a, b) => a.days - b.days); const next = documents[0] ?? null; const status = fleetVehicleStatus(row.status); return { id: row.id, vehicleNo: text(row.vehicle_no).toUpperCase(), stationCode: text(row.station_code).toUpperCase(), model: text(row.model) || "Model not recorded", fuelType: text(row.fuel_type) || "-", status: status.key, statusLabel: status.label, registrationExpiry: row.registration_expiry, insuranceExpiry: row.insurance_expiry, pucExpiry: row.puc_expiry, fitnessExpiry: row.fitness_expiry, taxExpiry: row.tax_expiry, nextDocument: next?.label ?? null, nextDocumentDate: next?.date ?? null, nextDocumentDays: next?.days ?? null, lastServiceDate: null, nextServiceDate: null, nextServiceOdometerKm: null, lastAuditDate: null }; }
function defaultSettings(): FleetControlSettings { return { defaultAuditCadenceDays: 30, documentWarningDays: 30, serviceWarningDays: 14, autoSuggestAudits: true, breakdownVehicleLinkRequired: false, auditEmailEnabled: true, auditVideoRequired: true }; }

export async function hasActiveFleetMembership(companyId: string | null, userId: string) {
  if (!supabaseAdmin || !companyId) return false;
  const result = await supabaseAdmin.from("fleet_portal_memberships").select("id").eq("company_id", companyId).eq("user_id", userId).eq("is_active", true).maybeSingle();
  if (result.error && isFeatureSetupError(result.error.message)) return false;
  return Boolean(result.data?.id);
}

export async function loadFleetControlData(companyId: string, authorization: AuthorizationContext): Promise<FleetControlData> {
  const today = todayKolkata(); const monthStart = `${today.slice(0, 7)}-01`; const errors: string[] = [];
  const locationsResult = await loadCodLocations(companyId, authorization.locationScopeIds, authorization.hasAllLocationAccess); if (locationsResult.error) errors.push(locationsResult.error);
  const locations = locationsResult.locations.filter(isAdHocActivityLocation); const stationCodes = locations.map((location) => normalized(location.station_code));
  const canManageFleet = authorization.isMasterOwner || hasPermission(authorization, "fleet_maintenance", "edit") || hasPermission(authorization, "fleet_vehicle_view", "edit");
  const canManageSettings = authorization.isMasterOwner || hasPermission(authorization, "app_settings", "edit") || hasPermission(authorization, "users", "edit");
  const base: FleetControlData = { generatedAt: new Date().toISOString(), today, operator: { name: authorization.fullName || authorization.email || "Fleet controller", role: authorization.roleName || authorization.designationName || "Fleet controller", company: authorization.companyName || "Tropics Logistics" }, capabilities: { canApprovePayments: hasPermission(authorization, "payment_approvals", "edit"), canAddVehicles: hasPermission(authorization, "fleet_vehicle_view", "add"), canEditVehicles: hasPermission(authorization, "fleet_vehicle_view", "edit"), canManageFleet, canManageSettings }, counts: { vehicles: 0, active: 0, underService: 0, unavailable: 0, documentAttention: 0, pendingPayments: 0, pendingAmount: 0, adHocToday: 0, adHocTodayAmount: 0, serviceDue: 0, auditsDue: 0 }, vehicles: [], payments: [], adHocRows: [], serviceHistory: [], audits: [], auditSuggestions: [], auditTemplates: [], checklistItems: [], members: [], settings: defaultSettings(), integrations: [{ key: "paytap", name: "Paytap", purpose: "Fuel cards and fuel transaction reconciliation", status: "in_progress", detail: "Integration workspace prepared", lastSyncAt: null }, { key: "wheelseye", name: "WheelsEye", purpose: "GPS location, daily kilometres and route visibility", status: "not_configured", detail: "Access token required", lastSyncAt: null }], featureReady: false, stationOptions: locations.map((location) => ({ code: normalized(location.station_code), name: text(location.station_name || location.city || location.station_code) })), errors };
  if (!supabaseAdmin) return { ...base, errors: [...errors, "Database service is unavailable."] };

  let vehicleQuery = supabaseAdmin.from("fleet_vehicles").select("id,vehicle_no,station_code,model,fuel_type,status,registration_expiry,insurance_expiry,puc_expiry,fitness_expiry,tax_expiry").eq("company_id", companyId).order("vehicle_no");
  if (!authorization.hasAllLocationAccess) vehicleQuery = vehicleQuery.in("station_code", stationCodes.length ? stationCodes : ["__NO_STATION__"]);
  let paymentQuery = supabaseAdmin.from("payment_requests").select("id,request_no,location_id,location_code,station_code,payment_head_id,amount,amount_approved,amount_requested,status,approval_status,current_approver_user_id,current_approver_role_id,current_approver_role_ids,requested_by,created_at,work_date,remarks,notes,details,profiles:requested_by(full_name,email)").eq("company_id", companyId).order("created_at", { ascending: false }).limit(1000);
  if (!authorization.hasAllLocationAccess) paymentQuery = paymentQuery.in("location_id", authorization.locationScopeIds.length ? authorization.locationScopeIds : ["00000000-0000-0000-0000-000000000000"]);
  const [vehiclesResult, headsResult, paymentsResult, adHocResult] = await Promise.all([vehicleQuery, supabaseAdmin.from("payment_heads").select("id,code,name").eq("company_id", companyId).eq("is_active", true), paymentQuery, loadAdHocActivity(companyId, locations, monthStart, today)]);
  if (vehiclesResult.error) errors.push(vehiclesResult.error.message); if (headsResult.error) errors.push(headsResult.error.message); if (paymentsResult.error) errors.push(paymentsResult.error.message); if (adHocResult.error) errors.push(adHocResult.error);
  let vehicles = ((vehiclesResult.data ?? []) as VehicleRow[]).map((row) => mapVehicle(row, today)); const vehicleById = new Map(vehicles.map((vehicle) => [vehicle.id, vehicle]));
  const heads = (headsResult.data ?? []) as PaymentHeadRow[]; const vehicleHeadIds = new Set(heads.filter(isFleetManagerPaymentHead).map((head) => head.id)); const headById = new Map(heads.map((head) => [head.id, head]));
  const paymentRows = ((paymentsResult.data ?? []) as unknown as PaymentRow[]).filter((row) => vehicleHeadIds.has(row.payment_head_id)); const pendingRows = paymentRows.filter(isPendingPayment); const eligibleIds = await getPaymentApprovalEligibility(companyId, authorization, pendingRows); const canEditApprovals = hasPermission(authorization, "payment_approvals", "edit");
  const payments = paymentRows.map((row): FleetControlPayment => { const head = headById.get(row.payment_head_id); const profile = firstRelation(row.profiles); return { id: row.id, requestNo: text(row.request_no) || row.id, stationCode: normalized(row.station_code || row.location_code) || "UNASSIGNED", head: text(head?.name || head?.code) || "Vehicle expense", amount: numberValue(row.amount_approved ?? row.amount ?? row.amount_requested), requestedBy: text(profile?.full_name || profile?.email) || "Station team", requestedAt: row.created_at, workDate: row.work_date, status: normalized(row.approval_status || row.status).toLowerCase(), statusLabel: paymentStatus(row), remarks: text(row.remarks || row.notes) || "No remarks recorded", canApprove: canEditApprovals && eligibleIds.has(row.id) }; });
  const adHocRows = adHocResult.stations.flatMap((station) => station.days.flatMap((day) => day.entries.filter((entry) => entry.category === "Van").map((entry): FleetControlAdHocRow => ({ id: entry.id, date: day.date, stationCode: station.code, stationName: station.name, reference: entry.reference, source: entry.source, reason: entry.reason, remark: entry.remark, amount: entry.amount })))).sort((a, b) => b.date.localeCompare(a.date) || a.stationCode.localeCompare(b.stationCode));

  const scopeVehicleIds = vehicles.map((vehicle) => vehicle.id); const scoped = scopeVehicleIds.length ? scopeVehicleIds : ["00000000-0000-0000-0000-000000000000"];
  const [serviceResult, auditResult, templateResult, checklistResult, settingsResult, membershipResult, wheelseyeResult, gpsSyncResult, fuelSyncResult, evidenceResult] = await Promise.all([
    supabaseAdmin.from("fleet_service_history").select("id,vehicle_id,service_date,service_type,odometer_km,vendor_name,vendor_contact,amount,status,description,invoice_url,next_service_date,next_service_odometer_km,downtime_hours").eq("company_id", companyId).in("vehicle_id", scoped).order("service_date", { ascending: false }).limit(500),
    supabaseAdmin.from("fleet_audits").select("id,vehicle_id,template_id,scheduled_for,scheduled_reason,risk_score,status,score,summary,completed_at,email_status").eq("company_id", companyId).in("vehicle_id", scoped).order("scheduled_for", { ascending: false }).limit(500),
    supabaseAdmin.from("fleet_audit_templates").select("id,name,description,cadence_days,is_default").eq("company_id", companyId).eq("is_active", true).order("name"),
    supabaseAdmin.from("fleet_audit_checklist_items").select("id,template_id,category,label,guidance,response_type,is_required,failure_severity,sort_order").eq("company_id", companyId).eq("is_active", true).order("sort_order"),
    supabaseAdmin.from("fleet_control_settings").select("default_audit_cadence_days,document_warning_days,service_warning_days,auto_suggest_audits,breakdown_vehicle_link_required,audit_email_enabled,audit_video_required").eq("company_id", companyId).maybeSingle(),
    supabaseAdmin.from("fleet_portal_memberships").select("id,user_id,access_level,has_all_location_access,location_scope_ids,is_active,profiles:user_id(full_name,email)").eq("company_id", companyId).order("created_at"),
    supabaseAdmin.from("wheelseye_settings").select("is_enabled,token_secret_id").eq("company_id", companyId).eq("id", true).maybeSingle(),
    supabaseAdmin.from("fleet_daily_km").select("calculated_at").eq("company_id", companyId).order("calculated_at", { ascending: false }).limit(1),
    supabaseAdmin.from("fleet_fuel_transactions").select("uploaded_at,provider").eq("company_id", companyId).order("uploaded_at", { ascending: false }).limit(1),
    supabaseAdmin.from("fleet_audit_evidence").select("audit_id").eq("company_id", companyId).limit(2000)
  ]);
  const featureErrors = [serviceResult, auditResult, templateResult, checklistResult, settingsResult, membershipResult, evidenceResult].flatMap((result) => result.error ? [result.error.message] : []); const featureReady = !featureErrors.some(isFeatureSetupError); featureErrors.filter((message) => !isFeatureSetupError(message)).forEach((message) => errors.push(message));
  const serviceHistory: FleetServiceRecord[] = (serviceResult.data ?? []).map((row: any) => { const vehicle = vehicleById.get(row.vehicle_id); return { id: row.id, vehicleId: row.vehicle_id, vehicleNo: vehicle?.vehicleNo ?? "Unknown", stationCode: vehicle?.stationCode ?? "—", serviceDate: row.service_date, serviceType: text(row.service_type), odometerKm: nullableNumber(row.odometer_km), vendorName: text(row.vendor_name), vendorContact: text(row.vendor_contact), amount: numberValue(row.amount), status: text(row.status), description: text(row.description), invoiceUrl: text(row.invoice_url), nextServiceDate: row.next_service_date, nextServiceOdometerKm: nullableNumber(row.next_service_odometer_km), downtimeHours: nullableNumber(row.downtime_hours) }; });
  const latestServiceByVehicle = new Map<string, FleetServiceRecord>(); serviceHistory.forEach((record) => { if (!latestServiceByVehicle.has(record.vehicleId)) latestServiceByVehicle.set(record.vehicleId, record); });
  const evidenceCount = new Map<string, number>(); (evidenceResult.data ?? []).forEach((row: any) => evidenceCount.set(row.audit_id, (evidenceCount.get(row.audit_id) ?? 0) + 1));
  const audits: FleetAudit[] = (auditResult.data ?? []).map((row: any) => { const vehicle = vehicleById.get(row.vehicle_id); return { id: row.id, vehicleId: row.vehicle_id, vehicleNo: vehicle?.vehicleNo ?? "Unknown", stationCode: vehicle?.stationCode ?? "—", templateId: row.template_id, scheduledFor: row.scheduled_for, scheduledReason: text(row.scheduled_reason), riskScore: numberValue(row.risk_score), status: text(row.status), score: nullableNumber(row.score), summary: text(row.summary), completedAt: row.completed_at, emailStatus: text(row.email_status || "not_sent"), evidenceCount: evidenceCount.get(row.id) ?? 0 }; });
  const latestAuditByVehicle = new Map<string, FleetAudit>(); audits.filter((audit) => ["passed", "failed"].includes(audit.status)).forEach((audit) => { if (!latestAuditByVehicle.has(audit.vehicleId)) latestAuditByVehicle.set(audit.vehicleId, audit); });
  vehicles = vehicles.map((vehicle) => { const service = latestServiceByVehicle.get(vehicle.id); const audit = latestAuditByVehicle.get(vehicle.id); return { ...vehicle, lastServiceDate: service?.serviceDate ?? null, nextServiceDate: service?.nextServiceDate ?? null, nextServiceOdometerKm: service?.nextServiceOdometerKm ?? null, lastAuditDate: audit?.completedAt?.slice(0, 10) ?? null }; });
  const settingsRow = settingsResult.data as any; const settings: FleetControlSettings = settingsRow ? { defaultAuditCadenceDays: numberValue(settingsRow.default_audit_cadence_days) || 30, documentWarningDays: numberValue(settingsRow.document_warning_days) || 30, serviceWarningDays: numberValue(settingsRow.service_warning_days) || 14, autoSuggestAudits: Boolean(settingsRow.auto_suggest_audits), breakdownVehicleLinkRequired: Boolean(settingsRow.breakdown_vehicle_link_required), auditEmailEnabled: settingsRow.audit_email_enabled !== false, auditVideoRequired: settingsRow.audit_video_required !== false } : defaultSettings();
  const checklistItems: FleetChecklistItem[] = (checklistResult.data ?? []).map((row: any) => ({ id: row.id, templateId: row.template_id, category: text(row.category), label: text(row.label), guidance: text(row.guidance), responseType: text(row.response_type), isRequired: Boolean(row.is_required), failureSeverity: text(row.failure_severity), sortOrder: numberValue(row.sort_order) }));
  const auditTemplates: FleetAuditTemplate[] = (templateResult.data ?? []).map((row: any) => ({ id: row.id, name: text(row.name), description: text(row.description), cadenceDays: numberValue(row.cadence_days), isDefault: Boolean(row.is_default), itemCount: checklistItems.filter((item) => item.templateId === row.id).length }));
  const activeAuditVehicleIds = new Set(audits.filter((audit) => ["scheduled", "in_progress"].includes(audit.status)).map((audit) => audit.vehicleId));
  const auditSuggestions: FleetAuditSuggestion[] = settings.autoSuggestAudits ? vehicles.flatMap((vehicle) => { if (activeAuditVehicleIds.has(vehicle.id) || ["sold", "disposed", "returned"].includes(vehicle.status)) return []; let score = 0; const reasons: string[] = []; if (vehicle.status === "breakdown") { score += 40; reasons.push("vehicle is in breakdown"); } if (vehicle.status === "under_service") { score += 25; reasons.push("vehicle is under service"); } if (vehicle.nextDocumentDays != null && vehicle.nextDocumentDays < 0) { score += 25; reasons.push(`${vehicle.nextDocument} has expired`); } else if (vehicle.nextDocumentDays != null && vehicle.nextDocumentDays <= settings.documentWarningDays) { score += 12; reasons.push(`${vehicle.nextDocument} expires soon`); } const lastAudit = latestAuditByVehicle.get(vehicle.id); if (!lastAudit) { score += 20; reasons.push("no completed audit in Fleet"); } else { const auditDate = lastAudit.completedAt?.slice(0, 10) ?? lastAudit.scheduledFor; const age = dayDifference(today, auditDate) ?? 0; if (age >= settings.defaultAuditCadenceDays) { score += 25; reasons.push(`last audit was ${age} days ago`); } if (lastAudit.status === "failed") { score += 20; reasons.push("last audit failed"); } } const service = latestServiceByVehicle.get(vehicle.id); if (service?.nextServiceDate && (dayDifference(service.nextServiceDate, today) ?? 999) <= settings.serviceWarningDays) { score += 20; reasons.push("service is due soon"); } if (score < 20) return []; return [{ vehicleId: vehicle.id, vehicleNo: vehicle.vehicleNo, stationCode: vehicle.stationCode, riskScore: Math.min(score, 100), reasons, recommendedFor: score >= 50 ? today : addDays(today, 7) }]; }).sort((a, b) => b.riskScore - a.riskScore) : [];
  const members: FleetPortalMember[] = (membershipResult.data ?? []).map((row: any) => { const profile = firstRelation(row.profiles as any) as any; return { id: row.id, userId: row.user_id, name: text(profile?.full_name) || text(profile?.email) || "User", email: text(profile?.email), accessLevel: text(row.access_level), scope: row.has_all_location_access ? "All stations" : `${Array.isArray(row.location_scope_ids) ? row.location_scope_ids.length : 0} stations`, isActive: Boolean(row.is_active) }; });
  const gpsLast = (gpsSyncResult.data?.[0] as any)?.calculated_at ?? null; const fuelLast = (fuelSyncResult.data?.[0] as any)?.uploaded_at ?? null; const fuelProvider = text((fuelSyncResult.data?.[0] as any)?.provider);
  const integrations: FleetIntegration[] = [{ key: "paytap", name: "Paytap", purpose: "Fuel cards and fuel transaction reconciliation", status: fuelProvider.toLowerCase() === "paytap" ? "connected" : "in_progress", detail: fuelProvider ? `Latest fuel source: ${fuelProvider}` : "Connector and vehicle mapping are being prepared", lastSyncAt: fuelLast }, { key: "wheelseye", name: "WheelsEye", purpose: "GPS location, daily kilometres and route visibility", status: (wheelseyeResult.data as any)?.is_enabled && (wheelseyeResult.data as any)?.token_secret_id ? "connected" : "not_configured", detail: (wheelseyeResult.data as any)?.is_enabled ? "GPS access token configured" : "GPS connection is not enabled", lastSyncAt: gpsLast }];
  const actionablePayments = payments.filter((payment) => payment.canApprove); const underService = vehicles.filter((vehicle) => ["under_service", "breakdown"].includes(vehicle.status)); const documentAttention = vehicles.filter((vehicle) => vehicle.nextDocumentDays != null && vehicle.nextDocumentDays <= settings.documentWarningDays); const adHocToday = adHocRows.filter((row) => row.date === today); const serviceDue = vehicles.filter((vehicle) => vehicle.nextServiceDate && (dayDifference(vehicle.nextServiceDate, today) ?? 999) <= settings.serviceWarningDays);
  return { ...base, vehicles, payments, adHocRows, serviceHistory, audits, auditSuggestions, auditTemplates, checklistItems, members, settings, integrations, featureReady, counts: { vehicles: vehicles.length, active: vehicles.filter((vehicle) => vehicle.status === "active").length, underService: underService.length, unavailable: vehicles.filter((vehicle) => vehicle.status !== "active").length, documentAttention: documentAttention.length, pendingPayments: actionablePayments.length, pendingAmount: actionablePayments.reduce((sum, payment) => sum + payment.amount, 0), adHocToday: adHocToday.length, adHocTodayAmount: adHocToday.reduce((sum, row) => sum + row.amount, 0), serviceDue: serviceDue.length, auditsDue: auditSuggestions.length + audits.filter((audit) => audit.status === "scheduled" && audit.scheduledFor <= today).length }, errors: [...new Set(errors)] };
}
