import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import { randomUUID } from 'node:crypto';
import * as policy from './payment-reminder-policy.ts';
import * as stages from './payment-stage-policy.ts';
function setup() {
  const sent=[];
  const tables={ payment_notification_templates:[{event_type:'payment_request',company_id:'company',is_enabled:true,reminder_interval_minutes:90,thread_by_station_month:true,reminder_work_hours:policy.defaultPaymentWorkHours},{event_type:'payment_reminder',company_id:'company',is_enabled:true}],payment_requests:[{id:'r1',company_id:'company',location_id:'station',location_code:'QLDA',status:'pending',approval_status:'PENDING',current_approver_user_id:'manager',email_next_reminder_at:null,email_send_count:0}],payment_email_attempts:[],payment_notification_threads:[] };
  const db={from(table){let filters=[],op='select',values,single=false;const q={select(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},in(k,v){filters.push(r=>v.includes(r[k]));return q;},limit(){return q;},single(){single=true;return q;},insert(v){op='insert';values=v;return q;},update(v){op='update';values=v;return q;},then(resolve){let rows=tables[table].filter(r=>filters.every(f=>f(r)));if(op==='insert'){const row={id:randomUUID(),...values};tables[table].push(row);rows=[row];}if(op==='update')rows.forEach(r=>Object.assign(r,values));return Promise.resolve({data:single?{...rows[0]}:rows.map(r=>({...r})),error:null}).then(resolve);}};return q;},async rpc(name,args){let thread=tables.payment_notification_threads.find(t=>t.location_id===args.p_location&&t.thread_month===args.p_month);if(!thread){thread={id:randomUUID(),location_id:args.p_location,thread_month:args.p_month,message_id:'<root@test>',last_message_id:null,subject:args.p_subject};tables.payment_notification_threads.push(thread);}if(thread.lock_token)return {data:[],error:null};thread.lock_token=args.p_token;return {data:[{...thread}],error:null};}};
  const source=readFileSync(new URL('./payment-mail-delivery.ts',import.meta.url),'utf8');
  const exports={};
  vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,console,Date,Intl,Set,require(name){if(name==='node:crypto')return {randomUUID};if(name.endsWith('supabase-admin'))return {supabaseAdmin:db};if(name.endsWith('/email'))return {sendEmail:async mail=>{sent.push(mail);return {messageId:mail.messageId};}};if(name.endsWith('payment-stage-policy'))return stages;if(name.endsWith('payment-reminder-policy'))return policy;throw Error(name);}});
  const send=(extra={})=>exports.deliverPaymentMail({companyId:'company',requestId:'r1',expectedApprover:'manager',eventType:'payment_reminder',reminder:true,catchUp:true,mail:{companyId:'company',to:['manager@example.test'],subject:'original',body:'Approve, Return or Reject'},...extra});
  return {send,tables,sent};
}
test('first catch-up accepted and repeated invocation skips not-yet-due request',async()=>{const x=setup();assert.equal((await x.send()).sent,true);assert.equal((await x.send()).sent,false);assert.equal(x.sent.length,1);assert.equal(x.tables.payment_email_attempts[0].status,'accepted');});
test('different requests and approvers share exactly one station/month chain',async()=>{const x=setup();await x.send();x.tables.payment_requests.push({...x.tables.payment_requests[0],id:'r2',current_approver_user_id:'next-manager',email_next_reminder_at:null});await x.send({requestId:'r2',expectedApprover:'next-manager',mail:{to:['next@example.test'],body:'review',subject:'other'}});assert.equal(x.sent.length,2);assert.equal(x.sent[0].subject,x.sent[1].subject);assert.equal(x.sent[1].inReplyTo,x.sent[0].messageId);assert.deepEqual(Array.from(x.sent[1].references),[x.sent[0].messageId]);assert.equal(x.tables.payment_notification_threads.length,1);});
test('terminal statuses and changed assignments never send',async()=>{for(const status of ['approved','returned','rejected','processed']){const x=setup();x.tables.payment_requests[0].status=status;assert.equal((await x.send()).sent,false);assert.equal(x.sent.length,0);}const x=setup();x.tables.payment_requests[0].current_approver_user_id='different';assert.equal((await x.send()).sent,false);});
test('intermediate approvals continue reminders for next assigned stage',async()=>{const x=setup();x.tables.payment_requests[0].status='OPERATIONS_BH_APPROVED';assert.equal((await x.send()).sent,true);assert.ok(x.tables.payment_requests[0].email_next_reminder_at);});
test('disabled reminders and uncertain prior sends cannot be resent',async()=>{const x=setup();x.tables.payment_notification_templates[1].is_enabled=false;assert.equal((await x.send()).sent,false);const y=setup();y.tables.payment_email_attempts.push({id:'uncertain',company_id:'company',request_id:'r1',status:'uncertain'});assert.equal((await y.send()).sent,false);assert.equal(y.sent.length,0);});
