import {test} from 'node:test';
import assert from 'node:assert/strict';
import {buildReviewMessages} from './review-digest-template.mjs';
const config={included_models:['EDSP'],recipient_role_codes:['MP'],email_domain:'example.test',send_zero_cases:true};
const snapshot=()=>({performanceDate:'2026-09-27',digestDate:'2026-09-28',stations:[{id:'s',station_code:'JDBD',station_name:'Test station',model:'EDSP'}],recipients:[{email:'owner@example.test',full_name:'Owner',designation_code:'MP',designation:'Owner',station_codes:['JDBD']}],routes:{s:{chain:[{reviewerName:'INAYATH SHAIK',reviewerRole:'Head Operations- Last Mile'}],error:null}},reviews:[],steps:[]});
test('unstarted digest uses People route and includes Ops Head',()=>{const mail=buildReviewMessages(snapshot(),config,'Review')[0];assert.match(mail.html,/Next: INAYATH SHAIK/);assert.equal(mail.scope.pendingStages,1);});
test('superseded assignment is not another skipped or pending review',()=>{const s=snapshot();s.reviews=[{id:'r',station_id:'s',status:'in_review'}];s.steps=[{review_id:'r',step_order:1,status:'skipped',reviewer_name:'OLD HEAD',reviewer_role:'National',route_superseded_at:'2026-09-28'},{review_id:'r',step_order:2,status:'pending',reviewer_name:'INAYATH SHAIK',reviewer_role:'Head Operations- Last Mile'}];const mail=buildReviewMessages(s,config,'Review')[0];assert.doesNotMatch(mail.html,/OLD HEAD/);assert.match(mail.html,/Next: INAYATH SHAIK/);assert.equal(mail.scope.pendingStages,1);});
test('mapping errors suppress stale pending names and are explicit in HTML and text',()=>{const s=snapshot();s.routes.s.error='Missing manager';s.reviews=[{id:'r',station_id:'s',status:'in_review',routing_error:'Missing manager'}];s.steps=[{review_id:'r',step_order:1,status:'pending',reviewer_name:'OLD HEAD',reviewer_role:'National'}];const mail=buildReviewMessages(s,config,'Review')[0];assert.doesNotMatch(mail.html,/OLD HEAD/);assert.match(mail.html,/Missing manager/);assert.match(mail.text,/Missing manager/);});
test('closed historical reviews do not change with current People mapping',()=>{const s=snapshot();s.routes.s.error='Missing manager';s.reviews=[{id:'r',station_id:'s',status:'closed'}];s.steps=[{review_id:'r',step_order:1,status:'completed',reviewer_name:'Historical reviewer',reviewer_role:'National',completed_at:'2026-09-27T12:00:00Z'}];const mail=buildReviewMessages(s,config,'Review')[0];assert.match(mail.html,/Historical reviewer/);assert.doesNotMatch(mail.html,/Missing manager/);assert.equal(mail.scope.complete,1);});
