'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import type {MasterRecord,BusinessMasterKind} from '@/lib/finance/now';
import {saveBusinessMaster} from './actions';
const sections:Record<BusinessMasterKind,string>={now_rate:'Rate cards',now_store:'Store categories',cost_head:'Expense heads',contract:'Outsourced contracts',overhead:'HO allocation',insight:'AI insights'};
const empty:Record<BusinessMasterKind,Record<string,any>>={now_rate:{category:'',city:'',monthly_mg:'',mg_upd:'',monthly_incentive:'0',slab_mode:'progressive',slabs:[],effective_from:'',source:''},now_store:{station_code:'',category:'',city:'',rate_key:'',monthly_mg_override:'',effective_from:''},cost_head:{description:''},contract:{head_key:'',station_code:'',vendor:'',amount:'',frequency:'monthly',effective_from:'',settlement_heads:[],reference:''},overhead:{station_code:'',mode:'regional',recipient_codes:[],effective_from:''},insight:{model:'',enabled:false}};
const labels:Record<string,string>={monthly_mg:'Monthly MG (₹)',mg_upd:'MG units per day',monthly_incentive:'Monthly incentive (₹)',monthly_mg_override:'Store MG override (optional ₹)',effective_from:'Effective from',effective_to:'Effective through (optional)',source:'Source / agreement',station_code:'Location',rate_key:'Rate card',head_key:'Expense head',amount:'Contract amount (₹)',settlement_heads:'Payment heads already covered by this contract',recipient_codes:'Operating locations sharing this HO cost',slab_mode:'Excess unit calculation'};
export function BusinessMasterEditor({records,locations,canAdd,canEdit}:{records:MasterRecord[];locations:{code:string;name:string;ho:boolean}[];canAdd:boolean;canEdit:boolean}){
 const router=useRouter();const [kind,setKind]=useState<BusinessMasterKind>('now_store'),[edit,setEdit]=useState<{key:string;label:string;data:Record<string,any>;revision:number}|null>(null),[message,setMessage]=useState(''),[pending,start]=useTransition(),[search,setSearch]=useState('');
 const data=edit?.data||{};const set=(k:string,v:any)=>setEdit(e=>e&&({...e,data:{...e.data,[k]:v}}));
 const save=(remove=false)=>{if(!edit)return;start(async()=>{const r=await saveBusinessMaster({...edit,kind,remove});setMessage(r.ok?(remove?'Record deleted.':'Saved.'):r.error);if(r.ok){setEdit(null);router.refresh();}});};
 return <div className="cfo"><nav className="cfo-tabs">{Object.entries(sections).map(([k,v])=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k as BusinessMasterKind);setEdit(null);}}>{v}</button>)}<Link href="/master/rent">Station & HO rent ↗</Link><Link href="/finance/profitability">P&L ↗</Link></nav><div className="cfo-toolbar"><input aria-label="Search master" placeholder="Search records" value={search} onChange={e=>setSearch(e.target.value)}/>{canAdd&&<button onClick={()=>setEdit({key:'',label:'',data:structuredClone(empty[kind]),revision:0})}>+ Add {sections[kind].toLowerCase()}</button>}</div>{message&&<p role="status">{message}</p>}
 {edit&&<form className="cfo-panel" onSubmit={e=>{e.preventDefault();save();}}><h2>{edit.revision?'Edit':'Add'} {sections[kind].toLowerCase()}</h2><div className="cfo-fields"><label>Record key<input required disabled={!!edit.revision} value={edit.key} placeholder="Unique reference" onChange={e=>setEdit({...edit,key:e.target.value})}/></label><label>Name<input required value={edit.label} onChange={e=>setEdit({...edit,label:e.target.value})}/></label>{Object.keys({...empty[kind],...data,...(['now_rate','now_store','contract','overhead'].includes(kind)?{effective_to:''}:{})}).filter(k=>!['slabs','recipient_codes','settlement_heads'].includes(k)).map(k=>{
 let options:{value:string;label:string}[]|null=null;
 if(k==='station_code')options=locations.filter(l=>kind!=='overhead'||l.ho).map(l=>({value:l.code,label:l.code+' · '+l.name}));
 if(k==='rate_key'||k==='head_key')options=records.filter(r=>r.kind===(k==='rate_key'?'now_rate':'cost_head')).map(r=>({value:r.key,label:r.label}));
 if(k==='frequency')options=['monthly','annual','once'].map(value=>({value,label:value}));
 if(k==='mode')options=[{value:'regional',label:'Share across selected locations'},{value:'corporate',label:'Central HO — separate business expense'}];
 if(k==='slab_mode')options=[{value:'progressive',label:'Progressive — each excess band'},{value:'all_excess',label:'One rate on all excess units'},{value:'unconfirmed',label:'Unconfirmed — exclude excess'}];
 return <label key={k}>{labels[k]||k.replaceAll('_',' ')}{typeof data[k]==='boolean'?<input type="checkbox" checked={data[k]} onChange={e=>set(k,e.target.checked)}/>:options?<select value={data[k]||''} onChange={e=>{set(k,e.target.value);if(k==='rate_key'){const r=records.find(r=>r.key===e.target.value&&r.kind==='now_rate');if(r)setEdit(old=>old&&({...old,data:{...old.data,rate_key:r.key,category:r.data.category,city:r.data.city}}));}}}><option value="">Choose…</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input type={k.startsWith('effective_')?'date':'text'} value={data[k]??''} onChange={e=>set(k,e.target.value)}/>}</label>;
 })}</div>
 {kind==='now_rate'&&<div className="cfo-scroll"><h3>Excess UPD bands</h3><table><thead><tr>{['Above units/day','Up to (blank = unlimited)','Base ₹/unit','Incentive ₹/unit',''].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{(data.slabs||[]).map((s:any,i:number)=><tr key={i}>{['above','upto','base','incentive'].map(k=><td key={k}><input aria-label={`${k} slab ${i+1}`} type="number" min="0" step={['base','incentive'].includes(k)?'.01':'1'} value={s[k]??''} onChange={e=>set('slabs',data.slabs.map((x:any,j:number)=>i===j?{...x,[k]:e.target.value}:x))}/></td>)}<td><button type="button" onClick={()=>set('slabs',data.slabs.filter((_:any,j:number)=>i!==j))}>Remove</button></td></tr>)}</tbody></table><button type="button" onClick={()=>set('slabs',[...data.slabs,{above:'',upto:'',base:'',incentive:'0'}])}>+ Band</button><p className="cfo-muted">Gaps are flagged in P&L. No rate is inferred for an unpriced band.</p></div>}
 {kind==='overhead'&&data.mode==='regional'&&<fieldset><legend>{labels.recipient_codes}</legend><div className="cfo-choices">{locations.filter(l=>!l.ho).map(l=><label key={l.code}><input type="checkbox" checked={data.recipient_codes.includes(l.code)} onChange={e=>set('recipient_codes',e.target.checked?[...data.recipient_codes,l.code]:data.recipient_codes.filter((s:string)=>s!==l.code))}/>{l.code} · {l.name}</label>)}</div><p>Equal shares use the full configured group even when the report is filtered.</p></fieldset>}
 {kind==='contract'&&<label>{labels.settlement_heads}<textarea value={data.settlement_heads.join('\n')} onChange={e=>set('settlement_heads',e.target.value.split('\n'))}/><small>One exact head per line. Matching booked costs at this location and within these dates are replaced by the contract accrual, preventing double counting.</small></label>}
 <div className="cfo-toolbar"><button disabled={pending} type="submit">{pending?'Saving…':'Save'}</button><button type="button" onClick={()=>setEdit(null)}>Cancel</button>{edit.revision>0&&<button type="button" disabled={pending} onClick={()=>{if(confirm('Delete this master record? Its change history is retained.'))save(true);}}>Delete</button>}</div></form>}
 <div className="cfo-panel cfo-scroll"><table><thead><tr><th>Name</th><th>Configuration</th><th>Effective from</th><th>Revision</th><th/></tr></thead><tbody>{records.filter(r=>r.kind===kind&&`${r.label} ${r.key} ${r.data.station_code||''}`.toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.id}><td><b>{r.label}</b><small>{r.key}</small></td><td>{kind==='now_rate'?`${r.data.category} · ${r.data.city} · ₹${Number(r.data.monthly_mg).toLocaleString('en-IN')} MG · ${r.data.mg_upd} UPD`:kind==='now_store'?`${r.data.station_code} · ${r.data.category} · ${r.data.city}`:kind==='contract'?`${r.data.station_code} · ${r.data.vendor} · ₹${r.data.amount} / ${r.data.frequency}`:kind==='overhead'?`${r.data.station_code} · ${r.data.mode} · ${r.data.recipient_codes.length} recipients`:kind==='insight'?`${r.data.model} · ${r.data.enabled?'Enabled':'Disabled'}`:r.data.description}</td><td>{r.data.effective_from||'—'}</td><td>{r.revision}</td><td>{canEdit&&<button onClick={()=>setEdit({key:r.key,label:r.label,data:structuredClone(r.data),revision:r.revision})}>Edit</button>}</td></tr>)}</tbody></table></div></div>;
}
