'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import type {MasterRecord} from '@/lib/finance/now';
import {saveBusinessMaster} from './actions';
export function RegionMappings({records,locations,canAdd,canEdit}:{records:MasterRecord[];locations:{code:string;name:string;ho:boolean;region:string;model:string}[];canAdd:boolean;canEdit:boolean}){
 const router=useRouter();const [search,setSearch]=useState(''),[region,setRegion]=useState(''),[edit,setEdit]=useState<string|null>(null),[value,setValue]=useState(''),[message,setMessage]=useState(''),[pending,start]=useTransition();
 const rows=locations.filter(l=>!l.ho).map(l=>{const record=records.find(r=>r.kind==='reporting_region'&&r.data.station_code===l.code);return {...l,record,mapped:record?.data.region||l.region};});
 const save=(code:string)=>start(async()=>{const row=rows.find(r=>r.code===code)!;const result=await saveBusinessMaster({kind:'reporting_region',key:code,label:code+' · reporting region',data:{station_code:code,region:value},revision:row.record?.revision||0});setMessage(result.ok?'Region saved. P&L will use this mapping.':result.error);if(result.ok){setEdit(null);router.refresh();}});
 return <section className="cfo-panel"><h2>Regions & stations</h2><p>Assign each station or Amazon Now store to its reporting region. Stations without an override use their existing region. XPT revenue follows its parent station. Changes affect Finance reporting; operational location and payroll settings stay intact.</p><div className="cfo-toolbar"><input aria-label="Find region mapping" placeholder="Station, store or model" value={search} onChange={e=>setSearch(e.target.value)}/><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">All regions</option>{[...new Set(rows.map(r=>r.mapped))].sort().map(r=><option key={r}>{r}</option>)}</select></label></div>{message&&<p role="status">{message}</p>}<datalist id="finance-region-names">{[...new Set(rows.map(r=>r.mapped).filter(r=>r!=='Unassigned'))].sort().map(r=><option key={r} value={r}/>)}</datalist><div className="cfo-scroll"><table><thead><tr><th>Station / store</th><th>Business model</th><th>Reporting region</th><th>Source</th><th/></tr></thead><tbody>{rows.filter(r=>(!region||r.mapped===region)&&`${r.code} ${r.name} ${r.model}`.toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.code}><td><b>{r.code}</b><small>{r.name}</small></td><td>{r.model}</td><td>{edit===r.code?<input aria-label={`Region for ${r.code}`} list="finance-region-names" maxLength={100} value={value} onChange={e=>setValue(e.target.value)}/>:r.mapped}</td><td>{r.record?'Finance Master':'Location Master'}</td><td>{edit===r.code?<><button disabled={pending||!value.trim()} onClick={()=>save(r.code)}>{pending?'Saving…':'Save'}</button><button disabled={pending} onClick={()=>setEdit(null)}>Cancel</button></>:(r.record?canEdit:canAdd)&&<button onClick={()=>{setEdit(r.code);setValue(r.mapped==='Unassigned'?'':r.mapped);}}>Edit region</button>}</td></tr>)}</tbody></table></div></section>;
}
