'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import type {CfoReport} from '@/lib/finance/cfo-data';
import {totalCfo,groupCfo,type CfoDay} from '@/lib/finance/cfo';
const money=(n:number|null)=>n===null?'—':'₹'+n.toLocaleString('en-IN',{maximumFractionDigits:2});
const num=(n:number|null)=>n===null?'—':n.toLocaleString('en-IN',{maximumFractionDigits:1});
const unique=(values:string[])=>[...new Set(values)].sort();
export function CfoWorkspace({report:r}:{report:CfoReport}){
 const [period,setPeriod]=useState(r.filters.period),[section,setSection]=useState('overview'),[by,setBy]=useState<'station'|'model'|'region'|'city'|'month'|'day'>('model'),[model,setModel]=useState(''),[region,setRegion]=useState(''),[city,setCity]=useState(''),[search,setSearch]=useState(''),[sort,setSort]=useState<{key:'key'|'revenue'|'expense'|'profit'|'margin';desc:boolean}>({key:'profit',desc:false}),[ai,setAi]=useState(''),[busy,setBusy]=useState(false);
 const rows=useMemo(()=>r.days.filter(d=>(!model||d.model===model)&&(!region||d.region===region)&&(!city||d.city===city)&&(!search||`${d.station} ${d.name} ${d.model} ${d.region} ${d.city}`.toLowerCase().includes(search.toLowerCase()))),[r.days,model,region,city,search]);
 const isBusiness=!model&&!region&&!city&&!search,corp=r.overhead.filter(o=>o.mode==='corporate'||o.mode==='unallocated').reduce((s,o)=>s+o.amount,0),total=totalCfo(rows,isBusiness?corp:0);
 const groups=groupCfo(rows,by).sort((a,b)=>{const av=a[sort.key],bv=b[sort.key];return(av===null?1:bv===null?-1:typeof av==='string'?av.localeCompare(String(bv)):Number(av)-Number(bv))*(sort.desc?-1:1);});
 const daily=groupCfo(rows,'day'),max=Math.max(1,...daily.flatMap(d=>[d.revenue||0,d.expense||0]));
 const issues=unique([...r.issues,...total.issues,...r.overhead.flatMap(o=>o.issue?[`${o.station}: ${o.issue}`]:[])]);
 const download=()=>{const fields=['Group','Revenue','Direct costs','Regional overhead','Expenses','Profit / loss','Margin %','Volume','Unit','Fully loaded CPS / CPU'];const data=[fields,...groups.map(g=>[g.key,g.revenue,g.direct,g.regional,g.expense,g.profit,g.margin,g.volume,g.unit,g.cpu])];const csv='\ufeff'+data.map(row=>row.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`profitability-${r.filters.from}-${r.filters.to}.csv`;a.click();URL.revokeObjectURL(url);};
 async function insight(){setBusy(true);setAi('');try{const res=await fetch('/finance/profitability/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:r.filters.from,to:r.filters.to,model,region,city})});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to analyse.');setAi(data.text);}catch(e){setAi(e instanceof Error?e.message:'Unable to analyse.');}finally{setBusy(false);}}
 return <div className="cfo"><header className="cfo-header"><div><p className="cfo-kicker">Finance · Business intelligence</p><h1>Profitability, explained.</h1><p>Revenue, operating costs and overhead in one view.</p></div><div className="cfo-toolbar"><Link href="/finance/now-volumes">Update Now units</Link><Link href="/master/business">Business masters</Link><button onClick={download}>Export CSV</button><button onClick={()=>window.print()}>Save PDF</button></div></header>
 <form className="cfo-panel cfo-fields" action="/finance/profitability"><label>Period<select name="period" value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="mtd">Month to date</option><option value="last-month">Last month</option><option value="month">Selected month</option><option value="yesterday">Yesterday</option><option value="today">Today</option><option value="custom">Custom dates</option></select></label><label>Month<input name="month" type="month" defaultValue={r.filters.month}/></label><label>From<input name="from" type="date" defaultValue={r.filters.from} onChange={()=>setPeriod('custom')}/></label><label>Through<input name="to" type="date" defaultValue={r.filters.to} onChange={()=>setPeriod('custom')}/></label><button type="submit">Apply dates</button></form>
 <div className="cfo-toolbar"><label>Business model<select value={model} onChange={e=>setModel(e.target.value)}><option value="">All models</option>{unique(r.days.map(d=>d.model)).map(v=><option key={v}>{v}</option>)}</select></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}><option value="">All regions</option>{unique(r.days.map(d=>d.region)).map(v=><option key={v}>{v}</option>)}</select></label><label>City<select value={city} onChange={e=>setCity(e.target.value)}><option value="">All cities</option>{unique(r.days.map(d=>d.city)).map(v=><option key={v}>{v}</option>)}</select></label><label>Find a station<input placeholder="Code or name" value={search} onChange={e=>setSearch(e.target.value)}/></label><button onClick={()=>{setModel('');setRegion('');setCity('');setSearch('');}}>Reset view</button></div>
 <p className="cfo-muted">{r.filters.from} — {r.filters.to} · Latest available operating date: {r.cutoff}. Each station’s revenue and direct costs use matching dates. Amazon Now daily units and excess revenue are allocated from the entered monthly UPD.</p>
 <nav className="cfo-tabs">{[['overview','Overview'],['analysis','Models & locations'],['overhead','HO & shared costs'],['now','Amazon Now'],['attention',`Needs attention (${issues.length})`],['insights','Insights']].map(([key,label])=><button key={key} aria-pressed={section===key} onClick={()=>setSection(key)}>{label}</button>)}</nav>
 <div className="cfo-kpis">{[['Revenue',total.revenue,''],['Operating expenses',total.direct,''],['Regional overhead',total.regional,''],[isBusiness?'Central / unallocated HO':'Contribution after regional HO',isBusiness?corp:total.profit,''],[isBusiness?'Net operating profit / loss':'Operating profit / loss',total.profit,total.profit!==null&&total.profit<0?'negative':'positive']].map(([label,value,color])=><article className={String(color)} key={String(label)}><small>{label}</small><strong>{money(value as number|null)}</strong></article>)}</div>
 {issues.length>0&&<button className="cfo-notice" onClick={()=>setSection('attention')}>Provisional management view · {issues.length} input or coverage notes. Review before relying on net profit.</button>}
 {!isBusiness&&<p className="cfo-muted">Central HO remains a separate business expense. It is not arbitrarily allocated to the selected model or region.</p>}
 {section==='overview'&&<><div className="cfo-two"><section className="cfo-panel"><h2>Revenue and expenses</h2><p className="cfo-muted">Daily operating trend · regional overhead included, central HO shown separately.</p><div className="cfo-chart" role="img" aria-label="Daily revenue and expense bar chart"><svg viewBox={`0 0 ${Math.max(daily.length*24,200)} 150`} preserveAspectRatio="none">{daily.map((d,i)=><g key={d.key}><title>{d.key}: revenue {money(d.revenue)}, expenses {money(d.expense)}</title><rect x={i*24+3} y={130-(d.revenue||0)/max*110} width="8" height={(d.revenue||0)/max*110} fill="#167e72"/><rect x={i*24+12} y={130-(d.expense||0)/max*110} width="8" height={(d.expense||0)/max*110} fill="#f1844c"/></g>)}</svg></div><p className="cfo-muted">Green: revenue · Orange: expenses · {daily[0]?.key} to {daily.at(-1)?.key}</p><button onClick={()=>{setSection('analysis');setBy('day');}}>Explore daily figures →</button></section><section className="cfo-panel"><h2>Where profit goes</h2>{[['Revenue',total.revenue],['Direct operating costs',total.direct],['Regional HO share',total.regional],['Central & unallocated HO',isBusiness?corp:null],['Net operating profit / loss',total.profit]].map(([label,value])=><div className="cfo-waterfall" key={String(label)}><span>{label}</span><b>{money(value as number|null)}</b></div>)}<p className="cfo-muted">Management operating P&L, before tax and unrecorded accounting adjustments. Missing costs are listed under Needs attention.</p></section></div><section className="cfo-panel"><h2>Model contribution</h2>{groupCfo(rows,'model').map(g=><button className="cfo-model" key={g.key} onClick={()=>{setModel(g.key);setSection('analysis');setBy('station');}}><b>{g.key}</b><span>Revenue {money(g.revenue)}</span><span>Expenses {money(g.expense)}</span><strong className={g.profit!==null&&g.profit<0?'negative':'positive'}>{g.profit!==null&&g.profit<0?'Loss':'Profit'} {money(g.profit===null?null:Math.abs(g.profit))}</strong></button>)}</section></>}
 {section==='analysis'&&<section className="cfo-panel"><div className="cfo-toolbar"><h2>Compare & investigate</h2>{(['model','region','city','station','month','day'] as const).map(v=><button key={v} aria-pressed={by===v} onClick={()=>setBy(v)}>By {v}</button>)}</div><div className="cfo-scroll"><table><thead><tr>{[['key','Group'],['revenue','Revenue'],['expense','Expenses'],['profit','Profit / loss'],['margin','Margin']].map(([key,label])=><th key={key} aria-sort={sort.key===key?(sort.desc?'descending':'ascending'):'none'}><button onClick={()=>setSort({key:key as typeof sort.key,desc:sort.key===key?!sort.desc:false})}>{label} {sort.key===key?(sort.desc?'↓':'↑'):'↕'}</button></th>)}<th>Volume / unit</th><th>CPS / CPU<small>Including allocated overhead</small></th><th>Details</th></tr></thead><tbody>{!groups.length&&<tr><td colSpan={8}>No locations match these filters.</td></tr>}{groups.map(g=><tr key={g.key}><td><b>{g.key}</b></td><td>{money(g.revenue)}</td><td>{money(g.expense)}</td><td className={g.profit!==null&&g.profit<0?'negative':'positive'}>{g.profit===null?'Unavailable':`${g.profit<0?'Loss':'Profit'} ${money(Math.abs(g.profit))}`}</td><td>{num(g.margin)}{g.margin!==null?'%':''}</td><td>{num(g.volume)}<small>{g.unit==='mixed'?'Mixed units — not combined':g.unit}</small></td><td>{money(g.cpu)}</td><td><details><summary>Breakdown</summary><Detail days={g.days}/>{by==='station'&&g.unit==='shipments'&&<Link href={`/finance/business?tab=pnl&period=custom&from=${r.filters.from}&to=${r.filters.to}&location=${encodeURIComponent(g.key)}`}>Full station calculations ↗</Link>}</details></td></tr>)}</tbody></table></div></section>}
 {section==='overhead'&&<section className="cfo-panel"><h2>HO cost ledger</h2><p>People CTC accrues by calendar day. Existing manager shares are deducted before allocating the remaining HO cost. <Link href="/master/business">Configure allocation ↗</Link> · <Link href="/master/rent">Add HO rent ↗</Link></p>{!r.allAccess?<p>Company-wide Finance access is required to view HO salary details.</p>:<div className="cfo-scroll"><table><thead><tr><th>HO / cost</th><th>Employee / vendor</th><th>Monthly basis</th><th>Dates</th><th>Gross cost</th><th>Already in stations</th><th>Remaining cost</th><th>Treatment</th></tr></thead><tbody>{Object.values(r.overhead.reduce<Record<string,typeof r.overhead>>((acc,o)=>{const k=[o.station,o.head,o.code,o.name,o.mode,o.monthly].join('|');(acc[k]??=[]).push(o);return acc;},{})).map((parts,i)=>{const o=parts[0],sum=(key:'gross'|'alreadyAllocated'|'amount')=>parts.reduce((s,p)=>s+p[key],0);return <tr key={i}><td>{o.station}<small>{o.head}</small></td><td>{o.name}<small>{o.code}</small></td><td>{money(o.monthly)}</td><td>{parts[0].date} — {parts.at(-1)?.date}<small>{parts.length} calendar days</small></td><td>{money(sum('gross'))}</td><td>{money(sum('alreadyAllocated'))}</td><td>{money(sum('amount'))}</td><td>{o.mode}<details><summary>{o.recipients.length} recipients</summary>{o.recipients.join(', ')||'Business level'}{o.issue&&<p>{o.issue}</p>}</details></td></tr>})}</tbody></table></div>}</section>}
 {section==='now'&&<section className="cfo-panel"><h2>Amazon Now · unit economics</h2><p>Monthly MG ÷ calendar days × covered days. Additional units are charged by the configured excess slabs. <Link href="/finance/now-volumes">Update monthly units ↗</Link></p>{r.nowDetails.filter(d=>rows.some(row=>row.station===d.station)).map((d,i)=><details className="cfo-disclosure" key={i}><summary><b>{d.station} · {d.category}</b><span>{d.month} · {d.daily.length} days · Revenue {money(d.daily.reduce((s:number,x:any)=>s+x.revenue,0))}</span></summary><div className="cfo-fields"><div><small>Monthly MG</small><strong>{money(d.monthlyMg)}</strong><p>÷ {d.daysInMonth} × {d.daily.length} days</p></div><div><small>MG units/day</small><strong>{num(d.mgUpd)}</strong></div><div><small>Actual average UPD</small><strong>{num(d.upd)}</strong></div><div><small>Excess units in period</small><strong>{num(d.excessUnits)}</strong></div><div><small>Earned incentive</small><strong>{d.incentivePercent===null?'Not confirmed':d.incentivePercent+'%'}</strong></div></div><div className="cfo-scroll"><table><thead><tr><th>Above UPD</th><th>Through UPD</th><th>Base ₹/unit</th><th>Incentive ₹/unit</th></tr></thead><tbody>{d.slabs.map((s:any,j:number)=><tr key={j}><td>{num(s.above)}</td><td>{s.upto===null?'Unlimited':num(s.upto)}</td><td>{money(Number(s.base))}</td><td>{money(Number(s.incentive))}</td></tr>)}</tbody></table></div>{d.issues.map((x:string)=><p className="cfo-muted" key={x}>{x}</p>)}</details>)}</section>}
 {section==='attention'&&<section className="cfo-panel"><h2>Complete the cost picture</h2><p>Resolve source gaps in the relevant master. No missing salary, contract amount or rate is silently invented.</p><ul>{issues.map(x=><li key={x}>{x}</li>)}</ul><div className="cfo-toolbar"><Link href="/master/business">Rates, contracts & allocation</Link><Link href="/master/rent">Rent Master</Link><Link href="/finance/now-volumes">Store units</Link><Link href="/finance/business?tab=pnl">Station mapping & cost details</Link></div></section>}
 {section==='insights'&&<section className="cfo-panel"><h2>Finance insights</h2><p>Review the lowest-contribution models, missing cost inputs and changes in daily profitability. AI uses aggregate financial figures only; it does not change pricing or approve payments.</p><ul>{groupCfo(rows,'model').sort((a,b)=>(a.margin??100)-(b.margin??100)).slice(0,3).map(g=><li key={g.key}>{g.key}: {num(g.margin)}% operating margin; {money(g.expense)} expenses against {money(g.revenue)} revenue.</li>)}</ul><button disabled={busy||!r.insightsEnabled} onClick={insight}>{busy?'Analysing…':'Generate AI review'}</button>{!r.insightsEnabled&&<p>Enable and choose a model in <Link href="/master/business">Business masters → AI insights</Link>.</p>}{ai&&<div className="cfo-ai" role="status">{ai}</div>}</section>}
 <footer className="cfo-muted">Read {new Date(r.readAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · CPS uses delivered shipments; Amazon Now CPU uses processed units. These denominators are never mixed. Finance cost per unit includes allocated overhead; OpsPulse shows direct operating CPU.</footer></div>;
}
function Detail({days}:{days:CfoDay[]}){const sum=(key:'da'|'utr'|'van'|'rent'|'other'|'contracts'|'regional')=>days.reduce((s,d)=>s+d[key],0);return <div className="cfo-detail">{[['DA','da'],['Station team','utr'],['Vehicles & fuel','van'],['Rent','rent'],['Other','other'],['Contracts','contracts'],['Regional overhead','regional']].map(([label,key])=><p key={key}><span>{label}</span><b>{money(sum(key as Parameters<typeof sum>[0]))}</b></p>)}</div>}
