'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {PnlInsights} from '../business/pnl-insights';
import {LiveRefresh} from '../business/refresh';
import {DetailedComparison} from './details';
import {chartReport,filterCfoDays,modelFamily,cfoViewHref} from '@/lib/finance/cfo-detail';
import type {CfoReport} from '@/lib/finance/cfo-data';
import {totalCfo,groupCfo,profitabilityView} from '@/lib/finance/cfo';
const money=(n:number|null)=>n===null?'—':'₹'+n.toLocaleString('en-IN',{maximumFractionDigits:2});
const num=(n:number|null)=>n===null?'—':n.toLocaleString('en-IN',{maximumFractionDigits:1});
const unique=(values:string[])=>[...new Set(values)].sort();
export function CfoWorkspace({report:r}:{report:CfoReport}){
 const [period,setPeriod]=useState(r.filters.period),[section,setSection]=useState('overview'),[model,setModel]=useState(r.viewFilters.model),[region,setRegion]=useState(r.viewFilters.region),[cluster,setCluster]=useState(r.viewFilters.cluster),[station,setStation]=useState(r.viewFilters.station),[includeOverhead,setIncludeOverhead]=useState(r.viewFilters.includeOverhead),[ai,setAi]=useState(''),[busy,setBusy]=useState(false);
 const rows=useMemo(()=>filterCfoDays(r.days,{model,region,cluster,station}),[r.days,model,region,cluster,station]);
 const isBusiness=!model&&!region&&!cluster&&!station,corp=r.overhead.filter(o=>o.mode==='corporate'||o.mode==='unallocated').reduce((s,o)=>s+o.amount,0),total=totalCfo(rows,isBusiness?corp:0);
 const view=profitabilityView(total,includeOverhead);
 const charts=useMemo(()=>chartReport(rows,r.overhead,isBusiness&&includeOverhead,includeOverhead),[rows,r.overhead,isBusiness,includeOverhead]);
 function changeView(change:Partial<{model:string;region:string;cluster:string;station:string;includeOverhead:boolean}>){
  const next={model,region,cluster,station,includeOverhead,...change};
  setModel(next.model);setRegion(next.region);setCluster(next.cluster);setStation(next.station);setIncludeOverhead(next.includeOverhead);setAi('');
  window.history.replaceState(null,'',cfoViewHref(r.filters,next,next.includeOverhead));
 }
 const basisLabel=includeOverhead?'After HO':'Before HO';
 const modelRows=r.days.filter(d=>!model||modelFamily(d.model)===model),regionRows=modelRows.filter(d=>!region||d.region===region),stationOptions=[...new Map(regionRows.filter(d=>!cluster||d.cluster===cluster).map(d=>[d.station,d])).values()].sort((a,b)=>a.station.localeCompare(b.station));
 const quick=(period:string)=>cfoViewHref({...r.filters,period},{model,region,cluster,station},includeOverhead);
 const groups=groupCfo(rows,'station');
 const issues=unique([...r.issues,...total.issues,...r.overhead.flatMap(o=>o.issue?[`${o.station}: ${o.issue}`]:[])]);
 const download=()=>{const fields=['Station / store','Revenue','Direct costs','Profit before HO','Margin before HO %','Regional overhead','Expenses after regional HO','Profit after regional HO','Margin after regional HO %','Volume','Unit','Direct CPS / CPU','CPS / CPU after regional HO'];const data=[fields,...groups.map(g=>[g.key,g.revenue,g.direct,g.directProfit,g.directMargin,g.regional,g.expense,g.profit,g.margin,g.volume,g.unit,g.directCpu,g.cpu])];const csv='\ufeff'+data.map(row=>row.map(v=>'"'+String(typeof v==='string'&&/^[=+@\-]/.test(v)?"'"+v:v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`profitability-${r.filters.from}-${r.filters.to}.csv`;a.click();URL.revokeObjectURL(url);};
 async function insight(){setBusy(true);setAi('');try{const res=await fetch('/finance/profitability/insights',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:r.filters.from,to:r.filters.to,model,region,cluster,station,includeOverhead})});const data=await res.json();if(!res.ok)throw Error(data.error||'Unable to analyse.');setAi(data.text);}catch(e){setAi(e instanceof Error?e.message:'Unable to analyse.');}finally{setBusy(false);}}
 return <div className="cfo live-pnl detailed-pnl"><header className="cfo-header"><div><p className="cfo-kicker">Finance · Live operating view</p><h1>Profit & loss</h1><p>Your revenue, cost and margin — from business model and region to every station and store.</p></div><div className="cfo-toolbar"><LiveRefresh/><Link href="/finance/now-volumes">Update Now units</Link><Link href="/master/business">Business masters</Link><button onClick={download}>Export CSV</button><button onClick={()=>window.print()}>Save PDF</button></div></header>
 {r.refreshDelayed&&<p className="cfo-notice" role="status">Refresh is delayed. Showing the last successful report from {new Date(r.readAt).toLocaleTimeString("en-IN",{timeZone:"Asia/Kolkata"})} IST. Use Refresh now to try again.</p>}
 <form className="cfo-panel pnl-date-panel" action="/finance/profitability"><div className="pnl-quick-periods">{[['today','Today'],['yesterday','Yesterday'],['mtd','MTD'],['last-month','Last month']].map(([key,label])=><Link prefetch={false} key={key} href={quick(key)} aria-current={period===key?'page':undefined}>{label}</Link>)}</div><input type="hidden" name="overhead" value={includeOverhead?'1':'0'}/><input type="hidden" name="model" value={model}/><input type="hidden" name="region" value={region}/><input type="hidden" name="cluster" value={cluster}/><input type="hidden" name="location" value={station}/><div className="cfo-fields"><label>Period<select name="period" value={period} onChange={e=>setPeriod(e.target.value as typeof period)}><option value="mtd">Month to date</option><option value="last-month">Last month</option><option value="month">Selected month</option><option value="yesterday">Yesterday</option><option value="today">Today</option><option value="custom">Custom dates</option></select></label><label>Month<input name="month" type="month" defaultValue={r.filters.month} onChange={()=>setPeriod('month')}/></label><label>From<input name="from" type="date" defaultValue={r.filters.from} onChange={()=>setPeriod('custom')}/></label><label>Through<input name="to" type="date" defaultValue={r.filters.to} onChange={()=>setPeriod('custom')}/></label><button type="submit">Apply dates</button></div></form>
 <div className="cfo-toolbar pnl-business-filters"><label>Business model<select value={model} onChange={e=>changeView({model:e.target.value,region:'',cluster:'',station:''})}><option value="">All business models</option>{unique(r.days.map(d=>modelFamily(d.model))).map(v=><option key={v}>{v}</option>)}</select></label><label>Region<select value={region} onChange={e=>changeView({region:e.target.value,cluster:'',station:''})}><option value="">All regions</option>{unique(modelRows.map(d=>d.region)).map(v=><option key={v}>{v}</option>)}</select></label><label>Cluster<select value={cluster} onChange={e=>changeView({cluster:e.target.value,station:''})}><option value="">All clusters</option>{unique(regionRows.map(d=>d.cluster||'Unassigned')).map(v=><option key={v}>{v}</option>)}</select></label><label>Station / store<select value={station} onChange={e=>changeView({station:e.target.value})}><option value="">All permitted stations & stores</option>{stationOptions.map(d=><option key={d.station} value={d.station}>{d.station} · {d.name}</option>)}</select></label><button onClick={()=>changeView({model:'',region:'',cluster:'',station:''})}>Reset view</button><Link href="/master/business">Configure regions ↗</Link></div>
 <p className="cfo-muted">{r.filters.from} — {r.filters.to} · Latest available operating date: {r.cutoff}. Each station’s revenue and direct costs use matching dates. Amazon Now daily units and excess revenue are allocated from the entered monthly UPD.</p>
 <nav className="cfo-tabs">{[['overview','Profit & loss'],['overhead','HO & shared costs'],['now','Amazon Now'],['attention',`Needs attention (${issues.length})`],['insights','Insights']].map(([key,label])=><button key={key} aria-pressed={section===key} onClick={()=>setSection(key)}>{label}</button>)}</nav>
 <div className="pnl-basis-control"><div><strong>{model||'All business models'}{region?' · '+region:''}{station?' · '+station:''}</strong><small>{includeOverhead?'Direct costs plus allocated regional HO. Central HO is included only in the full business total.':'Revenue minus direct operating costs. Regional and central HO are shown separately below.'}</small></div><div role="group" aria-label="Profit calculation"><button aria-pressed={!includeOverhead} onClick={()=>changeView({includeOverhead:false})}>Before HO</button><button aria-pressed={includeOverhead} onClick={()=>changeView({includeOverhead:true})}>After HO</button></div></div>
 <section className="pnl-kpis"><div><span>Revenue</span><strong>{money(total.revenue)}</strong><small>{total.unit==='mixed'?'Shipments and units reported separately':`${num(total.volume)} ${total.unit==='units'?'units · allocated from monthly UPD':'delivered shipments'}`}</small></div><div><span>{includeOverhead?'Expenses including HO':'Direct operating expenses'}</span><strong>{money(view.expense)}</strong><small>{includeOverhead?'Operating costs + regional HO'+(isBusiness?' + central HO':''):'Station and store costs, before HO'}</small></div><div className={`pnl-result ${view.profit===null?'unavailable':view.profit<0?'loss':''}`}><span>Profit / loss · {basisLabel.toLowerCase()}</span><strong>{money(view.profit)}</strong><small>{view.margin===null?'Margin unavailable':view.margin.toFixed(1)+'% margin · '+basisLabel.toLowerCase()}</small></div><div className="pnl-unit"><span>{total.unit==='units'?'Per processed unit':total.unit==='shipments'?'Per delivered shipment':'Unit economics'}</span><div><b>{total.volume&&total.revenue!==null?money(total.revenue/total.volume):'—'}</b><small>Revenue per unit</small><b>{money(view.cpu)}</b><small>{total.unit==='mixed'?'Select one model to compare':'Cost · '+basisLabel.toLowerCase()}</small></div></div></section>
 {issues.length>0&&<button className="cfo-notice" onClick={()=>setSection('attention')}>Provisional management view · {issues.length} input or coverage notes. Review before relying on net profit.</button>}
 {!isBusiness&&<p className="cfo-muted">Central HO remains a separate business expense. It is not arbitrarily allocated to the selected model or region.</p>}
 {(section==='overview'||section==='analysis')&&<><PnlInsights {...charts} includeUnreportedDays/><DetailedComparison key={`${model}/${region}/${cluster}/${station}`} days={rows} report={r} includeOverhead={includeOverhead} onModel={v=>changeView({model:v,region:'',cluster:'',station:''})} onRegion={v=>changeView({region:v,cluster:'',station:''})}/><section className="pnl-panel"><h2>Business result & overhead</h2>{[['Revenue',total.revenue],['Direct operating costs',total.direct],['Profit / loss before HO',total.directProfit],['Regional HO share',total.regional],['Central & unallocated HO',isBusiness?corp:null],[isBusiness?'Net operating profit / loss after all HO':'Profit / loss after regional HO',total.profit]].map(([label,value])=><div className="cfo-waterfall" key={String(label)}><span>{label}</span><b>{money(value as number|null)}</b></div>)}<p className="cfo-muted">Profit before HO = revenue − direct operating costs. Regional HO is deducted next. Central HO is deducted once, only in the full business result. Management operating P&L is before tax and unrecorded accounting adjustments.</p></section></>}
 {section==='overhead'&&<section className="cfo-panel"><h2>HO cost ledger</h2><p>People CTC accrues by calendar day. Existing manager shares are deducted before allocating the remaining HO cost. <Link href="/master/business">Configure allocation ↗</Link> · <Link href="/master/rent">Add HO rent ↗</Link></p>{!r.allAccess?<p>Company-wide Finance access is required to view HO salary details.</p>:<div className="cfo-scroll"><table><thead><tr><th>HO / cost</th><th>Employee / vendor</th><th>Monthly basis</th><th>Dates</th><th>Gross cost</th><th>Already in stations</th><th>Remaining cost</th><th>Treatment</th></tr></thead><tbody>{Object.values(r.overhead.reduce<Record<string,typeof r.overhead>>((acc,o)=>{const k=[o.station,o.head,o.code,o.name,o.mode,o.monthly].join('|');(acc[k]??=[]).push(o);return acc;},{})).map((parts,i)=>{const o=parts[0],sum=(key:'gross'|'alreadyAllocated'|'amount')=>parts.reduce((s,p)=>s+p[key],0);return <tr key={i}><td>{o.station}<small>{o.head}</small></td><td>{o.name}<small>{o.code}</small></td><td>{money(o.monthly)}</td><td>{parts[0].date} — {parts.at(-1)?.date}<small>{parts.length} calendar days</small></td><td>{money(sum('gross'))}</td><td>{money(sum('alreadyAllocated'))}</td><td>{money(sum('amount'))}</td><td>{o.mode}<details><summary>{o.recipients.length} recipients</summary>{o.recipients.join(', ')||'Business level'}{o.issue&&<p>{o.issue}</p>}</details></td></tr>})}</tbody></table></div>}</section>}
 {section==='now'&&<section className="cfo-panel"><h2>Amazon Now · unit economics</h2><p>Monthly MG ÷ calendar days × covered days. Additional units are charged by the configured excess slabs. <Link href="/finance/now-volumes">Update monthly units ↗</Link></p>{r.nowDetails.filter(d=>rows.some(row=>row.station===d.station)).map((d,i)=><details className="cfo-disclosure" key={i}><summary><b>{d.station} · {d.category}</b><span>{d.month} · {d.daily.length} days · Revenue {money(d.daily.reduce((s:number,x:any)=>s+x.revenue,0))}</span></summary><div className="cfo-fields"><div><small>Monthly MG</small><strong>{money(d.monthlyMg)}</strong><p>÷ {d.daysInMonth} × {d.daily.length} days</p></div><div><small>MG units/day</small><strong>{num(d.mgUpd)}</strong></div><div><small>Actual average UPD</small><strong>{num(d.upd)}</strong></div><div><small>Excess units in period</small><strong>{num(d.excessUnits)}</strong></div><div><small>Earned incentive</small><strong>{d.incentivePercent===null?'Not confirmed':d.incentivePercent+'%'}</strong></div></div><div className="cfo-scroll"><table><thead><tr><th>Above UPD</th><th>Through UPD</th><th>Base ₹/unit</th><th>Incentive ₹/unit</th></tr></thead><tbody>{d.slabs.map((s:any,j:number)=><tr key={j}><td>{num(s.above)}</td><td>{s.upto===null?'Unlimited':num(s.upto)}</td><td>{money(Number(s.base))}</td><td>{money(Number(s.incentive))}</td></tr>)}</tbody></table></div>{d.issues.map((x:string)=><p className="cfo-muted" key={x}>{x}</p>)}</details>)}</section>}
 {section==='attention'&&<section className="cfo-panel"><h2>Complete the cost picture</h2><p>Resolve source gaps in the relevant master. No missing salary, contract amount or rate is silently invented.</p><ul>{issues.map(x=><li key={x}>{x}</li>)}</ul><div className="cfo-toolbar"><Link href="/master/business">Rates, contracts & allocation</Link><Link href="/master/rent">Rent Master</Link><Link href="/finance/now-volumes">Store units</Link><Link prefetch={false} href="/finance/business?tab=pnl">Station mapping & cost details</Link></div></section>}
 {section==='insights'&&<section className="cfo-panel"><h2>Finance insights</h2><p>Review the lowest-contribution models, missing cost inputs and changes in daily profitability. AI uses aggregate financial figures only; it does not change pricing or approve payments.</p><ul>{groupCfo(rows,'model').map(g=>({...g,...profitabilityView(g,includeOverhead)})).sort((a,b)=>(a.margin??100)-(b.margin??100)).slice(0,3).map(g=><li key={g.key}>{g.key}: {num(g.margin)}% margin · {basisLabel.toLowerCase()}; {money(g.expense)} expenses against {money(g.revenue)} revenue.</li>)}</ul><button disabled={busy||!r.insightsEnabled} onClick={insight}>{busy?'Analysing…':'Generate AI review'}</button>{!r.insightsEnabled&&<p>Enable and choose a model in <Link href="/master/business">Business masters → AI insights</Link>.</p>}{ai&&<div className="cfo-ai" role="status">{ai}</div>}</section>}
 <footer className="cfo-muted">Read {new Date(r.readAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · CPS uses delivered shipments; Amazon Now CPU uses processed units. These denominators are never mixed. Charts, margins and unit costs follow the selected before-HO or after-HO view. OpsPulse shows direct operating CPU.</footer></div>;
}