-- Read-only outcome: temporary test writes are explicitly rolled back.
begin;
do $test$
declare
 c uuid='43866344-b550-4e8a-9a2d-9d23f3d8a997'; owner_id uuid; station uuid; cm uuid; aom uuid; nh uuid; tl uuid;
 rid uuid; next_rid uuid; sid uuid; stamp timestamptz; chain jsonb; task uuid; item_id uuid; cid uuid; ok boolean;
begin
 select p.id into owner_id from profiles p join user_roles r on r.id=p.role_id where p.company_id=c and p.is_active and r.code='OWNER' order by p.full_name limit 1;
 select id into station from stations where company_id=c and station_code='NLRF';
 select s.reviewer_user_id into cm from ops_performance_review_steps s join ops_performance_reviews r on r.id=s.review_id where r.company_id=c and r.station_id=station and r.source_date='2026-09-03' and s.status='pending' and s.reviewer_role='Cluster Manager';
 select s.reviewer_user_id into aom from ops_performance_review_steps s join ops_performance_reviews r on r.id=s.review_id where r.company_id=c and r.station_id=station and r.source_date='2026-09-03' and s.status='pending' and s.reviewer_role='Area Operations Manager';
 select s.reviewer_user_id into nh from ops_performance_review_steps s join ops_performance_reviews r on r.id=s.review_id where r.company_id=c and r.station_id=station and r.source_date='2026-09-03' and s.status='pending' and s.reviewer_role='National Head';
 select s.reviewer_user_id into tl from ops_performance_review_steps s join ops_performance_reviews r on r.id=s.review_id where r.company_id=c and r.station_id=station and r.source_date='2026-09-03' and s.reviewer_role='Team Lead' limit 1;
 assert cm is not null and aom is not null and nh is not null and tl is not null,'Fixture manager links missing';
 assert not exists(select 1 from ops_performance_reviews where company_id=c and station_id=station and source_date between '2099-12-28' and '2099-12-29'),'Test dates already occupied';
 chain=jsonb_build_array(jsonb_build_object('reviewerUserId',cm,'reviewerName','Test CM','reviewerRole','Cluster Manager'),jsonb_build_object('reviewerUserId',aom,'reviewerName','Test AOM','reviewerRole','Area Operations Manager'),jsonb_build_object('reviewerUserId',nh,'reviewerName','Test NH','reviewerRole','National Head'));
 rid=ops_start_manager_review(c,owner_id,station,'{"source_date":"2099-12-28","source_type":"operational_data"}',chain);
 assert ops_start_manager_review(c,owner_id,station,'{"source_date":"2099-12-28"}',chain)=rid,'Start must be idempotent';
 select id into sid from ops_performance_review_steps where review_id=rid and step_order=1;
 select updated_at into stamp from ops_performance_reviews where id=rid;
 ok=false;
 begin perform ops_take_proxy_review(c,tl,rid,sid,'Manager unavailable',stamp); exception when raise_exception then ok=true; end;
 assert ok,'Station user must not take proxy';
 ok=false;
 begin perform ops_bypass_review_level(c,aom,rid,sid,'Manager unavailable',stamp); exception when raise_exception then ok=true; end;
 assert ok,'AOM must not skip a level';
 ok=false;
 begin perform ops_take_proxy_review(c,aom,rid,sid,'',stamp); exception when raise_exception then ok=true; end;
 assert ok,'Proxy reason required';
 perform ops_take_proxy_review(c,aom,rid,sid,'Cluster manager is absent',stamp);
 assert (select reviewer_user_id=cm and proxy_reviewer_user_id=aom and status='pending' from ops_performance_review_steps where id=sid),'Proxy must preserve original reviewer and pending stage';
 ok=false;
 begin perform ops_mutate_manager_review(c,cm,rid,'complete',jsonb_build_object('step_id',sid)); exception when raise_exception then ok=true; end;
 assert ok,'Original reviewer cannot complete after proxy takes over';
 select updated_at into stamp from ops_performance_reviews where id=rid;
 perform ops_mutate_manager_review(c,aom,rid,'summary',jsonb_build_object('summary','Review test takeaway','expected_review_version',stamp,'author_name','Test proxy'));
 task=ops_save_review_followup(c,aom,station,'2099-12-28',jsonb_build_object('review_id',rid,'title','Arrange backup vehicle','owner_label','Station team','due_date','2099-12-29'));
 perform ops_mutate_manager_review(c,aom,rid,'complete',jsonb_build_object('step_id',sid,'note','Proxy reviewed'));
 assert (select completed_by=aom and reviewer_user_id=cm and status='completed' from ops_performance_review_steps where id=sid),'Proxy completion attribution';
 assert (select current_step_order=2 from ops_performance_reviews where id=rid),'Next AOM stage must remain';
 select id into sid from ops_performance_review_steps where review_id=rid and step_order=2;
 select updated_at into stamp from ops_performance_reviews where id=rid;
 perform ops_bypass_review_level(c,owner_id,rid,sid,'AOM unavailable for this review',stamp);
 assert (select status='skipped' and completed_by is null and bypassed_by=owner_id from ops_performance_review_steps where id=sid),'Skip must not be an approval';
 ok=false;
 begin perform ops_bypass_review_level(c,owner_id,rid,sid,'Repeated skip attempt',stamp); exception when raise_exception then ok=true; end;
 assert ok,'Repeated skip rejected';
 select id into sid from ops_performance_review_steps where review_id=rid and step_order=3;
 select updated_at into stamp from ops_performance_reviews where id=rid;
 perform ops_bypass_review_level(c,owner_id,rid,sid,'National Head unavailable today',stamp);
 assert (select status='closed' from ops_performance_reviews where id=rid),'Last skipped level closes review';
 assert (select status='open' from ops_performance_followups where id=task),'Closing review must not close actions';
 next_rid=ops_start_manager_review(c,owner_id,station,'{"source_date":"2099-12-29"}',chain);
 perform ops_save_review_followup(c,cm,station,'2099-12-29',jsonb_build_object('id',task,'version',1,'title','Arrange backup vehicle','owner_label','Station team','due_date','2099-12-29','status','done','progress_note','Vehicle arranged'));
 assert (select status='done' and source_date='2099-12-28' and version=2 from ops_performance_followups where id=task),'Next-day action completion must preserve source date';
 ok=false;
 begin perform ops_save_review_followup(c,cm,station,'2099-12-29',jsonb_build_object('id',task,'version',1,'title','x','owner_label','x','due_date','2099-12-29')); exception when raise_exception then ok=true; end;
 assert ok,'Stale action edit rejected';
 perform ops_save_review_noon_emd(c,owner_id,station,'2099-12-28',0,0);
 assert (select emd_noon_pct=0 from ops_performance_daily_inputs where company_id=c and station_id=station and source_date='2099-12-28'),'Zero EMD preserved';
 perform ops_save_review_noon_emd(c,owner_id,station,'2099-12-28',93.25,1);
 ok=false;
 begin perform ops_save_review_noon_emd(c,owner_id,station,'2099-12-28',50,1); exception when raise_exception then ok=true; end;
 assert ok,'Stale EMD update rejected';
 ok=false;
 begin perform ops_save_review_noon_emd(c,owner_id,station,'2099-12-28',101,2); exception when raise_exception then ok=true; end;
 assert ok,'EMD range enforced';
 cid=ops_save_review_connection(c,owner_id,station,'{"service_date":"2099-12-28","label":"Test connection 1","arrival":"2099-12-28T06:00:00+05:30","unloading":"2099-12-28T07:00:00+05:30","clearance":"2099-12-28T08:00:00+05:30","author_name":"Test station"}');
 perform ops_save_review_connection(c,owner_id,station,'{"service_date":"2099-12-28","label":"Test connection 2","arrival":"2099-12-28T23:30:00+05:30","unloading":"2099-12-29T00:20:00+05:30","clearance":"2099-12-29T01:00:00+05:30","author_name":"Test station"}');
 assert (select count(*)=2 from ops_performance_connections where company_id=c and station_id=station and service_date='2099-12-28'),'Repeatable connections';
 assert not has_function_privilege('authenticated','public.ops_take_proxy_review(uuid,uuid,uuid,uuid,text,timestamptz)','execute'),'Browser must not directly execute proxy';
 assert not has_function_privilege('anon','public.ops_save_review_noon_emd(uuid,uuid,uuid,date,numeric,integer)','execute'),'Anonymous must not save EMD';
end $test$;
select 'PASS: proxy, skip, scopes, stale edits, action carry-forward, EMD zero/range, multiple overnight connections. All test writes rolled back.' as result;
rollback;
