import {AppShell} from '@/components/app-shell';import {SearchableSelect} from '@/components/searchable-select';import {SubmitButton} from '@/components/submit-button';
import {requirePagePermission,hasPermission} from '@/lib/authorization';import {requireCompanyId} from '@/lib/company-scope';import {supabaseAdmin} from '@/lib/supabase-admin';import {readAllRows} from '@/lib/supabase-pagination';import {workforceClassification} from '@/lib/workforce-classification';
import styles from '@/components/workforce-hold-desk.module.css';import {submitLoss} from './actions';
export const dynamic='force-dynamic';
export default async function WorkforceLosses({searchParams:params={}}:{searchParams?:{status?:string;error?:string;notice?:string}}){
 const auth=await requirePagePermission('ops_workforce_losses','access'),company=requireCompanyId(auth),none='00000000-0000-0000-0000-000000000000';
 let error='',people:any[]=[],claims:any[]=[],stations:any[]=[];const actors=new Map<string,string>();
 try{
  if(!supabaseAdmin)throw new Error('Database is unavailable.');
  let persons=supabaseAdmin.from('workforce').select('id,dropx_id,full_name,location_id,designation_id,designation').eq('company_id',company).is('deleted_at',null).neq('migration_state','reclassified').order('full_name').order('id');
  let losses=supabaseAdmin.from('workforce_station_loss_claims').select('id,workforce_id,station_id,incident_date,reference,reported_by,reported_at,adjustment:workforce_adjustments(amount,category,effective_date,reason,status,reviewed_by,reviewed_at,review_remarks,payroll_run_id)').eq('company_id',company).order('reported_at',{ascending:false}).order('id');
  let locations=supabaseAdmin.from('stations').select('id,station_code').eq('company_id',company).order('station_code').order('id');
  if(!auth.hasAllLocationAccess){const scope=auth.locationScopeIds.length?auth.locationScopeIds:[none];persons=persons.in('location_id',scope);losses=losses.in('station_id',scope);locations=locations.in('id',scope);}
  const results=await Promise.all([readAllRows(persons),readAllRows(losses),readAllRows(locations)]);if(results.some(r=>r.error))throw new Error('Station claims could not be loaded. No changes were made; please retry.');
  const eligible=await workforceClassification(company);people=(results[0].data??[]).filter(eligible);stations=results[2].data??[];
  claims=(results[1].data??[]).map(row=>({...row,adjustment:Array.isArray(row.adjustment)?row.adjustment[0]:row.adjustment}));
  const ids=[...new Set(claims.flatMap(row=>[row.reported_by,row.adjustment?.reviewed_by]).filter(Boolean))];
  for(let n=0;n<ids.length;n+=100){const result=await supabaseAdmin.from('profiles').select('id,full_name').eq('company_id',company).in('id',ids.slice(n,n+100));for(const row of result.data??[])actors.set(row.id,row.full_name??'Authorised user');}
 }catch(e){error=e instanceof Error?e.message:'Unable to load station losses.';}
 const workers=new Map(people.map(row=>[row.id,row])),stationNames=new Map(stations.map(row=>[row.id,row.station_code]));
 const shown=claims.filter(row=>!params.status||row.adjustment?.status===params.status),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const money=(value:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(value));const time=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});
 return <AppShell active="Team Ops" pageCode="ops_workforce_losses"><div className={styles.desk}>
  <section className="panel"><header className="panel-head"><div><h1>Station loss claims</h1><p>Record a documented recovery against an associate. A different authorised Workforce reviewer decides the claim; pending or rejected claims never reduce earnings.</p><p>Keep the incident date separate from the payroll posting date. Already-confirmed payroll cannot be changed here.</p></div></header>
  {params.error||params.notice?<p role="status">{params.error||params.notice}</p>:null}{error?<p role="alert">{error}</p>:hasPermission(auth,'ops_workforce_losses','add')&&!auth.readOnly?<form action={submitLoss} className={styles.form}>
   <label>Station<select name="station_id" required defaultValue=""><option value="">Choose station</option>{stations.map(row=><option key={row.id} value={row.id}>{row.station_code}</option>)}</select></label>
   <label>Associate / DropX ID<SearchableSelect name="workforce_id" required placeholder="Search name, ID or station" options={people.map(row=>({value:row.id,label:`${row.dropx_id||'ID pending'} · ${row.full_name}`,helper:stationNames.get(row.location_id)}))}/></label>
   <label>Incident date<input name="incident_date" type="date" required max={today} defaultValue={today}/></label><label>Payroll posting date<input name="posting_date" type="date" required defaultValue={today}/></label>
   <label>Category<select name="category"><option value="cash_recovery">Cash / COD recovery</option><option value="asset_recovery">Asset recovery</option><option value="other">Other documented loss</option></select></label><label>Claim amount (₹)<input name="amount" type="number" min="0.01" step="0.01" required/></label>
   <label>Unique incident reference<input name="reference" minLength={3} maxLength={200} required placeholder="Station case / evidence reference"/></label><label>Reason and evidence reference<textarea name="reason" minLength={10} maxLength={2000} required placeholder="Describe the loss, supporting evidence and basis for review."/></label>
   <div><p>A claim is not an approved deduction. Use the applicable company review and associate-dispute process.</p><SubmitButton pendingText="Submitting claim" confirmTitle="Submit station loss claim?" confirmMessage="This sends the documented claim to Workforce for independent review. It does not immediately deduct earnings.">Submit for review</SubmitButton></div>
  </form>:null}</section>
  <section className="panel"><header className="panel-head"><h2>Claim history</h2><form method="get"><label>Status<select name="status" defaultValue={params.status??''}><option value="">All</option>{['pending','approved','rejected','posted','cancelled'].map(s=><option key={s}>{s}</option>)}</select></label><button className="button secondary">Filter</button></form></header><div className="table-wrap"><table><thead><tr><th>Associate / station</th><th>Incident / posting</th><th>Claim</th><th>Reported</th><th>Decision / payroll</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td>{workers.get(row.workforce_id)?.full_name??'Historical associate'}<br/>{workers.get(row.workforce_id)?.dropx_id}<br/>{stationNames.get(row.station_id)}</td><td>{row.incident_date}<br/>Posting: {row.adjustment?.effective_date}</td><td>{money(row.adjustment?.amount)}<br/>{row.reference}<p>{row.adjustment?.reason}</p></td><td>{actors.get(row.reported_by)??'Authorised operator'}<br/>{time(row.reported_at)} IST</td><td>{row.adjustment?.status}{row.adjustment?.reviewed_at?<p>{actors.get(row.adjustment.reviewed_by)??'Workforce reviewer'} · {time(row.adjustment.reviewed_at)} IST<br/>{row.adjustment.review_remarks}</p>:null}{row.adjustment?.payroll_run_id?<small>Included in payroll snapshot; payment remains subject to Finance approval.</small>:null}</td></tr>)}{!shown.length?<tr><td colSpan={5}>{error?'History unavailable.':'No claims match this view.'}</td></tr>:null}</tbody></table></div></section>
 </div></AppShell>;
}
