'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {parseNowVolumeCsv,type NowVolume} from '@/lib/finance/now';
import {saveNowVolumes} from './actions';
export function VolumeEditor({month,through,rows,stores,canAdd,canEdit}:{month:string;through:string;rows:NowVolume[];stores:{code:string;name:string}[];canAdd:boolean;canEdit:boolean}){
 const router=useRouter(),[values,setValues]=useState<Record<string,any>>(()=>Object.fromEntries(stores.map(s=>[s.code,rows.find(r=>r.station_code===s.code)||{station_code:s.code,month,through_date:through,units:'',incentive_percent:'',note:'',revision:0}]))),[changed,setChanged]=useState<string[]>([]),[message,setMessage]=useState(''),[pending,start]=useTransition();
 const update=(code:string,key:string,value:any)=>{setValues(v=>({...v,[code]:{...v[code],[key]:value}}));setChanged(v=>[...new Set([...v,code])]);};
 const save=()=>start(async()=>{const r=await saveNowVolumes(changed.map(code=>values[code]));setMessage(r.ok?'Saved all changed stores.':r.error);if(r.ok){setValues(v=>Object.fromEntries(Object.entries(v).map(([k,row])=>[k,changed.includes(k)?{...row,revision:(row.revision||0)+1}:row])));setChanged([]);router.refresh();}});
 return <div className="cfo"><div className="cfo-toolbar"><label>Month<input type="month" value={month} onChange={e=>router.push('/finance/now-volumes?month='+e.target.value)}/></label><a download="amazon-now-units.csv" href={'data:text/csv;charset=utf-8,'+encodeURIComponent('station_code,month,through_date,units,incentive_percent,note\n'+stores.map(s=>`${s.code},${month},${through},,,`).join('\n'))}>Download CSV template</a><label className="cfo-upload">Import CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw Error('Use a CSV smaller than 1 MB.');const incoming=parseNowVolumeCsv(await file.text());if(incoming.some(r=>r.month!==month||!stores.some(s=>s.code===r.station_code)))throw Error('Import only the selected month and your permitted stores.');setValues(v=>({...v,...Object.fromEntries(incoming.map(r=>[r.station_code,{...r,revision:v[r.station_code].revision}]))}));setChanged(incoming.map(r=>r.station_code));setMessage('Imported into the grid for review. Save to apply.');}catch(e){setMessage(e instanceof Error?e.message:'Import failed.');}}}/></label><Link href="/finance/profitability">View P&L ↗</Link></div><p>Incentives are included only when an earned percentage is entered. Leave blank until confirmed; enter 0 when not earned.</p>{message&&<p role="status">{message}</p>}<div className="cfo-panel cfo-scroll"><table><thead><tr><th>Store</th><th>Data through</th><th>Total units</th><th>Average UPD</th><th>Earned incentive %</th><th>Reference / note</th></tr></thead><tbody>{stores.map(s=>{const v=values[s.code],disabled=pending||!(v.revision?canEdit:canAdd);return <tr key={s.code}><td><b>{s.code}</b><small>{s.name}</small></td><td><input aria-label={`${s.code} data through`} disabled={disabled} type="date" min={month+'-01'} max={through} value={v.through_date} onChange={e=>update(s.code,'through_date',e.target.value)}/></td><td><input aria-label={`${s.code} units`} disabled={disabled} type="number" min="0" step="1" value={v.units} onChange={e=>update(s.code,'units',e.target.value)}/></td><td>{v.units===''?'—':(Number(v.units)/Number(v.through_date.slice(8))).toLocaleString('en-IN',{maximumFractionDigits:2})}</td><td><input aria-label={`${s.code} earned incentive`} disabled={disabled} type="number" min="0" max="100" step=".01" placeholder="Unconfirmed" value={v.incentive_percent??''} onChange={e=>update(s.code,'incentive_percent',e.target.value)}/></td><td><input aria-label={`${s.code} note`} disabled={disabled} value={v.note} onChange={e=>update(s.code,'note',e.target.value)}/></td></tr>})}</tbody></table></div><button disabled={pending||!changed.length} onClick={save}>{pending?'Saving…':`Save ${changed.length} changed stores`}</button></div>;
}
