import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import crypto from 'node:crypto';
import ts from 'typescript';
import { betaJourney } from './beta-journey.ts';

function fixture({beta=true,ready=true,authorized=true}={}){
 const state={reads:[],writes:[],uploads:[]};let saved=null;
 const account={id:'target',companyId:'company',profileType:'workforce',onboardingBeta:beta,activationStage:beta?'amazon_email_pilot:pending':null};
 const db={from(table){state.reads.push(table);const q={select(){return q},eq(){return q},is(){return q},async maybeSingle(){const data=table==='connect_login_sessions'?{country_code:'91',mobile_number:'test',expires_at:'2099-01-01'}:table==='workforce_amazon_email_pilot_candidates'?{continuation_status:ready?'continuing':'pending'}:saved;return {data,error:null}},async upsert(row){state.writes.push({table,row});saved=row;return {error:null}}};return q},storage:{from(){return {async upload(path){state.uploads.push(path);return {error:null}},async createSignedUrl(){return {data:{signedUrl:'https://example.com/fixture'}}},async remove(){throw Error('Unexpected removal')}}}}};
 const mocks={'@/lib/beta-journey':{betaJourney},crypto,'@/lib/user-facing-error':{userFacingError:e=>e.message},'next/headers':{cookies:()=>({get:()=>({value:'fixture-session'}),delete(){}})},'next/server':{NextResponse:{json:(b,o)=>Response.json(b,o)}},'../../../../src/lib/connect-auth':{connectSessionCookieName:'session',findConnectSessionAccounts:async()=>authorized?[account]:[]},'../../../../src/lib/profile-drafts':{isMissingProfileDraftTable:()=>false,loadProfileDraft:async()=>null,profileDraftFileSlots:['pan_upload']},'../../../../src/lib/supabase-admin':{supabaseAdmin:db},'../../../../src/lib/workforce-profiles':{isWorkforceProfileType:v=>v==='workforce'}};
 const mod={exports:{}};const src=fs.readFileSync(new URL('../../app/api/connect/profile-draft/route.ts',import.meta.url),'utf8');new Function('require','module','exports',ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(id=>{assert.ok(id in mocks,id);return mocks[id]},mod,mod.exports);
 return {...mod.exports,state};
}
function request(){const form=new FormData();form.set('account_id','target');form.set('profile_type','workforce');form.set('draft_data',JSON.stringify({_beta_status:'submitted',_beta_verification_status:'verified',pan_number:'fixture'}));form.set('profile_verification_results',JSON.stringify({kind:'pan',verified:true}));form.set('pan_upload',new File(['test only'],'pan.pdf',{type:'application/pdf'}));return new Request('https://one.example/api/connect/profile-draft',{method:'POST',body:form})}
test('beta registration saves only isolated candidate and upload path, ignores copied verification claims',async()=>{const f=fixture();assert.equal((await f.POST(request())).status,200);assert.equal(f.state.writes.length,1);const {table,row}=f.state.writes[0];assert.equal(table,'workforce_amazon_email_pilot_registrations');assert.equal(row.candidate_id,'target');assert.equal(row.company_id,'company');assert.equal(row.status,'submitted');assert.equal(row.draft_data._beta_verification_status,'pending_review');assert.deepEqual(row.verification_results,[]);assert.ok(f.state.uploads.every(p=>p.startsWith('company/amazon-email-pilot/target/')));assert.ok(!f.state.reads.includes('mob_app_registration_drafts'));assert.ok(!f.state.reads.includes('workforce'));});
test('canonical draft storage and existing verification snapshots are preserved',async()=>{const f=fixture({beta:false});assert.equal((await f.POST(request())).status,200);const {table,row}=f.state.writes[0];assert.equal(table,'mob_app_registration_drafts');assert.deepEqual(row.verification_results,[{kind:'pan',verified:true}]);assert.ok(f.state.uploads.every(p=>p.startsWith('company/registration-drafts/workforce/target/')));assert.ok(!f.state.reads.includes('workforce_amazon_email_pilot_registrations'));});
test('unready or unauthorised beta account cannot upload or submit',async()=>{for(const opts of [{ready:false},{authorized:false}]){const f=fixture(opts);assert.equal((await f.POST(request())).status,400);assert.equal(f.state.writes.length,0);assert.equal(f.state.uploads.length,0)}});
