import type { GuidanceLanguage } from "./beta-guidance";

// Screen labels stay verbatim so candidates can find them in Amazon's app.
// This is guidance, never evidence that a candidate completed an Amazon task.
export const flexGuideSteps = [
  { id: "signin", screen: "Amazon Flex → Sign in", source: "amazon", pages: "12–16" },
  { id: "privacy", screen: "Privacy Agreement → Start", source: "amazon", pages: "17" },
  { id: "about", screen: "About You → Start", source: "amazon", pages: "18–19" },
  { id: "licence", screen: "License Verification → Start", source: "amazon", pages: "20–25" },
  { id: "photo", screen: "Photo → Start", source: "amazon", pages: "26–27" },
  { id: "bgc", screen: "Background Check → Start", source: "amazon", pages: "28–32" },
  { id: "uan", screen: "UAN VERIFICATION", source: "dropx", pages: "16" },
  { id: "account", screen: "Account Setup / Resolve Other Accounts", source: "amazon", pages: "33–34" },
  { id: "learning", screen: "Training → LM Learning", source: "amazon", pages: "35–39" },
] as const;
export type FlexGuideStep = typeof flexGuideSteps[number]["id"];
export const flexInvitationWaiting: Record<GuidanceLanguage, string> = {
  en: "Waiting for your invitation email. The link will appear here when received; you do not need separate mailbox access.",
  ml: "ക്ഷണ ഇമെയിലിനായി കാത്തിരിക്കുന്നു. ലഭിച്ചാൽ ലിങ്ക് ഇവിടെ കാണിക്കും; പ്രത്യേകം മെയിൽബോക്സ് തുറക്കേണ്ടതില്ല.",
  te: "ఆహ్వాన ఇమెయిల్ కోసం వేచి ఉంది. అందగానే లింక్ ఇక్కడ కనిపిస్తుంది; ప్రత్యేకంగా మెయిల్‌బాక్స్ తెరవాల్సిన అవసరం లేదు.",
  ta: "அழைப்பு மின்னஞ்சலுக்காகக் காத்திருக்கிறது. வந்ததும் இணைப்பு இங்கு தோன்றும்; தனியாக மின்னஞ்சல் பெட்டியைத் திறக்கத் தேவையில்லை.",
  kn: "ಆಹ್ವಾನ ಇಮೇಲ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ. ಬಂದಾಗ ಲಿಂಕ್ ಇಲ್ಲಿ ಕಾಣುತ್ತದೆ; ಪ್ರತ್ಯೇಕ ಮೇಲ್‌ಬಾಕ್ಸ್ ತೆರೆಯಬೇಕಿಲ್ಲ.",
  hi: "निमंत्रण ईमेल का इंतजार है। मिलते ही लिंक यहाँ दिखेगा; अलग से मेलबॉक्स खोलने की जरूरत नहीं है।",
  or: "ନିମନ୍ତ୍ରଣ ଇମେଲ୍ ପାଇଁ ଅପେକ୍ଷା। ଆସିଲେ ଲିଙ୍କ୍ ଏଠାରେ ଦେଖାଯିବ; ଅଲଗା ମେଲ୍‌ବକ୍ସ ଖୋଲିବା ଦରକାର ନାହିଁ।",
};
export function betaFlexGuideEnabled(account: { workspace?: string; profileType?: string; onboardingBeta?: boolean; activationStage?: string | null }, isolatedBeta?: boolean) {
  return Boolean(isolatedBeta && account.workspace === "workforce" && account.profileType === "workforce"
    && account.onboardingBeta && account.activationStage?.startsWith("amazon_email_pilot:"));
}
export type FlexStepCopy = { title: string; actions: string[]; expect: string; help: string };
type GuideCopy = {
  title: string; intro: string; start: string; invitation: string; guide: string; choose: string;
  next: string; back: string; finish: string; step: string; screen: string; expect: string; help: string;
  evidence: string; source: string; amazonSource: string; dropxSource: string; pages: string;
  flexDownload: string; learningDownload: string; status: string; statusBody: string;
  email: string; copyEmail: string; emailCopied: string; copyLink: string; linkCopied: string;
  openInvitation: string; browserTitle: string; browserBody: string; invitationBody: string;
  ready: string; password: string; passwordBody: string;
  steps: Record<FlexGuideStep, FlexStepCopy>;
};

export const betaFlexGuide: Record<GuidanceLanguage, GuideCopy> = {
  hi: {
    title: "निमंत्रण से पहली डिलीवरी तक", intro: "Amazon का पासवर्ड बना लिया? अब Flex ऐप में आगे बढ़ें। हर स्क्रीन पर क्या करना है, यहाँ देखें।", start: "Amazon Flex में आगे बढ़ें", invitation: "निमंत्रण और ईमेल कोड", guide: "Flex रजिस्ट्रेशन गाइड", choose: "गाइड का चरण चुनें", next: "गाइड का अगला चरण", back: "पीछे", finish: "निमंत्रण पर लौटें", step: "गाइड का चरण", screen: "Amazon में यह स्क्रीन खोलें", expect: "आगे क्या होगा", help: "इस चरण में मदद चाहिए?", evidence: "यह केवल गाइड है। चरण पढ़ने या बदलने से रजिस्ट्रेशन की स्थिति नहीं बदलती। Amazon कामों का क्रम अलग दिखा सकता है; अपनी स्क्रीन के निर्देश मानें।", source: "गाइड का स्रोत", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "पृष्ठ", flexDownload: "Amazon Flex डाउनलोड करें", learningDownload: "LM Learning डाउनलोड करें", status: "कामों की मौजूदा स्थिति देखें", statusBody: "मौजूदा स्थिति Amazon Flex में देखें। इस बीटा में निमंत्रण और IDfy ईमेल मिलते हैं; Flex, UAN और प्रशिक्षण पूरा होने की विस्तृत पुष्टि यहाँ अभी नहीं मिलती।",
    email: "Amazon Flex में लॉगिन का ईमेल", copyEmail: "ईमेल कॉपी करें", emailCopied: "ईमेल कॉपी हो गया", copyLink: "निमंत्रण लिंक कॉपी करें", linkCopied: "लिंक कॉपी हो गया", openInvitation: "निमंत्रण खोलें", browserTitle: "अपने नए काम वाले खाते का उपयोग करें", browserBody: "पहले से खुला Amazon खाता साइन आउट करें या निमंत्रण लिंक private/incognito विंडो में खोलें। यह बटन सामान्य ब्राउज़र में खुलता है।", invitationBody: "इसी ईमेल से निमंत्रण स्वीकार करें। ड्राइविंग लाइसेंस और PAN वाला नाम ही डालें। याद रहने वाला मजबूत पासवर्ड बनाएँ। ईमेल कोड माँगे तो यहाँ से कॉपी करके Amazon पर लौटें।", ready: "आपका निमंत्रण तैयार है", password: "पासवर्ड निजी रखें", passwordBody: "Amazon पर बनाए पासवर्ड से Flex में लॉगिन करें। DropX इसे बनाता, पढ़ता या सहेजता नहीं है।",
    steps: {
      signin: { title: "उसी खाते से Flex खोलें", actions: ["निमंत्रण स्वीकार करके ईमेल सत्यापित करने के बाद Android फोन पर Amazon Flex इंस्टॉल करें। Amazon का डाउनलोड निर्देश या नीचे का लिंक इस्तेमाल करें।", "यहाँ दिख रहे ईमेल और अपने बनाए पासवर्ड से लॉगिन करें। ऐप की अनुमति संबंधी सूचनाएँ पढ़ें, फिर onboarding के काम खोलें।"], expect: "Start बटन वाली कामों की सूची दिखेगी। सिर्फ पासवर्ड बनाने से रजिस्ट्रेशन पूरा नहीं होता।", help: "काम नहीं दिख रहे? ईमेल जाँचें, गलत खाते से साइन आउट करके फिर लॉगिन करें। पासवर्ड भूले तो Amazon password reset करें; दूसरा खाता न बनाएँ।" },
      privacy: { title: "गोपनीयता की शर्तें पढ़ें", actions: ["Flex में Privacy Agreement के पास Start दबाएँ।", "सूचना पढ़ें। सहमत हों तो acknowledgement चुनकर Continue दबाएँ।"], expect: "कामों की सूची पर लौटकर अगला उपलब्ध काम खोलें।", help: "शर्तों पर सवाल हो तो स्वीकार करने से पहले स्टेशन टीम से पूछें। जरूरी काम न छोड़ें।" },
      about: { title: "अपनी जानकारी भरें", actions: ["About You खोलें। ड्राइविंग लाइसेंस में जैसा नाम है, वैसा ही भरें। PAN के नाम से अलग हो तो पहले स्टेशन टीम से पूछें।", "सही मोबाइल नंबर और पूरा वर्तमान पता भरें: मकान/मंजिल, सड़क, पहचान का स्थान, शहर, राज्य और PIN। जाँचकर Continue दबाएँ।"], expect: "जानकारी Flex में सहेजी जाएगी।", help: "दस्तावेजों से अलग छोटा नाम या शुरुआती अक्षर न डालें। गलत जानकारी बदल न पाएँ तो TL से संपर्क करें।" },
      licence: { title: "ड्राइविंग लाइसेंस अपलोड करें", actions: ["License Verification खोलें। स्थायी ड्राइविंग लाइसेंस के आगे और पीछे की पूरी, साफ तस्वीरें दें।", "लाइसेंस नंबर में spaces, hyphens, slashes और शुरू के शून्य ठीक वैसे ही भरें। जन्मतिथि, जारी करने वाला राज्य और समाप्ति तिथि जाँचकर Submit दबाएँ।"], expect: "In Progress का मतलब Amazon जाँच रहा है। रिजेक्ट हो तो बताए कारण के अनुसार जानकारी या तस्वीर सुधारकर फिर भेजें।", help: "धुँधली तस्वीर या गलत जानकारी से देरी होती है। BGC शुरू होने से पहले लाइसेंस जाँच पास होनी चाहिए। अटके तो TL से पूछें; तय समय में मंजूरी मानकर न चलें।" },
      photo: { title: "अपनी प्रोफाइल फोटो दें", actions: ["Photo खोलकर साफ चेहरे वाली तस्वीर के लिए स्क्रीन के निर्देश मानें।", "सेल्फी लें या ऐप अनुमति दे तो फोटो चुनें। जाँचकर Continue दबाएँ; साफ न हो तो Redo करें।"], expect: "फोटो जमा होगी। BGC के लिए लाइसेंस मंजूरी और स्टेशन की Associate Settings भी जरूरी हैं।", help: "BGC बंद है तो स्टेशन टीम से LSC में service area, service type और supervisor जाँचने को कहें।" },
      bgc: { title: "बैकग्राउंड जाँच की जानकारी दें", actions: ["Background Check खोलें। सहमति पढ़ें और सहमत हों तो आगे बढ़ें। PAN के अनुसार नाम, PAN नंबर और पिता का नाम भरें।", "पिछले इतिहास के सवालों का सही जवाब और स्थायी पता दें। जाँचकर जमा करें। DropX One में आने वाले IDfy वीडियो, दस्तावेज या पते के अनुरोध पूरे करें।"], expect: "जाँचें अलग-अलग चल सकती हैं। In Progress मतलब इंतजार करें; insufficiency मतलब माँगी गई कमी या गलती सुधारें। मिले IDfy काम Background verification में देखें।", help: "BGC शुरू न हो तो TL लाइसेंस, फोटो, Associate Settings और vendor की रुकावट जाँचें। किसी और के दस्तावेज न दें।" },
      uan: { title: "माँगे जाने पर e-Shram UAN दें", actions: ["Account setup में UAN VERIFICATION देखें। दिए गए गाइड में e-Shram UAN माँगा गया है, EPFO/PF UAN नहीं।", "है तो Yes चुनकर UAN ID वाला नाम और e-Shram UAN नंबर डालें। नहीं है तो सही जवाब No चुनें और Amazon के निर्देश मानें या TL से पूछें। जाँचकर Submit करें।"], expect: "Amazon का परिणाम या अगला निर्देश मानें। यह गाइड UAN सत्यापित नहीं करता और पूरा होने की पुष्टि नहीं है।", help: "स्क्रीन नहीं दिखी या नंबर स्वीकार नहीं हुआ? Amazon क्या दिखाता है, TL को बताएँ। नंबर न गढ़ें; e-Shram की जगह PF UAN न भरें।" },
      account: { title: "Amazon को खाता सेटअप पूरा करने दें", actions: ["Flex में Account Setup देखें और माँगे गए काम पूरे करें। यहाँ UAN माँगे तो भरें।", "Resolve Other Accounts आए तो Agree and Remove से पहले TL से बात करें। इससे सूची के पुराने Amazon delivery खाते हटते/offboard होते हैं। तय करें कौन सा खाता बनाए रखना है।"], expect: "जाँच के बाद Amazon खाता तैयार करता है। Pending का मतलब यह नहीं कि आपने फॉर्म छोड़ा है।", help: "अटका हो तो TL से LSC जाँचने को कहें। सिर्फ स्क्रीन हटाने के लिए दोबारा रजिस्ट्रेशन या खाता हटाना न करें।" },
      learning: { title: "Amazon का जरूरी प्रशिक्षण पूरा करें", actions: ["स्टेशन की buddy training, Amazon के LM Learning कोर्स का विकल्प नहीं है। LM Learning लॉगिन और दिए गए नए कर्मचारी के कोर्स के लिए TL से पूछें। यह लॉगिन Flex से अलग हो सकता है।", "LM Learning खोलकर हर जरूरी module पूरा करें। Flex पर लौटकर Training और बाकी कामों की स्थिति देखें।"], expect: "Amazon सभी जरूरी कामों की पुष्टि करे तो Ready to Deliver दिखेगा। कहा जाए तो उसी खाते से साइन आउट करके फिर लॉगिन करें। डिलीवरी कब शुरू करनी है, TL पुष्टि करेंगे।", help: "लॉगिन/कोर्स नहीं मिला या स्थिति नहीं बदली? स्टेशन टीम को LM Learning निर्देश मिलते हैं; वे Amazon से संपर्क करें। यह गाइड पढ़ना प्रशिक्षण नहीं माना जाता।" },
    },
  },
  or: {
    title: "ନିମନ୍ତ୍ରଣରୁ ପ୍ରଥମ ଡେଲିଭରି ପର୍ଯ୍ୟନ୍ତ", intro: "Amazon ପାସୱାର୍ଡ ତିଆରି କରିଛନ୍ତି? ଏବେ Flex ଆପ୍‌ରେ ଆଗକୁ ବଢ଼ନ୍ତୁ। ପ୍ରତି ସ୍କ୍ରିନ୍‌ରେ କ’ଣ କରିବେ ଏଠାରେ ଦେଖନ୍ତୁ।", start: "Amazon Flexରେ ଆଗକୁ ବଢ଼ନ୍ତୁ", invitation: "ନିମନ୍ତ୍ରଣ ଓ ଇମେଲ୍ କୋଡ୍", guide: "Flex ପଞ୍ଜୀକରଣ ଗାଇଡ୍", choose: "ଗାଇଡ୍ ପଦକ୍ଷେପ ବାଛନ୍ତୁ", next: "ପରବର୍ତ୍ତୀ ଗାଇଡ୍ ପଦକ୍ଷେପ", back: "ପଛକୁ", finish: "ନିମନ୍ତ୍ରଣକୁ ଫେରନ୍ତୁ", step: "ଗାଇଡ୍ ପଦକ୍ଷେପ", screen: "Amazonରେ ଏହି ସ୍କ୍ରିନ୍ ଖୋଲନ୍ତୁ", expect: "ପରେ କ’ଣ ହେବ", help: "ଏହି ପଦକ୍ଷେପରେ ସାହାଯ୍ୟ ଦରକାର?", evidence: "ଏହା କେବଳ ଗାଇଡ୍। ପଦକ୍ଷେପ ପଢ଼ିବା କିମ୍ବା ବଦଳାଇବାରେ ପଞ୍ଜୀକରଣ ସ୍ଥିତି ବଦଳେ ନାହିଁ। Amazon କାମର କ୍ରମ ଅଲଗା ଦେଖାଇପାରେ; ନିଜ ସ୍କ୍ରିନ୍‌ର ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।", source: "ଗାଇଡ୍‌ର ଉତ୍ସ", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "ପୃଷ୍ଠା", flexDownload: "Amazon Flex ଡାଉନଲୋଡ୍ କରନ୍ତୁ", learningDownload: "LM Learning ଡାଉନଲୋଡ୍ କରନ୍ତୁ", status: "ବର୍ତ୍ତମାନ କାମର ସ୍ଥିତି ଦେଖନ୍ତୁ", statusBody: "ବର୍ତ୍ତମାନ ସ୍ଥିତି Amazon Flexରେ ଦେଖନ୍ତୁ। ଏହି ବିଟାରେ ନିମନ୍ତ୍ରଣ ଓ IDfy ଇମେଲ୍ ଆସେ; Flex, UAN ଓ ପ୍ରଶିକ୍ଷଣ ସମ୍ପୂର୍ଣ୍ଣ ହେବାର ବିସ୍ତୃତ ନିଶ୍ଚିତକରଣ ଏଠାରେ ଏପର୍ଯ୍ୟନ୍ତ ନାହିଁ।",
    email: "Amazon Flex ଲଗଇନ୍ ଇମେଲ୍", copyEmail: "ଇମେଲ୍ କପି କରନ୍ତୁ", emailCopied: "ଇମେଲ୍ କପି ହେଲା", copyLink: "ନିମନ୍ତ୍ରଣ ଲିଙ୍କ୍ କପି କରନ୍ତୁ", linkCopied: "ଲିଙ୍କ୍ କପି ହେଲା", openInvitation: "ନିମନ୍ତ୍ରଣ ଖୋଲନ୍ତୁ", browserTitle: "ନୂଆ କାମର ଖାତା ବ୍ୟବହାର କରନ୍ତୁ", browserBody: "ପୂର୍ବରୁ ଖୋଲା Amazon ଖାତାରୁ ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ କିମ୍ବା ଲିଙ୍କ୍‌କୁ private/incognito ୱିଣ୍ଡୋରେ ଖୋଲନ୍ତୁ। ଏହି ବଟନ୍ ସାଧାରଣ ବ୍ରାଉଜର୍‌ରେ ଖୋଲେ।", invitationBody: "ଏହି ଇମେଲ୍‌ରେ ନିମନ୍ତ୍ରଣ ଗ୍ରହଣ କରନ୍ତୁ। ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ ଓ PANର ନାମ ଦିଅନ୍ତୁ। ମନେ ରହିବା ଭଳି ଶକ୍ତିଶାଳୀ ପାସୱାର୍ଡ କରନ୍ତୁ। ଇମେଲ୍ କୋଡ୍ ମାଗିଲେ ଏଠାରେ କପି କରି Amazonକୁ ଫେରନ୍ତୁ।", ready: "ଆପଣଙ୍କ ନିମନ୍ତ୍ରଣ ପ୍ରସ୍ତୁତ", password: "ପାସୱାର୍ଡ ଗୁପ୍ତ ରଖନ୍ତୁ", passwordBody: "Amazonରେ ତିଆରି ପାସୱାର୍ଡ ସହ Flexରେ ଲଗଇନ୍ କରନ୍ତୁ। DropX ଏହାକୁ ତିଆରି, ପଢ଼ିବା କିମ୍ବା ସଂରକ୍ଷଣ କରେ ନାହିଁ।",
    steps: {
      signin: { title: "ସେହି ଖାତାରେ Flex ଖୋଲନ୍ତୁ", actions: ["ନିମନ୍ତ୍ରଣ ଗ୍ରହଣ ଓ ଇମେଲ୍ ଯାଞ୍ଚ ପରେ Android ଫୋନ୍‌ରେ Amazon Flex ଇନ୍‌ଷ୍ଟଲ୍ କରନ୍ତୁ। Amazonର ଡାଉନଲୋଡ୍ ନିର୍ଦ୍ଦେଶ କିମ୍ବା ତଳ ଲିଙ୍କ୍ ବ୍ୟବହାର କରନ୍ତୁ।", "ଏଠାରେ ଥିବା ଇମେଲ୍ ଓ ନିଜ ପାସୱାର୍ଡରେ ଲଗଇନ୍ କରନ୍ତୁ। ଆପ୍ ଅନୁମତି ସୂଚନା ପଢ଼ି onboarding କାମ ଖୋଲନ୍ତୁ।"], expect: "Start ବଟନ୍ ସହ କାମ ତାଲିକା ଆସିବ। କେବଳ ପାସୱାର୍ଡ କଲେ ପଞ୍ଜୀକରଣ ସମ୍ପୂର୍ଣ୍ଣ ହୁଏ ନାହିଁ।", help: "କାମ ଦେଖାଯାଉନି? ଇମେଲ୍ ଯାଞ୍ଚ କରି ଭୁଲ ଖାତାରୁ ସାଇନ୍ ଆଉଟ୍ କରନ୍ତୁ, ପୁଣି ଲଗଇନ୍ କରନ୍ତୁ। ପାସୱାର୍ଡ ଭୁଲିଲେ Amazon password reset କରନ୍ତୁ; ଆଉ ଖାତା କରନ୍ତୁ ନାହିଁ।" },
      privacy: { title: "ଗୋପନୀୟତା ନିୟମ ପଢ଼ନ୍ତୁ", actions: ["Flexରେ Privacy Agreement ପାଖରେ Start ଦବାନ୍ତୁ।", "ସୂଚନା ପଢ଼ନ୍ତୁ। ସହମତ ହେଲେ acknowledgement ବାଛି Continue ଦବାନ୍ତୁ।"], expect: "କାମ ତାଲିକାକୁ ଫେରି ପରବର୍ତ୍ତୀ ଉପଲବ୍ଧ କାମ ଖୋଲନ୍ତୁ।", help: "ନିୟମରେ ସନ୍ଦେହ ଥିଲେ ଗ୍ରହଣ ପୂର୍ବରୁ ଷ୍ଟେସନ୍ ଟିମ୍‌କୁ ପଚାରନ୍ତୁ। ଆବଶ୍ୟକ କାମ ଛାଡ଼ନ୍ତୁ ନାହିଁ।" },
      about: { title: "ନିଜ ବିବରଣୀ ଦିଅନ୍ତୁ", actions: ["About You ଖୋଲି ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ ଅନୁଯାୟୀ ନାମ ଦିଅନ୍ତୁ। PAN ନାମ ଅଲଗା ଥିଲେ ପ୍ରଥମେ ଷ୍ଟେସନ୍ ଟିମ୍‌କୁ ପଚାରନ୍ତୁ।", "ଠିକ୍ ମୋବାଇଲ୍ ନମ୍ବର ଓ ସମ୍ପୂର୍ଣ୍ଣ ବର୍ତ୍ତମାନ ଠିକଣା ଦିଅନ୍ତୁ: ଘର/ମହଲା, ରାସ୍ତା, ଚିହ୍ନଟ ସ୍ଥାନ, ସହର, ରାଜ୍ୟ, PIN। ଯାଞ୍ଚ କରି Continue ଦବାନ୍ତୁ।"], expect: "ବିବରଣୀ Flexରେ ସେଭ୍ ହେବ।", help: "ଦଲିଲଠାରୁ ଅଲଗା ସଂକ୍ଷିପ୍ତ ନାମ ଦିଅନ୍ତୁ ନାହିଁ। ଭୁଲ ତଥ୍ୟ ବଦଳାଇ ନପାରିଲେ TLଙ୍କୁ ଯୋଗାଯୋଗ କରନ୍ତୁ।" },
      licence: { title: "ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ ଅପଲୋଡ୍ କରନ୍ତୁ", actions: ["License Verification ଖୋଲନ୍ତୁ। ସ୍ଥାୟୀ ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସର ଆଗ ଓ ପଛର ସମ୍ପୂର୍ଣ୍ଣ ସ୍ପଷ୍ଟ ଫଟୋ ଦିଅନ୍ତୁ।", "ଲାଇସେନ୍ସ ନମ୍ବରର spaces, hyphens, slashes ଓ ପ୍ରଥମ ଶୂନ ଠିକ୍ ସେହିପରି ଦିଅନ୍ତୁ। ଜନ୍ମତାରିଖ, ଜାରି ରାଜ୍ୟ, ଶେଷ ତାରିଖ ଯାଞ୍ଚ କରି Submit ଦବାନ୍ତୁ।"], expect: "In Progress ଅର୍ଥ Amazon ଯାଞ୍ଚ କରୁଛି। ଅଗ୍ରାହ୍ୟ ହେଲେ କାରଣ ଅନୁସାରେ ତଥ୍ୟ ବା ଫଟୋ ସୁଧାରି ପୁଣି ପଠାନ୍ତୁ।", help: "ଅସ୍ପଷ୍ଟ ଫଟୋ, ଭୁଲ ତଥ୍ୟ ବିଳମ୍ବ କରେ। BGC ପୂର୍ବରୁ ଲାଇସେନ୍ସ ଯାଞ୍ଚ ପାସ୍ ହେବା ଦରକାର। ବିଳମ୍ବ ହେଲେ TLଙ୍କୁ ପଚାରନ୍ତୁ; ନିର୍ଦ୍ଦିଷ୍ଟ ସମୟରେ ଅନୁମୋଦନ ଭାବନ୍ତୁ ନାହିଁ।" },
      photo: { title: "ନିଜ ପ୍ରୋଫାଇଲ୍ ଫଟୋ ଦିଅନ୍ତୁ", actions: ["Photo ଖୋଲି ମୁହଁ ସ୍ପଷ୍ଟ ଦେଖାଯିବା ପାଇଁ ସ୍କ୍ରିନ୍ ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।", "ସେଲ୍ଫି ନିଅନ୍ତୁ କିମ୍ବା ଆପ୍ ଅନୁମତି ଦେଲେ ଫଟୋ ବାଛନ୍ତୁ। ଯାଞ୍ଚ କରି Continue; ଅସ୍ପଷ୍ଟ ହେଲେ Redo ଦବାନ୍ତୁ।"], expect: "ଫଟୋ ଜମା ହେବ। BGC ପାଇଁ ଲାଇସେନ୍ସ ଅନୁମୋଦନ ଓ ଷ୍ଟେସନ୍‌ର Associate Settings ମଧ୍ୟ ଆବଶ୍ୟକ।", help: "BGC ଖୋଲୁନାହିଁ ତ LSCର service area, service type, supervisor ଯାଞ୍ଚ କରିବାକୁ ଷ୍ଟେସନ୍ ଟିମ୍‌କୁ କହନ୍ତୁ।" },
      bgc: { title: "ପୃଷ୍ଠଭୂମି ଯାଞ୍ଚ ତଥ୍ୟ ଦିଅନ୍ତୁ", actions: ["Background Check ଖୋଲି ସମ୍ମତି ପଢ଼ନ୍ତୁ; ସହମତ ହେଲେ ଆଗକୁ ବଢ଼ନ୍ତୁ। PAN ଅନୁସାରେ ନାମ, PAN ନମ୍ବର, ବାପାଙ୍କ ନାମ ଦିଅନ୍ତୁ।", "ପୂର୍ବ ଇତିହାସ ପ୍ରଶ୍ନର ସତ ଉତ୍ତର ଓ ସ୍ଥାୟୀ ଠିକଣା ଦିଅନ୍ତୁ। ଯାଞ୍ଚ କରି ପଠାନ୍ତୁ। DropX Oneରେ ଆସୁଥିବା IDfy ଭିଡିଓ, ଦଲିଲ, ଠିକଣା ଅନୁରୋଧ ପୂରଣ କରନ୍ତୁ।"], expect: "ଯାଞ୍ଚ ଅଲଗା ଅଲଗା ଚାଲିପାରେ। In Progress ଅର୍ଥ ଅପେକ୍ଷା; insufficiency ଅର୍ଥ ମାଗିଥିବା ଅଭାବ ସୁଧାରନ୍ତୁ। ଆସିଥିବା IDfy କାମ Background verificationରେ ଦେଖନ୍ତୁ।", help: "BGC ଆରମ୍ଭ ନହେଲେ ଲାଇସେନ୍ସ, ଫଟୋ, Associate Settings, vendor ବାଧା TL ଯାଞ୍ଚ କରନ୍ତୁ। ଅନ୍ୟଙ୍କ ଦଲିଲ ଦିଅନ୍ତୁ ନାହିଁ।" },
      uan: { title: "ମାଗିଲେ e-Shram UAN ଦିଅନ୍ତୁ", actions: ["Account setupରେ UAN VERIFICATION ଦେଖନ୍ତୁ। ଦିଆଯାଇଥିବା ଗାଇଡ୍ e-Shram UAN ମାଗେ, EPFO/PF UAN ନୁହେଁ।", "ଥିଲେ Yes ବାଛି UAN IDର ନାମ ଓ e-Shram UAN ନମ୍ବର ଦିଅନ୍ତୁ। ନଥିଲେ ସତରେ No ବାଛି Amazon ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ କିମ୍ବା TLଙ୍କୁ ପଚାରନ୍ତୁ। ଯାଞ୍ଚ କରି Submit କରନ୍ତୁ।"], expect: "Amazon ଫଳାଫଳ କିମ୍ବା ପରବର୍ତ୍ତୀ ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ। ଏହି ଗାଇଡ୍ UAN ଯାଞ୍ଚ କରେ ନାହିଁ କିମ୍ବା ସମ୍ପୂର୍ଣ୍ଣ ଚିହ୍ନିତ କରେ ନାହିଁ।", help: "ସ୍କ୍ରିନ୍ ନାହିଁ କିମ୍ବା ନମ୍ବର ଗ୍ରହଣ ହେଉନାହିଁ? Amazon କ’ଣ ଦେଖାଉଛି TLଙ୍କୁ କହନ୍ତୁ। ନମ୍ବର କଳ୍ପନା କରନ୍ତୁ ନାହିଁ; e-Shram ସ୍ଥାନରେ PF UAN ଦିଅନ୍ତୁ ନାହିଁ।" },
      account: { title: "Amazon ଖାତା ସେଟଅପ୍ ସାରୁ", actions: ["Flexରେ Account Setup ଦେଖି ମାଗିଥିବା କାମ କରନ୍ତୁ। ଏଠାରେ UAN ମାଗିଲେ ଦିଅନ୍ତୁ।", "Resolve Other Accounts ଆସିଲେ Agree and Remove ପୂର୍ବରୁ TLଙ୍କ ସହ କଥା ହୁଅନ୍ତୁ। ଏହା ତାଲିକାର ପୁରୁଣା Amazon delivery ଖାତା ହଟାଏ/offboard କରେ। କେଉଁ ଖାତା ରଖିବେ ନିଶ୍ଚିତ କରନ୍ତୁ।"], expect: "ଯାଞ୍ଚ ପରେ Amazon ଖାତା ପ୍ରସ୍ତୁତ କରେ। Pending ଅର୍ଥ ଆପଣ ଫର୍ମ ଛାଡ଼ିଛନ୍ତି ନୁହେଁ।", help: "ଅଟକିଲେ LSC ଦେଖିବାକୁ TLଙ୍କୁ କହନ୍ତୁ। ସ୍କ୍ରିନ୍ ହଟାଇବାକୁ ପୁଣି ପଞ୍ଜୀକରଣ କିମ୍ବା ଖାତା ହଟାନ୍ତୁ ନାହିଁ।" },
      learning: { title: "Amazon ପ୍ରଶିକ୍ଷଣ ସମ୍ପୂର୍ଣ୍ଣ କରନ୍ତୁ", actions: ["ଷ୍ଟେସନ୍ buddy training, Amazon LM Learning କୋର୍ସର ବିକଳ୍ପ ନୁହେଁ। LM Learning ଲଗଇନ୍ ଓ ଦିଆଯାଇଥିବା ନୂଆ କର୍ମୀ କୋର୍ସ ପାଇଁ TLଙ୍କୁ ପଚାରନ୍ତୁ। ଏହି ଲଗଇନ୍ Flexଠାରୁ ଅଲଗା ହୋଇପାରେ।", "LM Learning ଖୋଲି ସବୁ ଆବଶ୍ୟକ modules ସାରନ୍ତୁ। Flexକୁ ଫେରି Training ଓ ବାକି କାମ ଦେଖନ୍ତୁ।"], expect: "ସବୁ କାମ Amazon ନିଶ୍ଚିତ କଲେ Ready to Deliver ଦେଖାଏ। କହିଲେ ସେହି ଖାତାରୁ ସାଇନ୍ ଆଉଟ୍ କରି ପୁଣି ଲଗଇନ୍ କରନ୍ତୁ। ଡେଲିଭରି କେବେ ଆରମ୍ଭ କରିବେ TL ନିଶ୍ଚିତ କରିବେ।", help: "ଲଗଇନ୍/କୋର୍ସ ନାହିଁ କିମ୍ବା ସ୍ଥିତି ବଦଳିନି? ଷ୍ଟେସନ୍ ଟିମ୍‌କୁ LM Learning ନିର୍ଦ୍ଦେଶ ଆସେ; ସେମାନେ Amazonକୁ ପଚାରନ୍ତୁ। ଏହି ଗାଇଡ୍ ପଢ଼ିବା ପ୍ରଶିକ୍ଷଣ ନୁହେଁ।" },
    },
  },
  ta: {
    title: "அழைப்பிலிருந்து முதல் டெலிவரி வரை", intro: "Amazon கடவுச்சொல் அமைத்துவிட்டீர்களா? இனி Flex செயலியில் தொடரலாம். ஒவ்வொரு திரையிலும் செய்ய வேண்டியதைப் பாருங்கள்.", start: "Amazon Flex-ல் தொடரவும்", invitation: "அழைப்பு மற்றும் மின்னஞ்சல் குறியீடு", guide: "Flex பதிவு வழிகாட்டி", choose: "வழிகாட்டி படியைத் தேர்ந்தெடுக்கவும்", next: "அடுத்த வழிகாட்டி படி", back: "பின்செல்லவும்", finish: "அழைப்பிற்குத் திரும்பவும்", step: "வழிகாட்டி படி", screen: "Amazon-ல் இந்தத் திரையைத் திறக்கவும்", expect: "அடுத்து என்ன நடக்கும்", help: "இந்தப் படியில் உதவி வேண்டுமா?", evidence: "இது வழிகாட்டி மட்டுமே. படிகளைப் படிப்பதோ மாற்றுவதோ பதிவு நிலையை மாற்றாது. Amazon பணிகளை வேறு வரிசையில் காட்டலாம்; உங்கள் திரை வழிமுறைகளைப் பின்பற்றவும்.", source: "வழிகாட்டியின் மூலம்", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "பக்கங்கள்", flexDownload: "Amazon Flex பெறவும்", learningDownload: "LM Learning பெறவும்", status: "தற்போதைய பணிகளின் நிலையைப் பார்க்கவும்", statusBody: "தற்போதைய நிலையை Amazon Flex-ல் பார்க்கவும். இந்த பீட்டாவில் அழைப்பு மற்றும் IDfy மின்னஞ்சல்கள் கிடைக்கும்; Flex, UAN, பயிற்சி முடிவுகளின் விரிவான உறுதிப்படுத்தல் இங்கு இன்னும் இல்லை.",
    email: "Amazon Flex உள்நுழைவு மின்னஞ்சல்", copyEmail: "மின்னஞ்சலை நகலெடுக்கவும்", emailCopied: "மின்னஞ்சல் நகலெடுக்கப்பட்டது", copyLink: "அழைப்பு இணைப்பை நகலெடுக்கவும்", linkCopied: "இணைப்பு நகலெடுக்கப்பட்டது", openInvitation: "அழைப்பைத் திறக்கவும்", browserTitle: "புதிய பணிக் கணக்கைப் பயன்படுத்தவும்", browserBody: "ஏற்கெனவே திறந்திருக்கும் Amazon கணக்கிலிருந்து வெளியேறவும் அல்லது அழைப்பு இணைப்பை private/incognito சாளரத்தில் திறக்கவும். இந்தப் பொத்தான் வழக்கமான உலாவியில் திறக்கும்.", invitationBody: "இந்த மின்னஞ்சலில் அழைப்பை ஏற்கவும். ஓட்டுநர் உரிமம், PAN-ல் உள்ள பெயரையே உள்ளிடவும். நினைவில் வைக்கக்கூடிய வலுவான கடவுச்சொல் அமைக்கவும். மின்னஞ்சல் குறியீடு கேட்டால் இங்கு நகலெடுத்து Amazon-க்குத் திரும்பவும்.", ready: "உங்கள் அழைப்பு தயாராக உள்ளது", password: "கடவுச்சொல்லைத் தனிப்பட்டதாக வைத்திருக்கவும்", passwordBody: "Amazon-ல் அமைத்த கடவுச்சொல்லுடன் Flex-ல் உள்நுழையவும். DropX அதை உருவாக்கவோ படிக்கவோ சேமிக்கவோ செய்யாது.",
    steps: {
      signin: { title: "அதே கணக்கில் Flex திறக்கவும்", actions: ["அழைப்பை ஏற்று மின்னஞ்சலை உறுதிப்படுத்தியதும் Android தொலைபேசியில் Amazon Flex நிறுவவும். Amazon காட்டும் பதிவிறக்க வழிமுறை அல்லது கீழுள்ள இணைப்பைப் பயன்படுத்தவும்.", "இங்குள்ள மின்னஞ்சல், நீங்கள் அமைத்த கடவுச்சொல்லுடன் உள்நுழையவும். அனுமதி அறிவிப்புகளைப் படித்து onboarding பணிகளைத் திறக்கவும்."], expect: "Start பொத்தான்களுடன் பணிப் பட்டியல் வரும். கடவுச்சொல் அமைப்பது மட்டுமே பதிவு நிறைவு அல்ல.", help: "பணிகள் இல்லையா? மின்னஞ்சலைச் சரிபார்த்து தவறான கணக்கிலிருந்து வெளியேறி மீண்டும் உள்நுழையவும். கடவுச்சொல் மறந்தால் Amazon password reset பயன்படுத்தவும்; மற்றொரு கணக்கு உருவாக்க வேண்டாம்." },
      privacy: { title: "தனியுரிமை விதிகளைப் படிக்கவும்", actions: ["Flex-ல் Privacy Agreement அருகில் Start அழுத்தவும்.", "அறிவிப்பைப் படிக்கவும். ஒப்புக்கொண்டால் acknowledgement தேர்ந்தெடுத்து Continue அழுத்தவும்."], expect: "பணிப் பட்டியலுக்குத் திரும்பி அடுத்த கிடைக்கும் பணியைத் திறக்கவும்.", help: "விதிகளில் சந்தேகமிருந்தால் ஏற்பதற்கு முன் நிலையக் குழுவிடம் கேட்கவும். கட்டாயப் பணியைத் தவிர்க்க வேண்டாம்." },
      about: { title: "உங்கள் விவரங்களை உள்ளிடவும்", actions: ["About You திறந்து ஓட்டுநர் உரிமத்தில் உள்ளபடியே பெயரை உள்ளிடவும். PAN பெயர் வேறுபட்டால் முதலில் நிலையக் குழுவிடம் கேட்கவும்.", "சரியான கைப்பேசி எண், முழு தற்போதைய முகவரியை உள்ளிடவும்: வீடு/தளம், தெரு, அடையாள இடம், நகரம், மாநிலம், PIN. சரிபார்த்து Continue அழுத்தவும்."], expect: "விவரங்கள் Flex-ல் சேமிக்கப்படும்.", help: "ஆவணங்களிலிருந்து மாறுபடும் சுருக்கப்பெயர்களைப் பயன்படுத்த வேண்டாம். தவறான விவரத்தைத் திருத்த முடியாவிட்டால் TL-ஐ அணுகவும்." },
      licence: { title: "ஓட்டுநர் உரிமத்தைப் பதிவேற்றவும்", actions: ["License Verification திறந்து நிரந்தர ஓட்டுநர் உரிமத்தின் முன், பின் பக்கங்கள் முழுவதும் தெளிவாகத் தெரியும் படங்களை வழங்கவும்.", "உரிம எண்ணில் இடைவெளி, hyphen, slash, தொடக்க பூஜ்ஜியங்களை அப்படியே உள்ளிடவும். பிறந்த தேதி, வழங்கிய மாநிலம், காலாவதி தேதியைச் சரிபார்த்து Submit அழுத்தவும்."], expect: "In Progress என்றால் Amazon ஆய்வு செய்கிறது. நிராகரிக்கப்பட்டால் காரணத்திற்கேற்ப விவரங்கள் அல்லது படங்களைத் திருத்தி மீண்டும் சமர்ப்பிக்கவும்.", help: "மங்கலான படங்கள், விவர வேறுபாடுகள் தாமதம் தரும். BGC தொடங்க உரிம ஆய்வு தேர்ச்சி பெற வேண்டும். தாமதமானால் TL-ஐ கேட்கவும்; குறிப்பிட்ட நேரத்தில் ஒப்புதல் வரும் எனக் கருத வேண்டாம்." },
      photo: { title: "உங்கள் புகைப்படத்தைச் சேர்க்கவும்", actions: ["Photo திறந்து முகம் தெளிவாகத் தெரிய திரை வழிமுறைகளைப் பின்பற்றவும்.", "செல்ஃபி எடுக்கவும் அல்லது செயலி அனுமதித்தால் படம் தேர்ந்தெடுக்கவும். சரிபார்த்து Continue; தெளிவில்லையெனில் Redo அழுத்தவும்."], expect: "புகைப்படம் சமர்ப்பிக்கப்படும். BGC-க்கு உரிம ஒப்புதலும் நிலையத்தின் Associate Settings-உம் தேவை.", help: "BGC திறக்கவில்லை என்றால் LSC-ல் service area, service type, supervisor-ஐ நிலையக் குழுவிடம் சரிபார்க்கச் சொல்லவும்." },
      bgc: { title: "பின்னணி ஆய்வு விவரங்களை வழங்கவும்", actions: ["Background Check திறந்து சம்மதப் படிவத்தைப் படிக்கவும்; ஒப்புக்கொண்டால் தொடரவும். PAN-ல் உள்ளபடியே பெயர், PAN எண், தந்தை பெயர் உள்ளிடவும்.", "கடந்தகால விவரக் கேள்விகளுக்கு உண்மையாகப் பதிலளித்து நிரந்தர முகவரி வழங்கவும். சரிபார்த்து சமர்ப்பிக்கவும். DropX One-ல் வரும் IDfy காணொளி, ஆவணம், முகவரி கோரிக்கைகளை முடிக்கவும்."], expect: "ஆய்வுகள் தனித்தனியாக நடக்கலாம். In Progress என்றால் காத்திருக்கவும்; insufficiency என்றால் கேட்ட குறையைச் சரிசெய்யவும். கிடைத்த IDfy பணிகளை Background verification-ல் பார்க்கலாம்.", help: "BGC தொடங்கவில்லையெனில் உரிமம், படம், Associate Settings, vendor தடைகளை TL பார்க்க வேண்டும். மற்றவரின் ஆவணங்களை வழங்க வேண்டாம்." },
      uan: { title: "கேட்கும்போது e-Shram UAN வழங்கவும்", actions: ["Account setup-ல் UAN VERIFICATION வந்தால் திறக்கவும். வழங்கிய வழிகாட்டி e-Shram UAN கேட்கிறது; EPFO/PF UAN அல்ல.", "இருந்தால் Yes தேர்ந்தெடுத்து UAN ID-யில் உள்ள பெயர், e-Shram UAN எண் வழங்கவும். இல்லையெனில் உண்மையாக No தேர்ந்தெடுத்து Amazon வழிமுறையைப் பின்பற்றவும் அல்லது TL-ஐ கேட்கவும். சரிபார்த்து Submit செய்யவும்."], expect: "Amazon காட்டும் முடிவு அல்லது அடுத்த வழிமுறையைப் பின்பற்றவும். இந்த வழிகாட்டி UAN-ஐ சரிபார்க்கவோ நிறைவாகக் குறிக்கவோ செய்யாது.", help: "திரை இல்லையா அல்லது எண் நிராகரிக்கப்பட்டதா? Amazon காட்டுவதை TL-க்கு சொல்லவும். எண்ணை ஊகிக்க வேண்டாம்; e-Shram இடத்தில் PF UAN வழங்க வேண்டாம்." },
      account: { title: "Amazon கணக்கு அமைப்பை முடிக்கட்டும்", actions: ["Flex-ல் Account Setup பார்த்து கேட்ட பணிகளை முடிக்கவும். இங்கு UAN கேட்டால் வழங்கவும்.", "Resolve Other Accounts வந்தால் Agree and Remove-க்கு முன் TL-ஐ அணுகவும். பட்டியலிலுள்ள பழைய Amazon delivery கணக்குகள் நீக்கப்படும்/offboard செய்யப்படும். எந்தக் கணக்கு தொடர வேண்டும் என உறுதிப்படுத்தவும்."], expect: "ஆய்வுகளுக்குப் பிறகு Amazon கணக்கை அமைக்கும். Pending என்பது நீங்கள் படிவம் தவறவிட்டதாக அர்த்தமல்ல.", help: "தடைப்பட்டால் LSC பார்க்க TL-ஐ கேட்கவும். திரையை மாற்றுவதற்காக மீண்டும் பதிவு செய்யவோ கணக்கை நீக்கவோ வேண்டாம்." },
      learning: { title: "Amazon பயிற்சியை முடிக்கவும்", actions: ["நிலைய buddy training, Amazon LM Learning பாடத்திற்குப் பதிலல்ல. LM Learning உள்நுழைவு, ஒதுக்கப்பட்ட புதியவர் பாடத்தை TL-இடம் கேட்கவும். இந்த உள்நுழைவு Flex-லிருந்து வேறுபடலாம்.", "LM Learning திறந்து கட்டாயமான அனைத்து modules-ஐயும் முடிக்கவும். Flex திரும்பி Training மற்றும் மீதிப் பணிகளைப் பார்க்கவும்."], expect: "அனைத்தையும் Amazon உறுதிப்படுத்தினால் Ready to Deliver வரும். கேட்டால் அதே கணக்கில் வெளியேறி மீண்டும் உள்நுழையவும். டெலிவரி தொடங்குவதை TL உறுதிப்படுத்துவார்.", help: "உள்நுழைவு/பாடம் இல்லையா அல்லது நிலை மாறவில்லையா? நிலையக் குழுவுக்கு LM Learning வழிமுறைகள் கிடைக்கும்; அவர்கள் Amazon-ஐ அணுக வேண்டும். இந்த வழிகாட்டியைப் படிப்பது பயிற்சி அல்ல." },
    },
  },
  kn: {
    title: "ಆಹ್ವಾನದಿಂದ ಮೊದಲ ಡೆಲಿವರಿವರೆಗೆ", intro: "Amazon ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿದ್ದೀರಾ? ಈಗ Flex ಆ್ಯಪ್‌ನಲ್ಲಿ ಮುಂದುವರಿಯಿರಿ. ಪ್ರತಿ ಪರದೆಯಲ್ಲಿ ಏನು ಮಾಡಬೇಕೆಂದು ಇಲ್ಲಿ ನೋಡಿ.", start: "Amazon Flex‌ನಲ್ಲಿ ಮುಂದುವರಿಯಿರಿ", invitation: "ಆಹ್ವಾನ ಮತ್ತು ಇಮೇಲ್ ಕೋಡ್", guide: "Flex ನೋಂದಣಿ ಮಾರ್ಗದರ್ಶಿ", choose: "ಮಾರ್ಗದರ್ಶಿ ಹಂತ ಆರಿಸಿ", next: "ಮುಂದಿನ ಮಾರ್ಗದರ್ಶಿ ಹಂತ", back: "ಹಿಂದೆ", finish: "ಆಹ್ವಾನಕ್ಕೆ ಮರಳಿ", step: "ಮಾರ್ಗದರ್ಶಿ ಹಂತ", screen: "Amazon‌ನಲ್ಲಿ ಈ ಪರದೆ ನೋಡಿ", expect: "ಮುಂದೆ ಏನಾಗುತ್ತದೆ", help: "ಈ ಹಂತದಲ್ಲಿ ನೆರವು ಬೇಕೇ?", evidence: "ಇದು ಮಾರ್ಗದರ್ಶಿ ಮಾತ್ರ. ಹಂತಗಳನ್ನು ಓದುವುದು ಅಥವಾ ಬದಲಿಸುವುದು ನೋಂದಣಿ ಸ್ಥಿತಿಯನ್ನು ಬದಲಿಸುವುದಿಲ್ಲ. Amazon ಕೆಲಸಗಳ ಕ್ರಮ ಬದಲಾಗಬಹುದು; ನಿಮ್ಮ ಪರದೆಯ ಸೂಚನೆ ಅನುಸರಿಸಿ.", source: "ಮಾರ್ಗದರ್ಶಿಯ ಮೂಲ", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "ಪುಟಗಳು", flexDownload: "Amazon Flex ಪಡೆಯಿರಿ", learningDownload: "LM Learning ಪಡೆಯಿರಿ", status: "ಪ್ರಸ್ತುತ ಕೆಲಸಗಳ ಸ್ಥಿತಿ ನೋಡಿ", statusBody: "ಪ್ರಸ್ತುತ ಸ್ಥಿತಿಯನ್ನು Amazon Flex‌ನಲ್ಲಿ ನೋಡಿ. ಈ ಬೀಟಾದಲ್ಲಿ ಆಹ್ವಾನ ಮತ್ತು IDfy ಇಮೇಲ್‌ಗಳು ಬರುತ್ತವೆ; Flex, UAN, ತರಬೇತಿ ಪೂರ್ಣಗೊಂಡ ವಿವರಗಳು ಇಲ್ಲಿ ಇನ್ನೂ ದೃಢಪಟ್ಟಿಲ್ಲ.",
    email: "Amazon Flex ಲಾಗಿನ್ ಇಮೇಲ್", copyEmail: "ಇಮೇಲ್ ನಕಲಿಸಿ", emailCopied: "ಇಮೇಲ್ ನಕಲಿಸಲಾಗಿದೆ", copyLink: "ಆಹ್ವಾನ ಲಿಂಕ್ ನಕಲಿಸಿ", linkCopied: "ಲಿಂಕ್ ನಕಲಿಸಲಾಗಿದೆ", openInvitation: "ಆಹ್ವಾನ ತೆರೆಯಿರಿ", browserTitle: "ಹೊಸ ಕೆಲಸದ ಖಾತೆ ಬಳಸಿ", browserBody: "ಈಗಾಗಲೇ ತೆರೆದಿರುವ Amazon ಖಾತೆಯಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಿ ಅಥವಾ ಆಹ್ವಾನ ಲಿಂಕ್ ಅನ್ನು private/incognito ಕಿಟಕಿಯಲ್ಲಿ ತೆರೆಯಿರಿ. ಈ ಬಟನ್ ಸಾಮಾನ್ಯ ಬ್ರೌಸರ್ ತೆರೆಯುತ್ತದೆ.", invitationBody: "ಈ ಇಮೇಲ್‌ನೊಂದಿಗೆ ಆಹ್ವಾನ ಸ್ವೀಕರಿಸಿ. ಚಾಲನಾ ಪರವಾನಗಿ ಮತ್ತು PAN‌ನಲ್ಲಿರುವಂತೆಯೇ ಹೆಸರು ನೀಡಿ. ನೆನಪಿಡಬಹುದಾದ ಬಲವಾದ ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸಿ. ಇಮೇಲ್ ಕೋಡ್ ಕೇಳಿದರೆ ಇಲ್ಲಿ ನಕಲಿಸಿ Amazon‌ಗೆ ಮರಳಿ.", ready: "ನಿಮ್ಮ ಆಹ್ವಾನ ಸಿದ್ಧವಾಗಿದೆ", password: "ಪಾಸ್‌ವರ್ಡ್ ರಹಸ್ಯವಾಗಿರಲಿ", passwordBody: "Amazon‌ನಲ್ಲಿ ಹೊಂದಿಸಿದ ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ Flex‌ಗೆ ಲಾಗಿನ್ ಮಾಡಿ. DropX ಅದನ್ನು ರಚಿಸುವುದಿಲ್ಲ, ಓದುವುದಿಲ್ಲ ಅಥವಾ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ.",
    steps: {
      signin: { title: "ಅದೇ ಖಾತೆಯೊಂದಿಗೆ Flex ತೆರೆಯಿರಿ", actions: ["ಆಹ್ವಾನ ಸ್ವೀಕರಿಸಿ ಇಮೇಲ್ ದೃಢಪಡಿಸಿದ ನಂತರ Android ಫೋನ್‌ನಲ್ಲಿ Amazon Flex ಸ್ಥಾಪಿಸಿ. Amazon ಡೌನ್‌ಲೋಡ್ ಸೂಚನೆ ಅಥವಾ ಕೆಳಗಿನ ಲಿಂಕ್ ಬಳಸಿ.", "ಇಲ್ಲಿ ತೋರಿಸಿದ ಇಮೇಲ್ ಮತ್ತು ನೀವು ಹೊಂದಿಸಿದ ಪಾಸ್‌ವರ್ಡ್‌ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ. ಅನುಮತಿ ಸೂಚನೆಗಳನ್ನು ಓದಿ onboarding ಕೆಲಸಗಳನ್ನು ತೆರೆಯಿರಿ."], expect: "Start ಬಟನ್‌ಗಳಿರುವ ಕೆಲಸದ ಪಟ್ಟಿ ಕಾಣುತ್ತದೆ. ಪಾಸ್‌ವರ್ಡ್ ಹೊಂದಿಸುವುದಷ್ಟೇ ನೋಂದಣಿ ಪೂರ್ಣವಲ್ಲ.", help: "ಕೆಲಸಗಳು ಕಾಣುತ್ತಿಲ್ಲವೇ? ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ, ತಪ್ಪು ಖಾತೆಯಿಂದ ಹೊರಬಂದು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ. ಪಾಸ್‌ವರ್ಡ್ ಮರೆತರೆ Amazon password reset ಬಳಸಿ; ಮತ್ತೊಂದು ಖಾತೆ ರಚಿಸಬೇಡಿ." },
      privacy: { title: "ಗೌಪ್ಯತಾ ನಿಯಮ ಓದಿ", actions: ["Flex‌ನಲ್ಲಿ Privacy Agreement ಪಕ್ಕದ Start ಒತ್ತಿ.", "ಸೂಚನೆ ಓದಿ. ಒಪ್ಪಿದರೆ acknowledgement ಆಯ್ಕೆ ಮಾಡಿ Continue ಒತ್ತಿ."], expect: "ಕೆಲಸದ ಪಟ್ಟಿಗೆ ಮರಳಿ ಮುಂದಿನ ಲಭ್ಯ ಕೆಲಸ ತೆರೆಯಿರಿ.", help: "ನಿಯಮದ ಬಗ್ಗೆ ಅನುಮಾನವಿದ್ದರೆ ಒಪ್ಪುವ ಮೊದಲು ಸ್ಟೇಷನ್ ತಂಡವನ್ನು ಕೇಳಿ. ಕಡ್ಡಾಯ ಕೆಲಸ ಬಿಡಬೇಡಿ." },
      about: { title: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವಿವರ ನೀಡಿ", actions: ["About You ತೆರೆಯಿರಿ. ಚಾಲನಾ ಪರವಾನಗಿಯಲ್ಲಿರುವ ಹೆಸರು ಯಥಾವತ್ತಾಗಿ ನೀಡಿ. PAN ಹೆಸರಿನಲ್ಲಿ ವ್ಯತ್ಯಾಸವಿದ್ದರೆ ಮೊದಲು ಸ್ಟೇಷನ್ ತಂಡವನ್ನು ಕೇಳಿ.", "ಸರಿಯಾದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ಸಂಪೂರ್ಣ ಪ್ರಸ್ತುತ ವಿಳಾಸ ನೀಡಿ: ಮನೆ/ಮಹಡಿ, ರಸ್ತೆ, ಗುರುತು, ನಗರ, ರಾಜ್ಯ, PIN. ಪರಿಶೀಲಿಸಿ Continue ಒತ್ತಿ."], expect: "ನಿಮ್ಮ ವಿವರಗಳು Flex‌ನಲ್ಲಿ ಉಳಿಯುತ್ತವೆ.", help: "ದಾಖಲೆಗಿಂತ ಭಿನ್ನವಾದ ಸಂಕ್ಷಿಪ್ತ ಹೆಸರು ಬೇಡ. ತಪ್ಪು ವಿವರ ಸರಿಪಡಿಸಲಾಗದಿದ್ದರೆ TL ಸಂಪರ್ಕಿಸಿ." },
      licence: { title: "ಚಾಲನಾ ಪರವಾನಗಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", actions: ["License Verification ತೆರೆಯಿರಿ. ಶಾಶ್ವತ ಚಾಲನಾ ಪರವಾನಗಿಯ ಮುಂಭಾಗ ಮತ್ತು ಹಿಂಭಾಗ ಪೂರ್ಣವಾಗಿ ಸ್ಪಷ್ಟವಾಗಿರುವ ಚಿತ್ರ ನೀಡಿ.", "ಪರವಾನಗಿ ಸಂಖ್ಯೆಯ spaces, hyphens, slashes ಮತ್ತು ಆರಂಭದ ಸೊನ್ನೆಗಳನ್ನು ಹಾಗೆಯೇ ನೀಡಿ. ಜನ್ಮದಿನ, ನೀಡಿದ ರಾಜ್ಯ, ಅವಧಿ ಪರಿಶೀಲಿಸಿ Submit ಒತ್ತಿ."], expect: "In Progress ಎಂದರೆ Amazon ಪರಿಶೀಲಿಸುತ್ತಿದೆ. ತಿರಸ್ಕೃತವಾದರೆ ಕಾರಣದಂತೆ ವಿವರ ಅಥವಾ ಚಿತ್ರ ಸರಿಪಡಿಸಿ ಮತ್ತೆ ಸಲ್ಲಿಸಿ.", help: "ಮಸುಕಾದ ಚಿತ್ರ, ತಪ್ಪು ವಿವರ ವಿಳಂಬ ಉಂಟುಮಾಡುತ್ತವೆ. BGC ಆರಂಭಕ್ಕೆ ಪರವಾನಗಿ ಪರಿಶೀಲನೆ ಪಾಸ್ ಆಗಬೇಕು. ವಿಳಂಬವಾದರೆ TL ಕೇಳಿ; ಖಚಿತ ಅನುಮೋದನಾ ಸಮಯ ಊಹಿಸಬೇಡಿ." },
      photo: { title: "ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಫೋಟೋ ನೀಡಿ", actions: ["Photo ತೆರೆದು ಮುಖ ಸ್ಪಷ್ಟವಾಗಿ ಕಾಣಲು ಪರದೆಯ ಸೂಚನೆ ಅನುಸರಿಸಿ.", "ಸೆಲ್ಫಿ ತೆಗೆಯಿರಿ ಅಥವಾ ಆ್ಯಪ್ ಅನುಮತಿಸಿದರೆ ಚಿತ್ರ ಆರಿಸಿ. ಪರಿಶೀಲಿಸಿ Continue; ಅಸ್ಪಷ್ಟವಾದರೆ Redo ಒತ್ತಿ."], expect: "ಫೋಟೋ ಸಲ್ಲಿಕೆಯಾಗುತ್ತದೆ. BGC‌ಗೆ ಪರವಾನಗಿ ಅನುಮೋದನೆ ಮತ್ತು ಸ್ಟೇಷನ್ Associate Settings ಕೂಡ ಬೇಕು.", help: "BGC ತೆರೆಯದಿದ್ದರೆ LSC‌ನ service area, service type, supervisor ಪರಿಶೀಲಿಸಲು ಸ್ಟೇಷನ್ ತಂಡವನ್ನು ಕೇಳಿ." },
      bgc: { title: "ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ವಿವರ ನೀಡಿ", actions: ["Background Check ತೆರೆದು ಸಮ್ಮತಿ ಓದಿ; ಒಪ್ಪಿದರೆ ಮುಂದುವರಿಯಿರಿ. PAN‌ನಂತೆಯೇ ಹೆಸರು, PAN ಸಂಖ್ಯೆ, ತಂದೆಯ ಹೆಸರು ನೀಡಿ.", "ಹಿಂದಿನ ಇತಿಹಾಸ ಪ್ರಶ್ನೆಗಳಿಗೆ ಸತ್ಯವಾಗಿ ಉತ್ತರಿಸಿ, ಶಾಶ್ವತ ವಿಳಾಸ ನೀಡಿ. ಪರಿಶೀಲಿಸಿ ಸಲ್ಲಿಸಿ. DropX One‌ನಲ್ಲಿ ಬಂದ IDfy ವೀಡಿಯೊ, ದಾಖಲೆ, ವಿಳಾಸ ವಿನಂತಿ ಪೂರ್ಣಗೊಳಿಸಿ."], expect: "ಪರಿಶೀಲನೆಗಳು ಪ್ರತ್ಯೇಕವಾಗಿ ನಡೆಯಬಹುದು. In Progress ಎಂದರೆ ಕಾಯಿರಿ; insufficiency ಎಂದರೆ ಕೇಳಿದ ಕೊರತೆ ಸರಿಪಡಿಸಿ. ಬಂದ IDfy ಕೆಲಸಗಳನ್ನು Background verification‌ನಲ್ಲಿ ನೋಡಿ.", help: "BGC ಆರಂಭವಾಗದಿದ್ದರೆ ಪರವಾನಗಿ, ಫೋಟೋ, Associate Settings, vendor ಅಡಚಣೆಗಳನ್ನು TL ಪರಿಶೀಲಿಸಬೇಕು. ಬೇರೆಯವರ ದಾಖಲೆ ನೀಡಬೇಡಿ." },
      uan: { title: "ಕೇಳಿದಾಗ e-Shram UAN ನೀಡಿ", actions: ["Account setup ವೇಳೆ UAN VERIFICATION ನೋಡಿ. ನೀಡಿದ ಗೈಡ್ e-Shram UAN ಕೇಳುತ್ತದೆ; EPFO/PF UAN ಅಲ್ಲ.", "ಇದ್ದರೆ Yes ಆರಿಸಿ UAN ID‌ನ ಹೆಸರು, e-Shram UAN ಸಂಖ್ಯೆ ನೀಡಿ. ಇಲ್ಲದಿದ್ದರೆ ಸತ್ಯವಾಗಿ No ಆರಿಸಿ Amazon ಸೂಚನೆ ಅನುಸರಿಸಿ ಅಥವಾ TL ಕೇಳಿ. ಪರಿಶೀಲಿಸಿ Submit ಮಾಡಿ."], expect: "Amazon ಫಲಿತಾಂಶ ಅಥವಾ ಮುಂದಿನ ಸೂಚನೆ ಅನುಸರಿಸಿ. ಈ ಗೈಡ್ UAN ಪರಿಶೀಲಿಸುವುದಿಲ್ಲ ಅಥವಾ ಪೂರ್ಣ ಎಂದು ಗುರುತಿಸುವುದಿಲ್ಲ.", help: "ಪರದೆ ಇಲ್ಲವೇ ಅಥವಾ ಸಂಖ್ಯೆ ತಿರಸ್ಕೃತವೇ? Amazon ತೋರಿಸುವುದನ್ನು TL‌ಗೆ ತಿಳಿಸಿ. ಸಂಖ್ಯೆ ಊಹಿಸಬೇಡಿ; e-Shram ಜಾಗದಲ್ಲಿ PF UAN ನೀಡಬೇಡಿ." },
      account: { title: "Amazon ಖಾತೆ ಸೆಟಪ್ ಮುಗಿಸಲಿ", actions: ["Flex‌ನಲ್ಲಿ Account Setup ನೋಡಿ ಕೇಳಿದ ಕೆಲಸ ಮುಗಿಸಿ. ಇಲ್ಲಿ UAN ಕೇಳಿದರೆ ನೀಡಿ.", "Resolve Other Accounts ಬಂದರೆ Agree and Remove ಮೊದಲು TL ಜೊತೆ ಮಾತನಾಡಿ. ಪಟ್ಟಿಯ ಹಳೆಯ Amazon delivery ಖಾತೆಗಳು ತೆಗೆದುಹಾಕಲ್ಪಡುತ್ತವೆ/offboard ಆಗುತ್ತವೆ. ಯಾವ ಖಾತೆ ಉಳಿಸಬೇಕು ಎಂದು ದೃಢಪಡಿಸಿ."], expect: "ಪರಿಶೀಲನೆ ನಂತರ Amazon ಖಾತೆ ಸಿದ್ಧಗೊಳಿಸುತ್ತದೆ. Pending ಎಂದರೆ ನೀವು ಫಾರ್ಮ್ ಬಿಟ್ಟಿದ್ದೀರಿ ಎಂದಲ್ಲ.", help: "ನಿಂತಿದ್ದರೆ LSC ಪರಿಶೀಲಿಸಲು TL ಕೇಳಿ. ಪರದೆ ತೆರವುಗೊಳಿಸಲು ಮತ್ತೆ ನೋಂದಣಿ ಅಥವಾ ಖಾತೆ ಅಳಿಸುವುದು ಬೇಡ." },
      learning: { title: "Amazon ತರಬೇತಿ ಪೂರ್ಣಗೊಳಿಸಿ", actions: ["ಸ್ಟೇಷನ್ buddy training, Amazon LM Learning ಕೋರ್ಸ್‌ಗೆ ಪರ್ಯಾಯವಲ್ಲ. LM Learning ಲಾಗಿನ್ ಮತ್ತು ನೇಮಿಸಿದ ಹೊಸಬರ ಕೋರ್ಸ್‌ಗಾಗಿ TL ಕೇಳಿ. ಈ ಲಾಗಿನ್ Flex‌ಗಿಂತ ಭಿನ್ನವಾಗಬಹುದು.", "LM Learning ತೆರೆದು ಎಲ್ಲಾ ಕಡ್ಡಾಯ modules ಪೂರ್ಣಗೊಳಿಸಿ. Flex‌ಗೆ ಮರಳಿ Training ಮತ್ತು ಉಳಿದ ಕೆಲಸ ನೋಡಿ."], expect: "ಎಲ್ಲಾ ಕೆಲಸ Amazon ದೃಢಪಡಿಸಿದಾಗ Ready to Deliver ಕಾಣುತ್ತದೆ. ಕೇಳಿದರೆ ಅದೇ ಖಾತೆಯಿಂದ ಹೊರಬಂದು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ. ಡೆಲಿವರಿ ಆರಂಭವನ್ನು TL ದೃಢಪಡಿಸುತ್ತಾರೆ.", help: "ಲಾಗಿನ್/ಕೋರ್ಸ್ ಇಲ್ಲವೇ, ಸ್ಥಿತಿ ಬದಲಾಗಿಲ್ಲವೇ? ಸ್ಟೇಷನ್ ತಂಡಕ್ಕೆ LM Learning ಸೂಚನೆ ಬರುತ್ತದೆ; ಅವರು Amazon ಸಂಪರ್ಕಿಸಬೇಕು. ಈ ಗೈಡ್ ಓದುವುದು ತರಬೇತಿ ಅಲ್ಲ." },
    },
  },
  en: {
    title: "From invitation to your first delivery", intro: "Already set your Amazon password? Continue in the Flex app. We’ll guide you one screen at a time.",
    start: "Continue in Amazon Flex", invitation: "Invitation & email code", guide: "Flex registration guide", choose: "Choose a guide step",
    next: "Next guide step", back: "Back", finish: "Back to invitation", step: "Guide step", screen: "Find this in Amazon", expect: "What happens next", help: "Stuck on this step?",
    evidence: "This is a guide, not a completion checklist. Moving between steps does not change your registration status. Amazon may show tasks in a different order; follow the screen you see.",
    source: "Guide source", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "pages",
    flexDownload: "Get Amazon Flex", learningDownload: "Get LM Learning", status: "Check your live tasks", statusBody: "Open Amazon Flex for your current task status. This beta receives invitation and IDfy emails; detailed Flex, UAN and training completion are not yet confirmed here.",
    email: "Your Amazon Flex sign-in email", copyEmail: "Copy email", emailCopied: "Email copied", copyLink: "Copy invitation link", linkCopied: "Link copied", openInvitation: "Open invitation",
    browserTitle: "Use your new work account", browserBody: "Sign out of any Amazon account already open, or copy the invitation link into a private/incognito window. This button opens your normal browser.",
    invitationBody: "Accept the invitation with this email. Use your name exactly as on your driving licence and PAN. Set a strong password you can remember. If asked for an email code, return here to copy it, then go back to Amazon.",
    ready: "Your invitation is ready", password: "Keep your password private", passwordBody: "Use the password you set on Amazon when signing in to Flex. DropX does not create, read or store it.",
    steps: {
      signin: { title: "Open Flex with the same account", actions: ["After accepting the invitation and verifying your email, install Amazon Flex on your Android phone using Amazon’s download prompt or the link below.", "Open Flex. Sign in with the email shown here and the password you just created. Review the app’s permission prompts, then open your onboarding tasks."], expect: "A task list with Start buttons. Creating a password alone does not finish registration.", help: "Wrong account or no tasks? Check the email, sign out of the other account and sign in again. Forgot the password? Use Amazon’s password reset; do not create another account." },
      privacy: { title: "Read the Privacy Agreement", actions: ["In Flex, tap Start beside Privacy Agreement.", "Read the notice. If you agree, select the acknowledgement and Continue."], expect: "Return to the task list and open the next available task.", help: "If you have questions about the terms, ask your station team before accepting. Don’t skip a required task." },
      about: { title: "Enter your personal details", actions: ["Open About You. Enter your legal name exactly as on your driving licence. If it differs from your PAN, ask your station team first.", "Enter your correct mobile number and full current address: house/floor, street, landmark, city, state and PIN code. Review, then Continue."], expect: "Your personal details are saved in Flex.", help: "Avoid initials or shortened names that differ from your documents. If you cannot edit an incorrect detail, contact your team leader." },
      licence: { title: "Upload your driving licence", actions: ["Open License Verification. Upload clear, complete images of both FRONT and BACK of your permanent driving licence.", "Enter the licence number exactly, including spaces, hyphens, slashes and leading zeros. Check date of birth, issuing state and expiry date, then Submit."], expect: "In Progress means Amazon is reviewing it. If rejected, follow the stated reason and resubmit the corrected details or photos.", help: "Blurred images or mismatched details delay checks. Licence verification must pass before BGC can start. Ask your TL if review remains stuck; don’t assume a fixed approval time." },
      photo: { title: "Add your profile photo", actions: ["Open Photo and follow the on-screen requirements for a clear photo of your face.", "Take a selfie or choose a suitable photo if the app allows. Review it and Continue; use Redo if it is unclear."], expect: "The photo task is submitted. BGC also needs passed licence verification and the station’s Associate Settings.", help: "If BGC is still locked, ask the station team to check your service area, service type and supervisor in LSC." },
      bgc: { title: "Submit background-check details", actions: ["Open Background Check. Read the consent and proceed if you agree. Enter your name, PAN number and father’s name exactly as on PAN.", "Answer the history questions truthfully and provide the requested permanent address. Review and submit. Complete any IDfy video, document or address request shown in DropX One."], expect: "Checks may run separately. In Progress means wait; an insufficiency means provide the specific missing or corrected detail. Use Background verification here to see received IDfy actions.", help: "No BGC start? Your TL should check licence approval, photo, Associate Settings and any vendor-side block. Never submit another person’s documents." },
      uan: { title: "Complete e-Shram UAN when asked", actions: ["During account setup, look for UAN VERIFICATION. The supplied guide asks for an e-Shram UAN, not an EPFO/PF UAN.", "If you have one, select Yes and enter the name as on your UAN ID and your e-Shram UAN number. If not, select No truthfully and follow Amazon’s instructions or ask your TL. Review before Submit."], expect: "Follow Amazon’s result or next prompt. This guide cannot verify your UAN or mark it complete.", help: "Can’t find this screen, or the number is rejected? Tell your TL what Amazon shows. Do not invent a number or enter your PF UAN in an e-Shram field." },
      account: { title: "Let Amazon finish account setup", actions: ["Check Account Setup in Flex and complete any action Amazon asks for, including UAN if it appears here.", "If you see Resolve Other Accounts, speak to your TL before Agree and Remove. It removes/offboards the listed old Amazon delivery accounts; confirm which account must be retained."], expect: "Amazon provisions the account after its checks. Pending setup is not proof that you have missed a form.", help: "Ask your TL to check LSC if it is stuck. Do not repeat registration or remove an account simply to clear the screen." },
      learning: { title: "Finish Amazon’s required training", actions: ["Buddy training at the station does not replace Amazon’s assigned LM Learning course. Ask your TL for your LM Learning login and assigned new-hire course; this login may differ from Flex.", "Open LM Learning, complete every required module and follow the course’s completion instructions. Return to Flex and check Training and the remaining tasks."], expect: "When Amazon confirms all required tasks, Flex shows Ready to Deliver. If asked, sign out and sign back in with the same account. Your TL confirms when you can start deliveries.", help: "Missing credentials/course or training not updated? Your station team receives LM Learning instructions and should follow up with Amazon. Watching this guide does not count as training." },
    },
  },
  ml: {
    title: "ക്ഷണം മുതൽ ആദ്യ ഡെലിവറി വരെ", intro: "Amazon പാസ്‌വേഡ് സജ്ജമാക്കിയോ? ഇനി Flex ആപ്പിൽ തുടരാം. ഓരോ സ്ക്രീനിലും ചെയ്യേണ്ടത് ഇവിടെ കാണാം.", start: "Amazon Flex-ൽ തുടരാം", invitation: "ക്ഷണവും ഇമെയിൽ കോഡും", guide: "Flex രജിസ്ട്രേഷൻ സഹായം", choose: "സഹായഘട്ടം തിരഞ്ഞെടുക്കുക", next: "അടുത്ത സഹായഘട്ടം", back: "മടങ്ങുക", finish: "ക്ഷണത്തിലേക്ക് മടങ്ങുക", step: "സഹായഘട്ടം", screen: "Amazon-ൽ ഈ സ്ക്രീൻ തുറക്കുക", expect: "അടുത്തതായി എന്ത് സംഭവിക്കും", help: "ഈ ഘട്ടത്തിൽ സഹായം വേണോ?",
    evidence: "ഇത് ചെയ്യേണ്ട കാര്യങ്ങളുടെ വഴികാട്ടിയാണ്. ഘട്ടങ്ങൾ വായിക്കുന്നതോ മാറ്റുന്നതോ രജിസ്ട്രേഷൻ പൂർത്തിയായതായി രേഖപ്പെടുത്തില്ല. Amazon കാണിക്കുന്ന ക്രമം വ്യത്യസ്തമായേക്കാം; നിങ്ങളുടെ സ്ക്രീനിലെ നിർദ്ദേശം പിന്തുടരുക.", source: "മാർഗനിർദ്ദേശത്തിന്റെ ഉറവിടം", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "പേജുകൾ", flexDownload: "Amazon Flex ഡൗൺലോഡ് ചെയ്യുക", learningDownload: "LM Learning ഡൗൺലോഡ് ചെയ്യുക", status: "നിലവിലെ സ്ഥിതി പരിശോധിക്കുക", statusBody: "നിലവിലെ ജോലികളുടെ സ്ഥിതി Amazon Flex-ൽ നോക്കുക. ഈ ബീറ്റയിൽ ക്ഷണവും IDfy ഇമെയിലുകളും ലഭിക്കും; Flex, UAN, പരിശീലനം എന്നിവ പൂർത്തിയായതിന്റെ വിശദമായ സ്ഥിരീകരണം ഇവിടെ ഇതുവരെ ലഭ്യമല്ല.",
    email: "Amazon Flex-ൽ പ്രവേശിക്കാനുള്ള ഇമെയിൽ", copyEmail: "ഇമെയിൽ കോപ്പി ചെയ്യുക", emailCopied: "ഇമെയിൽ കോപ്പി ചെയ്തു", copyLink: "ക്ഷണലിങ്ക് കോപ്പി ചെയ്യുക", linkCopied: "ലിങ്ക് കോപ്പി ചെയ്തു", openInvitation: "ക്ഷണം തുറക്കുക", browserTitle: "പുതിയ ജോലി അക്കൗണ്ട് ഉപയോഗിക്കുക", browserBody: "മറ്റൊരു Amazon അക്കൗണ്ട് തുറന്നിട്ടുണ്ടെങ്കിൽ സൈൻ ഔട്ട് ചെയ്യുക. അല്ലെങ്കിൽ ക്ഷണലിങ്ക് കോപ്പി ചെയ്ത് private/incognito വിൻഡോയിൽ തുറക്കുക. ഈ ബട്ടൺ സാധാരണ ബ്രൗസറിലാണ് തുറക്കുന്നത്.", invitationBody: "ഈ ഇമെയിൽ ഉപയോഗിച്ച് ക്ഷണം സ്വീകരിക്കുക. ഡ്രൈവിംഗ് ലൈസൻസിലും PAN-ലുമുള്ള അതേ പേര് നൽകുക. ഓർത്തുവയ്ക്കാൻ കഴിയുന്ന ശക്തമായ പാസ്‌വേഡ് സജ്ജമാക്കുക. ഇമെയിൽ കോഡ് ചോദിച്ചാൽ ഇവിടെ വന്ന് കോപ്പി ചെയ്ത് Amazon-ലേക്ക് മടങ്ങുക.", ready: "നിങ്ങളുടെ ക്ഷണം തയ്യാറാണ്", password: "പാസ്‌വേഡ് സ്വകാര്യമായി സൂക്ഷിക്കുക", passwordBody: "Amazon-ൽ സജ്ജമാക്കിയ പാസ്‌വേഡ് ഉപയോഗിച്ചാണ് Flex-ൽ പ്രവേശിക്കേണ്ടത്. DropX അത് സൃഷ്ടിക്കുകയോ വായിക്കുകയോ സൂക്ഷിക്കുകയോ ചെയ്യുന്നില്ല.",
    steps: {
      signin: { title: "അതേ അക്കൗണ്ടിൽ Flex തുറക്കുക", actions: ["ക്ഷണം സ്വീകരിച്ച് ഇമെയിൽ സ്ഥിരീകരിച്ചശേഷം Android ഫോണിൽ Amazon Flex ഇൻസ്റ്റാൾ ചെയ്യുക. Amazon കാണിക്കുന്ന ഡൗൺലോഡ് നിർദ്ദേശമോ താഴെയുള്ള ലിങ്കോ ഉപയോഗിക്കാം.", "ഇവിടെ കാണുന്ന ഇമെയിലും നിങ്ങൾ സജ്ജമാക്കിയ പാസ്‌വേഡും നൽകി പ്രവേശിക്കുക. ആപ്പിലെ അനുമതി നിർദ്ദേശങ്ങൾ വായിച്ചശേഷം onboarding ജോലികൾ തുറക്കുക."], expect: "Start ബട്ടണുകളുള്ള ജോലിപ്പട്ടിക കാണും. പാസ്‌വേഡ് സജ്ജമാക്കുന്നതോടെ മാത്രം രജിസ്ട്രേഷൻ പൂർത്തിയാകില്ല.", help: "ജോലികൾ കാണുന്നില്ലേ? ഇമെയിൽ പരിശോധിക്കുക; തെറ്റായ അക്കൗണ്ടിൽനിന്ന് സൈൻ ഔട്ട് ചെയ്ത് വീണ്ടും പ്രവേശിക്കുക. പാസ്‌വേഡ് മറന്നാൽ Amazon password reset ഉപയോഗിക്കുക; പുതിയ അക്കൗണ്ട് ഉണ്ടാക്കരുത്." },
      privacy: { title: "സ്വകാര്യതാ നിബന്ധന വായിക്കുക", actions: ["Flex-ൽ Privacy Agreement-ന് സമീപമുള്ള Start അമർത്തുക.", "നിബന്ധന വായിക്കുക. സമ്മതമാണെങ്കിൽ acknowledgement തിരഞ്ഞെടുത്ത് Continue അമർത്തുക."], expect: "ജോലിപ്പട്ടികയിലേക്ക് മടങ്ങി അടുത്ത ലഭ്യമായ ജോലി തുറക്കുക.", help: "നിബന്ധനയിൽ സംശയമുണ്ടെങ്കിൽ സ്വീകരിക്കുന്നതിന് മുമ്പ് സ്റ്റേഷൻ ടീമിനോട് ചോദിക്കുക. നിർബന്ധമായ ജോലി ഒഴിവാക്കരുത്." },
      about: { title: "നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക", actions: ["About You തുറക്കുക. ഡ്രൈവിംഗ് ലൈസൻസിലെ അതേ പേര് നൽകുക. PAN-ലെ പേരുമായി വ്യത്യാസമുണ്ടെങ്കിൽ ആദ്യം സ്റ്റേഷൻ ടീമിനോട് ചോദിക്കുക.", "ശരിയായ മൊബൈൽ നമ്പറും നിലവിലെ പൂർണ്ണ വിലാസവും നൽകുക: വീട്/നില, തെരുവ്, സമീപ അടയാളം, നഗരം, സംസ്ഥാനം, PIN. പരിശോധിച്ചശേഷം Continue അമർത്തുക."], expect: "നിങ്ങളുടെ വിവരങ്ങൾ Flex-ൽ സേവ് ചെയ്യും.", help: "രേഖകളിൽനിന്ന് വ്യത്യസ്തമായ ചുരുക്കപ്പേര് ഉപയോഗിക്കരുത്. തെറ്റായ വിവരം തിരുത്താൻ കഴിയുന്നില്ലെങ്കിൽ TL-നെ ബന്ധപ്പെടുക." },
      licence: { title: "ഡ്രൈവിംഗ് ലൈസൻസ് അപ്‌ലോഡ് ചെയ്യുക", actions: ["License Verification തുറക്കുക. സ്ഥിരം ഡ്രൈവിംഗ് ലൈസൻസിന്റെ മുന്നും പിന്നും മുഴുവനായി വ്യക്തമായി കാണുന്ന ചിത്രങ്ങൾ നൽകുക.", "ലൈസൻസ് നമ്പറിലെ space, hyphen, slash, തുടക്കത്തിലെ പൂജ്യം എന്നിവ അതേപടി നൽകുക. ജനനത്തീയതി, നൽകിയ സംസ്ഥാനം, കാലാവധി എന്നിവ പരിശോധിച്ച് Submit അമർത്തുക."], expect: "In Progress എന്നാൽ Amazon പരിശോധിക്കുന്നു എന്നാണ്. നിരസിച്ചാൽ കാരണം വായിച്ച് തെറ്റായ വിവരമോ ചിത്രമോ തിരുത്തി വീണ്ടും നൽകുക.", help: "മങ്ങിയ ചിത്രങ്ങളും വിവരങ്ങളിലെ വ്യത്യാസവും കാലതാമസം വരുത്തും. BGC തുടങ്ങാൻ ലൈസൻസ് പരിശോധന വിജയിക്കണം. വൈകിയാൽ TL-നോട് ചോദിക്കുക; നിശ്ചിത സമയത്ത് അംഗീകാരം ലഭിക്കുമെന്ന് കരുതരുത്." },
      photo: { title: "നിങ്ങളുടെ ഫോട്ടോ നൽകുക", actions: ["Photo തുറന്ന് മുഖം വ്യക്തമായി കാണാനുള്ള നിർദ്ദേശങ്ങൾ പാലിക്കുക.", "സെൽഫി എടുക്കുക, അല്ലെങ്കിൽ ആപ്പ് അനുവദിച്ചാൽ ചിത്രം തിരഞ്ഞെടുക്കുക. പരിശോധിച്ച് Continue അമർത്തുക; വ്യക്തമല്ലെങ്കിൽ Redo ഉപയോഗിക്കുക."], expect: "ഫോട്ടോ സമർപ്പിക്കും. BGC-ക്ക് ലൈസൻസ് അംഗീകാരവും സ്റ്റേഷന്റെ Associate Settings-ഉം ആവശ്യമാണ്.", help: "BGC തുറക്കാനാകുന്നില്ലെങ്കിൽ LSC-യിലെ service area, service type, supervisor എന്നിവ സ്റ്റേഷൻ ടീമിനോട് പരിശോധിക്കാൻ പറയുക." },
      bgc: { title: "പശ്ചാത്തല പരിശോധനയ്ക്കുള്ള വിവരങ്ങൾ", actions: ["Background Check തുറക്കുക. സമ്മതപത്രം വായിച്ച് സമ്മതമാണെങ്കിൽ തുടരുക. PAN-ലെ അതേ പേര്, PAN നമ്പർ, അച്ഛന്റെ പേര് എന്നിവ നൽകുക.", "ചരിത്രത്തെക്കുറിച്ചുള്ള ചോദ്യങ്ങൾക്ക് സത്യസന്ധമായി മറുപടി നൽകി സ്ഥിരവിലാസം ചേർക്കുക. പരിശോധിച്ച് സമർപ്പിക്കുക. DropX One-ൽ വരുന്ന IDfy വീഡിയോ, രേഖ, വിലാസ പരിശോധനകൾ പൂർത്തിയാക്കുക."], expect: "പരിശോധനകൾ വേറിട്ട സമയങ്ങളിൽ നടക്കാം. In Progress എന്നാൽ കാത്തിരിക്കുക; insufficiency എന്നാൽ ആവശ്യപ്പെട്ട കുറവോ തെറ്റോ പരിഹരിക്കുക. ലഭിച്ച IDfy നിർദ്ദേശങ്ങൾ Background verification-ൽ കാണാം.", help: "BGC തുടങ്ങിയില്ലെങ്കിൽ ലൈസൻസ്, ഫോട്ടോ, Associate Settings, vendor തടസ്സങ്ങൾ എന്നിവ TL പരിശോധിക്കണം. മറ്റൊരാളുടെ രേഖകൾ നൽകരുത്." },
      uan: { title: "ആവശ്യപ്പെടുമ്പോൾ e-Shram UAN നൽകുക", actions: ["Account setup-ൽ UAN VERIFICATION വന്നാൽ തുറക്കുക. നൽകിയ ഗൈഡിൽ ചോദിക്കുന്നത് e-Shram UAN ആണ്; EPFO/PF UAN അല്ല.", "ഉണ്ടെങ്കിൽ Yes തിരഞ്ഞെടുത്ത് UAN ID-യിലെ പേരും e-Shram UAN നമ്പറും നൽകുക. ഇല്ലെങ്കിൽ സത്യസന്ധമായി No തിരഞ്ഞെടുത്ത് Amazon നിർദ്ദേശം പിന്തുടരുകയോ TL-നോട് ചോദിക്കുകയോ ചെയ്യുക. പരിശോധിച്ച് Submit ചെയ്യുക."], expect: "Amazon കാണിക്കുന്ന ഫലമോ അടുത്ത നിർദ്ദേശമോ പിന്തുടരുക. ഈ ഗൈഡ് UAN പരിശോധിക്കുകയോ പൂർത്തിയായതായി രേഖപ്പെടുത്തുകയോ ചെയ്യില്ല.", help: "സ്ക്രീൻ കാണുന്നില്ലേ, നമ്പർ സ്വീകരിക്കുന്നില്ലേ? Amazon കാണിക്കുന്നത് TL-നെ അറിയിക്കുക. നമ്പർ ഊഹിച്ച് നൽകരുത്; e-Shram സ്ഥാനത്ത് PF UAN നൽകരുത്." },
      account: { title: "Amazon അക്കൗണ്ട് സജ്ജമാക്കട്ടെ", actions: ["Flex-ൽ Account Setup പരിശോധിച്ച് ആവശ്യപ്പെടുന്ന കാര്യങ്ങൾ ചെയ്യുക. ഇവിടെ UAN ചോദിച്ചാൽ അതും പൂർത്തിയാക്കുക.", "Resolve Other Accounts വന്നാൽ Agree and Remove അമർത്തുന്നതിന് മുമ്പ് TL-നോട് സംസാരിക്കുക. അതിൽ കാണുന്ന പഴയ Amazon delivery അക്കൗണ്ടുകൾ നീക്കും/offboard ചെയ്യും. ഏത് അക്കൗണ്ടാണ് നിലനിർത്തേണ്ടതെന്ന് ഉറപ്പാക്കുക."], expect: "പരിശോധനകൾക്കുശേഷം Amazon അക്കൗണ്ട് സജ്ജമാക്കും. Pending എന്നത് നിങ്ങൾ ഒരു ഫോം വിട്ടുപോയി എന്നർത്ഥമല്ല.", help: "തടസ്സമുണ്ടെങ്കിൽ LSC പരിശോധിക്കാൻ TL-നോട് പറയുക. സ്ക്രീൻ മാറ്റാനായി വീണ്ടും രജിസ്റ്റർ ചെയ്യുകയോ അക്കൗണ്ട് നീക്കുകയോ അരുത്." },
      learning: { title: "Amazon പരിശീലനം പൂർത്തിയാക്കുക", actions: ["സ്റ്റേഷനിലെ buddy training, Amazon-ന്റെ LM Learning കോഴ്സിന് പകരമല്ല. LM Learning ലോഗിനും അനുവദിച്ച പുതിയ ജീവനക്കാരുടെ കോഴ്സും TL-നോട് ചോദിക്കുക. ഈ ലോഗിൻ Flex-ലേതിൽനിന്ന് വ്യത്യസ്തമായേക്കാം.", "LM Learning തുറന്ന് നിർബന്ധമായ എല്ലാ modules-ഉം പൂർത്തിയാക്കുക. Flex-ലേക്ക് മടങ്ങി Training-ഉം ബാക്കിയുള്ള ജോലികളും പരിശോധിക്കുക."], expect: "എല്ലാ ജോലികളും Amazon സ്ഥിരീകരിച്ചാൽ Ready to Deliver കാണിക്കും. ആവശ്യപ്പെട്ടാൽ അതേ അക്കൗണ്ടിൽ സൈൻ ഔട്ട് ചെയ്ത് വീണ്ടും പ്രവേശിക്കുക. ഡെലിവറി തുടങ്ങേണ്ടത് TL സ്ഥിരീകരിക്കും.", help: "ലോഗിൻ/കോഴ്സ് ഇല്ലേ, പൂർത്തിയായതായി കാണുന്നില്ലേ? സ്റ്റേഷൻ ടീമിന് LM Learning നിർദ്ദേശങ്ങൾ ലഭിക്കും; അവർ Amazon-നോട് അന്വേഷിക്കണം. ഈ ഗൈഡ് വായിക്കുന്നത് പരിശീലനമായി കണക്കാക്കില്ല." },
    },
  },
  te: {
    title: "ఆహ్వానం నుంచి మొదటి డెలివరీ వరకు", intro: "Amazon పాస్‌వర్డ్ సెట్ చేశారా? ఇప్పుడు Flex యాప్‌లో కొనసాగండి. ఒక్కో స్క్రీన్‌లో ఏం చేయాలో ఇక్కడ చూడండి.", start: "Amazon Flex‌లో కొనసాగండి", invitation: "ఆహ్వానం, ఇమెయిల్ కోడ్", guide: "Flex నమోదు మార్గదర్శిని", choose: "మార్గదర్శక దశను ఎంచుకోండి", next: "తదుపరి మార్గదర్శక దశ", back: "వెనుకకు", finish: "ఆహ్వానానికి తిరిగి వెళ్లండి", step: "మార్గదర్శక దశ", screen: "Amazon‌లో ఈ స్క్రీన్ చూడండి", expect: "తర్వాత ఏమవుతుంది", help: "ఈ దశలో సహాయం కావాలా?",
    evidence: "ఇది మార్గదర్శిని మాత్రమే. దశలు చదవడం లేదా మార్చడం వల్ల నమోదు స్థితి మారదు. Amazon పనుల క్రమం వేరుగా ఉండవచ్చు; మీ స్క్రీన్ సూచనలు అనుసరించండి.", source: "మార్గదర్శక మూలం", amazonSource: "Amazon DA onboarding guide", dropxSource: "DropX ID creation guide", pages: "పేజీలు", flexDownload: "Amazon Flex పొందండి", learningDownload: "LM Learning పొందండి", status: "ప్రస్తుత పనుల స్థితి చూడండి", statusBody: "ప్రస్తుత స్థితిని Amazon Flex‌లో చూడండి. ఈ బీటాలో ఆహ్వానం, IDfy ఇమెయిళ్లు అందుతాయి; Flex, UAN, శిక్షణ పూర్తయిన వివరాలు ఇక్కడ ఇంకా నిర్ధారించబడలేదు.",
    email: "Amazon Flex లాగిన్ ఇమెయిల్", copyEmail: "ఇమెయిల్ కాపీ చేయండి", emailCopied: "ఇమెయిల్ కాపీ అయింది", copyLink: "ఆహ్వాన లింక్ కాపీ చేయండి", linkCopied: "లింక్ కాపీ అయింది", openInvitation: "ఆహ్వానం తెరవండి", browserTitle: "కొత్త పని ఖాతాను ఉపయోగించండి", browserBody: "ఇప్పటికే తెరిచి ఉన్న Amazon ఖాతా నుంచి సైన్ అవుట్ చేయండి లేదా లింక్‌ను private/incognito విండోలో తెరవండి. ఈ బటన్ సాధారణ బ్రౌజర్‌లో తెరుస్తుంది.", invitationBody: "ఈ ఇమెయిల్‌తో ఆహ్వానం అంగీకరించండి. డ్రైవింగ్ లైసెన్స్, PAN‌లో ఉన్నట్లే పేరు ఇవ్వండి. గుర్తుంచుకోగల బలమైన పాస్‌వర్డ్ సెట్ చేయండి. ఇమెయిల్ కోడ్ అడిగితే ఇక్కడ కాపీ చేసి Amazon‌కు తిరిగి వెళ్లండి.", ready: "మీ ఆహ్వానం సిద్ధంగా ఉంది", password: "పాస్‌వర్డ్‌ను రహస్యంగా ఉంచండి", passwordBody: "Amazon‌లో సెట్ చేసిన పాస్‌వర్డ్‌తో Flex‌లో ప్రవేశించండి. DropX దాన్ని సృష్టించదు, చదవదు, నిల్వ చేయదు.",
    steps: {
      signin: { title: "అదే ఖాతాతో Flex తెరవండి", actions: ["ఆహ్వానం అంగీకరించి ఇమెయిల్ నిర్ధారించిన తర్వాత Android ఫోన్‌లో Amazon Flex ఇన్‌స్టాల్ చేయండి. Amazon చూపే డౌన్‌లోడ్ సూచన లేదా కింది లింక్ వాడండి.", "ఇక్కడ చూపిన ఇమెయిల్, మీరు సెట్ చేసిన పాస్‌వర్డ్‌తో లాగిన్ అవ్వండి. అనుమతి సూచనలు చదివి onboarding పనులు తెరవండి."], expect: "Start బటన్‌లతో పనుల జాబితా వస్తుంది. పాస్‌వర్డ్ సెట్ చేయడం మాత్రమే నమోదు పూర్తి కాదు.", help: "పనులు కనిపించలేదా? ఇమెయిల్ తనిఖీ చేసి తప్పు ఖాతా నుంచి సైన్ అవుట్ చేసి మళ్లీ లాగిన్ అవ్వండి. పాస్‌వర్డ్ మరిస్తే Amazon password reset వాడండి; మరో ఖాతా సృష్టించవద్దు." },
      privacy: { title: "గోప్యతా నిబంధన చదవండి", actions: ["Flex‌లో Privacy Agreement పక్కన Start నొక్కండి.", "నిబంధన చదవండి. అంగీకరిస్తే acknowledgement ఎంచుకుని Continue నొక్కండి."], expect: "పనుల జాబితాకు తిరిగి వెళ్లి తదుపరి అందుబాటులో ఉన్న పని తెరవండి.", help: "నిబంధనలపై సందేహం ఉంటే అంగీకరించే ముందు స్టేషన్ బృందాన్ని అడగండి. తప్పనిసరి పనిని వదలవద్దు." },
      about: { title: "మీ వ్యక్తిగత వివరాలు ఇవ్వండి", actions: ["About You తెరిచి డ్రైవింగ్ లైసెన్స్‌లో ఉన్నట్లే పేరు ఇవ్వండి. PAN పేరుతో తేడా ఉంటే ముందుగా స్టేషన్ బృందాన్ని అడగండి.", "సరైన మొబైల్ నంబర్, పూర్తి ప్రస్తుత చిరునామా ఇవ్వండి: ఇల్లు/అంతస్తు, వీధి, గుర్తింపు ప్రదేశం, నగరం, రాష్ట్రం, PIN. తనిఖీ చేసి Continue నొక్కండి."], expect: "మీ వివరాలు Flex‌లో సేవ్ అవుతాయి.", help: "పత్రాలకు భిన్నమైన పొట్టి పేర్లు వాడవద్దు. తప్పు వివరాన్ని మార్చలేకపోతే TL‌ను సంప్రదించండి." },
      licence: { title: "డ్రైవింగ్ లైసెన్స్ అప్‌లోడ్ చేయండి", actions: ["License Verification తెరిచి శాశ్వత డ్రైవింగ్ లైసెన్స్ ముందు, వెనుక భాగాలు పూర్తిగా స్పష్టంగా కనిపించే ఫోటోలు ఇవ్వండి.", "లైసెన్స్ నంబర్‌లో spaces, hyphens, slashes, మొదటి సున్నాలు యథాతథంగా ఇవ్వండి. పుట్టిన తేదీ, జారీ రాష్ట్రం, గడువు తనిఖీ చేసి Submit నొక్కండి."], expect: "In Progress అంటే Amazon పరిశీలిస్తోంది. తిరస్కరిస్తే కారణం ప్రకారం వివరాలు లేదా ఫోటోలు సరిచేసి మళ్లీ పంపండి.", help: "అస్పష్టమైన ఫోటోలు, వివరాల తేడాలు ఆలస్యం చేస్తాయి. BGC ప్రారంభానికి లైసెన్స్ ఆమోదం అవసరం. ఆలస్యమైతే TL‌ను అడగండి; నిర్దిష్ట ఆమోద సమయం అనుకోకండి." },
      photo: { title: "మీ ప్రొఫైల్ ఫోటో ఇవ్వండి", actions: ["Photo తెరిచి ముఖం స్పష్టంగా కనిపించడానికి స్క్రీన్ సూచనలు పాటించండి.", "సెల్ఫీ తీసుకోండి లేదా యాప్ అనుమతిస్తే ఫోటో ఎంచుకోండి. తనిఖీ చేసి Continue; స్పష్టంగా లేకపోతే Redo నొక్కండి."], expect: "ఫోటో సమర్పించబడుతుంది. BGC‌కు లైసెన్స్ ఆమోదం, స్టేషన్ Associate Settings కూడా అవసరం.", help: "BGC తెరుచుకోకపోతే LSC‌లో service area, service type, supervisor తనిఖీ చేయమని స్టేషన్ బృందాన్ని అడగండి." },
      bgc: { title: "నేపథ్య తనిఖీ వివరాలు ఇవ్వండి", actions: ["Background Check తెరిచి సమ్మతి చదవండి; అంగీకరిస్తే కొనసాగండి. PAN‌లో ఉన్నట్లే పేరు, PAN నంబర్, తండ్రి పేరు ఇవ్వండి.", "గత చరిత్ర ప్రశ్నలకు నిజాయితీగా సమాధానం ఇచ్చి శాశ్వత చిరునామా నమోదు చేయండి. తనిఖీ చేసి పంపండి. DropX One‌లో వచ్చే IDfy వీడియో, పత్రం, చిరునామా అభ్యర్థనలు పూర్తి చేయండి."], expect: "తనిఖీలు వేర్వేరుగా జరగవచ్చు. In Progress అంటే వేచి ఉండండి; insufficiency అంటే అడిగిన లోపాన్ని సరిచేయండి. అందిన IDfy పనులు Background verification‌లో చూడండి.", help: "BGC మొదలవకపోతే లైసెన్స్, ఫోటో, Associate Settings, vendor అడ్డంకులను TL తనిఖీ చేయాలి. ఇతరుల పత్రాలు ఇవ్వవద్దు." },
      uan: { title: "అడిగినప్పుడు e-Shram UAN ఇవ్వండి", actions: ["Account setup సమయంలో UAN VERIFICATION చూడండి. ఇచ్చిన గైడ్‌లో e-Shram UAN అడుగుతోంది; EPFO/PF UAN కాదు.", "ఉంటే Yes ఎంచుకుని UAN ID‌లోని పేరు, e-Shram UAN నంబర్ ఇవ్వండి. లేకపోతే నిజాయితీగా No ఎంచుకుని Amazon సూచనలు పాటించండి లేదా TL‌ను అడగండి. తనిఖీ చేసి Submit చేయండి."], expect: "Amazon చూపే ఫలితం లేదా తదుపరి సూచన అనుసరించండి. ఈ గైడ్ UAN‌ను ధృవీకరించదు లేదా పూర్తిగా గుర్తించదు.", help: "స్క్రీన్ కనిపించలేదా, నంబర్ తిరస్కరించిందా? Amazon చూపేది TL‌కు చెప్పండి. ఊహించిన నంబర్ ఇవ్వవద్దు; e-Shram స్థానంలో PF UAN ఇవ్వవద్దు." },
      account: { title: "Amazon ఖాతా సెటప్ పూర్తి చేయనివ్వండి", actions: ["Flex‌లో Account Setup చూడండి. అడిగిన పనులు పూర్తి చేయండి; ఇక్కడ UAN అడిగితే ఇవ్వండి.", "Resolve Other Accounts వస్తే Agree and Remove ముందు TL‌తో మాట్లాడండి. జాబితాలోని పాత Amazon delivery ఖాతాలు తొలగించబడతాయి/offboard అవుతాయి. ఏ ఖాతా ఉంచాలో నిర్ధారించండి."], expect: "తనిఖీల తర్వాత Amazon ఖాతా సిద్ధం చేస్తుంది. Pending అంటే మీరు ఫారం మిస్ చేశారని కాదు.", help: "ఆగిపోయితే LSC తనిఖీ చేయమని TL‌ను అడగండి. స్క్రీన్ తొలగించడానికి మళ్లీ నమోదు లేదా ఖాతా తొలగింపు చేయవద్దు." },
      learning: { title: "Amazon శిక్షణ పూర్తి చేయండి", actions: ["స్టేషన్ buddy training, Amazon LM Learning కోర్సుకు ప్రత్యామ్నాయం కాదు. LM Learning లాగిన్, కేటాయించిన కొత్తవారి కోర్సు కోసం TL‌ను అడగండి. ఈ లాగిన్ Flex‌కు భిన్నంగా ఉండవచ్చు.", "LM Learning తెరిచి ప్రతి తప్పనిసరి మాడ్యూల్ పూర్తి చేయండి. Flex‌కు తిరిగి వచ్చి Training, మిగిలిన పనులు చూడండి."], expect: "అన్ని పనులు Amazon నిర్ధారిస్తే Ready to Deliver కనిపిస్తుంది. అడిగితే అదే ఖాతాతో సైన్ అవుట్ చేసి మళ్లీ లాగిన్ అవ్వండి. డెలివరీలు ఎప్పుడు మొదలుపెట్టాలో TL నిర్ధారిస్తారు.", help: "లాగిన్/కోర్సు లేదా స్థితి అప్‌డేట్ లేదా? స్టేషన్ బృందానికి LM Learning సూచనలు అందుతాయి; వారు Amazon‌తో మాట్లాడాలి. ఈ గైడ్ చదవడం శిక్షణ కాదు." },
    },
  },
};
