export const betaAmazonOtpCopy = {
  te: {
    label: "AMAZON ఇమెయిల్ నిర్ధారణ", title: "మీ నిర్ధారణ కోడ్", waiting: "కొత్త కోడ్ కోసం వేచి ఉంది", empty: "Amazon OTP అడుగుతోందా?", emptyBody: "Amazon నిర్ధారణ పేజీ తెరిచి ఉంచండి. ఇమెయిల్ కోడ్ ఇక్కడ స్వయంగా కనిపిస్తుంది.", instruction: "కోడ్ కాపీ చేసి Amazonకు తిరిగి వెళ్లి “Enter security code”లో పేస్ట్ చేయండి.", older: "కొత్త కోడ్ కోరండి", olderBody: "తాజా ఇమెయిల్ పాతది. కోడ్ గడువు Amazon నిర్ణయిస్తుంది; అవసరమైతే కొత్తది కోరండి.", unreadable: "ఇమెయిల్ వచ్చింది, కోడ్ చదవలేకపోయాం", unreadableBody: "Amazonలో మరో కోడ్ కోరండి. కనిపించకపోతే సహాయం కోసం కాల్ చేయండి.", resend: "కొత్త కోడ్ కావాలా?", resendTitle: "Amazon నుంచి మళ్లీ పంపించండి", resendBody: "Amazon నిర్ధారణ పేజీలో “Resend code” నొక్కండి. ఆ పేజీ తెరిచి ఉంచి ఇక్కడికి రండి. కొత్త ఇమెయిల్ కోడ్ స్వయంగా కనిపిస్తుంది.", previous: "వేచి ఉన్నప్పుడు పాత కోడ్ దాచబడుతుంది. మరో కోడ్ Amazon మాత్రమే పంపగలదు.", delayed: "ఆలస్యమవుతోందా? Amazonలో పై ఇమెయిల్ ఉందో చూడండి. మళ్లీ “Resend code” నొక్కే ముందు Amazon చెప్పిన సమయం వేచి ఉండండి లేదా సహాయం కోసం కాల్ చేయండి.", check: "కొత్త కోడ్ చూడండి", checking: "ఇన్‌బాక్స్ తనిఖీ చేస్తోంది…", automatic: "ప్రతి 15 సెకన్లకు స్వయంగా అప్‌డేట్", received: "ఇమెయిల్ అందిన సమయం", copy: "కోడ్ కాపీ చేయండి", copied: "కోడ్ కాపీ అయింది", copyError: "కోడ్‌ను నొక్కి పట్టుకుని కాపీ చేయండి.", offline: "ఇంటర్నెట్ లేదు. మళ్లీ కనెక్ట్ చేసి కోడ్ చూడండి.", error: "ఇన్‌బాక్స్ చూడలేకపోయాం. మళ్లీ ప్రయత్నించండి; Amazon పేజీ తెరిచి ఉంచవచ్చు.", signin: "ఈ ప్రైవేట్ ఇన్‌బాక్స్ చూడటానికి మీ బీటా ఖాతా మళ్లీ తెరవండి.", retry: "మళ్లీ ప్రయత్నించండి", privacy: "మీ బీటా ఖాతాలో మాత్రమే కనిపిస్తుంది. కోడ్ ఎవరితోనూ పంచుకోవద్దు.",
  },
  ta: {
    label: "AMAZON மின்னஞ்சல் உறுதிப்படுத்தல்", title: "உங்கள் உறுதிப்படுத்தல் குறியீடு", waiting: "புதிய குறியீட்டிற்காகக் காத்திருக்கிறது", empty: "Amazon OTP கேட்கிறதா?", emptyBody: "Amazon உறுதிப்படுத்தல் பக்கத்தைத் திறந்து வைக்கவும். மின்னஞ்சல் குறியீடு இங்கு தானாகத் தோன்றும்.", instruction: "குறியீட்டை நகலெடுத்து Amazon திரும்பி “Enter security code” பகுதியில் ஒட்டவும்.", older: "புதிய குறியீடு கோரவும்", olderBody: "கடைசி மின்னஞ்சல் பழையது. குறியீட்டின் காலாவதியை Amazon தீர்மானிக்கும்; தேவைப்பட்டால் புதியது கோரவும்.", unreadable: "மின்னஞ்சல் வந்தது, குறியீட்டைப் படிக்க முடியவில்லை", unreadableBody: "Amazon-ல் மற்றொரு குறியீடு கோரவும். வரவில்லையெனில் உதவிக்கு அழைக்கவும்.", resend: "புதிய குறியீடு வேண்டுமா?", resendTitle: "Amazon-லிருந்து மீண்டும் அனுப்பவும்", resendBody: "Amazon உறுதிப்படுத்தல் பக்கத்தில் “Resend code” அழுத்தவும். அப்பக்கத்தைத் திறந்து வைத்துவிட்டு இங்கு திரும்பவும். புதிய மின்னஞ்சல் குறியீடு தானாகத் தோன்றும்.", previous: "காத்திருக்கும்போது பழைய குறியீடு மறைக்கப்படும். Amazon மட்டுமே புதிய குறியீடு அனுப்ப முடியும்.", delayed: "தாமதமாகிறதா? Amazon-ல் மேலுள்ள மின்னஞ்சல்தான் உள்ளதா பாருங்கள். மீண்டும் “Resend code” அழுத்தும்முன் Amazon கூறும் நேரம் காத்திருக்கவும் அல்லது உதவிக்கு அழைக்கவும்.", check: "புதிய குறியீட்டைப் பார்க்கவும்", checking: "இன்பாக்ஸ் சரிபார்க்கிறது…", automatic: "ஒவ்வொரு 15 வினாடிக்கும் தானாகப் புதுப்பிக்கும்", received: "மின்னஞ்சல் வந்த நேரம்", copy: "குறியீட்டை நகலெடுக்கவும்", copied: "குறியீடு நகலெடுக்கப்பட்டது", copyError: "குறியீட்டை அழுத்திப் பிடித்து நகலெடுக்கவும்.", offline: "இணையம் இல்லை. இணைந்தபின் குறியீட்டைப் பார்க்கவும்.", error: "இன்பாக்ஸ் பார்க்க முடியவில்லை. மீண்டும் முயலவும்; Amazon பக்கத்தைத் திறந்து வைக்கலாம்.", signin: "இந்தத் தனிப்பட்ட இன்பாக்ஸ் பார்க்க உங்கள் பீட்டா கணக்கை மீண்டும் திறக்கவும்.", retry: "மீண்டும் முயலவும்", privacy: "உங்கள் பீட்டா கணக்கில் மட்டுமே தெரியும். குறியீட்டைப் பகிர வேண்டாம்.",
  },
  kn: {
    label: "AMAZON ಇಮೇಲ್ ದೃಢೀಕರಣ", title: "ನಿಮ್ಮ ದೃಢೀಕರಣ ಕೋಡ್", waiting: "ಹೊಸ ಕೋಡ್‌ಗಾಗಿ ಕಾಯುತ್ತಿದೆ", empty: "Amazon OTP ಕೇಳುತ್ತಿದೆಯೇ?", emptyBody: "Amazon ದೃಢೀಕರಣ ಪುಟ ತೆರೆದಿಡಿ. ಇಮೇಲ್ ಕೋಡ್ ಇಲ್ಲಿ ತಾನಾಗಿಯೇ ಕಾಣುತ್ತದೆ.", instruction: "ಕೋಡ್ ನಕಲಿಸಿ Amazonಗೆ ಮರಳಿ “Enter security code”ನಲ್ಲಿ ಅಂಟಿಸಿ.", older: "ಹೊಸ ಕೋಡ್ ಕೇಳಿ", olderBody: "ಕೊನೆಯ ಇಮೇಲ್ ಹಳೆಯದು. ಕೋಡ್ ಅವಧಿಯನ್ನು Amazon ನಿರ್ಧರಿಸುತ್ತದೆ; ಬೇಕಾದರೆ ಹೊಸದು ಕೇಳಿ.", unreadable: "ಇಮೇಲ್ ಬಂದಿದೆ, ಕೋಡ್ ಓದಲಾಗಲಿಲ್ಲ", unreadableBody: "Amazonನಲ್ಲಿ ಮತ್ತೊಂದು ಕೋಡ್ ಕೇಳಿ. ಕಾಣದಿದ್ದರೆ ಸಹಾಯಕ್ಕೆ ಕರೆ ಮಾಡಿ.", resend: "ಹೊಸ ಕೋಡ್ ಬೇಕೇ?", resendTitle: "Amazonನಿಂದ ಮತ್ತೆ ಕಳುಹಿಸಿ", resendBody: "Amazon ದೃಢೀಕರಣ ಪುಟದಲ್ಲಿ “Resend code” ಒತ್ತಿ. ಆ ಪುಟ ತೆರೆದಿಟ್ಟು ಇಲ್ಲಿಗೆ ಮರಳಿ. ಹೊಸ ಇಮೇಲ್ ಕೋಡ್ ತಾನಾಗಿಯೇ ಕಾಣುತ್ತದೆ.", previous: "ಕಾಯುವಾಗ ಹಳೆಯ ಕೋಡ್ ಮರೆಮಾಡಲಾಗುತ್ತದೆ. Amazon ಮಾತ್ರ ಮತ್ತೊಂದು ಕೋಡ್ ಕಳುಹಿಸಬಲ್ಲದು.", delayed: "ತಡವಾಗುತ್ತಿದೆಯೇ? Amazonನಲ್ಲಿ ಮೇಲಿನ ಇಮೇಲ್ ಇದೆಯೇ ನೋಡಿ. ಮತ್ತೆ “Resend code” ಒತ್ತುವ ಮೊದಲು Amazon ಹೇಳಿದ ಸಮಯ ಕಾಯಿರಿ ಅಥವಾ ಸಹಾಯಕ್ಕೆ ಕರೆ ಮಾಡಿ.", check: "ಹೊಸ ಕೋಡ್ ನೋಡಿ", checking: "ಇನ್‌ಬಾಕ್ಸ್ ಪರಿಶೀಲಿಸುತ್ತಿದೆ…", automatic: "ಪ್ರತಿ 15 ಸೆಕೆಂಡಿಗೆ ತಾನಾಗಿಯೇ ನವೀಕರಣ", received: "ಇಮೇಲ್ ಬಂದ ಸಮಯ", copy: "ಕೋಡ್ ನಕಲಿಸಿ", copied: "ಕೋಡ್ ನಕಲಿಸಲಾಗಿದೆ", copyError: "ಕೋಡ್ ಒತ್ತಿಹಿಡಿದು ನಕಲಿಸಿ.", offline: "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ. ಸಂಪರ್ಕಿಸಿ ಮತ್ತೆ ಕೋಡ್ ನೋಡಿ.", error: "ಇನ್‌ಬಾಕ್ಸ್ ಪರಿಶೀಲಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ; Amazon ಪುಟ ತೆರೆದಿರಬಹುದು.", signin: "ಈ ಖಾಸಗಿ ಇನ್‌ಬಾಕ್ಸ್ ನೋಡಲು ನಿಮ್ಮ ಬೀಟಾ ಖಾತೆ ಮತ್ತೆ ತೆರೆಯಿರಿ.", retry: "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ", privacy: "ನಿಮ್ಮ ಬೀಟಾ ಖಾತೆಯಲ್ಲಿ ಮಾತ್ರ ಕಾಣುತ್ತದೆ. ಕೋಡ್ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.",
  },
  hi: {
    label: "AMAZON ईमेल सत्यापन", title: "आपका सत्यापन कोड", waiting: "नए कोड का इंतजार है", empty: "Amazon OTP माँग रहा है?", emptyBody: "Amazon का सत्यापन पेज खुला रखें। ईमेल का कोड यहाँ अपने आप दिखेगा।", instruction: "कोड कॉपी करके Amazon पर लौटें और “Enter security code” में पेस्ट करें।", older: "नया कोड माँगें", olderBody: "आखिरी ईमेल पुराना है। कोड कब खत्म होगा, Amazon तय करता है; जरूरत हो तो नया माँगें।", unreadable: "ईमेल मिला, लेकिन कोड नहीं पढ़ पाए", unreadableBody: "Amazon पर दूसरा कोड माँगें। फिर भी न दिखे तो मदद के लिए कॉल करें।", resend: "नया कोड चाहिए?", resendTitle: "Amazon से दोबारा भेजें", resendBody: "Amazon के सत्यापन पेज पर “Resend code” दबाएँ। वह पेज खुला रखकर यहाँ लौटें। नया ईमेल कोड अपने आप दिखेगा।", previous: "इंतजार के दौरान पुराना कोड छिपा रहेगा। सिर्फ Amazon दूसरा कोड भेज सकता है।", delayed: "देरी हो रही है? Amazon में ऊपर वाला ईमेल ही है, यह जाँचें। दोबारा “Resend code” दबाने से पहले Amazon का बताया समय रुकें या मदद के लिए कॉल करें।", check: "नया कोड देखें", checking: "इनबॉक्स जाँच रहे हैं…", automatic: "हर 15 सेकंड में अपने आप अपडेट", received: "ईमेल मिलने का समय", copy: "कोड कॉपी करें", copied: "कोड कॉपी हो गया", copyError: "कोड को दबाकर रखें और कॉपी करें।", offline: "इंटरनेट नहीं है। दोबारा जुड़कर कोड देखें।", error: "इनबॉक्स नहीं देख पाए। फिर कोशिश करें; Amazon पेज खुला रख सकते हैं।", signin: "यह निजी इनबॉक्स देखने के लिए अपना बीटा खाता फिर खोलें।", retry: "फिर कोशिश करें", privacy: "सिर्फ आपके बीटा खाते में दिखता है। कोड किसी से साझा न करें।",
  },
  or: {
    label: "AMAZON ଇମେଲ୍ ଯାଞ୍ଚ", title: "ଆପଣଙ୍କ ଯାଞ୍ଚ କୋଡ୍", waiting: "ନୂଆ କୋଡ୍ ପାଇଁ ଅପେକ୍ଷା", empty: "Amazon OTP ମାଗୁଛି?", emptyBody: "Amazon ଯାଞ୍ଚ ପୃଷ୍ଠା ଖୋଲା ରଖନ୍ତୁ। ଇମେଲ୍ କୋଡ୍ ଏଠାରେ ଆପେ ଦେଖାଯିବ।", instruction: "କୋଡ୍ କପି କରି Amazonକୁ ଫେରି “Enter security code”ରେ ପେଷ୍ଟ କରନ୍ତୁ।", older: "ନୂଆ କୋଡ୍ ମାଗନ୍ତୁ", olderBody: "ଶେଷ ଇମେଲ୍ ପୁରୁଣା। କୋଡ୍‌ର ଅବଧି Amazon ନିର୍ଦ୍ଧାରଣ କରେ; ଦରକାର ହେଲେ ନୂଆ ମାଗନ୍ତୁ।", unreadable: "ଇମେଲ୍ ଆସିଛି, କୋଡ୍ ପଢ଼ିପାରିଲୁ ନାହିଁ", unreadableBody: "Amazonରେ ଆଉ କୋଡ୍ ମାଗନ୍ତୁ। ନଦେଖାଗଲେ ସାହାଯ୍ୟ ପାଇଁ କଲ୍ କରନ୍ତୁ।", resend: "ନୂଆ କୋଡ୍ ଦରକାର?", resendTitle: "Amazonରୁ ପୁଣି ପଠାନ୍ତୁ", resendBody: "Amazon ଯାଞ୍ଚ ପୃଷ୍ଠାରେ “Resend code” ଦବାନ୍ତୁ। ସେହି ପୃଷ୍ଠା ଖୋଲା ରଖି ଏଠାକୁ ଫେରନ୍ତୁ। ନୂଆ ଇମେଲ୍ କୋଡ୍ ଆପେ ଦେଖାଯିବ।", previous: "ଅପେକ୍ଷା ବେଳେ ପୁରୁଣା କୋଡ୍ ଲୁଚିବ। କେବଳ Amazon ଆଉ କୋଡ୍ ପଠାଇପାରେ।", delayed: "ବିଳମ୍ବ ହେଉଛି? Amazonରେ ଉପର ଇମେଲ୍ ଅଛି କି ଦେଖନ୍ତୁ। ପୁଣି “Resend code” ପୂର୍ବରୁ Amazon କହିଥିବା ସମୟ ଅପେକ୍ଷା କରନ୍ତୁ ବା ସାହାଯ୍ୟ ପାଇଁ କଲ୍ କରନ୍ତୁ।", check: "ନୂଆ କୋଡ୍ ଦେଖନ୍ତୁ", checking: "ଇନବକ୍ସ ଯାଞ୍ଚ ହେଉଛି…", automatic: "ପ୍ରତି 15 ସେକେଣ୍ଡରେ ଆପେ ଅପଡେଟ୍", received: "ଇମେଲ୍ ଆସିବା ସମୟ", copy: "କୋଡ୍ କପି କରନ୍ତୁ", copied: "କୋଡ୍ କପି ହେଲା", copyError: "କୋଡ୍ ଦବାଇ ଧରି କପି କରନ୍ତୁ।", offline: "ଇଣ୍ଟରନେଟ୍ ନାହିଁ। ପୁଣି ଯୋଡ଼ି କୋଡ୍ ଦେଖନ୍ତୁ।", error: "ଇନବକ୍ସ ଦେଖିପାରିଲୁ ନାହିଁ। ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ; Amazon ପୃଷ୍ଠା ଖୋଲା ରଖିପାରିବେ।", signin: "ଏହି ନିଜସ୍ୱ ଇନବକ୍ସ ଦେଖିବାକୁ ବିଟା ଖାତା ପୁଣି ଖୋଲନ୍ତୁ।", retry: "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ", privacy: "କେବଳ ଆପଣଙ୍କ ବିଟା ଖାତାରେ ଦେଖାଯାଏ। କୋଡ୍ କାହାକୁ ଦିଅନ୍ତୁ ନାହିଁ।",
  },
  en: {
    label: "AMAZON EMAIL VERIFICATION", title: "Your verification code", waiting: "Waiting for your new code",
    empty: "Amazon asking for an OTP?", emptyBody: "Keep Amazon’s verification page open. Your email code will appear here automatically.",
    instruction: "Copy this code, return to Amazon and paste it into “Enter security code”.",
    older: "Request a fresh code", olderBody: "The latest email is older. Amazon decides when a code expires; request a new one if needed.",
    unreadable: "We received an email, but couldn’t read its code", unreadableBody: "Request another code on Amazon. If it still does not appear, use Call for help.",
    resend: "Need a new code?", resendTitle: "Resend from Amazon", resendBody: "On Amazon’s verification page, tap “Resend code”. Keep that page open, then return here. DropX will show the new email automatically.",
    previous: "The previous code is hidden while you wait. Only Amazon can send another code.",
    delayed: "Taking longer than usual? Check that Amazon shows the email above. Follow any wait time on Amazon before tapping “Resend code” again, or use Call for help.",
    check: "Check for new code", checking: "Checking inbox…", automatic: "Updates automatically · every 15 seconds",
    received: "Email received", copy: "Copy code", copied: "Code copied", copyError: "Press and hold the code to copy it.",
    offline: "You’re offline. Reconnect to check for your code.", error: "We couldn’t check your inbox. Try again; your Amazon page can stay open.",
    signin: "Reopen your beta account to check this private inbox.", retry: "Try again", privacy: "Visible only in your own beta account. Never share this code.",
  },
  ml: {
    label: "AMAZON ഇമെയിൽ സ്ഥിരീകരണം", title: "നിങ്ങളുടെ സ്ഥിരീകരണ കോഡ്", waiting: "പുതിയ കോഡിനായി കാത്തിരിക്കുന്നു",
    empty: "Amazon OTP ചോദിക്കുന്നുണ്ടോ?", emptyBody: "Amazon സ്ഥിരീകരണ പേജ് തുറന്നുവയ്ക്കുക. ഇമെയിലിൽ വരുന്ന കോഡ് ഇവിടെ സ്വയം കാണിക്കും.",
    instruction: "ഈ കോഡ് കോപ്പി ചെയ്ത് Amazon-ലേക്ക് മടങ്ങുക. “Enter security code” എന്നിടത്ത് പേസ്റ്റ് ചെയ്യുക.",
    older: "പുതിയ കോഡ് ആവശ്യപ്പെടുക", olderBody: "അവസാനം ലഭിച്ച ഇമെയിൽ പഴയതാണ്. കോഡിന്റെ കാലാവധി Amazon തീരുമാനിക്കുന്നു. ആവശ്യമെങ്കിൽ പുതിയ കോഡ് ആവശ്യപ്പെടുക.",
    unreadable: "ഇമെയിൽ ലഭിച്ചു, പക്ഷേ കോഡ് വായിക്കാനായില്ല", unreadableBody: "Amazon-ൽ വീണ്ടും കോഡ് ആവശ്യപ്പെടുക. ഇനിയും കാണുന്നില്ലെങ്കിൽ സഹായത്തിനായി വിളിക്കുക.",
    resend: "പുതിയ കോഡ് വേണോ?", resendTitle: "Amazon-ൽ നിന്ന് വീണ്ടും അയയ്ക്കുക", resendBody: "Amazon സ്ഥിരീകരണ പേജിൽ “Resend code” അമർത്തുക. ആ പേജ് തുറന്നുവച്ച് ഇവിടെ തിരിച്ചുവരിക. പുതിയ ഇമെയിൽ ലഭിച്ചാൽ കോഡ് സ്വയം കാണിക്കും.",
    previous: "കാത്തിരിക്കുമ്പോൾ പഴയ കോഡ് മറച്ചിരിക്കുന്നു. പുതിയ കോഡ് അയയ്ക്കാൻ Amazon-ന് മാത്രമേ കഴിയൂ.",
    delayed: "വൈകുന്നുണ്ടോ? Amazon-ൽ മുകളിൽ കാണുന്ന അതേ ഇമെയിലാണെന്ന് ഉറപ്പാക്കുക. Amazon പറയുന്ന സമയം കാത്തിരുന്നശേഷം “Resend code” വീണ്ടും അമർത്തുക, അല്ലെങ്കിൽ സഹായത്തിനായി വിളിക്കുക.",
    check: "പുതിയ കോഡ് പരിശോധിക്കുക", checking: "ഇൻബോക്സ് പരിശോധിക്കുന്നു…", automatic: "ഓരോ 15 സെക്കൻഡിലും സ്വയം പുതുക്കും",
    received: "ഇമെയിൽ ലഭിച്ചത്", copy: "കോഡ് കോപ്പി ചെയ്യുക", copied: "കോഡ് കോപ്പി ചെയ്തു", copyError: "കോഡ് അമർത്തിപ്പിടിച്ച് കോപ്പി ചെയ്യുക.",
    offline: "ഇന്റർനെറ്റ് ലഭ്യമല്ല. കണക്ഷൻ വന്നശേഷം കോഡ് പരിശോധിക്കുക.", error: "ഇൻബോക്സ് പരിശോധിക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക. Amazon പേജ് തുറന്നുവയ്ക്കാം.",
    signin: "ഈ സ്വകാര്യ ഇൻബോക്സ് കാണാൻ നിങ്ങളുടെ ബീറ്റ അക്കൗണ്ട് വീണ്ടും തുറക്കുക.", retry: "വീണ്ടും ശ്രമിക്കുക", privacy: "നിങ്ങളുടെ സ്വന്തം ബീറ്റ അക്കൗണ്ടിൽ മാത്രം കാണാം. കോഡ് മറ്റാരുമായും പങ്കിടരുത്.",
  },
};
