import type { GuidanceLanguage } from "./beta-guidance";
import type { FlexGuideStep } from "./beta-flex-guide";

// Only flattened, redacted examples belong here. Never link the original PDFs.
export const flexScreenExamples = {
  signin: ["flex-signin"], privacy: ["privacy"], about: ["about-name", "about-contact"],
  licence: ["licence-front", "licence-back", "licence-review"], photo: ["profile-photo"],
  bgc: ["bgc-consent", "bgc-details", "bgc-address"], uan: ["eshram-uan"],
  account: ["account-review", "account-resolve"], learning: ["training-task"],
} as const satisfies Record<FlexGuideStep, readonly string[]>;
export type FlexScreenId = typeof flexScreenExamples[FlexGuideStep][number];
type ScreenCopy = {
  title: string; note: string; enlarge: string; close: string; previous: string; next: string;
  screen: string; examples: Record<FlexScreenId, readonly string[]>;
};
export const flexScreenCopy: Record<GuidanceLanguage, ScreenCopy> = {
  en: {
    title: "See what to fill", note: "Example screens · Personal details removed. Enter your own details. Your Amazon screen may look different.",
    enlarge: "View full screen", close: "Close example", previous: "Previous screen", next: "Next screen", screen: "Example screen",
    examples: {
      "flex-signin": ["Enter the invited email shown in DropX One.", "Use the Amazon password you created when accepting the invitation.", "Tap Sign in."],
      privacy: ["Open and read the Privacy Notice.", "Continue after reviewing it. Read any agreement before accepting."],
      "about-name": ["Enter your full legal name exactly as on your driving licence.", "Fill your current address and city."],
      "about-contact": ["Use your own mobile number, state and PIN code. Answer the personal questions accurately.", "Review your details, then Continue."],
      "licence-front": ["Photograph the entire front of your own licence clearly.", "Continue when the image is readable; use Redo if needed."],
      "licence-back": ["Photograph the entire back of the same licence.", "Check that it is clear, then Continue."],
      "licence-review": ["Check both images, date of birth and all licence details.", "Submit only when they match your document."],
      "profile-photo": ["Use a clear photo of yourself, with your whole face visible.", "Review it, then Submit. Retake if unclear."],
      "bgc-consent": ["Read the background-check consent and the checks listed.", "Continue only if you agree."],
      "bgc-details": ["Enter your name as on PAN.", "Enter your PAN and father's name as on PAN. Answer history questions truthfully."],
      "bgc-address": ["Enter your permanent address, city, state and PIN code.", "Review the address, then Continue."],
      "eshram-uan": ["Enter your name as on your UAN ID.", "If you have an e-Shram UAN, choose Yes and enter it. Otherwise choose No; follow Amazon's instructions or ask your TL. Do not enter PF UAN here.", "Check the details before Submit."],
      "account-review": ["Resolve Other Accounts appears only if Amazon finds an earlier delivery account. Ask your TL to review it."],
      "account-resolve": ["Agree and Remove removes/offboards the listed earlier accounts. Confirm with your TL which account to keep before using it."],
      "training-task": ["Open Training → Next. Ask your TL for your LM Learning login and assigned course; complete every required module."],
    },
  },
  ml: {
    title: "എന്ത് പൂരിപ്പിക്കണമെന്ന് കാണാം", note: "മാതൃകാ സ്ക്രീനുകൾ · വ്യക്തിവിവരങ്ങൾ നീക്കിയിട്ടുണ്ട്. നിങ്ങളുടെ സ്വന്തം വിവരങ്ങൾ നൽകുക. Amazon സ്ക്രീനിൽ ചെറിയ വ്യത്യാസങ്ങൾ ഉണ്ടാകാം.",
    enlarge: "സ്ക്രീൻ വലുതായി കാണുക", close: "മാതൃക അടയ്ക്കുക", previous: "മുൻ സ്ക്രീൻ", next: "അടുത്ത സ്ക്രീൻ", screen: "മാതൃകാ സ്ക്രീൻ",
    examples: {
      "flex-signin": ["DropX One-ൽ കാണുന്ന ക്ഷണം ലഭിച്ച ഇമെയിൽ നൽകുക.", "ക്ഷണം സ്വീകരിക്കുമ്പോൾ നിങ്ങൾ സൃഷ്ടിച്ച Amazon പാസ്‌വേഡ് നൽകുക.", "Sign in അമർത്തുക."],
      privacy: ["Privacy Notice തുറന്ന് വായിക്കുക.", "വായിച്ചശേഷം Continue ചെയ്യുക. കരാർ അംഗീകരിക്കുന്നതിന് മുമ്പ് വായിക്കുക."],
      "about-name": ["ഡ്രൈവിങ് ലൈസൻസിലുള്ളതുപോലെ പൂർണ പേര് നൽകുക.", "നിലവിലെ വിലാസവും നഗരവും പൂരിപ്പിക്കുക."],
      "about-contact": ["സ്വന്തം മൊബൈൽ നമ്പർ, സംസ്ഥാനം, പിൻ കോഡ് നൽകുക. വ്യക്തിഗത ചോദ്യങ്ങൾക്ക് കൃത്യമായി മറുപടി നൽകുക.", "വിവരങ്ങൾ പരിശോധിച്ച് Continue അമർത്തുക."],
      "licence-front": ["സ്വന്തം ലൈസൻസിന്റെ മുൻവശം മുഴുവനായി വ്യക്തമായി ചിത്രമെടുക്കുക.", "ചിത്രം വായിക്കാൻ കഴിയുന്നുവെങ്കിൽ Continue; ആവശ്യമെങ്കിൽ Redo ഉപയോഗിക്കുക."],
      "licence-back": ["അതേ ലൈസൻസിന്റെ പിൻവശം മുഴുവനായി ചിത്രമെടുക്കുക.", "വ്യക്തമാണെന്ന് ഉറപ്പാക്കി Continue അമർത്തുക."],
      "licence-review": ["രണ്ട് ചിത്രങ്ങളും ജനനത്തീയതിയും ലൈസൻസ് വിവരങ്ങളും പരിശോധിക്കുക.", "രേഖയുമായി ഒത്തുനോക്കിയശേഷം Submit ചെയ്യുക."],
      "profile-photo": ["മുഖം മുഴുവൻ വ്യക്തമായി കാണുന്ന സ്വന്തം ഫോട്ടോ നൽകുക.", "പരിശോധിച്ച് Submit ചെയ്യുക. വ്യക്തമല്ലെങ്കിൽ വീണ്ടും എടുക്കുക."],
      "bgc-consent": ["പശ്ചാത്തല പരിശോധനയ്ക്കുള്ള സമ്മതപത്രവും പരിശോധനകളുടെ പട്ടികയും വായിക്കുക.", "സമ്മതമാണെങ്കിൽ മാത്രം Continue ചെയ്യുക."],
      "bgc-details": ["PAN-ലുള്ളതുപോലെ പേര് നൽകുക.", "PAN നമ്പറും PAN-ലുള്ള അച്ഛന്റെ പേരും നൽകുക. മുൻകാല വിവരങ്ങൾക്ക് സത്യസന്ധമായി മറുപടി നൽകുക."],
      "bgc-address": ["സ്ഥിരവിലാസം, നഗരം, സംസ്ഥാനം, പിൻ കോഡ് നൽകുക.", "വിലാസം പരിശോധിച്ച് Continue ചെയ്യുക."],
      "eshram-uan": ["UAN ID-ലുള്ളതുപോലെ പേര് നൽകുക.", "e-Shram UAN ഉണ്ടെങ്കിൽ Yes തിരഞ്ഞെടുത്ത് നൽകുക. ഇല്ലെങ്കിൽ No തിരഞ്ഞെടുക്കുക; Amazon നിർദേശം പിന്തുടരുക അല്ലെങ്കിൽ TL-നോട് ചോദിക്കുക. ഇവിടെ PF UAN നൽകരുത്.", "വിവരങ്ങൾ പരിശോധിച്ചശേഷം Submit ചെയ്യുക."],
      "account-review": ["മുൻ Amazon ഡെലിവറി അക്കൗണ്ട് കണ്ടെത്തിയാൽ മാത്രം Resolve Other Accounts കാണും. TL-നോട് പരിശോധിക്കാൻ പറയുക."],
      "account-resolve": ["Agree and Remove അമർത്തിയാൽ കാണിച്ച പഴയ അക്കൗണ്ടുകൾ നീക്കം/offboard ചെയ്യും. ഏത് അക്കൗണ്ട് നിലനിർത്തണമെന്ന് TL-നോട് ഉറപ്പാക്കിയശേഷം മാത്രം ഉപയോഗിക്കുക."],
      "training-task": ["Training → Next തുറക്കുക. LM Learning ലോഗിനും കോഴ്സും TL-നോട് ചോദിച്ച് എല്ലാ നിർബന്ധിത ഭാഗങ്ങളും പൂർത്തിയാക്കുക."],
    },
  },
  te: {
    title: "ఏం నింపాలో చూడండి", note: "నమూనా స్క్రీన్‌లు · వ్యక్తిగత వివరాలు తొలగించబడ్డాయి. మీ సొంత వివరాలు ఇవ్వండి. మీ Amazon స్క్రీన్ కొంత భిన్నంగా ఉండవచ్చు.",
    enlarge: "పూర్తి స్క్రీన్ చూడండి", close: "నమూనా మూసివేయండి", previous: "ముందు స్క్రీన్", next: "తర్వాతి స్క్రీన్", screen: "నమూనా స్క్రీన్",
    examples: {
      "flex-signin": ["DropX Oneలో చూపిన ఆహ్వాన ఇమెయిల్ ఇవ్వండి.", "ఆహ్వానం అంగీకరించేటప్పుడు మీరు సృష్టించిన Amazon పాస్‌వర్డ్ వాడండి.", "Sign in నొక్కండి."],
      privacy: ["Privacy Notice తెరిచి చదవండి.", "చదివిన తర్వాత Continue చేయండి. ఏ ఒప్పందమైనా అంగీకరించే ముందు చదవండి."],
      "about-name": ["డ్రైవింగ్ లైసెన్స్‌లో ఉన్నట్లే పూర్తి పేరు ఇవ్వండి.", "ప్రస్తుత చిరునామా, నగరం నింపండి."],
      "about-contact": ["మీ మొబైల్ నంబర్, రాష్ట్రం, PIN కోడ్ ఇవ్వండి. వ్యక్తిగత ప్రశ్నలకు కచ్చితంగా జవాబివ్వండి.", "వివరాలు చూసి Continue నొక్కండి."],
      "licence-front": ["మీ లైసెన్స్ ముందు భాగం పూర్తిగా స్పష్టంగా ఫోటో తీయండి.", "చదవగలిగితే Continue; అవసరమైతే Redo వాడండి."],
      "licence-back": ["అదే లైసెన్స్ వెనుక భాగం పూర్తిగా ఫోటో తీయండి.", "స్పష్టంగా ఉందని చూసి Continue నొక్కండి."],
      "licence-review": ["రెండు చిత్రాలు, పుట్టిన తేదీ, లైసెన్స్ వివరాలు చూడండి.", "మీ పత్రంతో సరిపోలినప్పుడే Submit చేయండి."],
      "profile-photo": ["ముఖం పూర్తిగా స్పష్టంగా కనిపించే మీ ఫోటో ఇవ్వండి.", "పరిశీలించి Submit చేయండి. స్పష్టంగా లేకపోతే మళ్లీ తీయండి."],
      "bgc-consent": ["నేపథ్య తనిఖీ సమ్మతి, తనిఖీల జాబితా చదవండి.", "అంగీకరిస్తేనే Continue చేయండి."],
      "bgc-details": ["PANలో ఉన్నట్లే పేరు ఇవ్వండి.", "PAN నంబర్, PANలోని తండ్రి పేరు ఇవ్వండి. గత చరిత్ర ప్రశ్నలకు నిజాయితీగా జవాబివ్వండి."],
      "bgc-address": ["శాశ్వత చిరునామా, నగరం, రాష్ట్రం, PIN కోడ్ ఇవ్వండి.", "చిరునామా చూసి Continue చేయండి."],
      "eshram-uan": ["UAN IDలో ఉన్నట్లే పేరు ఇవ్వండి.", "e-Shram UAN ఉంటే Yes ఎంచుకుని ఇవ్వండి. లేకపోతే No ఎంచుకుని Amazon సూచనలు పాటించండి లేదా TLను అడగండి. ఇక్కడ PF UAN ఇవ్వవద్దు.", "వివరాలు చూసిన తర్వాత Submit చేయండి."],
      "account-review": ["పాత Amazon డెలివరీ ఖాతా ఉంటేనే Resolve Other Accounts కనిపిస్తుంది. TLతో పరిశీలించండి."],
      "account-resolve": ["Agree and Remove నొక్కితే చూపిన పాత ఖాతాలు తొలగించబడతాయి/offboard అవుతాయి. ఏ ఖాతా ఉంచాలో TLతో నిర్ధారించుకున్న తర్వాతే వాడండి."],
      "training-task": ["Training → Next తెరవండి. LM Learning లాగిన్, కేటాయించిన కోర్సు కోసం TLను అడిగి అన్ని తప్పనిసరి modules పూర్తి చేయండి."],
    },
  },
  ta: {
    title: "எதை நிரப்ப வேண்டும் என்று பாருங்கள்", note: "மாதிரித் திரைகள் · தனிப்பட்ட விவரங்கள் நீக்கப்பட்டுள்ளன. உங்கள் சொந்த விவரங்களை உள்ளிடுங்கள். Amazon திரை சற்று மாறுபடலாம்.",
    enlarge: "முழுத் திரையைப் பார்க்க", close: "மாதிரியை மூடு", previous: "முந்தைய திரை", next: "அடுத்த திரை", screen: "மாதிரித் திரை",
    examples: {
      "flex-signin": ["DropX One-ல் காட்டும் அழைப்பு மின்னஞ்சலை உள்ளிடுங்கள்.", "அழைப்பை ஏற்கும்போது உருவாக்கிய Amazon கடவுச்சொல்லைப் பயன்படுத்துங்கள்.", "Sign in அழுத்துங்கள்."],
      privacy: ["Privacy Notice திறந்து படியுங்கள்.", "படித்த பிறகு Continue செய்யுங்கள். ஒப்பந்தத்தை ஏற்கும் முன் படியுங்கள்."],
      "about-name": ["ஓட்டுநர் உரிமத்தில் உள்ளபடியே முழுப் பெயரை உள்ளிடுங்கள்.", "தற்போதைய முகவரி, நகரத்தை நிரப்புங்கள்."],
      "about-contact": ["உங்கள் கைபேசி எண், மாநிலம், அஞ்சல் குறியீடு உள்ளிடுங்கள். தனிப்பட்ட கேள்விகளுக்குத் துல்லியமாகப் பதிலளியுங்கள்.", "விவரங்களைச் சரிபார்த்து Continue அழுத்துங்கள்."],
      "licence-front": ["உங்கள் உரிமத்தின் முன்பக்கம் முழுவதையும் தெளிவாகப் படம் எடுங்கள்.", "படிக்க முடிந்தால் Continue; தேவைப்பட்டால் Redo பயன்படுத்துங்கள்."],
      "licence-back": ["அதே உரிமத்தின் பின்பக்கம் முழுவதையும் படம் எடுங்கள்.", "தெளிவாக இருப்பதை உறுதிசெய்து Continue அழுத்துங்கள்."],
      "licence-review": ["இரு படங்கள், பிறந்த தேதி, உரிம விவரங்களைச் சரிபாருங்கள்.", "உங்கள் ஆவணத்துடன் பொருந்தினால் மட்டுமே Submit செய்யுங்கள்."],
      "profile-photo": ["முகம் முழுவதும் தெளிவாகத் தெரியும் உங்கள் புகைப்படத்தைப் பயன்படுத்துங்கள்.", "சரிபார்த்து Submit செய்யுங்கள். தெளிவில்லையெனில் மீண்டும் எடுங்கள்."],
      "bgc-consent": ["பின்னணிச் சோதனைக்கான சம்மதத்தையும் சோதனைப் பட்டியலையும் படியுங்கள்.", "ஒப்புக்கொண்டால் மட்டுமே Continue செய்யுங்கள்."],
      "bgc-details": ["PAN-ல் உள்ளபடியே பெயரை உள்ளிடுங்கள்.", "PAN எண், PAN-ல் உள்ள தந்தையின் பெயரை உள்ளிடுங்கள். கடந்தகாலக் கேள்விகளுக்கு உண்மையாகப் பதிலளியுங்கள்."],
      "bgc-address": ["நிரந்தர முகவரி, நகரம், மாநிலம், அஞ்சல் குறியீடு உள்ளிடுங்கள்.", "முகவரியைச் சரிபார்த்து Continue செய்யுங்கள்."],
      "eshram-uan": ["UAN ID-ல் உள்ளபடியே பெயரை உள்ளிடுங்கள்.", "e-Shram UAN இருந்தால் Yes தேர்ந்தெடுத்து உள்ளிடுங்கள். இல்லையெனில் No தேர்ந்தெடுத்து Amazon வழிமுறைகளைப் பின்பற்றுங்கள் அல்லது TL-ஐக் கேளுங்கள். இங்கு PF UAN உள்ளிட வேண்டாம்.", "விவரங்களைச் சரிபார்த்த பிறகு Submit செய்யுங்கள்."],
      "account-review": ["முந்தைய Amazon டெலிவரி கணக்கு இருந்தால் மட்டுமே Resolve Other Accounts வரும். TL-யிடம் சரிபார்க்கச் சொல்லுங்கள்."],
      "account-resolve": ["Agree and Remove காட்டப்பட்ட பழைய கணக்குகளை நீக்கும்/offboard செய்யும். எந்தக் கணக்கை வைத்திருக்க வேண்டும் என TL-யிடம் உறுதிசெய்த பிறகே பயன்படுத்துங்கள்."],
      "training-task": ["Training → Next திறக்கவும். LM Learning உள்நுழைவு, ஒதுக்கிய பாடத்திற்காக TL-ஐக் கேட்டு கட்டாயப் பகுதிகள் அனைத்தையும் முடிக்கவும்."],
    },
  },
  kn: {
    title: "ಏನು ತುಂಬಬೇಕೆಂದು ನೋಡಿ", note: "ಮಾದರಿ ಪರದೆಗಳು · ವೈಯಕ್ತಿಕ ವಿವರಗಳನ್ನು ತೆಗೆದುಹಾಕಲಾಗಿದೆ. ನಿಮ್ಮ ಸ್ವಂತ ವಿವರ ನೀಡಿ. Amazon ಪರದೆ ಸ್ವಲ್ಪ ಬೇರೆಯಾಗಿರಬಹುದು.",
    enlarge: "ಪೂರ್ಣ ಪರದೆ ನೋಡಿ", close: "ಮಾದರಿ ಮುಚ್ಚಿ", previous: "ಹಿಂದಿನ ಪರದೆ", next: "ಮುಂದಿನ ಪರದೆ", screen: "ಮಾದರಿ ಪರದೆ",
    examples: {
      "flex-signin": ["DropX Oneನಲ್ಲಿ ತೋರಿಸಿದ ಆಹ್ವಾನದ ಇಮೇಲ್ ನೀಡಿ.", "ಆಹ್ವಾನ ಒಪ್ಪುವಾಗ ನೀವು ರಚಿಸಿದ Amazon ಪಾಸ್‌ವರ್ಡ್ ಬಳಸಿ.", "Sign in ಒತ್ತಿ."],
      privacy: ["Privacy Notice ತೆರೆದು ಓದಿ.", "ಓದಿದ ಬಳಿಕ Continue ಮಾಡಿ. ಯಾವುದೇ ಒಪ್ಪಂದ ಒಪ್ಪುವ ಮೊದಲು ಓದಿ."],
      "about-name": ["ಚಾಲನಾ ಪರವಾನಗಿಯಲ್ಲಿರುವಂತೆ ಪೂರ್ಣ ಹೆಸರು ನೀಡಿ.", "ಪ್ರಸ್ತುತ ವಿಳಾಸ ಮತ್ತು ನಗರ ತುಂಬಿ."],
      "about-contact": ["ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ, ರಾಜ್ಯ, PIN ಕೋಡ್ ನೀಡಿ. ವೈಯಕ್ತಿಕ ಪ್ರಶ್ನೆಗಳಿಗೆ ಸರಿಯಾಗಿ ಉತ್ತರಿಸಿ.", "ವಿವರ ಪರಿಶೀಲಿಸಿ Continue ಒತ್ತಿ."],
      "licence-front": ["ನಿಮ್ಮ ಪರವಾನಗಿಯ ಪೂರ್ಣ ಮುಂಭಾಗವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಫೋಟೋ ತೆಗೆಯಿರಿ.", "ಓದಲು ಸಾಧ್ಯವಿದ್ದರೆ Continue; ಬೇಕಾದರೆ Redo ಬಳಸಿ."],
      "licence-back": ["ಅದೇ ಪರವಾನಗಿಯ ಪೂರ್ಣ ಹಿಂಭಾಗದ ಫೋಟೋ ತೆಗೆಯಿರಿ.", "ಸ್ಪಷ್ಟವಾಗಿದೆಯೇ ನೋಡಿ Continue ಒತ್ತಿ."],
      "licence-review": ["ಎರಡು ಚಿತ್ರಗಳು, ಜನ್ಮದಿನ, ಪರವಾನಗಿ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ.", "ನಿಮ್ಮ ದಾಖಲೆಗೆ ಹೊಂದಿದಾಗ ಮಾತ್ರ Submit ಮಾಡಿ."],
      "profile-photo": ["ನಿಮ್ಮ ಪೂರ್ಣ ಮುಖ ಸ್ಪಷ್ಟವಾಗಿ ಕಾಣುವ ಸ್ವಂತ ಫೋಟೋ ಬಳಸಿ.", "ಪರಿಶೀಲಿಸಿ Submit ಮಾಡಿ. ಅಸ್ಪಷ್ಟವಾದರೆ ಮತ್ತೆ ತೆಗೆಯಿರಿ."],
      "bgc-consent": ["ಹಿನ್ನೆಲೆ ಪರಿಶೀಲನೆ ಸಮ್ಮತಿ ಮತ್ತು ಪರೀಕ್ಷೆಗಳ ಪಟ್ಟಿಯನ್ನು ಓದಿ.", "ಒಪ್ಪಿದರೆ ಮಾತ್ರ Continue ಮಾಡಿ."],
      "bgc-details": ["PANನಲ್ಲಿರುವಂತೆ ಹೆಸರು ನೀಡಿ.", "PAN ಸಂಖ್ಯೆ ಮತ್ತು PANನಲ್ಲಿರುವ ತಂದೆಯ ಹೆಸರು ನೀಡಿ. ಹಿಂದಿನ ಇತಿಹಾಸ ಪ್ರಶ್ನೆಗಳಿಗೆ ಸತ್ಯವಾಗಿ ಉತ್ತರಿಸಿ."],
      "bgc-address": ["ಶಾಶ್ವತ ವಿಳಾಸ, ನಗರ, ರಾಜ್ಯ, PIN ಕೋಡ್ ನೀಡಿ.", "ವಿಳಾಸ ಪರಿಶೀಲಿಸಿ Continue ಮಾಡಿ."],
      "eshram-uan": ["UAN IDನಲ್ಲಿರುವಂತೆ ಹೆಸರು ನೀಡಿ.", "e-Shram UAN ಇದ್ದರೆ Yes ಆರಿಸಿ ನೀಡಿ. ಇಲ್ಲದಿದ್ದರೆ No ಆರಿಸಿ Amazon ಸೂಚನೆ ಅನುಸರಿಸಿ ಅಥವಾ TL ಕೇಳಿ. ಇಲ್ಲಿ PF UAN ನೀಡಬೇಡಿ.", "ವಿವರ ಪರಿಶೀಲಿಸಿದ ಬಳಿಕ Submit ಮಾಡಿ."],
      "account-review": ["ಹಿಂದಿನ Amazon ಡೆಲಿವರಿ ಖಾತೆ ಕಂಡರೆ ಮಾತ್ರ Resolve Other Accounts ಬರುತ್ತದೆ. TL ಜೊತೆ ಪರಿಶೀಲಿಸಿ."],
      "account-resolve": ["Agree and Remove ಪಟ್ಟಿಯ ಹಳೆಯ ಖಾತೆಗಳನ್ನು ತೆಗೆದುಹಾಕುತ್ತದೆ/offboard ಮಾಡುತ್ತದೆ. ಯಾವ ಖಾತೆ ಉಳಿಸಬೇಕೆಂದು TL ಜೊತೆ ದೃಢಪಡಿಸಿ ಮಾತ್ರ ಬಳಸಿ."],
      "training-task": ["Training → Next ತೆರೆಯಿರಿ. LM Learning ಲಾಗಿನ್ ಮತ್ತು ನೇಮಿಸಿದ ಕೋರ್ಸ್‌ಗಾಗಿ TL ಕೇಳಿ; ಎಲ್ಲ ಕಡ್ಡಾಯ modules ಪೂರ್ಣಗೊಳಿಸಿ."],
    },
  },
  hi: {
    title: "देखें क्या भरना है", note: "उदाहरण स्क्रीन · निजी विवरण हटा दिए गए हैं। अपनी जानकारी भरें। आपकी Amazon स्क्रीन थोड़ी अलग दिख सकती है।",
    enlarge: "पूरी स्क्रीन देखें", close: "उदाहरण बंद करें", previous: "पिछली स्क्रीन", next: "अगली स्क्रीन", screen: "उदाहरण स्क्रीन",
    examples: {
      "flex-signin": ["DropX One में दिखाया गया निमंत्रण वाला ईमेल भरें।", "निमंत्रण स्वीकार करते समय बनाया गया अपना Amazon पासवर्ड डालें।", "Sign in दबाएँ।"],
      privacy: ["Privacy Notice खोलकर पढ़ें।", "पढ़ने के बाद Continue करें। कोई भी समझौता स्वीकार करने से पहले पढ़ें।"],
      "about-name": ["ड्राइविंग लाइसेंस के अनुसार अपना पूरा कानूनी नाम भरें।", "मौजूदा पता और शहर भरें।"],
      "about-contact": ["अपना मोबाइल नंबर, राज्य और PIN कोड भरें। निजी सवालों के सही जवाब दें।", "विवरण जाँचकर Continue दबाएँ।"],
      "licence-front": ["अपने लाइसेंस के पूरे सामने वाले हिस्से की साफ फोटो लें।", "फोटो पढ़ने योग्य हो तो Continue; जरूरत हो तो Redo करें।"],
      "licence-back": ["उसी लाइसेंस के पूरे पीछे वाले हिस्से की फोटो लें।", "साफ दिख रहा हो तो Continue दबाएँ।"],
      "licence-review": ["दोनों फोटो, जन्मतिथि और लाइसेंस के विवरण जाँचें।", "दस्तावेज से मेल खाने पर ही Submit करें।"],
      "profile-photo": ["अपनी साफ फोटो दें जिसमें पूरा चेहरा दिखे।", "जाँचकर Submit करें। धुँधली हो तो दोबारा लें।"],
      "bgc-consent": ["पृष्ठभूमि जाँच की सहमति और जाँचों की सूची पढ़ें।", "सहमत होने पर ही Continue करें।"],
      "bgc-details": ["PAN के अनुसार अपना नाम भरें।", "PAN नंबर और PAN पर पिता का नाम भरें। पुराने इतिहास के सवालों के सच्चे जवाब दें।"],
      "bgc-address": ["स्थायी पता, शहर, राज्य और PIN कोड भरें।", "पता जाँचकर Continue करें।"],
      "eshram-uan": ["UAN ID के अनुसार नाम भरें।", "e-Shram UAN है तो Yes चुनकर भरें। नहीं है तो No चुनें; Amazon के निर्देश मानें या TL से पूछें। यहाँ PF UAN न भरें।", "विवरण जाँचने के बाद Submit करें।"],
      "account-review": ["पहले का Amazon डिलीवरी खाता मिलने पर ही Resolve Other Accounts दिखता है। TL से जाँच करवाएँ।"],
      "account-resolve": ["Agree and Remove सूची में दिखाए पुराने खाते हटाता/offboard करता है। कौन-सा खाता रखना है, TL से पुष्टि करने के बाद ही इसका उपयोग करें।"],
      "training-task": ["Training → Next खोलें। TL से LM Learning लॉगिन और सौंपा गया कोर्स लें; सभी जरूरी modules पूरे करें।"],
    },
  },
  or: {
    title: "କ’ଣ ପୂରଣ କରିବେ ଦେଖନ୍ତୁ", note: "ନମୁନା ସ୍କ୍ରିନ୍ · ବ୍ୟକ୍ତିଗତ ତଥ୍ୟ ହଟାଯାଇଛି। ନିଜ ତଥ୍ୟ ଦିଅନ୍ତୁ। ଆପଣଙ୍କ Amazon ସ୍କ୍ରିନ୍ କିଛି ଅଲଗା ହୋଇପାରେ।",
    enlarge: "ପୂରା ସ୍କ୍ରିନ୍ ଦେଖନ୍ତୁ", close: "ନମୁନା ବନ୍ଦ କରନ୍ତୁ", previous: "ପୂର୍ବ ସ୍କ୍ରିନ୍", next: "ପରବର୍ତ୍ତୀ ସ୍କ୍ରିନ୍", screen: "ନମୁନା ସ୍କ୍ରିନ୍",
    examples: {
      "flex-signin": ["DropX Oneରେ ଦେଖାଯାଇଥିବା ନିମନ୍ତ୍ରଣ ଇମେଲ୍ ଦିଅନ୍ତୁ।", "ନିମନ୍ତ୍ରଣ ଗ୍ରହଣ ବେଳେ ତିଆରି କରିଥିବା ନିଜ Amazon ପାସୱାର୍ଡ ଦିଅନ୍ତୁ।", "Sign in ଦବାନ୍ତୁ।"],
      privacy: ["Privacy Notice ଖୋଲି ପଢ଼ନ୍ତୁ।", "ପଢ଼ିବା ପରେ Continue କରନ୍ତୁ। କୌଣସି ଚୁକ୍ତି ମାନିବା ପୂର୍ବରୁ ପଢ଼ନ୍ତୁ।"],
      "about-name": ["ଡ୍ରାଇଭିଂ ଲାଇସେନ୍ସ ଅନୁସାରେ ପୂରା ନାମ ଦିଅନ୍ତୁ।", "ବର୍ତ୍ତମାନର ଠିକଣା ଓ ସହର ପୂରଣ କରନ୍ତୁ।"],
      "about-contact": ["ନିଜ ମୋବାଇଲ୍ ନମ୍ବର, ରାଜ୍ୟ ଓ PIN କୋଡ୍ ଦିଅନ୍ତୁ। ବ୍ୟକ୍ତିଗତ ପ୍ରଶ୍ନର ସଠିକ୍ ଉତ୍ତର ଦିଅନ୍ତୁ।", "ତଥ୍ୟ ଯାଞ୍ଚ କରି Continue ଦବାନ୍ତୁ।"],
      "licence-front": ["ନିଜ ଲାଇସେନ୍ସର ସମ୍ପୂର୍ଣ୍ଣ ଆଗପଟର ସ୍ପଷ୍ଟ ଫଟୋ ନିଅନ୍ତୁ।", "ପଢ଼ିହେଉଥିଲେ Continue; ଆବଶ୍ୟକ ହେଲେ Redo କରନ୍ତୁ।"],
      "licence-back": ["ସେହି ଲାଇସେନ୍ସର ସମ୍ପୂର୍ଣ୍ଣ ପଛପଟର ଫଟୋ ନିଅନ୍ତୁ।", "ସ୍ପଷ୍ଟ ଅଛି କି ଦେଖି Continue ଦବାନ୍ତୁ।"],
      "licence-review": ["ଦୁଇଟି ଫଟୋ, ଜନ୍ମତାରିଖ ଓ ଲାଇସେନ୍ସ ତଥ୍ୟ ଯାଞ୍ଚ କରନ୍ତୁ।", "ନିଜ ଦଲିଲ ସହ ମେଳ ହେଲେ ମାତ୍ର Submit କରନ୍ତୁ।"],
      "profile-photo": ["ପୂରା ମୁହଁ ସ୍ପଷ୍ଟ ଦେଖାଯାଉଥିବା ନିଜ ଫଟୋ ଦିଅନ୍ତୁ।", "ଯାଞ୍ଚ କରି Submit କରନ୍ତୁ। ଅସ୍ପଷ୍ଟ ହେଲେ ପୁଣି ନିଅନ୍ତୁ।"],
      "bgc-consent": ["ପୃଷ୍ଠଭୂମି ଯାଞ୍ଚର ସମ୍ମତି ଓ ଯାଞ୍ଚ ତାଲିକା ପଢ଼ନ୍ତୁ।", "ସହମତ ହେଲେ ମାତ୍ର Continue କରନ୍ତୁ।"],
      "bgc-details": ["PAN ଅନୁସାରେ ନାମ ଦିଅନ୍ତୁ।", "PAN ନମ୍ବର ଓ PANରେ ଥିବା ବାପାଙ୍କ ନାମ ଦିଅନ୍ତୁ। ପୂର୍ବ ଇତିହାସ ପ୍ରଶ୍ନର ସତ ଉତ୍ତର ଦିଅନ୍ତୁ।"],
      "bgc-address": ["ସ୍ଥାୟୀ ଠିକଣା, ସହର, ରାଜ୍ୟ ଓ PIN କୋଡ୍ ଦିଅନ୍ତୁ।", "ଠିକଣା ଯାଞ୍ଚ କରି Continue କରନ୍ତୁ।"],
      "eshram-uan": ["UAN ID ଅନୁସାରେ ନାମ ଦିଅନ୍ତୁ।", "e-Shram UAN ଥିଲେ Yes ବାଛି ଦିଅନ୍ତୁ। ନଥିଲେ No ବାଛନ୍ତୁ; Amazon ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ କିମ୍ବା TLଙ୍କୁ ପଚାରନ୍ତୁ। ଏଠାରେ PF UAN ଦିଅନ୍ତୁ ନାହିଁ।", "ତଥ୍ୟ ଯାଞ୍ଚ ପରେ Submit କରନ୍ତୁ।"],
      "account-review": ["ପୂର୍ବ Amazon ଡେଲିଭରି ଖାତା ମିଳିଲେ ମାତ୍ର Resolve Other Accounts ଦେଖାଯାଏ। TLଙ୍କୁ ଯାଞ୍ଚ କରିବାକୁ କୁହନ୍ତୁ।"],
      "account-resolve": ["Agree and Remove ତାଲିକାର ପୁରୁଣା ଖାତା ହଟାଏ/offboard କରେ। କେଉଁ ଖାତା ରଖିବେ TLଙ୍କ ସହ ନିଶ୍ଚିତ କରିବା ପରେ ହିଁ ବ୍ୟବହାର କରନ୍ତୁ।"],
      "training-task": ["Training → Next ଖୋଲନ୍ତୁ। LM Learning ଲଗଇନ୍ ଓ ଦିଆଯାଇଥିବା କୋର୍ସ ପାଇଁ TLଙ୍କୁ ପଚାରନ୍ତୁ; ସମସ୍ତ ଜରୁରୀ modules ଶେଷ କରନ୍ତୁ।"],
    },
  },
};
