import Link from 'next/link';
import {AppShell} from '@/components/app-shell';
import {requirePagePermission} from '@/lib/authorization';
import {requireCompanyId} from '@/lib/company-scope';
import {supabaseAdmin} from '@/lib/supabase-admin';
import {saveAdhocReason} from './actions';
export const dynamic='force-dynamic';
export default async function AdhocReasons(){
 const auth=await requirePagePermission('master_payment_heads','access'),company=requireCompanyId(auth),db=supabaseAdmin!;
 const [rules,roles,sources,states]=await Promise.all([db.from('fleet_adhoc_reason_rules').select('*').eq('company_id',company).order('sort_order'),db.from('user_roles').select('id,name,code').eq('company_id',company).order('name'),db.from('designations').select('code,name').eq('company_id',company).eq('is_active',true),db.from('fleet_vehicle_status_master').select('status_key,label').eq('company_id',company)]);
 if([rules,roles,sources,states].some(r=>r.error))throw new Error('Unable to load deployment rules.');
 return <AppShell active="Payment Heads" pageCode="master_payment_heads"><section className="panel"><div className="panel-head"><div><h1>Ad hoc van reasons</h1><p className="subtle">Vehicle eligibility, daily availability and approval routing.</p></div><Link href="/master/payment-heads" className="button secondary compact">Payment heads</Link></div><div className="panel-body">{rules.data?.map(rule=><details key={rule.reason_key} style={{borderBottom:'1px solid #e2e8f0',padding:'12px 0'}}><summary><strong>{rule.label}</strong> · {rule.source_code||'All stations'} · {rule.is_active?'Enabled':'Disabled'}</summary><form action={saveAdhocReason}><fieldset disabled={!auth.permissions.master_payment_heads?.canEdit} style={{border:0,padding:'12px 0'}}><input type="hidden" name="reason_key" value={rule.reason_key}/><div className="form-grid three"><label>Label<input className="field" name="label" defaultValue={rule.label} required maxLength={100}/></label><label>Vehicle source<select className="field" name="source_code" defaultValue={rule.source_code||''}><option value="">No vehicle selection</option><option value="OWN">Own</option>{sources.data?.map(s=><option key={s.code} value={s.code}>{s.name} ({s.code})</option>)}</select></label><label>Order<input className="field" type="number" name="sort_order" min={0} defaultValue={rule.sort_order}/></label>{['required_status','effect_status'].map(key=><label key={key}>{key==='required_status'?'Required current status':'Status recorded for request day'}<select className="field" name={key} defaultValue={rule[key]||''}><option value="">None</option>{states.data?.map(s=><option key={s.status_key} value={s.status_key}>{s.label}</option>)}</select></label>)}</div><p><label><input type="checkbox" name="is_active" defaultChecked={rule.is_active}/> Enabled</label> · <label><input type="checkbox" name="block_rent" defaultChecked={rule.block_rent}/> Exclude vehicle rent for the recorded day</label></p><p><label><input type="checkbox" name="special_route" defaultChecked={!!rule.approval_steps}/> Use this reason’s approval route</label> (Otherwise follows the payment head.)</p><div className="form-grid three">{['first_role','final_role','fallback_role'].map((key,i)=><label key={key}>{['First approval','Final approval','Final fallback'][i]}<select className="field" name={key} defaultValue={rule.approval_steps?.[i===0?0:1]?.candidates?.[i===2?1:0]?.role_id||''}><option value="">Select role</option>{roles.data?.map(r=><option key={r.id} value={r.id}>{r.name} ({r.code})</option>)}</select></label>)}</div><div className="form-actions"><button className="button" type="submit">Save reason</button></div></fieldset></form></details>)}</div></section></AppShell>;
}
