import type {CodException} from '@/lib/ops-pulse/cod-exceptions';
import type {CodHistoryRow} from '@/lib/ops-pulse/cod-proof-history';
import {formatDateTime} from '@/lib/ops-pulse/cod';
export function CodExceptionDetails({item}:{item:CodException}){
 const failed=['Email not found','Email check unavailable'].includes(item.email_check_status);
 return <div style={{whiteSpace:'normal'}}><p>{item.reason}</p><p>Updated by {item.updater_name} · {formatDateTime(item.updated_at)}</p>
 {item.kind==='No Cash'?<a className="button secondary" href={'/api/ops-pulse/cod/exceptions/proof?id='+encodeURIComponent(item.id)} target="_blank" rel="noreferrer">View ERP screenshot</a>:<><p><strong>Email subject:</strong> {item.email_subject}</p><p>From: {item.sender_email} · {formatDateTime(item.email_sent_at)}</p><p>Stakeholders: {item.stakeholder_emails.join(', ')}<br/>Client COD POCs: {item.client_poc_emails.join(', ')}<br/>CC: {item.email_cc.join(', ')}</p><span className={`status-pill ${failed?'bad':item.email_check_status==='Email confirmed'?'good':'warn'}`}>{item.email_check_status}</span><p style={{color:failed?'#b91c1c':undefined}}>{item.email_check_reason||'The recorded email is awaiting confirmation in the Control Tower mailbox.'}</p></>}
 </div>;
}
const labels:Record<string,string>={deposited_amount:'Deposited amount',deposit_date:'Deposit date',remittance_code:'Remittance code',reference_no:'Reference',submitter_name:'Submitted by',remarks:'Remarks',validation:'Slip validation',reason:'Reason',email_subject:'Email subject',email_check_status:'Email confirmation',email_check_reason:'Email check reason',kind:'Daily update',report_date:'Report date',sender_email:'Sender',stakeholder_emails:'Stakeholders',client_poc_emails:'Client COD POCs',email_sent_at:'Email sent at',email_cc:'CC',cod_period_from:'COD from',cod_period_to:'COD to'};
const value=(v:unknown)=>Array.isArray(v)?v.join(', '):v==null?'—':String(v);
export function CodHistory({rows,error}:{rows:CodHistoryRow[];error?:string}){
 return <details style={{margin:'12px 0',whiteSpace:'normal'}}><summary style={{cursor:'pointer'}}>Update & validation history ({rows.length})</summary>{error?<p role="alert">{error}</p>:!rows.length?<p>No recorded history.</p>:rows.map(row=><article key={row.id} style={{borderLeft:'3px solid #e2e8f0',padding:'4px 12px',margin:'12px 0'}}><strong>{row.event}</strong><p>{row.actor_name||'Recorded system event'} · {formatDateTime(row.created_at)}</p>{row.new_values.remittance_code?<p>Reference: {String(row.new_values.remittance_code)}</p>:null}{Object.entries(labels).filter(([key])=>key in row.new_values&&JSON.stringify(row.old_values?.[key])!==JSON.stringify(row.new_values[key])).map(([key,label])=><div key={key}><strong>{label}:</strong> {row.old_values?`${value(row.old_values[key])} → `:''}{value(row.new_values[key])}</div>)}{['attachments','deposit_slip_attachments','proof'].some(key=>JSON.stringify(row.old_values?.[key])!==JSON.stringify(row.new_values[key])&&row.new_values[key])?<p>Proof recorded or replaced.</p>:null}</article>)}</details>;
}
