import {hasPermission,type AuthorizationContext} from '@/lib/authorization';
import {digestDatabase} from '@/lib/portal-digest-delivery';
import {saveCodPendingSettings} from '@/app/settings/notifications/actions';
export async function CodNotificationSettings({companyId,auth}:{companyId:string;auth:AuthorizationContext}){
 const db=digestDatabase();const [controls,history]=await Promise.all([
 db.from('portal_notification_controls').select('event_key,state,config').eq('company_id',companyId).eq('portal','ops').in('event_key',['cod_pending_evening','cod_pending_morning']),
 db.from('portal_digest_deliveries').select('id,event_key,report_date,recipient_email,status,error').eq('company_id',companyId).eq('portal','ops').in('event_key',['cod_pending_evening','cod_pending_morning']).order('report_date',{ascending:false}).order('started_at',{ascending:false}).limit(50)]);
 const states=controls.data||[];const ready=!controls.error&&states.length===2;
 return <section className="panel" id="cod-pending" style={{padding:24,marginBottom:20}}><h2>Daily COD slips &amp; outstanding cash</h2><p><strong>8:30 PM IST:</strong> same-day deposit slips. <strong>9:00 AM IST:</strong> recheck the previous deposit day.</p><p>Each recipient receives only permitted COD stations. Both reminders use the last complete EDSP upload available by the report day’s 8:30 PM deadline, labelled with its D−1 data date. Cash pending more than two days is highlighted. Evening and morning messages share one thread per recipient per report month.</p>
 {!ready?<p role="alert">COD reminder schedule is not configured yet.</p>:<form action={saveCodPendingSettings}><label>COD email delivery<select className="field" name="state" defaultValue={states.every(s=>s.state==='enabled')?'enabled':states.every(s=>s.state==='disabled')?'disabled':'paused'} disabled={!hasPermission(auth,'ops_notification_settings','edit')}><option value="enabled">Enabled</option><option value="paused">Paused</option><option value="disabled">Disabled</option></select></label><p className="subtle">Times: 8:30 PM and 9:00 AM IST · Monthly subject: OpsPulse | COD report | Month Year</p><button className="button primary" disabled={!hasPermission(auth,'ops_notification_settings','edit')}>Save COD email settings</button></form>}
 <h3>Recent COD deliveries</h3>{history.error?<p role="alert">Delivery history unavailable.</p>:history.data?.length?<div className="table-wrap"><table><thead><tr><th>Deposit day</th><th>Reminder</th><th>Recipient</th><th>Status</th><th>Details</th></tr></thead><tbody>{history.data.map(r=><tr key={r.id}><td>{r.report_date}</td><td>{r.event_key.endsWith('morning')?'9:00 AM follow-up':'8:30 PM'}</td><td>{r.recipient_email}</td><td>{r.status}</td><td>{r.error||'—'}</td></tr>)}</tbody></table></div>:<p className="subtle">No scheduled COD emails sent yet.</p>}</section>;
}
