import Link from 'next/link';
import {ageingBands,type CodAgeingSnapshot} from '@/lib/ops-pulse/cod-ageing';
import {formatDate,formatDateTime} from '@/lib/ops-pulse/cod';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
export function CodAgeingReport({source,date,location,detail}:{source:CodAgeingSnapshot;date:string;location?:string;detail?:string}){
 const rows=source.stations.filter(s=>s.total>0),selected=rows.find(s=>s.stationCode===detail);
 const href='/api/ops-pulse/cod/pending/export?'+new URLSearchParams({date,type:'ageing',...(location?{location}:{})});
 return <section className="panel" id="outstanding-cash"><div className="panel-head"><div><h2>EDSP outstanding cash · {formatDate(source.dataDate)}</h2><p className="subtle">Upload day: {formatDate(source.uploadDate)} · Data as of {formatDate(source.dataDate)} (D−1). Both reminders use the last complete upload available by 8:30 PM on the upload day.</p>{source.importedAt?<p className="subtle">Imported: {formatDateTime(source.importedAt)} · {source.fileName}</p>:null}</div>{!source.error?<a className="button secondary" href={href}>Download ageing CSV</a>:null}</div>
 {source.error?<div className="panel-body" role="alert">{source.error}</div>:<><div className="panel-body"><strong style={{color:'#b91c1c'}}>{rows.filter(r=>r.overTwo>0).length} stations have cash pending more than 2 days · ₹{money(rows.reduce((n,r)=>n+r.overTwo,0))}</strong></div><div className="table-wrap"><table><thead><tr><th>Station / details</th>{ageingBands.map(b=><th key={b}>{b}</th>)}<th>Grand total</th></tr></thead><tbody>{rows.map(row=><tr key={row.stationCode}><td><Link href={'/cod/pending?'+new URLSearchParams({date,detail:row.stationCode,...(location?{location}:{})})+'#outstanding-details'}>{row.stationCode}</Link>{row.overTwo>0?<span className="status-pill warn" style={{marginLeft:8}}>&gt;2 days</span>:null}</td>{ageingBands.map(b=><td key={b} style={{color:b!=='2 DAYS'&&row.bands[b]>0?'#b91c1c':undefined,fontVariantNumeric:'tabular-nums'}}>{row.bands[b]?money(row.bands[b]):'—'}</td>)}<td><strong>{money(row.total)}</strong></td></tr>)}<tr style={{background:'#e5efd9',fontWeight:700}}><td>Grand total</td>{ageingBands.map(b=><td key={b}>{money(rows.reduce((n,r)=>n+r.bands[b],0))}</td>)}<td>{money(rows.reduce((n,r)=>n+r.total,0))}</td></tr></tbody></table></div>
 <div className="panel-body"><p className="subtle">Exactly 2 days is shown separately. 0–1 days (₹{money(source.stations.reduce((n,r)=>n+r.recent,0))}) is excluded from this table. Other / older preserves source bands, including year-labelled balances. Missing stations in a complete network file have no outstanding rows in that file. These are outstanding balances, not automatically deposit shortages.</p></div>
 {selected?<div className="panel-body" id="outstanding-details"><h3>{selected.stationCode} · Outstanding transaction details</h3><p>Source data as of {formatDate(source.dataDate)} · Original age bands are preserved.</p><a className="button secondary" href={href+'&detail='+encodeURIComponent(selected.stationCode)}>Download transaction CSV</a><div className="table-wrap" style={{maxHeight:480,overflow:'auto'}}><table><thead><tr><th>Tracking ID</th><th>Associate</th><th>Pending since</th><th>Source age band</th><th>Amount</th></tr></thead><tbody>{selected.lines.map((line,i)=><tr key={line.rowNumber+':'+i}><td>{line.trackingId||'—'}</td><td>{line.associate}</td><td>{formatDate(line.pendingDate)}</td><td>{line.bucket}</td><td>{money(line.amount)}</td></tr>)}</tbody></table></div></div>:null}</>}
 </section>;
}
