'use client';
import {useEffect,useState,useRef} from 'react';
import type {CpsPeoplePolicy} from '@/lib/ops-pulse/cps';
type Expense={id?:string;cost_label:string;mode:string;effective_from:string;updated_at?:string};
export function CpsAllocationSettings() {
 const dialog=useRef<HTMLDialogElement>(null);
 const [data,setData]=useState<{people:CpsPeoplePolicy[];expenses:Expense[];canEdit:boolean}|null>(null);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [editing,setEditing]=useState<(Record<string,unknown>&{kind:string})|null>(null);
 useEffect(()=>{const c=new AbortController();fetch('/api/ops-pulse/cps/settings',{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setError('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>c.abort()},[revision]);
 useEffect(()=>{if(editing)dialog.current?.showModal()},[editing]);
 async function save(form:HTMLFormElement){if(busy||!editing)return;setBusy(true);setError('');try{const r=await fetch('/api/ops-pulse/cps/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editing,...Object.fromEntries(new FormData(form))})});const d=await r.json();if(!r.ok)throw Error(d.error);setEditing(null);setRevision(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}}
 return <section className="panel"><div className="panel-head"><div><h2>Allocation &amp; recognition rules</h2><p>Company-wide rules with effective dates. HO roles stay excluded unless deliberately enabled. Individual People salaries are never displayed in CPS.</p></div></div>
 {error&&<p className="panel-body" role="alert">{error} <button onClick={()=>setRevision(n=>n+1)}>Reload</button></p>}
 {!data?<p className="panel-body">Loading rules…</p>:<>
 <details className="cps-drilldown" open><summary>People cost inclusion <span>Station staff · manager share · telecaller share</span></summary><div className="cps-table-wrap"><table><thead><tr><th>Role</th><th>Include from</th><th>Allocation</th><th>Cost group</th><th>Action</th></tr></thead><tbody>{data.people.map(p=><tr key={p.id||p.designation_code}><td>{p.designation_name}<small>{p.designation_code} · {p.effective_from}</small></td><td>{p.mode==='excluded'?'Excluded / HO':p.mode==='home'?'Assigned station':'Mapped stations only'}</td><td>{p.allocation==='equal'?'Equal share':'Delivered-volume share'}</td><td>{p.mode==='excluded'?'—':`${p.head} · ${p.label}`}</td><td>{data.canEdit&&<><button className="button" onClick={()=>setEditing({...p,kind:'people'})}>Edit</button> <button className="button" onClick={()=>setEditing({...p,id:undefined,kind:'people',effective_from:''})}>New revision</button></>}</td></tr>)}</tbody></table></div><p className="cps-footnote">Managed roles use their mapped operating stations. No all-company or HO-region fallback. A revision changes calculations from its effective date.</p></details>
 <details className="cps-drilldown"><summary>Monthly bills &amp; expense recognition</summary><div className="cps-table-wrap"><table><thead><tr><th>Cost label</th><th>Method</th><th>From</th><th>Action</th></tr></thead><tbody>{data.expenses.map(p=><tr key={p.id}><td>{p.cost_label}</td><td>{p.mode==='monthly'?'Spread over billing period':'Charge on expense date'}</td><td>{p.effective_from}</td><td>{data.canEdit&&<><button className="button" onClick={()=>setEditing({...p,kind:'expense'})}>Edit</button> <button className="button" onClick={()=>setEditing({...p,id:undefined,kind:'expense',effective_from:''})}>New revision</button></>}</td></tr>)}</tbody></table></div>{data.canEdit&&<button className="button" onClick={()=>setEditing({kind:'expense',cost_label:'',mode:'monthly',effective_from:''})}>Add expense rule</button>}<p className="cps-footnote">Match the expense label exactly. Unconfigured expenses retain their transaction date. Bill dates can be corrected from Other → Billing periods in the overview.</p></details>
 </>}
 {editing&&<dialog ref={dialog} className="panel cps-editor" aria-label="Edit cost rule" onCancel={e=>{e.preventDefault();if(!busy)setEditing(null)}}><div className="panel-head"><h2>{editing.id?'Edit rule':'Add effective revision'}</h2><button className="button" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div><form className="cps-input-form" onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}}>
 {editing.kind==='people'?<><p className="cps-form-note">{String(editing.designation_name)}</p><label>Include cost<select name="mode" defaultValue={String(editing.mode)}><option value="excluded">Excluded / HO reserve</option><option value="home">Assigned station only</option><option value="managed">Mapped operating stations</option></select></label><label>Head<select name="head" defaultValue={String(editing.head)}>{['UTR','DA','Van','Overhead'].map(h=><option key={h}>{h}</option>)}</select></label><label>Anonymous group label<input name="label" defaultValue={String(editing.label)} required minLength={3} maxLength={80}/></label><label>Allocation<select name="allocation" defaultValue={String(editing.allocation)}><option value="equal">Equal share</option><option value="delivery_share">Daily delivered-volume share</option></select></label></>:<><label>Exact cost label<input name="cost_label" defaultValue={String(editing.cost_label)} required minLength={3}/></label><label>Recognition<select name="mode" defaultValue={String(editing.mode)}><option value="monthly">Billing period / calendar month</option><option value="transaction">Expense date</option></select></label></>}
 <label>Effective from<input name="effective_from" type="date" required defaultValue={String(editing.effective_from)}/></label><button className="button primary" disabled={busy}>{busy?'Saving…':'Save rule'}</button>{error&&<p role="alert">{error}</p>}</form></dialog>}
 </section>
}
