'use client';
import {FleetFindingActions} from './fleet-finding-actions';
import {useEffect,useState} from 'react';
import {Download,ExternalLink,RefreshCw,X} from 'lucide-react';
import type {AuditReport} from '@/lib/fleet/audit-health';
export function FleetAuditReport({auditId,onClose}:{auditId:string;onClose:()=>void}) {
 const [report,setReport]=useState<AuditReport|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[downloading,setDownloading]=useState(false),[pdfError,setPdfError]=useState('');
 useEffect(()=>{const controller=new AbortController();setReport(previous=>previous?.id===auditId?previous:null);setError('');fetch(`/api/fleet/audit-report?id=${encodeURIComponent(auditId)}`,{signal:controller.signal,cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);setReport(body);}).catch(e=>{if(!controller.signal.aborted)setError(e.message||'Report unavailable. Retry.');});return()=>controller.abort();},[auditId,retry]);
 async function download(){setDownloading(true);setPdfError('');try{const r=await fetch(`/api/fleet/audit-report?id=${encodeURIComponent(auditId)}&format=pdf`,{cache:'no-store'});if(!r.ok){const result=await r.json();throw new Error(result.error);}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`Audit-${report?.vehicleNo}-${report?.date}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setPdfError(e instanceof Error?e.message:'PDF unavailable. Retry.');}finally{setDownloading(false);}}
 return <div className="fc-modal-backdrop fc-report-backdrop"><section role="dialog" aria-modal="true" aria-label="Vehicle health report" className="fc-health-report">
 <header className="fc-health-header"><div><small>DROPX / VEHICLE ASSURANCE</small><h2>{report?.vehicleNo||'Audit report'}</h2><p>{report?`${report.station} · ${report.model} · ${report.mode}`:'Loading saved audit…'}</p></div><div><button className="fc-button secondary" disabled={!report||downloading} onClick={download} type="button"><Download size={16}/>{downloading?'Preparing photos…':'Download PDF'}</button><button aria-label="Close audit report" onClick={onClose} type="button"><X size={21}/></button></div></header>
 <div className="fc-health-body">{error?<div role="alert" className="fc-inline-message error">{error}<button type="button" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={14}/> Retry</button></div>:null}{pdfError?<div role="alert" className="fc-inline-message error">{pdfError}</div>:null}
 {report?<><div className="fc-health-hero"><div className={`fc-health-ring ${report.health.critical?'critical':''}`} style={{'--health':`${report.score??0}%`} as React.CSSProperties}><strong>{report.score===null?'—':`${report.score}%`}</strong></div><div><small>{report.scoreBasis}</small><h3>{report.completedAt?report.status==='failed'?'Completed · Needs attention':'Completed · Passed':'Audit in progress'}</h3><p>{report.date} · {report.inspector}</p><p>{report.responses.length} checks · {report.evidence.length} attachments · {report.findings.length} findings</p>{report.health.critical?<b className="fc-critical">Critical finding · Immediate action required</b>:null}</div></div>
 <FleetFindingActions report={report} onSaved={()=>setRetry(n=>n+1)}/>
 {report.summary?<p className="fc-health-summary">{report.summary}</p>:null}
 <nav className="fc-report-jump" aria-label="Report sections"><a href="#fleet-action-tracker">Action points & closure</a><a href="#fleet-health-areas">Health</a><a href="#fleet-health-gaps">Findings & earlier gaps</a><a href="#fleet-health-checks">Checklist</a><a href="#fleet-health-photos">Photos & evidence</a></nav>
 <section id="fleet-health-areas"><h3>Health by area</h3><div className="fc-health-areas">{report.health.areas.map(a=><article key={a.category}><div><b>{a.category}</b><strong>{a.score===null?'Not assessed':`${a.score}%`}</strong></div><progress max="100" value={a.score??0}/><small>{a.share}% of scored weight · {a.assessed}/{a.total} assessed</small></article>)}</div><details className="fc-report-disclosure"><summary>How this score works</summary><p>{report.scoreBasis==='Weighted health'?'Each assessed answer earns 0–100 health points multiplied by its configured checklist weight. The total is divided by the assessed weight.':'This earlier audit keeps its original pass/fail score. Area scores use equal weights; no historical score has been changed.'} Unassessed and zero-weight checks are excluded. Critical findings remain flagged regardless of score.</p><p>{report.health.excluded} checks excluded. Masters → Vehicle Audit controls weights and answer points for future submissions.</p></details></section>
 <section id="fleet-health-gaps"><h3>Findings & follow-up</h3>{!report.findings.length?<p className="fc-health-clear">No findings recorded in this inspection.</p>:<div className="fc-health-findings">{report.findings.map(f=><article key={f.id}><div><b>{f.category}</b><span className={`fc-severity ${f.severity}`}>{f.severity}</span></div><p>{f.finding}</p><strong>{f.action||'Review and rectify'}</strong><small>Due {f.due||'not set'} · {f.status}{f.resolution?` · ${f.resolution}`:''}</small></article>)}</div>}
 <details className="fc-report-disclosure" open={report.continuity.some(c=>['Repeated','Recurred'].includes(c.comparison))}><summary>Earlier gaps · {report.continuity.filter(c=>c.comparison!=='Closed').length} need review</summary>{report.continuity.length?report.continuity.map(c=><article className="fc-continuity" key={c.id}><b>{c.comparison}</b><p>{c.finding}</p><small>{c.date} · {c.previousCount} previous occurrence(s) · Due {c.due||'not set'}</small>{c.action?<p>{c.action}</p>:null}</article>):<p>No earlier recorded findings for this vehicle.</p>}<p>Passing an item does not close its previous action. Use Action points & closure above to record repairs and upload closure proof.</p></details>
 <details className="fc-report-disclosure"><summary>Previous audits · {report.previous.length}</summary>{report.previous.map(p=><p key={p.id}>{p.date} · {p.score??'—'}% · {p.status==='failed'?'Needs attention':'Passed'}</p>)}{!report.previous.length?<p>This is the first completed audit recorded for this vehicle.</p>:null}</details></section>
 <section id="fleet-health-checks"><h3>Recorded checklist</h3>{[...new Set(report.responses.map(r=>r.category))].map(category=><details className="fc-report-disclosure" key={category}><summary>{category} · {report.responses.filter(r=>r.category===category).length} checks</summary>{report.responses.filter(r=>r.category===category).map(r=><article className="fc-report-answer" key={r.itemId}><b>{r.label}</b><strong className={r.passed===false?'attention':''}>{r.answer||'Not answered'}</strong>{r.comments?<p>{r.comments}</p>:null}{r.action?<p>Action: {r.action}{r.days?` · within ${r.days} days`:''}</p>:null}<small>{r.score===null?'Not scored':`${r.score}/100 points`} · Weight {r.weight}</small></article>)}</details>)}</section>
 <section id="fleet-health-photos"><h3>Photos & evidence <small>{report.evidence.length}</small></h3><div className="fc-health-photos">{report.evidence.map((e,i)=><a key={e.id} href={e.url} target="_blank" rel="noreferrer">{e.type==='photo'?<img src={e.url} loading="lazy" alt={e.caption||`Audit photo ${i+1}`}/>:<div className="fc-evidence-link"><ExternalLink size={28}/>{e.type}</div>}<span>{i+1}. {e.caption||'Audit evidence'}</span></a>)}</div>{!report.evidence.length?<p>No attachments recorded.</p>:null}</section>
 <footer>Saved {report.completedAt?new Date(report.completedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'as a draft'} · Action status as of {new Date(report.generatedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</footer>
 </>:!error?<p role="status">Loading saved answers, photos and previous findings…</p>:null}</div></section></div>;
}
