"use client";
import type { FleetControlVehicle } from "@/lib/fleet-control";
import { useEffect, useState, type FormEvent } from 'react';

export function FleetArchiveVehicle({vehicleNo,onArchived}:{vehicleNo:string;onArchived:()=>void}) {
  const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function archive(e:FormEvent){
    e.preventDefault();setBusy(true);setError('');
    try { const r=await fetch('/api/fleet/vehicles',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicle_no:vehicleNo,reason})});const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to archive.');onArchived(); }
    catch(e){setError(e instanceof Error?e.message:'Unable to archive.');}finally{setBusy(false);}
  }
  return <details className="fc-manage-card" style={{padding:16}}><summary>Delete / archive vehicle</summary><p>Remove {vehicleNo} from current operations. Its documents, reports and change history are retained. You can restore it from Archived vehicles.</p><form onSubmit={archive} className="fc-add-form"><label className="full"><span>Reason</span><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} required rows={2} disabled={busy}/></label>{error&&<p className="full" role="alert">{error}</p>}<button type="submit" className="fc-button secondary" disabled={busy}>{busy?'Archiving…':'Confirm archive'}</button></form></details>;
}

type Archived={vehicle:FleetControlVehicle;id:string;vehicle_no:string;model:string;station_code:string;status_comment:string;status_updated_at:string};
type Change={id:string;created_at:string;actor_label:string;before_values:Record<string,unknown>;after_values:Record<string,unknown>};
export function FleetVehicleChangeHistory({vehicleNo}:{vehicleNo:string}){
 const [open,setOpen]=useState(false),[rows,setRows]=useState<Change[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!open)return;const c=new AbortController();setLoading(true);setError('');fetch('/api/fleet/vehicles?'+new URLSearchParams({history:vehicleNo,page:String(page)}),{signal:c.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.rows);setTotal(j.total);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[open,vehicleNo,page]);
 const value=(v:unknown)=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
 return <details className="fc-manage-card" style={{padding:12}} onToggle={e=>setOpen(e.currentTarget.open)}><summary>Change history</summary>{open&&<div>{error&&<p role="alert">{error}</p>}{loading?<p>Loading history…</p>:rows.map(row=><details key={row.id} style={{padding:'10px 0'}}><summary>{new Date(row.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · {row.actor_label}</summary><div className="fc-table-scroll"><table><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{Array.from(new Set([...Object.keys(row.before_values),...Object.keys(row.after_values)])).map(key=><tr key={key}><td>{key.replaceAll('_',' ')}</td><td>{value(row.before_values[key])}</td><td>{value(row.after_values[key])}</td></tr>)}</tbody></table></div></details>)}{!loading&&!rows.length&&!error&&<p>No recorded changes. Older activity may predate System Logs.</p>}<div className="fc-log-pagination"><button type="button" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{total} changes</span><button type="button" disabled={loading||page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</details>;
}
export function FleetArchivedVehicles({onRestored,onLifecycle}:{onRestored:()=>void;onLifecycle:(vehicle:FleetControlVehicle)=>void}) {
 const [open,setOpen]=useState(false),[search,setSearch]=useState(''),[page,setPage]=useState(1),[version,setVersion]=useState(0),[rows,setRows]=useState<Archived[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState(''),[restoring,setRestoring]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!open)return;const c=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{fetch('/api/fleet/vehicles?'+new URLSearchParams({page:String(page),search}),{signal:c.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.vehicles);setTotal(j.total);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});},250);return()=>{clearTimeout(timer);c.abort();};},[open,search,page,version]);
 async function restore(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/fleet/vehicles',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({vehicle_no:restoring,reason})});const j=await r.json();if(!r.ok)throw Error(j.error);setRestoring('');setReason('');setVersion(v=>v+1);onRestored();}catch(e){setError(e instanceof Error?e.message:'Unable to restore.');}finally{setBusy(false);}}
 return <details className="fc-panel" onToggle={e=>setOpen(e.currentTarget.open)}><summary style={{padding:16,cursor:'pointer'}}>Archived vehicles & history</summary>{open&&<div style={{padding:16}}><p>Removed from current operations. Restoration keeps the vehicle inactive and not deployed until you review it.</p><label>Search vehicle, model or station<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label>{error&&<p role="alert">{error}</p>}{loading?<p>Loading…</p>:rows.map(v=><article key={v.id} className="fc-manage-card" style={{padding:12,marginTop:8}}><strong>{v.vehicle_no}</strong><small className="fc-cell-note">{v.model} · {v.station_code} · Archived {new Date(v.status_updated_at).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</small><p>{v.status_comment}</p><div className="fc-toolbar-actions"><button type="button" className="fc-button secondary" onClick={()=>onLifecycle(v.vehicle)}>Vehicle lifecycle</button><FleetVehicleChangeHistory vehicleNo={v.vehicle_no}/><button type="button" className="fc-button secondary" onClick={()=>{setRestoring(v.vehicle_no);setReason('');}}>Restore</button></div>{restoring===v.vehicle_no&&<form onSubmit={restore} className="fc-add-form"><label className="full">Restore reason<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={5} maxLength={500} rows={2} required/></label><button type="submit" disabled={busy} className="fc-button primary">{busy?'Restoring…':'Restore as inactive'}</button><button type="button" disabled={busy} className="fc-button secondary" onClick={()=>setRestoring('')}>Cancel</button></form>}</article>)}{!loading&&!rows.length&&!error&&<p>No archived vehicles.</p>}<div className="fc-log-pagination"><button type="button" disabled={loading||page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{total} vehicles · Page {page}</span><button type="button" disabled={loading||page*20>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}</details>;
}
