"use client";
import { useState } from 'react';
import { ChevronDown, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import type { FleetVehicleStatusDefinition as Status, FleetVehicleStatusReason as Reason } from '@/lib/fleet-control';
export function FleetStatusMaster({statuses,canEdit,onEdit,onRemove,onAddReason,onEditReason,onRemoveReason}:{statuses:Status[];canEdit:boolean;onEdit:(s:Status|null)=>void;onRemove:(s:Status)=>void;onAddReason:(s:Status)=>void;onEditReason:(s:Status,r:Reason)=>void;onRemoveReason:(r:Reason)=>void}) {
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [expanded,setExpanded]=useState<string|null>(null);
 const active=statuses.filter(s=>s.isActive);const needle=query.trim().toLowerCase();
 const visible=active.filter(s=>(filter==='all'||(filter==='operational'?s.isOperational:filter==='closed'?s.isTerminal:!s.isOperational&&!s.isTerminal))&&`${s.label} ${s.helper} ${s.reasons.filter(r=>r.isActive).map(r=>r.label).join(' ')}`.toLowerCase().includes(needle));
 return <article className="fc-panel fc-compact-master"><div className="fc-panel-head"><div><span className="fc-eyebrow">Vehicle statuses</span><h2>Availability & reasons</h2><p>{active.length} statuses · expand a row to manage reasons</p></div>{canEdit&&<button type="button" onClick={()=>onEdit(null)}>Add status <Plus size={15}/></button>}</div><div className="fc-master-toolbar"><label className="fc-master-search"><Search size={16}/><input aria-label="Search statuses and reasons" placeholder="Search status or reason" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Status category" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All statuses</option><option value="operational">Operational</option><option value="unavailable">Non-operational</option><option value="closed">Closed lifecycle</option></select></div><div className="fc-compact-status-list">{visible.map(s=>{const reasons=s.reasons.filter(r=>r.isActive);const open=expanded===s.id||Boolean(needle);return <section key={s.id}><div className="fc-compact-status-row"><button className="fc-status-expand" aria-expanded={open} aria-controls={`reasons-${s.id}`} onClick={()=>setExpanded(expanded===s.id?null:s.id)} type="button"><ChevronDown size={16} style={{transform:open?'rotate(180deg)':undefined}}/><span className={`fc-status ${s.tone}`}><i/>{s.label}</span><span className="fc-status-description"><strong>{s.helper||s.label}</strong><small>{s.isOperational?'Operational':s.isTerminal?'Closed lifecycle':'Non-operational'} · {reasons.length} reasons{s.requiresExpectedDate?' · Return date required':''}{s.requiresReason?' · Reason required':''}</small></span></button>{canEdit&&<div className="fc-master-actions"><button type="button" aria-label={`Edit ${s.label}`} onClick={()=>onEdit(s)}><Pencil size={15}/></button><button type="button" className="danger" disabled={s.key==='active'} aria-label={`Remove ${s.label}`} onClick={()=>onRemove(s)}><Trash2 size={15}/></button></div>}</div>{open&&<div className="fc-compact-reasons" id={`reasons-${s.id}`}><div className="fc-reason-master-head"><b>Reasons for {s.label}</b>{canEdit&&!s.isOperational&&<button type="button" onClick={()=>onAddReason(s)}><Plus size={14}/>Add reason</button>}</div>{reasons.map(r=><div className="fc-compact-reason" key={r.id}><div><strong>{r.label}</strong><small>{r.helper}</small></div>{canEdit&&<div className="fc-master-actions"><button type="button" aria-label={`Edit ${r.label}`} onClick={()=>onEditReason(s,r)}><Pencil size={14}/></button><button type="button" className="danger" aria-label={`Remove ${r.label}`} onClick={()=>onRemoveReason(r)}><Trash2 size={14}/></button></div>}</div>)}{!reasons.length&&<p>{s.isOperational?'No reason needed when a vehicle is operational.':'No reasons configured yet.'}</p>}</div>}</section>})}{!visible.length&&<p className="fc-master-no-results">No matching statuses.</p>}</div></article>;
}
