'use client';
import { useState } from 'react';
import { AlertTriangle, CheckCircle2, X } from 'lucide-react';
import { fleetAttention, type AttentionItem } from '@/lib/fleet/attention';
import type { FleetControlData } from '@/lib/fleet-control';
import { FleetExportButtons } from '@/components/fleet-export-buttons';
export function FleetAttentionWorkspace({data,onNavigate,onChanged}:{data:FleetControlData;onNavigate:(item:AttentionItem)=>void;onChanged:()=>void}){
 const [category,setCategory]=useState('');const [station,setStation]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('open');const [editing,setEditing]=useState<AttentionItem|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const all=fleetAttention(data);const rows=all.filter(r=>(status==='resolved'?r.resolved:!r.resolved)&&(!category||r.category===category)&&(!station||r.station===station)&&`${r.title} ${r.vehicle} ${r.station}`.toLowerCase().includes(query.toLowerCase()));
 return <section><div className="fc-section-head"><div><span className="fc-eyebrow">Daily action list</span><h1>Need Attention</h1><p>Prioritise issues, finish follow-ups and keep every vehicle ready.</p></div><FleetExportButtons image compact report={{title:'Fleet · Need Attention',subtitle:`As at ${data.today}`,fileName:`fleet-attention-${data.today}`,headers:['Priority','Station','Vehicle','Category','Finding','Action','Due'],rows:rows.map(r=>[r.priority===0?'Critical':r.priority===1?'High':'Routine',r.station,r.vehicle,r.category,r.title,r.detail,r.due])}}/></div>
 <div className="fc-attention-kpis"><article><small>Open actions</small><strong>{all.filter(r=>!r.resolved).length}</strong></article><article className="urgent"><small>Critical</small><strong>{all.filter(r=>!r.resolved&&r.priority===0).length}</strong></article><article><small>Overdue</small><strong>{all.filter(r=>!r.resolved&&r.due&&r.due<data.today).length}</strong></article><article><small>Due today</small><strong>{all.filter(r=>!r.resolved&&r.due===data.today).length}</strong></article></div>
 <div className="fc-attention-filters"><label>Search<input placeholder="Vehicle or issue" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(all.map(r=>r.category))].map(c=><option key={c}>{c}</option>)}</select></label><label>Station<select value={station} onChange={e=>setStation(e.target.value)}><option value="">All stations</option>{[...new Set(all.map(r=>r.station))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">Open</option><option value="resolved">Resolved findings</option></select></label></div>
 <div className="fc-attention-list">{rows.map(r=><article key={r.id} className={r.priority===0?'critical':''}><div className="fc-attention-icon">{r.resolved?<CheckCircle2/>:<AlertTriangle/>}</div><div><small>{r.station} · {r.vehicle} · {r.category}</small><h3>{r.title}</h3><p>{r.detail}</p><span className={r.due&&r.due<data.today?'fc-overdue':''}>{r.due?`${r.due<data.today?'Overdue':r.due===data.today?'Due today':'Due'} · ${r.due}`:'Date needs review'}</span></div><button className="fc-button secondary" type="button" onClick={()=>{if(r.findingId){setError('');setEditing(r);}else onNavigate(r);}}>{r.findingId?'Review finding':r.auditId?'Open audit':'Open'}</button></article>)}{!rows.length&&<div className="fc-empty"><CheckCircle2 size={36}/><h3>No matching actions</h3><p>Change filters to see other priorities.</p></div>}</div>
 {editing&&<div className="fc-modal-backdrop"><section className="fc-modal"><button className="fc-modal-close" aria-label="Close finding" onClick={()=>setEditing(null)} type="button"><X/></button><h2>{editing.vehicle} · Follow-up</h2><p>{editing.title}</p><p>{editing.detail}</p><p>Due: {editing.due||'Not set'}</p>{error&&<p role="alert">{error}</p>}<form className="fc-add-form" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const form=new FormData(e.currentTarget);const res=await fetch('/api/fleet-control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'finding.update',findingId:editing.findingId,...Object.fromEntries(form)})});const result=await res.json();if(!res.ok)throw new Error(result.error);setEditing(null);onChanged();}catch(e){setError(e instanceof Error?e.message:'Update failed.');}finally{setBusy(false);}}}><label className="full">Status<select name="status" defaultValue={data.findings.find(f=>f.id===editing.findingId)?.status||'open'}><option value="open">Open</option><option value="in_progress">Work in progress</option><option value="resolved">Resolved</option></select></label><label className="full">Update / work completed<textarea required name="resolutionNote" rows={3} defaultValue={data.findings.find(f=>f.id===editing.findingId)?.resolutionNote||''}/></label><button disabled={busy||!data.capabilities.canManageFleet} className="fc-button primary" type="submit">{busy?'Saving…':'Save update'}</button></form></section></div>}
 </section>;
}
