'use client';
import {useMemo,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ExternalLink,MapPin,Route} from 'lucide-react';
import {normalizeGpsPolicy,gpsPolicyLabel} from "@/lib/fleet/gps-policy";
import type {MovementEvent,MovementProgressPoint,WheelseyeMovementSummary} from '@/lib/wheelseye-history';
import {dayDuration,dayHours,dayTime} from '@/lib/fleet/day-tracking';
import {journeyOverview,locationLink,sampleProgress,traceTime} from '@/lib/fleet/journey-progress';
import {RouteMap} from './fleet-dashboard';
import {FleetExportButtons} from './fleet-export-buttons';
export type DayJourney={locationCheck?:import("@/lib/fleet/journey-endpoints").JourneyLocationCheck|null;points:Array<{lat:number;lng:number}>;routeSegments:Array<Array<{lat:number;lng:number}>>;timeline:MovementEvent[];summary:WheelseyeMovementSummary;progress?:MovementProgressPoint[]};
const number=(v:number|null|undefined,digits=2)=>v==null?'—':v.toLocaleString('en-IN',{maximumFractionDigits:digits});
const names={moving:'Moving',idle:'Idling · engine on',stopped:'Parked · engine off',stop_unknown:'Stopped · ignition unknown',gap:'GPS gap',start:'First recorded point'};
function Place({lat,lng,label}:{lat:number;lng:number;label?:string}){return <a className="fc-journey-location" href={locationLink(lat,lng)} target="_blank" rel="noopener noreferrer" aria-label={`${label||'Location'}: ${lat.toFixed(5)}, ${lng.toFixed(5)}. Open in maps`}><MapPin size={13}/>{label||`${lat.toFixed(5)}, ${lng.toFixed(5)}`}<ExternalLink size={12}/></a>;}
export function FleetJourneyDetail({journey,vehicle,date,model,station}:{journey:DayJourney;vehicle:string;date:string;model?:string;station?:string}){
 const points=journey.progress??[];
 const [selected,setSelected]=useState<number|null>(null),[nearby,setNearby]=useState<number[]>([]),[view,setView]=useState('events'),[interval,setInterval]=useState(5),[page,setPage]=useState(1),[onlyAfter,setOnlyAfter]=useState(false),[mapMessage,setMapMessage]=useState('');
 const mapRef=useRef<HTMLDivElement|null>(null);
 const gpsPolicy=normalizeGpsPolicy(journey.summary.gpsPolicy);
 const overview=useMemo(()=>journeyOverview(journey.timeline,points,normalizeGpsPolicy(journey.summary.gpsPolicy)),[journey]);
 const routePoints=useMemo(()=>journey.routeSegments.flat(),[journey]);
 const sampled=useMemo(()=>sampleProgress(points,interval).filter(p=>!onlyAfter||p.afterHours&&(p.speed??0)>0),[points,interval,onlyAfter]);
 const current=selected==null?null:points[selected];
 const hasMovement=points.some(p=>(p.speed??0)>0);
 const first=points.find(p=>(p.speed??0)>0)??points[0],last=points.findLast(p=>(p.speed??0)>0)??points.at(-1);
 const select=(index:number,scroll=false)=>{setSelected(Math.max(0,Math.min(points.length-1,index)));setMapMessage('');if(scroll)mapRef.current?.scrollIntoView({behavior:'smooth',block:'center'});};
 const locateEvent=(e:MovementEvent)=>{const index=points.findIndex(p=>p.at>=e.to);if(index>=0){setNearby([]);select(index,true);}};
 const exportTable={title:`${vehicle} · Journey progress`,subtitle:`${model || "Model not recorded"} · ${station || "Station not mapped"} · ${date} · IST · GPS-derived distance; unknown gaps excluded. Filters apply.`,fileName:`fleet-journey-${vehicle}-${date}`,headers:['Recorded time IST','State','Added km','Total so far km','Speed km/h','GPS gap before','After hours','Latitude','Longitude','Map link'],rows:sampled.map(p=>[traceTime(p.at),names[p.kind],p.addedKm,p.cumulativeKm,p.speed,p.gapBefore,p.afterHours,p.lat,p.lng,locationLink(p.lat,p.lng)])};
 return <section className="fc-journey" aria-label="Journey explorer">
  <div className="fc-day-heading"><h3><Route size={17}/> Explore this journey</h3><span className="fc-journey-chip">{date} · IST</span></div>
  <div className="fc-journey-summary">
   <article><small>Recorded distance</small><strong>{number(points.length?points.at(-1)?.cumulativeKm:null)} <em>km</em></strong><span>{journey.summary.distanceReliable?'From accepted GPS movement':'Incomplete · GPS gaps / review'}</span></article>
   <article><small>Moving time</small><strong>{dayDuration(points.length?journey.summary.movingMinutes:null)}</strong><span>Avg moving {number(overview.averageMovingSpeed,1)} km/h</span></article>
   <article><small>Stops ≥ {gpsPolicy.minimumStopMinutes} min</small><strong>{points.length?overview.stops:"—"}</strong><span>Longest {dayDuration(overview.longest?.minutes??null)}</span></article>
   <article className={overview.afterHoursPoints?'fc-journey-warning':''}><small>After-hours movement</small><strong>{number(points.length?overview.afterHoursKm:null)} <em>km</em></strong><span>{!points.length?'No GPS history':overview.afterHoursPoints?`Review · ${gpsPolicyLabel(gpsPolicy)}`:'None in recorded points'}</span></article>
  </div>
  {first&&last&&<div className="fc-journey-endpoints"><span><b>{hasMovement?'First movement':'First record'} {dayTime(first.at)}</b><Place lat={first.lat} lng={first.lng} label="Start location"/></span><ArrowRight size={16}/><span><b>{hasMovement?'Last movement':'Last record'} {dayTime(last.at)}</b><Place lat={last.lat} lng={last.lng} label="Last location"/></span><span>Top speed <b>{number(journey.summary.maxSpeed)} km/h</b></span></div>}
  <div ref={mapRef} className="fc-journey-map-wrap">
   <div className="fc-day-map"><RouteMap currentPoint={current} points={routePoints.length?routePoints:journey.points} segments={journey.routeSegments} tracePoints={points} onTraceSelect={indices=>{setNearby(indices);if(indices.length)select(indices[0]);else setMapMessage('Tap closer to the recorded route or use the time slider.');}}/></div>
   <div className="fc-journey-map-card" aria-live="polite">{current?<><div><strong>{traceTime(current.at)}</strong><span>{names[current.kind]}{current.afterHours&&(current.speed??0)>0?' · After hours':''}</span></div><div><b>{number(current.cumulativeKm)} km so far</b><span>{number(current.speed)} km/h</span><Place lat={current.lat} lng={current.lng}/></div>{nearby.length>1&&<label>Recorded points near this spot<select value={selected??''} onChange={e=>select(Number(e.target.value))}>{nearby.map(i=><option key={i} value={i}>{traceTime(points[i].at)} · {number(points[i].cumulativeKm)} km</option>)}</select></label>}{current.gapBefore&&<small>GPS gap before this point · unrecorded travel is excluded.</small>}</>:<span><MapPin size={15}/> Tap the route to see time, speed and kilometres at that point.</span>}{mapMessage&&<small>{mapMessage}</small>}</div>
  </div>
  {points.length>0&&<div className="fc-journey-scrubber"><button type="button" aria-label="Previous GPS point" disabled={selected===0} onClick={()=>{setNearby([]);select((selected??1)-1);}}><ArrowLeft size={17}/></button><label>Trace the day <span>{current?`${traceTime(current.at)} · point ${selected!+1} of ${points.length}`:`${points.length} recorded GPS points`}</span><input aria-label="Journey time slider" aria-valuetext={current?`${traceTime(current.at)}, ${number(current.cumulativeKm)} kilometres`:traceTime(points[0].at)} type="range" min={0} max={points.length-1} value={selected??0} onChange={e=>{setNearby([]);select(Number(e.target.value));}}/></label><button type="button" aria-label="Next GPS point" disabled={selected===points.length-1} onClick={()=>{setNearby([]);select((selected??-1)+1);}}><ArrowRight size={17}/></button></div>}
  <p className="fc-day-footnote">{overview.gapCount?`${overview.gapCount} GPS gap periods · totals include recorded travel only. `:''}Distances use the same accepted moving GPS fixes as the daily report. After-hours km excludes legs crossing {gpsPolicyLabel(gpsPolicy)} boundaries. Stops do not prove delivery; compare locations with the planned route.</p>
  <div className="fc-day-heading"><div className="fc-journey-tabs" aria-label="Journey detail view"><button type="button" aria-pressed={view==='events'} onClick={()=>{setView('events');setPage(1);}}>Movement & stops</button><button type="button" aria-pressed={view==='points'} onClick={()=>{setView('points');setPage(1);}}>GPS point details</button></div><FleetExportButtons report={view==='points'?exportTable:{title:`${vehicle} · Movement & stops`,subtitle:`${model || "Model not recorded"} · ${station || "Station not mapped"} · ${date} · IST · GPS-derived distances`,fileName:`fleet-route-${vehicle}-${date}`,headers:['Event','From IST','To IST','Hours','This leg km','Total so far km','Incomplete distance','Start map','End map'],rows:journey.timeline.map(e=>[names[e.kind],traceTime(e.from),traceTime(e.to),dayHours(e.minutes),e.kind==='gap'?null:e.distanceKm,e.cumulativeKm,e.distanceIncomplete,locationLink(e.lat,e.lng),locationLink(e.endLat,e.endLng)])}}/></div>
  {view==='events'?<><div className="fc-journey-row-head"><span>Time / movement</span><span>Duration</span><span>This leg</span><span>Total so far</span><span>Location</span></div><ol className="fc-journey-events">{journey.timeline.slice((page-1)*80,page*80).map(e=><li key={`${e.from}-${e.kind}`} className={e.kind}><button type="button" title="Highlight this period’s end point on the map" onClick={()=>locateEvent(e)}><strong>{names[e.kind]}</strong><small>{traceTime(e.from)} – {traceTime(e.to)}</small></button><span>{dayDuration(e.minutes)}</span><span>{e.kind==='gap'?'—':`${number(e.distanceKm,3)} km`}</span><b>{number(e.cumulativeKm)} km</b><Place lat={e.endLat} lng={e.endLng} label={e.kind==='moving'?'End point':'View location'}/></li>)}</ol>{!journey.timeline.length&&<p>No sufficient GPS history to build a timeline.</p>}</>:<><div className="fc-journey-point-filters"><label>Show readings<select disabled={onlyAfter} value={interval} onChange={e=>{setInterval(Number(e.target.value));setPage(1);}}><option value={5}>Every 5 minutes</option><option value={15}>Every 15 minutes</option><option value={0}>Every GPS point</option></select></label><label className="fc-journey-check"><input type="checkbox" checked={onlyAfter} onChange={e=>{setOnlyAfter(e.target.checked);if(e.target.checked)setInterval(0);setPage(1);}}/>After-hours moving points</label><small>Real sample times · added km covers each selected interval.</small></div><div className="fc-journey-row-head"><span>Recorded time / state</span><span>Speed</span><span>Added km</span><span>Total so far</span><span>Location</span></div><ol className="fc-journey-events">{sampled.slice((page-1)*80,page*80).map(p=><li key={p.at} className={p.gapBefore?'gap':p.kind}><button type="button" onClick={()=>{setNearby([]);select(points.findIndex(point=>point.at===p.at),true);}}><strong>{traceTime(p.at)}</strong><small>{p.gapBefore?'Includes GPS gap':names[p.kind]}{p.afterHours&&(p.speed??0)>0?' · After hours':''}</small></button><span>{number(p.speed)} km/h</span><span>{p.addedKm==null?'—':`${number(p.addedKm,3)} km`}</span><b>{number(p.cumulativeKm)} km</b><Place lat={p.lat} lng={p.lng}/></li>)}</ol>{!sampled.length&&<p>No GPS points match this filter.</p>}</>}
  {(view==='events'?journey.timeline.length:sampled.length)>80&&<div className="fc-day-pagination"><button className="fc-button" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous rows</button><span>{page} / {Math.ceil((view==='events'?journey.timeline.length:sampled.length)/80)}</span><button className="fc-button" disabled={page*80>=(view==='events'?journey.timeline.length:sampled.length)} onClick={()=>setPage(p=>p+1)}>Next rows</button></div>}
 </section>;
}
