"use client";
import { FleetMobileSection } from "./fleet-mobile-section";

import { Activity, ArrowDownUp, CalendarDays, Eye, RefreshCw, Search, Truck, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { FleetMultiSelect } from "@/components/fleet-multi-select";
import { FleetExportButtons } from "@/components/fleet-export-buttons";
import type { FleetControlAdHocRow, FleetControlData } from "@/lib/fleet-control";

import { reportDateRangeError } from "@/lib/fleet/operating-policy";

const money = (value: number) => `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const labelDate = (value: string) => new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(new Date(`${value}T12:00:00+05:30`));

type SortKey = "date" | "station" | "type" | "head" | "amount";

function RequestTable({ emptyText, fileName, onOpen, rows, sort, setSort, title }: {
  emptyText: string; fileName: string; onOpen: (row: FleetControlAdHocRow) => void; rows: FleetControlAdHocRow[];
  sort: { key: SortKey; direction: "asc" | "desc" }; setSort: (key: SortKey) => void; title: string;
}) {
  const sorted = useMemo(() => [...rows].sort((a, b) => {
    const left = sort.key === "station" ? a.stationCode : sort.key === "type" ? a.requestType : sort.key === "head" ? a.paymentHeadName : sort.key === "amount" ? a.amount : a.date;
    const right = sort.key === "station" ? b.stationCode : sort.key === "type" ? b.requestType : sort.key === "head" ? b.paymentHeadName : sort.key === "amount" ? b.amount : b.date;
    const order = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right));
    return order * (sort.direction === "asc" ? 1 : -1) || a.stationCode.localeCompare(b.stationCode);
  }), [rows, sort]);
  const sortButton = (key: SortKey, label: string) => <button onClick={() => setSort(key)} type="button">{label}<ArrowDownUp size={11} /></button>;
  return <div className="fc-table-panel fc-adhoc-grid"><div className="fc-table-toolbar"><span>{title}<small> · {rows.length} requests · {money(rows.reduce((sum, row) => sum + row.amount, 0))}</small></span><FleetExportButtons compact report={{ title: "Ad Hoc van and driver usage", subtitle: title, fileName: fileName.replace(/\.csv$/, ""), headers: ["Date", "Region", "Cluster", "Placement", "Payment head", "Request type", "Request", "Reason", "Operational remark", "Source", "Amount"], rows: sorted.map((row) => [row.date, row.region, row.cluster, row.stationCode, row.paymentHeadName, row.requestType, row.reference, row.reason, row.remark, row.source, row.amount]) }} /></div><div className="fc-table-scroll"><table><thead><tr><th>{sortButton("date", "Date")}</th><th>{sortButton("station", "Placement")}</th><th>{sortButton("head", "Usage")}</th><th>Request</th><th>Reason</th><th>{sortButton("amount", "Amount")}</th><th>Details</th></tr></thead><tbody>{sorted.map((row) => <tr key={`${row.id}-${row.date}-${row.source}`}><td data-label="Date">{labelDate(row.date)}</td><td data-label="Placement"><b className="fc-station-chip">{row.stationCode}</b><small className="fc-cell-note">{row.cluster} · {row.region}</small></td><td data-label="Usage"><strong>{row.paymentHeadName}</strong><small className="fc-cell-note"><span className={`fc-request-type ${row.requestType.toLowerCase()}`}>{row.requestType}</span></small></td><td data-label="Request"><strong>{row.reference}</strong></td><td data-label="Reason">{row.reason}</td><td data-label="Amount"><strong>{money(row.amount)}</strong></td><td data-label="Details"><button className="fc-row-action" onClick={() => onOpen(row)} type="button"><Eye size={14} /> View</button></td></tr>)}</tbody></table></div>{!rows.length ? <div className="fc-empty"><Activity size={34} /><strong>{emptyText}</strong><p>Change the dates or clear one of the filters.</p></div> : null}</div>;
}

export function FleetAdHocCapacity({ rows, stationOptions, today }: { rows: FleetControlAdHocRow[]; stationOptions: FleetControlData["stationOptions"]; today: string }) {
  const router = useRouter();
  const [view, setView] = useState<"live" | "history">("live");
  const [from, setFrom] = useState(`${today.slice(0, 7)}-01`); const [to, setTo] = useState(today);
  const [draftFrom, setDraftFrom] = useState(from); const [draftTo, setDraftTo] = useState(to);
  const [liveDate, setLiveDate] = useState(today);
  const [stations, setStations] = useState<string[]>([]); const [clusters, setClusters] = useState<string[]>([]); const [regions, setRegions] = useState<string[]>([]);
  const [requestTypes, setRequestTypes] = useState<string[]>([]); const [paymentHeads, setPaymentHeads] = useState<string[]>([]); const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<FleetControlAdHocRow | null>(null);
  const [liveSort, setLiveSort] = useState<{ key: SortKey; direction: "asc" | "desc" }>({ key: "station", direction: "asc" });
  const [allSort, setAllSort] = useState<{ key: SortKey; direction: "asc" | "desc" }>({ key: "date", direction: "desc" });
  useEffect(() => { const timer = window.setInterval(() => router.refresh(), 60_000); return () => window.clearInterval(timer); }, [router]);

  const stationByCode = useMemo(() => new Map(stationOptions.map((station) => [station.code, station])), [stationOptions]);
  const option = (values: string[]) => [...new Set(values.filter(Boolean))].sort().map((value) => ({ value, label: value }));
  const filteredStationOptions = stationOptions.filter((station) => (!clusters.length || clusters.includes(station.cluster)) && (!regions.length || regions.includes(station.region))).map((station) => ({ value: station.code, label: station.code, helper: station.name }));
  const paymentHeadOptions = [...new Map(rows.map((row) => [row.paymentHeadCode || row.paymentHeadName, { value: row.paymentHeadCode || row.paymentHeadName, label: row.paymentHeadName }])).values()].sort((a, b) => a.label.localeCompare(b.label));
  const needle = search.trim().toLowerCase();
  const matches = (row: FleetControlAdHocRow) => { const station = stationByCode.get(row.stationCode); return (!stations.length || stations.includes(row.stationCode)) && (!clusters.length || clusters.includes(row.cluster || station?.cluster || "Unassigned cluster")) && (!regions.length || regions.includes(row.region || station?.region || "Unassigned region")) && (!requestTypes.length || requestTypes.includes(row.requestType)) && (!paymentHeads.length || paymentHeads.includes(row.paymentHeadCode || row.paymentHeadName)) && (!needle || `${row.stationCode} ${row.stationName} ${row.cluster} ${row.region} ${row.paymentHeadName} ${row.reference} ${row.reason} ${row.remark}`.toLowerCase().includes(needle)); };
  const liveRows = rows.filter((row) => row.date === liveDate && matches(row));
  const rangeError = reportDateRangeError(draftFrom,draftTo);
  const loadedFrom = new Date(Date.parse(`${today}T00:00:00Z`)-92*86400000).toISOString().slice(0,10);
  const rangeRows = rows.filter((row) => row.date >= from && row.date <= to && matches(row));
  const vanRows = rangeRows.filter((row) => row.requestType === "Van"); const driverRows = rangeRows.filter((row) => row.requestType === "Driver");
  const changeSort = (setter: typeof setLiveSort) => (key: SortKey) => setter((current) => ({ key, direction: current.key === key && current.direction === "desc" ? "asc" : "desc" }));
  const clear = () => { setStations([]); setClusters([]); setRegions([]); setRequestTypes([]); setPaymentHeads([]); setSearch(""); };

  return <div className="fc-adhoc-workspace">
    <div className="fc-section-head"><div><span className="fc-eyebrow">Operations demand · visibility only</span><h1>Ad Hoc Usage</h1><p>Monitor live van and driver usage without changing the Operations approval flow.</p></div><button className="fc-button secondary" onClick={() => router.refresh()} type="button"><RefreshCw size={15} /> Refresh live</button></div>
    <div className="fc-view-switch" role="tablist"><button aria-selected={view === "live"} className={view === "live" ? "active" : ""} onClick={() => setView("live")} role="tab" type="button"><Activity size={15} /> Live today</button><button aria-selected={view === "history"} className={view === "history" ? "active" : ""} onClick={() => setView("history")} role="tab" type="button"><CalendarDays size={15} /> Usage history</button></div>
    <FleetMobileSection title="Search & filters" summary={[search,...regions,...clusters,...stations,...paymentHeads,...requestTypes].filter(Boolean).join(" · ") || "All stations · van & driver"} className="fc-mobile-filters"><section className="fc-adhoc-filters fc-filter-grid"><FleetMultiSelect allLabel="All regions" label="Region" onChange={setRegions} options={option(stationOptions.map((station) => station.region))} values={regions} /><FleetMultiSelect allLabel="All clusters" label="Cluster" onChange={setClusters} options={option(stationOptions.map((station) => station.cluster))} values={clusters} /><FleetMultiSelect allLabel="All placements" label="Station" onChange={setStations} options={filteredStationOptions} values={stations} /><FleetMultiSelect allLabel="All payment heads" label="Payment head" onChange={setPaymentHeads} options={paymentHeadOptions} values={paymentHeads} /><FleetMultiSelect allLabel="Van + Driver" label="Request type" onChange={setRequestTypes} options={[{ value: "Van", label: "Ad Hoc van" }, { value: "Driver", label: "Ad Hoc driver" }]} searchable={false} values={requestTypes} /><label className="fc-filter-search"><span>Search</span><div><Search size={14} /><input onChange={(event) => setSearch(event.target.value)} placeholder="Request, reason or remark" value={search} /></div></label><button onClick={clear} type="button">Clear filters</button></section></FleetMobileSection>
    {view === "live" ? <><section className="fc-grid-datebar"><div><strong>Live requests</strong><span>Auto-refreshes every minute</span></div><label><span>Request date</span><input max={today} onChange={(event) => setLiveDate(event.target.value)} type="date" value={liveDate} /></label></section><section className="fc-adhoc-kpis live"><article className="total"><Activity size={19} /><div><small>Selected day · total amount</small><strong>{money(liveRows.reduce((sum, row) => sum + row.amount, 0))}</strong><p>For the selected cluster and station filters</p></div></article><article className="van"><Truck size={19} /><div><small>Ad Hoc vans</small><strong>{liveRows.filter((row) => row.requestType === "Van").length}</strong><p>{money(liveRows.filter((row) => row.requestType === "Van").reduce((sum, row) => sum + row.amount, 0))}</p></div></article><article className="driver"><Users size={19} /><div><small>Ad Hoc drivers</small><strong>{liveRows.filter((row) => row.requestType === "Driver").length}</strong><p>{money(liveRows.filter((row) => row.requestType === "Driver").reduce((sum, row) => sum + row.amount, 0))}</p></div></article><article><CalendarDays size={19} /><div><small>Stations using capacity</small><strong>{new Set(liveRows.map((row) => row.stationCode)).size}</strong><p>{liveRows.length} total requests</p></div></article></section><RequestTable emptyText="No live van or driver request" fileName={`adhoc-live-${liveDate}.csv`} onOpen={setSelected} rows={liveRows} setSort={changeSort(setLiveSort)} sort={liveSort} title={`Live requests · ${labelDate(liveDate)}`} /></> : <>
      <section className="fc-grid-datebar fc-history-datebar"><div><strong>Usage history</strong><span>Loaded window: {loadedFrom}–{today}. Choose dates within this window, then filter or export.</span></div><div className="fc-date-pair"><label><span>From</span><input min={loadedFrom} max={draftTo || today} onChange={(event) => setDraftFrom(event.target.value)} type="date" value={draftFrom} /></label><label><span>To</span><input min={draftFrom || loadedFrom} max={today} onChange={(event) => setDraftTo(event.target.value)} type="date" value={draftTo} /></label><button onClick={() => { setDraftFrom(`${today.slice(0, 7)}-01`); setDraftTo(today); }} type="button">MTD</button><button onClick={() => { setDraftFrom(today); setDraftTo(today); }} type="button">Today</button><button className="fc-button primary" disabled={Boolean(rangeError)||draftFrom<loadedFrom||draftTo>today} onClick={() => { setFrom(draftFrom); setTo(draftTo); }} type="button">Apply</button></div></section>
      <section className="fc-adhoc-kpis"><article className="van"><Truck size={19} /><div><small>Van requests</small><strong>{vanRows.length}</strong><p>{money(vanRows.reduce((sum, row) => sum + row.amount, 0))}</p></div></article><article className="driver"><Users size={19} /><div><small>Driver requests</small><strong>{driverRows.length}</strong><p>{money(driverRows.reduce((sum, row) => sum + row.amount, 0))}</p></div></article><article><Activity size={19} /><div><small>Total jobs</small><strong>{rangeRows.length}</strong><p>{new Set(rangeRows.map((row) => row.stationCode)).size} placements</p></div></article><article className="total"><CalendarDays size={19} /><div><small>Total recorded amount</small><strong>{money(rangeRows.reduce((sum, row) => sum + row.amount, 0))}</strong><p>{labelDate(from)}–{labelDate(to)}</p></div></article></section>
      <RequestTable emptyText="No request data in this range" fileName={`adhoc-usage-${from}-${to}.csv`} onOpen={setSelected} rows={rangeRows} setSort={changeSort(setAllSort)} sort={allSort} title={`${labelDate(from)}–${labelDate(to)}`} />
    </>}
    {selected ? <div className="fc-modal-backdrop"><section className="fc-modal fc-adhoc-detail"><button aria-label="Close" className="fc-modal-close" onClick={() => setSelected(null)} type="button"><X size={19} /></button><div className="fc-modal-title"><span className="fc-vehicle-big"><Activity size={23} /></span><div><small>{selected.stationCode} · {labelDate(selected.date)}</small><h2>{selected.paymentHeadName}</h2><p>{selected.reference}</p></div></div><div className="fc-detail-grid"><div><small>Request type</small><strong>{selected.requestType}</strong></div><div><small>Amount</small><strong>{money(selected.amount)}</strong></div><div><small>Region / cluster</small><strong>{selected.region} · {selected.cluster}</strong></div><div><small>Source</small><strong>{selected.source}</strong></div></div><section className="fc-remarks"><small>Reason</small><p>{selected.reason}</p></section><section className="fc-remarks"><small>Operational remark</small><p>{selected.remark || "No operational remark recorded."}</p></section></section></div> : null}
  </div>;
}
