'use client';
import {useState} from 'react';
import {findingUrgency,type AuditReport,type FindingAction,type FindingProof} from '@/lib/fleet/audit-health';
const date=(value:string|null)=>value?new Date(`${value}T12:00:00+05:30`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'Not set';
const stamp=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});
const closed=(f:FindingAction)=>['resolved','accepted'].includes(f.status);
export function FleetFindingActions({report,onSaved}:{report:AuditReport;onSaved:()=>void}) {
 const [filter,setFilter]=useState('open');
 const today=new Date(report.generatedAt).toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
 const actions=report.actions||[],pending=actions.filter(f=>!closed(f));
 const urgent=pending.filter(f=>['Immediate','Overdue','Due today'].includes(findingUrgency(f,today)));
 const shown=actions.filter(f=>filter==='all'||(filter==='closed'?closed(f):filter==='urgent'?urgent.includes(f):!closed(f))).sort((a,b)=>Number(closed(a))-Number(closed(b))||(['critical','high','medium','low'].indexOf(a.severity)-['critical','high','medium','low'].indexOf(b.severity))||(a.due||'9999').localeCompare(b.due||'9999'));
 return <section id="fleet-action-tracker" className="fc-finding-tracker"><div className="fc-action-heading"><div><h3>Action points & closure</h3><p>Current and earlier audit findings · close with proof</p></div><nav aria-label="Filter audit actions">{[['open',`${pending.length} open`],['urgent',`${urgent.length} urgent / due`],['closed',`${actions.length-pending.length} closed`],['all','All']].map(([value,label])=><button type="button" key={value} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</nav></div>
 {!shown.length?<p className="fc-health-clear">No {filter==='all'?'':filter} actions.</p>:shown.map(f=><article key={`${f.id}-${f.updatedAt}`} className={`fc-action-card ${closed(f)?'closed':f.severity}`}><div className="fc-action-title"><b>{f.action||f.finding}</b><span>{findingUrgency(f,today)}</span></div><div className="fc-action-meta"><span>{f.severity.toUpperCase()} · {f.status.replace('_',' ')}</span><span>Due <b>{date(f.due)}</b></span><span>Responsible: <b>{f.owner||'Not assigned'}</b></span>{f.auditId!==report.id?<span>Earlier audit · {date(f.date)}</span>:null}</div>
 <details className="fc-report-disclosure"><summary>Remarks, proof & updates · {f.updates.length}{report.canManageActions?' · Update / close':''}</summary><p><b>Finding:</b> {f.finding}</p>{f.resolution?<p><b>Latest remark:</b> {f.resolution}</p>:null}{f.resolvedAt?<p>Closed {stamp(f.resolvedAt)} IST</p>:null}
 <div className="fc-action-history"><h4>Follow-up history</h4><p>Raised {date(f.date)} · {f.category}</p>{f.updates[0]?.before.resolution?<p><b>Earlier recorded remark:</b> {f.updates[0].before.resolution}</p>:null}{!f.updates.length?<p>No follow-up updates recorded.{closed(f)?' This earlier closure has no proof recorded in the action tracker.':''}</p>:f.updates.map(u=><article key={u.id}><b>{u.status.replace('_',' ')} · {stamp(u.at)} IST</b><small>{u.actor} · Responsible: {u.owner} · Due {date(u.due)} · {u.severity}</small><p>{u.note}</p>{u.before.action!==u.action?<p>Action: {u.before.action||'Not set'} → {u.action}</p>:null}{u.before.due!==u.due?<p>Due date: {date(u.before.due)} → {date(u.due)}</p>:null}{u.before.status!==u.status?<p>Status: {u.before.status.replace('_',' ')} → {u.status.replace('_',' ')}</p>:null}{u.before.severity!==u.severity?<p>Priority: {u.before.severity} → {u.severity}</p>:null}{u.before.owner!==u.owner?<p>Responsible: {u.before.owner||'Not assigned'} → {u.owner}</p>:null}<Proofs proofs={u.proofs}/></article>)}</div>
 {report.canManageActions?<FindingEditor finding={f} onSaved={onSaved}/>:<p>View only. A Fleet audit or maintenance editor can update and close this action.</p>}</details></article>)}
 </section>;
}
function Proofs({proofs}:{proofs:FindingProof[]}){return <div className="fc-action-proofs">{proofs.map(p=><a href={p.url} target="_blank" rel="noreferrer" key={p.id}>{p.type==='photo'?<img loading="lazy" src={p.url} alt={p.caption}/>:<b>PDF</b>}<span>{p.caption||'Supporting proof'}</span></a>)}</div>;}
function FindingEditor({finding:f,onSaved}:{finding:FindingAction;onSaved:()=>void}) {
 const [status,setStatus]=useState(closed(f)?'resolved':f.status),[action,setAction]=useState(f.action),[owner,setOwner]=useState(f.owner),[due,setDue]=useState(f.due||''),[severity,setSeverity]=useState(f.severity),[note,setNote]=useState('');
 const [proofs,setProofs]=useState<FindingProof[]>([]),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[receipt,setReceipt]=useState<{payload:string;id:string}|null>(null);
 async function upload(files:File[]){
  if(proofs.length+files.length>10){setError('Add up to 10 files per update. Save an update to add more.');return;}
  setUploading(true);setError('');const failures:string[]=[];
  for(const file of files){try{if(!file.size||file.size>3500000)throw new Error('Choose a file under 3.5 MB.');const form=new FormData();form.set('auditId',f.auditId);form.set('findingId',f.id);form.set('file',file);const r=await fetch('/api/fleet/audit-evidence',{method:'POST',body:form});const data=await r.json();if(!r.ok||!data.uploadId)throw new Error(data.error||'Upload failed.');setProofs(p=>[...p,{id:data.uploadId,url:data.url,type:data.type,caption:file.name,auditId:f.auditId}]);}catch(e){failures.push(`${file.name}: ${e instanceof Error?e.message:'Upload failed.'}`);}}
  setError(failures.join(' '));setUploading(false);
 }
 return <form className="fc-action-editor" onSubmit={async e=>{e.preventDefault();if(uploading||busy||saved)return;setBusy(true);setError('');try{
  if(status==='resolved'&&!proofs.length)throw new Error('Upload at least one photo or PDF as closure proof.');
  const data={findingId:f.id,expectedUpdatedAt:f.updatedAt,status,actionRequired:action,responsibleName:owner,dueDate:due,severity,resolutionNote:note,uploadIds:proofs.map(p=>p.id)};
  const payload=JSON.stringify(data),eventId=receipt?.payload===payload?receipt.id:crypto.randomUUID();setReceipt({payload,id:eventId});
  const r=await fetch('/api/fleet/finding-update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,eventId})});const result=await r.json();if(!r.ok)throw new Error(result.error||'Update failed.');setSaved(true);onSaved();
 }catch(e){setError(e instanceof Error?e.message:'Save failed. Retry.');}finally{setBusy(false);}}}>
 <h4>{closed(f)?'Add proof or reopen this action':'Update this action'}</h4><fieldset disabled={busy||uploading||saved}><div className="fc-action-fields"><label className="full">Action point<input required maxLength={2000} value={action} onChange={e=>setAction(e.target.value)}/></label><label>Responsible person<input required maxLength={160} value={owner} placeholder="Name / team responsible" onChange={e=>setOwner(e.target.value)}/></label><label>Target closure date<input required type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><label>Priority<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="critical">Critical · immediate</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">{closed(f)?'Reopen':'Open'}</option><option value="in_progress">In progress</option><option value="resolved">{closed(f)?'Keep closed · add proof':'Close with proof'}</option></select></label><label className="full">{status==='resolved'?'Closure remarks · what was fixed and verified':'Update remarks'}<textarea required maxLength={4000} rows={3} value={note} placeholder="Work done, outstanding issue or reason for changing the deadline" onChange={e=>setNote(e.target.value)}/></label><label className="full">{status==='resolved'?'Closure proof required':'Add supporting proof'}<input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';void upload(files);}}/><small>Up to 10 photos or PDFs per update · 3.5 MB each · You can add more in later updates.</small></label></div>
 <Proofs proofs={proofs}/>{proofs.map(p=><button className="fc-proof-remove" type="button" key={p.id} onClick={()=>setProofs(items=>items.filter(i=>i.id!==p.id))}>Remove {p.caption}</button>)}</fieldset>
 {error?<p role="alert" className="fc-inline-message error">{error}</p>:null}{saved?<p role="status">Update saved. Refresh the report to see the latest action.</p>:null}<button type="submit" className="fc-button primary" disabled={busy||uploading||saved}>{uploading?'Uploading proof…':busy?'Saving…':status==='resolved'?'Close action with proof':'Save follow-up'}</button>
 </form>;
}
