'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Save,Search,UsersRound} from 'lucide-react';
import type {MappingData,VehicleDA} from '@/lib/fleet/da-mapping';
import {FleetExportButtons} from './fleet-export-buttons';
import './fleet-da-mapping.css';
const vehicleName=(v:VehicleDA)=>v.vehicle_no.startsWith('PENDING-')?(v.ownership_type==='own'?'':v.da_name||v.vendor_name)||v.model||'Registration not added':v.vehicle_no;
type Draft={ids:string[];selected:boolean;remarks:string};
export function FleetDAMapping(){
 const [data,setData]=useState<MappingData|null>(null),[date,setDate]=useState(''),[station,setStation]=useState(''),[query,setQuery]=useState(''),[includeVendor,setIncludeVendor]=useState(false),[tab,setTab]=useState<'daily'|'defaults'>('daily');
 const [draft,setDraft]=useState<Record<string,Draft>>({}),[editing,setEditing]=useState<string|null>(null),[riderSearch,setRiderSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[recentDays,setRecentDays]=useState(7);
 const request=useRef(0),dirty=useRef(false);
 async function load(nextStation=station,nextDate=date){
  const n=++request.current;setLoading(true);setError('');
  try{const r=await fetch(`/api/fleet/da-mapping?station=${encodeURIComponent(nextStation)}&date=${encodeURIComponent(nextDate)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load mappings.');if(n!==request.current)return;setData(d);setDate(d.date);setStation(d.station);setRecentDays(d.recentDays);setDraft(Object.fromEntries(d.vehicles.map((v:MappingData['vehicles'][number])=>{const saved=d.assignments.filter((a:MappingData['assignments'][number])=>a.vehicle_id===v.id),def=d.defaults.find((a:MappingData['defaults'][number])=>a.vehicle_id===v.id);return[v.id,{ids:saved.length?saved.map((a:MappingData['assignments'][number])=>a.provider_employee_id):d.confirmations.some((c:{vehicle_id:string})=>c.vehicle_id===v.id)?[]:def?[def.provider_employee_id]:[],selected:false,remarks:''}];})));dirty.current=false;setEditing(null);
  }catch(e){if(n===request.current)setError(e instanceof Error?e.message:'Unable to load mappings.');}finally{if(n===request.current)setLoading(false);}
 }
 useEffect(()=>{void load('','');return()=>{request.current++;};},[]); // Initial scoped load only; filters load explicitly.
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 function change(id:string,patch:Partial<Draft>){dirty.current=true;setDraft(prev=>({...prev,[id]:{...prev[id],...patch}}));}
 function navigate(s:string,d:string){if(!dirty.current||window.confirm('Discard unsaved mapping selections?'))void load(s,d);}
 async function save(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/fleet/da-mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,station:data?.station,date:data?.date})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save.');await load();setNotice(body.action==='mapping.confirm'?`${result.saved} vehicle mapping(s) confirmed.`:'Saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 const vehicles=(data?.vehicles??[]).filter(v=>(includeVendor||!['VNV','VAN_VENDOR','VENDOR'].includes(v.sourceCode.toUpperCase()))&&(!query||`${v.vehicle_no} ${v.model} ${v.sourceName} ${draft[v.id]?.ids.map(id=>data?.options.find(o=>o.id===id)?.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())));
 const selected=vehicles.filter(v=>draft[v.id]?.selected),allSelected=vehicles.length>0&&selected.length===vehicles.length;
 const options=(data?.options??[]).filter(o=>`${o.name} ${o.id}`.toLowerCase().includes(riderSearch.toLowerCase()));
 const controlsDisabled=busy||loading;
 return <section className="da-mapping" aria-busy={loading}>
 <header><div><span className="da-eyebrow">Fleet + Operations</span><h1><UsersRound size={22}/> Vehicle DA mapping</h1><p>Confirm who used each van. Amazon counts update after the daily import.</p></div><button disabled={controlsDisabled} onClick={()=>navigate(station,date)}><RefreshCw size={16}/> Refresh</button></header>
 {error&&<div className="da-message error" role="alert">{error} <button disabled={controlsDisabled} onClick={()=>navigate(station,date)}>Retry</button></div>}{notice&&<div className="da-message" role="status">{notice}</div>}
 {loading&&!data?<p>Loading permitted vehicles…</p>:null}
 {data&&<>
 <nav><button aria-pressed={tab==='daily'} onClick={()=>{setTab('daily');setEditing(null);}}>Daily assignments</button>{data.canDefaults&&<button aria-pressed={tab==='defaults'} onClick={()=>{setTab('defaults');setEditing(null);}}>Default DA master</button>}</nav>
 <div className="da-filters"><label>Station<select disabled={controlsDisabled} value={station} onChange={e=>navigate(e.target.value,date)}>{data.stations.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><label>Work date<input disabled={controlsDisabled||tab==='defaults'} type="date" value={date} max={data.today} onChange={e=>{if(e.target.value)navigate(station,e.target.value);}}/></label><details className="da-extra-filters"><summary>Search / vehicle sources</summary><label className="da-search">Find vehicle / associate<input placeholder="Number, model or name" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="da-check"><input type="checkbox" checked={includeVendor} onChange={e=>setIncludeVendor(e.target.checked)}/> Include van vendors</label></details></div>
 <div className="da-summary"><strong>{vehicles.length} vehicles</strong><span>{data.assignments.length} confirmed rider IDs</span><small>{data.latestFeed?`Feed updated ${new Date(data.latestFeed).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}`:'Counts pending import for this date'}</small></div>
 {data.warning&&<div className="da-message" role="status">{data.warning}</div>}
 {tab==='defaults'?<div className="da-explainer">Defaults prefill future daily confirmations; they do not rewrite saved days. {data.canPolicy&&<details><summary>Rider list settings</summary><label>Recent activity window (days)<input type="number" min={3} max={30} value={recentDays} onChange={e=>setRecentDays(Number(e.target.value))}/></label><button disabled={controlsDisabled} onClick={()=>save({action:'mapping.policy',recentDays})}>Save window</button></details>}</div>:<details className="da-explainer"><summary>How counts are linked</summary><p>Vehicle selection follows current station placement. Rider IDs seen in the last {data.recentDays} calendar days appear here, regardless of the work date selected. Confirm only associates who actually used the van for that day's delivery work. More than one associate can share a van; one rider's full-day count can belong to only one van. For split van/bike or multi-vehicle routes, leave the count unassigned until route-level evidence is available. SWA is part of Delivered. Small/volumetric mix needs shipment-level linkage and is not inferred from these totals.</p></details>}
 {tab==='daily'&&<div className="da-bulk"><label className="da-check"><input type="checkbox" disabled={!data.canEdit||controlsDisabled} checked={allSelected} onChange={()=>{dirty.current=true;setDraft(p=>{const n={...p};vehicles.forEach(v=>n[v.id]={...n[v.id],selected:!allSelected});return n;});}}/> Select all shown</label><button className="da-primary" disabled={!data.canEdit||controlsDisabled||!selected.length} onClick={()=>save({action:'mapping.confirm',rows:selected.map(v=>({vehicleId:v.id,ids:draft[v.id].ids,remarks:draft[v.id].remarks,expectedRevision:data.confirmations.find(c=>c.vehicle_id===v.id)?.updated_at??null,expectedIds:data.assignments.filter(a=>a.vehicle_id===v.id).map(a=>a.id).sort()}))})}><Save size={15}/>{busy?'Saving…':`Confirm selected${selected.length?` (${selected.length})`:''}`}</button><FleetExportButtons compact image={false} report={{title:'Vehicle DA daily assignments',subtitle:`${data.station} · ${data.date} · Confirmed only; blank counts mean awaiting import`,fileName:`fleet-da-${data.station}-${data.date}`,headers:['Vehicle','Model','Station','Date','Associate','Rider ID','Delivered','C-return','SWA (in Delivered)'],rows:data.assignments.filter(a=>vehicles.some(v=>v.id===a.vehicle_id)).map(a=>{const v=data.vehicles.find(v=>v.id===a.vehicle_id)!;return[v.vehicle_no,v.model,v.station_code,date,a.name,a.provider_employee_id,a.delivered,a.cReturn,a.swa];})}}/></div>}
 <div className="da-rows">{vehicles.map(v=>{const row=draft[v.id]||{ids:[],selected:false,remarks:''},saved=data.assignments.filter(a=>a.vehicle_id===v.id),def=data.defaults.find(a=>a.vehicle_id===v.id),confirmation=data.confirmations.find(a=>a.vehicle_id===v.id),ids=tab==='daily'?row.ids:def?[def.provider_employee_id]:[];const total=(key:'delivered'|'cReturn'|'swa')=>!saved.length||saved.some(a=>a[key]==null)?'—':saved.reduce((n,a)=>n+a[key]!,0);return <article key={v.id} className="da-row">
 <div className="da-vehicle">{tab==='daily'&&<input type="checkbox" aria-label={`Select ${v.vehicle_no}`} disabled={!data.canEdit||controlsDisabled} checked={row.selected} onChange={e=>change(v.id,{selected:e.target.checked})}/>}<div><strong>{vehicleName(v)}</strong><small>{v.model||'Model not recorded'} · {v.station_code}{v.vehicle_no.startsWith('PENDING-')?' · Registration not added':''}</small><small>{v.sourceName} · {v.status.replaceAll('_',' ')}</small></div></div>
 <div className="da-associate"><strong>{ids.length?ids.map(id=>data.options.find(o=>o.id===id)?.name||id).join(' + '):'No associate selected'}</strong><small>{ids.join(' · ')||'Choose the rider who used this vehicle'}</small><span className={`da-chip ${saved.length||confirmation?'confirmed':''}`}>{tab==='defaults'?'Default suggestion':saved.length?'Confirmed':confirmation?'No delivery work confirmed':ids.length?'Default · confirm for this day':'Not confirmed'}</span>{ids.some(id=>!data.options.find(o=>o.id===id)?.lastSeen)&&ids.length>0?<small className="da-warning">Not in recent feed · verify before confirming</small>:null}</div>
 {tab==='daily'&&<div className="da-counts"><span>Delivered<strong>{total('delivered')}</strong></span><span>C-return<strong>{total('cReturn')}</strong></span><span>SWA<strong>{total('swa')}</strong></span></div>}
 {confirmation?.remarks&&<small className="da-saved-note">{confirmation.remarks}</small>}
 <button disabled={controlsDisabled||(tab==='defaults'?!data.canDefaults:!data.canEdit)} onClick={()=>{if(tab==='defaults')setDraft(p=>({...p,[v.id]:{...p[v.id],ids:def?[def.provider_employee_id]:[]}}));setEditing(editing===v.id?null:v.id);setRiderSearch('');}}>{editing===v.id?'Close':tab==='defaults'?'Set default':'Change'}</button>
 {editing===v.id&&<div className="da-picker"><label><Search size={15}/> Search associate name / rider ID<input autoFocus value={riderSearch} onChange={e=>setRiderSearch(e.target.value)} placeholder="Search recent station IDs"/></label><div className="da-option-list">{options.map(o=><label key={o.id} className="da-option"><input type={tab==='defaults'?'radio':'checkbox'} name={`rider-${v.id}`} checked={tab==='defaults'?row.ids[0]===o.id:row.ids.includes(o.id)} onChange={()=>change(v.id,{ids:tab==='defaults'?[o.id]:row.ids.includes(o.id)?row.ids.filter(id=>id!==o.id):[...row.ids,o.id],selected:true})}/><span><strong>{o.name}</strong><small>{o.id} · {o.lastSeen?`Seen ${o.lastSeen}`:'Saved identity'}</small></span></label>)}{!options.length&&<p>No recent rider IDs found. Refresh after the Amazon daily import.</p>}</div>
 {tab==='defaults'?<div className="da-bulk"><button disabled={controlsDisabled||row.ids.length!==1} onClick={()=>save({action:'mapping.default',vehicleId:v.id,providerId:row.ids[0],expectedUpdatedAt:def?.updated_at??null})}>Save default</button>{def&&<button disabled={controlsDisabled} onClick={()=>save({action:'mapping.default',vehicleId:v.id,providerId:null,expectedUpdatedAt:def.updated_at})}>Remove default</button>}</div>:<><button type="button" onClick={()=>change(v.id,{ids:[],selected:true})}>No delivery work / clear selection</button><label>Reason / note {saved.length||!row.ids.length?'(required for correction / clearing)':''}<input value={row.remarks} maxLength={1000} onChange={e=>change(v.id,{remarks:e.target.value,selected:true})} placeholder="Replacement, leave, handover or correction"/></label><small>Selection saved only when you press Confirm selected.</small></>}
 </div>}
 </article>;})}{!vehicles.length&&<p className="da-empty">No vehicles match this station and filter.</p>}</div>
 {!data.canEdit&&<p>Read-only access. Contact your Fleet or Operations administrator to update mappings.</p>}
 </>}
 </section>;
}
