"use client";
import {FleetMappingPending} from "./fleet-mapping-pending";
import { FleetMobileSection } from "./fleet-mobile-section";
import { FleetVehicleMeta } from "@/components/fleet-vehicle-meta";
import {FleetAuditReport} from './fleet-audit-report';
import { useState } from 'react';
import { CheckCircle2, ChevronDown, X } from 'lucide-react';
import { fleetAttention, type AttentionItem } from '@/lib/fleet/attention';
import type { FleetControlData, FleetControlVehicle } from '@/lib/fleet-control';
import { FleetExportButtons } from '@/components/fleet-export-buttons';
import { FleetVehicleRentEditor } from '@/components/fleet-vehicle-rent';

const categories=['Rent setup','Documents','Service','Availability','Audit findings','Audits due','Tracking exceptions','Approvals'];
const priorityLabel=(r:AttentionItem)=>r.priority===0?'Critical':r.priority===1?'High':'Routine';
export function FleetAttentionWorkspace({data,onNavigate,onChanged,onRentSaved}:{data:FleetControlData;onNavigate:(item:AttentionItem)=>void;onChanged:()=>void;onRentSaved:(id:string,values:Pick<FleetControlVehicle,'rentAmount'|'rentPeriod'>)=>void}){
 const [category,setCategory]=useState('');const [station,setStation]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('open');const [editing,setEditing]=useState<AttentionItem|null>(null);const [rentId,setRentId]=useState<string|null>(null);
 const all=fleetAttention(data), open=all.filter(r=>!r.resolved);
 const scoped=all.filter(r=>(status==='resolved'?r.resolved:!r.resolved)&&(!station||r.station===station)&&`${r.title} ${r.vehicle} ${r.station} ${r.detail}`.toLowerCase().includes(query.toLowerCase())&&(status!=='overdue'||Boolean(r.due&&r.due<data.today))&&(status!=='today'||r.due===data.today));
 const rows=scoped.filter(r=>!category||r.category===category);
 const rentVehicle=data.vehicles.find(v=>v.id===rentId);
 const counts=categories.map(name=>({name,count:scoped.filter(r=>r.category===name).length}));
 const openItem=(r:AttentionItem)=>{if(r.category==='Rent setup')setRentId(r.vehicleId);else if(r.findingId){setEditing(r);}else onNavigate(r);};
 return <section className="fc-attention-workspace"><div className="fc-section-head"><div><span className="fc-eyebrow">Daily action list</span><h1>Need Attention</h1><p>See exactly what is pending. Saved updates clear resolved items.</p></div><FleetExportButtons image compact report={{title:'Fleet · Need Attention',subtitle:`As at ${data.today}`,fileName:`fleet-attention-${data.today}`,headers:['Priority','Station','Vehicle','Category','Pending item','Action','Due'],rows:rows.map(r=>[priorityLabel(r),r.station,r.vehicle,r.category,r.title,r.detail,r.due])}}/></div>
 <FleetMappingPending surface="fleet"/>
 <div className="fc-attention-summary" aria-label="Action summary"><span><strong>{open.length}</strong> pending</span><span className="urgent"><strong>{open.filter(r=>r.priority===0).length}</strong> critical</span><button type="button" onClick={()=>{setStatus('overdue');setCategory('');}}><strong>{open.filter(r=>r.due&&r.due<data.today).length}</strong> overdue</button><button type="button" onClick={()=>{setStatus('today');setCategory('');}}><strong>{open.filter(r=>r.due===data.today).length}</strong> due today</button></div>
 <FleetMobileSection title="Search & filters" summary={[query,station,status].filter(Boolean).join(" · ") || "All open actions"} className="fc-mobile-filters"><div className="fc-attention-filters"><label>Search<input placeholder="Vehicle, pending field or issue" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Station<select value={station} onChange={e=>setStation(e.target.value)}><option value="">All stations</option>{[...new Set(all.map(r=>r.station))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="open">All pending</option><option value="overdue">Overdue</option><option value="today">Due today</option><option value="resolved">Resolved findings</option></select></label><button type="button" className="fc-button secondary" onClick={()=>{setCategory('');setStation('');setQuery('');setStatus('open');}}>Clear filters</button></div></FleetMobileSection>
 <nav className="fc-attention-sections" aria-label="Pending work sections"><button type="button" aria-pressed={!category} onClick={()=>setCategory('')}>All <b>{scoped.length}</b></button>{counts.map(c=><button key={c.name} type="button" aria-pressed={category===c.name} onClick={()=>setCategory(c.name)}>{c.name} <b>{c.count}</b></button>)}</nav>
 <div className="fc-attention-groups">{counts.filter(c=>(!category||c.name===category)&&c.count>0).map(c=><details key={c.name} open className="fc-attention-group"><summary><ChevronDown size={16}/><strong>{c.name}</strong><span>{c.count} {status==='resolved'?'resolved':'pending'}</span></summary><div className="fc-attention-table"><div className="fc-attention-row fc-attention-columns" aria-hidden="true"><span>Vehicle / Station</span><span>Pending field / Action</span><span>Due</span><span>Priority</span><span>Update</span></div>{rows.filter(r=>r.category===c.name).map(r=><article key={r.id} className="fc-attention-row"><div className="fc-attention-vehicle"><strong>{r.vehicle||r.station}</strong>{r.vehicle?<FleetVehicleMeta vehicleNo={r.vehicle} model={data.vehicles.find(v=>v.id===r.vehicleId)?.model} stationCode={r.station}/>:<small>{r.category}</small>}</div><div className="fc-attention-issue"><h3>{r.title}</h3><p>{r.detail}</p></div><span className={`fc-attention-due ${r.due&&r.due<data.today?'fc-overdue':''}`}>{r.due||'Setup pending'}{r.due&&r.due<data.today?<small>Overdue</small>:null}</span><span className={`fc-attention-priority p${r.priority}`}>{r.resolved?'Resolved':priorityLabel(r)}</span><button className="fc-button secondary fc-attention-action" type="button" onClick={()=>openItem(r)}>{r.category==='Rent setup'?(data.capabilities.canEditVehicles?'Set rent':'View rent'):r.findingId?'Review':r.auditId?'Open audit':r.category==='Documents'?'Update document':r.category==='Service'?'View service':r.category==='Availability'?'Update status':'Review'}</button></article>)}</div></details>)}{!rows.length&&<div className="fc-empty"><CheckCircle2 size={28}/><h3>No {category?category.toLowerCase()+' ':''}items {status==='resolved'?'resolved':'pending'}</h3><p>{scoped.length?'Choose another section to see pending work.':'This view is up to date.'}</p></div>}</div>
 {rentVehicle&&<div className="fc-modal-backdrop"><section className="fc-modal fc-attention-rent-modal" role="dialog" aria-modal="true" aria-labelledby="attention-rent-title"><button className="fc-modal-close" aria-label="Close rent" type="button" onClick={()=>setRentId(null)}><X/></button><h2 id="attention-rent-title">{rentVehicle.vehicleNo} · Rent</h2><p>{rentVehicle.stationCode} · {rentVehicle.model}</p><FleetVehicleRentEditor key={rentVehicle.id} vehicle={rentVehicle} canEdit={data.capabilities.canEditVehicles} onSaved={values=>{onRentSaved(rentVehicle.id,values);if(values.rentAmount!=null&&values.rentPeriod)setRentId(null);onChanged();}}/></section></div>}
 {editing&&<FleetAuditReport auditId={data.findings.find(f=>f.id===editing.findingId)?.auditId||editing.auditId||''} onClose={()=>{setEditing(null);onChanged();}}/>}
 </section>;
}
