'use client';
import {useEffect,useRef,useState} from 'react';
import {RefreshCw,Save,Search,UsersRound} from 'lucide-react';
import {isODCD,riderAvailableAt,type MappingData,type VehicleDA} from '@/lib/fleet/da-mapping';
import {FleetMappingPending} from './fleet-mapping-pending';
import {FleetExportButtons} from './fleet-export-buttons';
import {SearchableSelect} from './searchable-select';
import './fleet-da-mapping.css';
const vehicleName=(v:VehicleDA)=>v.vehicle_no.startsWith('PENDING-')?(v.ownership_type==='own'?'':v.da_name||v.vendor_name)||v.model||'Registration not added':v.vehicle_no;
type Draft={ids:string[];selected:boolean;remarks:string;dayStatus?:string};
export function FleetDAMapping({mode='daily',surface='ops'}:{mode?:'daily'|'defaults';surface?:'fleet'|'ops'}){
 const tab=mode;
 const [alertFrom,setAlertFrom]=useState('');
 const [sourceFilter,setSourceFilter]=useState(''),[modelFilter,setModelFilter]=useState(''),[assignmentFilter,setAssignmentFilter]=useState('');
 const [data,setData]=useState<MappingData|null>(null),[date,setDate]=useState(''),[station,setStation]=useState(''),[query,setQuery]=useState(''),[includeVendor,setIncludeVendor]=useState(false);
 const [draft,setDraft]=useState<Record<string,Draft>>({}),[editing,setEditing]=useState<string|null>(null),[riderSearch,setRiderSearch]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[recentDays,setRecentDays]=useState(7);
 const request=useRef(0),dirty=useRef(false);
 async function load(nextStation=station,nextDate=date){
  const n=++request.current;setLoading(true);setError('');
  try{const r=await fetch(`/api/fleet/da-mapping?station=${encodeURIComponent(nextStation)}&date=${encodeURIComponent(nextDate)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load mappings.');if(n!==request.current)return;setData(d);setDate(d.date);setStation(d.station);setRecentDays(d.recentDays);setAlertFrom(d.alertFrom||d.today);setDraft(Object.fromEntries(d.vehicles.map((v:MappingData['vehicles'][number])=>{const saved=d.assignments.filter((a:MappingData['assignments'][number])=>a.vehicle_id===v.id),def=d.defaults.find((a:MappingData['defaults'][number])=>a.vehicle_id===v.id);return[v.id,{ids:saved.length?saved.map((a:MappingData['assignments'][number])=>a.provider_employee_id):d.confirmations.some((c:{vehicle_id:string})=>c.vehicle_id===v.id)?[]:def?[def.provider_employee_id]:[],selected:false,remarks:d.confirmations.find((c:{vehicle_id:string;remarks:string})=>c.vehicle_id===v.id)?.remarks||'',dayStatus:d.confirmations.find((c:{vehicle_id:string;day_status?:string})=>c.vehicle_id===v.id)?.day_status||''}];})));dirty.current=false;const target=new URLSearchParams(window.location.search).get('mappingVehicle');setEditing(n===1&&d.vehicles.some((v:VehicleDA)=>v.id===target)?target:null);
  }catch(e){if(n===request.current)setError(e instanceof Error?e.message:'Unable to load mappings.');}finally{if(n===request.current)setLoading(false);}
 }
 useEffect(()=>{const p=new URLSearchParams(window.location.search);void load(p.get('mappingStation')||'',mode==='daily'?p.get('mappingDate')||'':'');return()=>{request.current++;};},[]); // Initial scoped load only; filters load explicitly.
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 function change(id:string,patch:Partial<Draft>){dirty.current=true;setDraft(prev=>({...prev,[id]:{...prev[id],...patch}}));}
 function navigate(s:string,d:string){if(!dirty.current||window.confirm('Discard unsaved mapping selections?'))void load(s,d);}
 async function save(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/fleet/da-mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,station:data?.station,date:data?.date})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save.');await load();window.dispatchEvent(new Event('fleet-mapping-saved'));setNotice(body.action==='mapping.confirm'?`${result.saved} vehicle assignment(s) saved.`:'Saved.');}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 const vehicles=(data?.vehicles??[]).filter(v=>(includeVendor||!['VNV','VAN_VENDOR','VENDOR'].includes(v.sourceCode.toUpperCase()))&&(!query||`${v.vehicle_no} ${v.station_code} ${v.model} ${v.sourceName} ${v.da_name||''} ${draft[v.id]?.ids.join(' ')||''} ${draft[v.id]?.ids.map(id=>data?.options.find(o=>o.id===id)?.name).join(' ')}`.toLowerCase().includes(query.toLowerCase()))&&(!sourceFilter||v.sourceCode===sourceFilter)&&(!modelFilter||v.model===modelFilter)&&(!assignmentFilter||(assignmentFilter==='confirmed'?data?.confirmations.some(c=>c.vehicle_id===v.id):assignmentFilter==='pending'?!data?.confirmations.some(c=>c.vehicle_id===v.id):!draft[v.id]?.ids.length)));
 const selected=vehicles.filter(v=>draft[v.id]?.selected),allSelected=vehicles.length>0&&selected.length===vehicles.length;
 const editingStation=data?.vehicles.find(v=>v.id===editing)?.station_code;
 const options=(data?.options??[]).filter(o=>(!editingStation||riderAvailableAt(o,editingStation))&&`${o.name} ${o.id}`.toLowerCase().includes(riderSearch.toLowerCase()));
 const controlsDisabled=busy||loading;
 const needsReview=(v:VehicleDA)=>{const row=draft[v.id],saved=data?.assignments.filter(a=>a.vehicle_id===v.id)??[];if(!row)return true;const changed=[...row.ids].sort().join('|')!==saved.map(a=>a.provider_employee_id).sort().join('|');return (!row.ids.length||(changed&&saved.length>0))&&row.remarks.trim().length<3;};
 const notReady=selected.filter(needsReview);
 function confirmSelected(){if(notReady.length){setError(`${notReady.length} selected vehicle(s) need an associate or a reason before saving. Review the highlighted rows, or select ready vehicles.`);setEditing(notReady[0].id);return;}void save({action:'mapping.confirm',rows:selected.map(v=>({vehicleId:v.id,ids:draft[v.id].ids,remarks:draft[v.id].remarks,dayStatus:draft[v.id].dayStatus||'',expectedRevision:data?.confirmations.find(c=>c.vehicle_id===v.id)?.updated_at??null,expectedIds:data?.assignments.filter(a=>a.vehicle_id===v.id).map(a=>a.id).sort()??[]}))});}

 return <section className="da-mapping" aria-busy={loading}>
 <header><div><span className="da-eyebrow">Fleet + Operations</span><h1><UsersRound size={22}/> {tab==='defaults'?'Default DA master':'Vehicle DA mapping'}</h1><p>{tab==='defaults'?'Set the regular associate once; daily assignments will prefill.':'Choose the associate for each active vehicle, select the rows and save.'}</p></div><button disabled={controlsDisabled} onClick={()=>navigate(station,date)}><RefreshCw size={16}/> Refresh</button></header>
 {error&&<div className="da-message error" role="alert">{error} <button disabled={controlsDisabled} onClick={()=>navigate(station,date)}>Retry</button></div>}{notice&&<div className="da-message" role="status">{notice}</div>}
 {loading&&!data?<p>Loading permitted vehicles…</p>:null}
 {data&&<>
 {tab==='daily'&&<FleetMappingPending surface={surface}/>}
 <div className="da-filters"><div className="da-station-field"><span>Station</span><SearchableSelect name="mapping-station" disabled={controlsDisabled} value={station} maxOptions={data.stations.length+1} options={[{value:'*',label:'All stations',helper:'All permitted locations with vehicles'},...data.stations.map(s=>({value:s.code,label:`${s.code} · ${s.name}`,helper:s.code}))]} placeholder="Search station code or location" onValueChange={value=>navigate(value||'*',date)}/></div>{tab==='daily'&&<label>Work date<input disabled={controlsDisabled} type="date" value={date} max={data.today} onChange={e=>{if(e.target.value)navigate(station,e.target.value);}}/></label>}<label>Search vehicle / associate<input placeholder="Station, number, model, name or rider ID" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <details className="da-filter-panel"><summary>Filters{sourceFilter||modelFilter||assignmentFilter||includeVendor?' · applied':''}</summary><div className="da-filter-options"><label>Vehicle source<select value={sourceFilter} onChange={e=>setSourceFilter(e.target.value)}><option value="">All sources</option>{[...new Map(data.vehicles.map(v=>[v.sourceCode,v.sourceName])).entries()].filter(([code])=>includeVendor||!['VNV','VAN_VENDOR','VENDOR'].includes(code.toUpperCase())).map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label>Model<select value={modelFilter} onChange={e=>setModelFilter(e.target.value)}><option value="">All models</option>{[...new Set(data.vehicles.map(v=>v.model).filter(Boolean))].sort().map(m=><option key={m} value={m!}>{m}</option>)}</select></label>{tab==='daily'&&<label>Assignment<select value={assignmentFilter} onChange={e=>setAssignmentFilter(e.target.value)}><option value="">All assignments</option><option value="pending">Not saved</option><option value="confirmed">Saved</option><option value="missing">Associate not selected</option></select></label>}<label className="da-check"><input type="checkbox" checked={includeVendor} onChange={e=>{setIncludeVendor(e.target.checked);setSourceFilter('');}}/> Include van vendors</label><button type="button" onClick={()=>{setQuery('');setSourceFilter('');setModelFilter('');setAssignmentFilter('');setIncludeVendor(false);}}>Clear filters</button></div></details>
 <div className="da-summary"><strong>{vehicles.length} {date<data.today?'vehicles on this date':'active vehicles'} · {new Set(vehicles.map(v=>v.station_code)).size} locations</strong>{tab==='daily'&&<span>{vehicles.filter(v=>data.confirmations.some(c=>c.vehicle_id===v.id)).length} saved · {selected.length} selected</span>}<small>{date<data.today?(data.placementRecorded?'Recorded vehicle placement for this date':'Current vehicle list · historical placement unavailable'):'Locations with deployed vehicles'}</small></div>
 {tab==='daily'&&<div className="da-day-summary"><strong>{date}</strong><span>{vehicles.filter(v=>!data.confirmations.some(c=>c.vehicle_id===v.id)).length} mapping pending</span><span>{vehicles.filter(v=>data.assignments.some(a=>a.vehicle_id===v.id)).length} assigned</span><span>{vehicles.filter(v=>data.confirmations.some(c=>c.vehicle_id===v.id)&&!data.assignments.some(a=>a.vehicle_id===v.id)).length} no-work / corrected days</span>{(data.unavailableVehicles?.length??0)>0&&<details><summary>{data.unavailableVehicles!.length} unavailable in Fleet · no mapping required</summary>{data.unavailableVehicles!.map(v=><div key={v.id}><strong>{vehicleName(v)}</strong><span>{v.model||'Model not recorded'} · {v.station_code}</span><span>{data.dayStatuses?.find(s=>s.key===v.status)?.label||v.status.replaceAll('_',' ')}</span></div>)}</details>}</div>}
 {data.warning&&<div className="da-message" role="status">{data.warning}</div>}
 {tab==='defaults'?<div className="da-explainer">Defaults prefill future daily confirmations; they do not rewrite saved days. {data.canPolicy&&<details><summary>Rider list settings</summary><label>Recent activity window (days)<input type="number" min={3} max={30} value={recentDays} onChange={e=>setRecentDays(Number(e.target.value))}/></label><button disabled={controlsDisabled} onClick={()=>save({action:'mapping.policy',recentDays})}>Save window</button><label>Pending alerts from<input type="date" value={alertFrom} max={data.today} onChange={e=>setAlertFrom(e.target.value)}/></label><small>Only recorded days are supported. Moving this date forward hides older pending alerts; saved assignments are retained.</small><button disabled={controlsDisabled} onClick={()=>save({action:'mapping.alert-policy',alertFrom})}>Save alert start</button></details>}</div>:<details className="da-explainer"><summary>Assignment guidance</summary><p>Choose from rider IDs active in the last {data.recentDays} days. Defaults prefill automatically; save the associates who actually used the vehicle on this date. One rider can belong to only one vehicle per day. ODCD names come from the registry; Fleet links their Amazon rider ID once in Masters. Saved days are never overwritten by a new default.</p></details>}
 {tab==='daily'&&<div className="da-bulk"><label className="da-check"><input type="checkbox" disabled={!data.canEdit||controlsDisabled||!vehicles.length} checked={allSelected} onChange={()=>{dirty.current=true;setDraft(p=>{const n={...p};vehicles.forEach(v=>n[v.id]={...n[v.id],selected:!allSelected});return n;});}}/> Select all shown</label><button className="da-primary" disabled={!data.canEdit||controlsDisabled||!selected.length} onClick={confirmSelected}><Save size={15}/>{busy?'Saving…':`Save selected${selected.length?` (${selected.length})`:''}`}</button><FleetExportButtons compact image={false} report={{title:'Vehicle DA daily assignments',subtitle:`${data.station==='*'?'All stations':data.station} · ${data.date} · Saved assignments`,fileName:`fleet-da-${data.station==='*'?'all':data.station}-${data.date}`,headers:['Vehicle','Model','Station','Date','Associate','Rider ID'],rows:data.assignments.filter(a=>vehicles.some(v=>v.id===a.vehicle_id)).map(a=>{const v=data.vehicles.find(v=>v.id===a.vehicle_id)!;return[v.vehicle_no,v.model,v.station_code,date,a.name,a.provider_employee_id];})}}/></div>}
 {tab==='daily'&&notReady.length>0&&<div className="da-selection-review" role="status"><span>{notReady.length} selected vehicle(s) need an associate or a no-work reason.</span><button type="button" disabled={controlsDisabled} onClick={()=>{setDraft(p=>{const n={...p};vehicles.forEach(v=>n[v.id]={...n[v.id],selected:!needsReview(v)});return n;});dirty.current=true;}}>Select ready vehicles</button></div>}
 <div className="da-rows">{vehicles.map(v=>{const row=draft[v.id]||{ids:[],selected:false,remarks:''},saved=data.assignments.filter(a=>a.vehicle_id===v.id),def=data.defaults.find(a=>a.vehicle_id===v.id),confirmation=data.confirmations.find(a=>a.vehicle_id===v.id),ids=tab==='daily'?row.ids:def?[def.provider_employee_id]:[];return <article key={v.id} className={`da-row ${tab==='daily'&&row.selected&&needsReview(v)?'da-row-review':''}`}>
 <div className="da-vehicle">{tab==='daily'&&<input type="checkbox" aria-label={`Select ${v.vehicle_no}`} disabled={!data.canEdit||controlsDisabled} checked={row.selected} onChange={e=>change(v.id,{selected:e.target.checked})}/>}<div><strong>{vehicleName(v)}</strong><small>{v.model||'Model not recorded'} · {v.station_code}{v.vehicle_no.startsWith('PENDING-')?' · Registration not added':''}</small><small>{v.sourceName} · Fleet: {v.status.replaceAll('_',' ')}</small></div></div>
 <div className="da-associate"><strong>{ids.length?ids.map(id=>data.options.find(o=>o.id===id)?.name||id).join(' + '):isODCD(v)&&v.da_name?v.da_name:'No associate selected'}</strong><small>{ids.join(' · ')||(isODCD(v)&&v.da_name?'Registry DA · Amazon ID needs one-time linking':'Choose the rider who used this vehicle')}</small><span className={`da-chip ${saved.length||confirmation?'confirmed':''}`}>{tab==='defaults'?'Default suggestion':saved.length?'Confirmed':confirmation?(confirmation.day_status_label?`${data.dayStatuses?.find(s=>s.key===confirmation.day_status)?.label||confirmation.day_status_label} · dated correction`:'No delivery work confirmed'):ids.length?'Default · confirm for this day':'Not confirmed'}</span>{ids.some(id=>!data.options.find(o=>o.id===id)?.lastSeen)&&ids.length>0?<small className="da-warning">Not in recent feed · verify before confirming</small>:null}</div>

 {confirmation?.remarks&&<small className="da-saved-note">{confirmation.remarks}</small>}
 <button disabled={controlsDisabled||(tab==='defaults'?!data.canDefaults:!data.canEdit)} onClick={()=>{if(tab==='defaults')setDraft(p=>({...p,[v.id]:{...p[v.id],ids:def?[def.provider_employee_id]:[]}}));setEditing(editing===v.id?null:v.id);setRiderSearch('');}}>{editing===v.id?'Close':tab==='defaults'?'Set default':'Change'}</button>
 {editing===v.id&&<div className="da-picker"><label><Search size={15}/> Search associate name / rider ID<input autoFocus value={riderSearch} onChange={e=>setRiderSearch(e.target.value)} placeholder="Search recent station IDs"/></label><div className="da-option-list">{options.map(o=><label key={o.id} className="da-option"><input type={tab==='defaults'?'radio':'checkbox'} name={`rider-${v.id}`} checked={tab==='defaults'?row.ids[0]===o.id:row.ids.includes(o.id)} onChange={()=>change(v.id,{ids:tab==='defaults'?[o.id]:row.ids.includes(o.id)?row.ids.filter(id=>id!==o.id):[...row.ids,o.id],selected:true,dayStatus:''})}/><span><strong>{o.name}</strong><small>{o.id} · {o.lastSeen?`Seen ${o.lastSeen}`:'Saved identity'}</small></span></label>)}{!options.length&&<p>No recent rider IDs found. Refresh after the Amazon daily import.</p>}</div>
 {tab==='defaults'?<div className="da-bulk"><button disabled={controlsDisabled||row.ids.length!==1} onClick={()=>save({action:'mapping.default',vehicleId:v.id,providerId:row.ids[0],expectedUpdatedAt:def?.updated_at??null})}>Save default</button>{def&&<button disabled={controlsDisabled} onClick={()=>save({action:'mapping.default',vehicleId:v.id,providerId:null,expectedUpdatedAt:def.updated_at})}>Remove default</button>}</div>:<><label>Vehicle was unavailable on {date}<select value={row.dayStatus||''} onChange={e=>change(v.id,{dayStatus:e.target.value,ids:e.target.value?[]:row.ids,selected:true})}><option value="">No dated status correction</option>{data.dayStatuses?.map(s=><option key={s.key} value={s.key}>{s.label}</option>)}</select></label><small>Use when Fleet was not updated for this date. A reason is required; current vehicle status stays unchanged.</small><button type="button" onClick={()=>change(v.id,{ids:[],selected:true,dayStatus:''})}>No delivery work / clear selection</button><label>Reason / note {saved.length||!row.ids.length?'(required for correction / clearing)':''}<input value={row.remarks} maxLength={1000} onChange={e=>change(v.id,{remarks:e.target.value,selected:true})} placeholder="Replacement, leave, handover or correction"/></label><small>Selection saved only when you press Save selected.</small></>}
 </div>}
 </article>;})}{!vehicles.length&&<p className="da-empty">No active vehicles match your locations and filters.</p>}</div>
 {!data.canEdit&&<p>Read-only access. Contact your Fleet or Operations administrator to update mappings.</p>}
 </>}
 </section>;
}
