'use client';
import {useEffect,useState} from 'react';
import {SearchableSelect} from './searchable-select';
import {riderAvailableAt,type MappingData} from '@/lib/fleet/da-mapping';

/** The existing default-ID master is the single source for registry and daily mapping. */
export function FleetODCDDALink({vehicleId,station}:{vehicleId:string;station:string}){
 const [data,setData]=useState<MappingData|null>(null),[id,setId]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');fetch(`/api/fleet/da-mapping?registry=1&station=${encodeURIComponent(station)}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load station DA IDs.');setData(d);setId(d.defaults.find((v:{vehicle_id:string})=>v.vehicle_id===vehicleId)?.provider_employee_id||'');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[vehicleId,station]);
 const current=data?.defaults.find(v=>v.vehicle_id===vehicleId),options=data?.options.filter(o=>riderAvailableAt(o,station))??[],selected=options.find(o=>o.id===id);
 async function save(){if(!data)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/fleet/da-mapping',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'mapping.default',station,date:data.date,vehicleId,providerId:id||null,expectedUpdatedAt:current?.updated_at??null})});const result=await r.json();if(!r.ok)throw Error(result.error||'Unable to save DA ID.');const reload=await fetch(`/api/fleet/da-mapping?registry=1&station=${encodeURIComponent(station)}`,{cache:'no-store'});if(!reload.ok)throw Error('DA ID saved. Reopen this vehicle to refresh the linked record.');setData(await reload.json());setNotice('DA ID saved. Future daily mappings use this ID; saved days stay unchanged.');window.dispatchEvent(new Event('fleet-mapping-saved'));}catch(e){setError(e instanceof Error?e.message:'Unable to save DA ID.');}finally{setBusy(false);}}
 return <div className="fc-odcd-link"><strong>ODCD delivery associate</strong><small>Link the Amazon DA ID for {station}. Names are shown from the shipment feed.</small><div className="fc-placement-grid"><div><span>DA ID</span><SearchableSelect name="odcd-da-id" value={id} disabled={busy||!data?.canDefaults} options={options.map(o=>({value:o.id,label:o.id,helper:o.name}))} placeholder={data?'Search station DA ID or name':'Loading station DA IDs…'} onValueChange={value=>setId(value||'')}/></div><label><span>DA name · linked ID</span><input readOnly value={selected?.name||''} placeholder="Select a DA ID"/></label></div>{data?.canDefaults&&<button type="button" className="fc-button secondary" disabled={busy||id===(current?.provider_employee_id||'')} onClick={save}>{busy?'Saving…':'Save DA ID'}</button>}{data&&!data.canDefaults&&<small>Fleet Masters edit permission is required to change the linked ID.</small>}{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</div>;
}
