"use client";
import { type FormEvent } from "react";
import { normalizeFleetOperatingPolicy, type FleetOperatingPolicy } from "@/lib/fleet/operating-policy";

export function FleetOperatingPolicyEditor({value,canEdit,busy,onSave}:{value?:FleetOperatingPolicy;canEdit:boolean;busy:boolean;onSave:(value:FleetOperatingPolicy)=>Promise<unknown>}) {
  const policy=normalizeFleetOperatingPolicy(value);
  const gps=policy.gps!;
  async function submit(event:FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form=new FormData(event.currentTarget);
    const targets:Record<string,number>={};
    for(const line of String(form.get("stationVehicleTargets")||"").split("\n").filter(v=>v.trim())) {const [code,count]=line.split("=").map(v=>v.trim());targets[code.toUpperCase()]=Number(count);}
    await onSave({stationVehicleTargets:targets,gps:{afterHoursStart:String(form.get("afterHoursStart")),afterHoursEnd:String(form.get("afterHoursEnd")),minimumStopMinutes:Number(form.get("minimumStopMinutes")),exceptionMinSpeedKph:Number(form.get("exceptionMinSpeedKph"))},availabilityTargetPercent:Number(form.get("availabilityTargetPercent")),serviceWorkTypes:String(form.get("serviceWorkTypes")||"").split("\n").map(v=>v.trim()).filter(Boolean)});
  }
  return <article className="fc-panel fc-settings-card"><div className="fc-panel-head"><div><span className="fc-eyebrow">Operating controls</span><h2>Availability, GPS & service</h2><p>Shared controls for Fleet. Saved GPS reports retain the rules used at capture; refreshing a day recalculates it under the current rules.</p></div></div><form className="fc-settings-form fc-operating-policy-form" onSubmit={submit} key={JSON.stringify(policy)}><fieldset disabled={!canEdit||busy} style={{border:0,padding:0,margin:0,display:"grid",gap:16}}><label><span>Availability target (%)</span><input name="availabilityTargetPercent" type="number" min="1" max="100" step="0.1" required defaultValue={policy.availabilityTargetPercent}/></label><label><span>Service work categories · one per line</span><textarea name="serviceWorkTypes" rows={7} required defaultValue={policy.serviceWorkTypes.join("\n")}/><small>First category is the default. Add, rename or remove choices here.</small></label><label><span>Station vehicle targets · CODE = count</span><textarea name="stationVehicleTargets" rows={4} defaultValue={Object.entries(policy.stationVehicleTargets||{}).map(([code,n])=>`${code} = ${n}`).join("\n")}/><small>Minimum operational, deployed vehicles. Leave blank for stations without a target. Used by Capacity & cost in Reports.</small></label><label><span>After-hours starts · IST</span><input name="afterHoursStart" type="time" required defaultValue={gps.afterHoursStart}/></label><label><span>After-hours ends · IST</span><input name="afterHoursEnd" type="time" required defaultValue={gps.afterHoursEnd}/></label><label><span>Count stops from (minutes)</span><input name="minimumStopMinutes" type="number" min="1" max="120" required defaultValue={gps.minimumStopMinutes}/></label><label><span>Flag after-hours speeds above (km/h)</span><input name="exceptionMinSpeedKph" type="number" min="0" max="60" step="0.1" required defaultValue={gps.exceptionMinSpeedKph}/><small>0 flags any recorded movement. GPS gaps never count as confirmed travel.</small></label>{canEdit?<button className="fc-button primary" type="submit">{busy?"Saving…":"Save operating controls"}</button>:null}</fieldset></form></article>;
}
