"use client";

import { AlertTriangle, CalendarClock, CircleDollarSign, ExternalLink, History, Plus, Search, Share2, Truck, Wrench } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { FleetMultiSelect } from "@/components/fleet-multi-select";
import { FleetExportButtons } from "@/components/fleet-export-buttons";
import type { FleetReportTable } from "@/lib/fleet/report-export";
import type { FleetControlData, FleetControlVehicle, FleetServiceRecord } from "@/lib/fleet-control";

type View = "schedule" | "history" | "non_operational" | "daily_status" | "bills";
type StationStatus = { station: string; ownTotal: number; ownOperational: number; ownNonOperational: number; partnerTotal: number; partnerOperational: number; partnerNonOperational: number; totalNonOperational: number; adHocVans: number };

const money = (value: number) => `₹${value.toLocaleString("en-IN", { maximumFractionDigits: 0 })}`;
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const ownershipLabel = (value: FleetControlVehicle["ownershipType"]) => value === "odcd" ? "ODCD" : value === "rented" ? "Rented" : "Own";
const showDate = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(new Date(`${value.slice(0, 10)}T12:00:00+05:30`)) : "—";
const daysFrom = (date: string | null, today: string) => date ? Math.round((Date.parse(`${date.slice(0, 10)}T00:00:00Z`) - Date.parse(`${today}T00:00:00Z`)) / 86_400_000) : null;
const approvedAdHoc = (status: string, source: string) => source === "Cashbook" || ["approved", "final_approved", "processing", "processed", "paid"].includes(status);
const closedStatus = (status: string) => ["sold", "disposed", "returned"].includes(status);

function DueState({ date, today }: { date: string | null; today: string }) { const days = daysFrom(date, today); if (days == null) return <span className="fc-due-pill neutral">Not planned</span>; if (days < 0) return <span className="fc-due-pill bad">Overdue {Math.abs(days)}d</span>; if (days === 0) return <span className="fc-due-pill bad">Due today</span>; if (days <= 14) return <span className="fc-due-pill warn">Due in {days}d</span>; return <span className="fc-due-pill good">Planned · {days}d</span>; }

export function FleetServiceWorkspace({ data, vehicles, onChanged }: { data: FleetControlData; vehicles: FleetControlVehicle[]; onChanged: () => void }) {
  const [view, setView] = useState<View>("schedule");
  const [search, setSearch] = useState("");
  const [stations, setStations] = useState<string[]>([]);
  const [statuses, setStatuses] = useState<string[]>([]);
  const [ownership, setOwnership] = useState<string[]>([]);
  const [reportDate, setReportDate] = useState(data.today);
  const [selected, setSelected] = useState<FleetControlVehicle | null>(null);
  const [statusVehicle, setStatusVehicle] = useState<FleetControlVehicle | null>(null);
  const [recording, setRecording] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const option = (values: string[]) => [...new Set(values.filter(Boolean))].sort().map((value) => ({ value, label: pretty(value) }));
  const latestByVehicle = useMemo(() => { const map = new Map<string, FleetServiceRecord>(); data.serviceHistory.filter((row) => row.status !== "scheduled").forEach((row) => { if (!map.has(row.vehicleId)) map.set(row.vehicleId, row); }); return map; }, [data.serviceHistory]);
  const plannedByVehicle = useMemo(() => { const map = new Map<string, FleetServiceRecord>(); data.serviceHistory.filter((row) => row.status === "scheduled").sort((a, b) => a.serviceDate.localeCompare(b.serviceDate)).forEach((row) => map.set(row.vehicleId, row)); return map; }, [data.serviceHistory]);
  const matchesVehicle = (vehicle: FleetControlVehicle) => (!stations.length || stations.includes(vehicle.stationCode)) && (!ownership.length || ownership.includes(vehicle.ownershipType)) && (!search || `${vehicle.vehicleNo} ${vehicle.model} ${vehicle.stationCode} ${vehicle.statusComment}`.toLowerCase().includes(search.toLowerCase()));
  const plans = useMemo(() => vehicles.map((vehicle) => { const planned = plannedByVehicle.get(vehicle.id); const latest = latestByVehicle.get(vehicle.id); return { vehicle, planned, latest, dueDate: planned?.serviceDate ?? latest?.nextServiceDate ?? vehicle.nextServiceDate }; }).filter(({ vehicle, dueDate }) => { const days = daysFrom(dueDate, data.today); const state = days == null ? "not_planned" : days < 0 ? "overdue" : days <= 14 ? "due_soon" : "planned"; return matchesVehicle(vehicle) && (!statuses.length || statuses.includes(state)); }).sort((a, b) => (daysFrom(a.dueDate, data.today) ?? 9999) - (daysFrom(b.dueDate, data.today) ?? 9999)), [vehicles, plannedByVehicle, latestByVehicle, stations, ownership, statuses, search, data.today]);
  const history = data.serviceHistory.filter((row) => row.status !== "scheduled" && (!stations.length || stations.includes(row.stationCode)) && (!statuses.length || statuses.includes(row.status)) && (!search || `${row.vehicleNo} ${row.serviceType} ${row.vendorName} ${row.stationCode}`.toLowerCase().includes(search.toLowerCase())));
  const bills = data.payments.filter((row) => (!stations.length || stations.includes(row.stationCode)) && (!statuses.length || statuses.includes(row.statusLabel)) && (!search || `${row.requestNo} ${row.head} ${row.stationCode} ${row.remarks}`.toLowerCase().includes(search.toLowerCase())));
  const exceptions = vehicles.filter((vehicle) => !closedStatus(vehicle.status) && vehicle.status !== "active" && matchesVehicle(vehicle) && (!statuses.length || statuses.includes(vehicle.status)));
  const report = useMemo(() => {
    const relevantVehicles = vehicles.filter((vehicle) => !closedStatus(vehicle.status) && matchesVehicle(vehicle));
    const approvedVans = data.adHocRows.filter((row) => row.date === reportDate && row.requestType === "Van" && approvedAdHoc(row.approvalStatus, row.source));
    const codes = [...new Set([...relevantVehicles.map((row) => row.stationCode), ...approvedVans.map((row) => row.stationCode)])].sort();
    return codes.map((station): StationStatus => { const rows = relevantVehicles.filter((row) => row.stationCode === station); const own = rows.filter((row) => row.ownershipType === "own"); const partner = rows.filter((row) => row.ownershipType !== "own"); const ownOperational = own.filter((row) => row.status === "active").length; const partnerOperational = partner.filter((row) => row.status === "active").length; return { station, ownTotal: own.length, ownOperational, ownNonOperational: own.length - ownOperational, partnerTotal: partner.length, partnerOperational, partnerNonOperational: partner.length - partnerOperational, totalNonOperational: rows.filter((row) => row.status !== "active").length, adHocVans: approvedVans.filter((row) => row.stationCode === station).length }; }).filter((row) => !statuses.length || (statuses.includes("affected") ? row.totalNonOperational > 0 || row.adHocVans > 0 : true));
  }, [vehicles, data.adHocRows, reportDate, stations, ownership, statuses, search]);
  const due = vehicles.filter((vehicle) => { const date = plannedByVehicle.get(vehicle.id)?.serviceDate ?? latestByVehicle.get(vehicle.id)?.nextServiceDate ?? vehicle.nextServiceDate; const days = daysFrom(date, data.today); return days != null && days <= 14; }).length;
  const unplanned = vehicles.filter((vehicle) => !plannedByVehicle.get(vehicle.id) && !latestByVehicle.get(vehicle.id)?.nextServiceDate && !vehicle.nextServiceDate).length;

  async function act(action: string, payload: Record<string, unknown>) { setSaving(true); setMessage(""); try { const response = await fetch("/api/fleet-control", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...payload }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Service update failed."); setMessage(result.message || "Service updated."); setSelected(null); setRecording(false); onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "Service update failed."); } finally { setSaving(false); } }
  async function savePlan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); await act("service.schedule", { vehicleId: selected.id, serviceDate: form.get("serviceDate"), serviceType: form.get("serviceType"), nextServiceOdometerKm: form.get("nextServiceOdometerKm"), description: form.get("description") }); }
  async function saveRecord(event: FormEvent<HTMLFormElement>) { event.preventDefault(); await act("service.create", Object.fromEntries(new FormData(event.currentTarget).entries())); }
  async function saveStatus(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!statusVehicle) return; setSaving(true); setMessage(""); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); try { const response = await fetch("/api/fleet/vehicles", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vehicle_no: statusVehicle.vehicleNo, ...values, status_reason: values.status_comment }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Vehicle status could not be updated."); setStatusVehicle(null); setMessage(`${statusVehicle.vehicleNo} availability updated.`); onChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "Vehicle status could not be updated."); } finally { setSaving(false); } }
  const reportRows = () => [["Station","Own total","Own operational","Own non-operational","ODCD/Rented total","ODCD/Rented operational","ODCD/Rented non-operational","Total non-operational","Approved ad-hoc vans"], ...report.map((row) => [row.station,row.ownTotal,row.ownOperational,row.ownNonOperational,row.partnerTotal,row.partnerOperational,row.partnerNonOperational,row.totalNonOperational,row.adHocVans])];
  const exportReport: FleetReportTable = view === "schedule"
    ? { title: "Vehicle service schedule", subtitle: `As at ${data.today}`, fileName: `fleet-service-plan-${data.today}`, headers: ["Vehicle","Station","Model","Next due","Days to due","Last service"], rows: plans.map(({ vehicle, dueDate, latest }) => [vehicle.vehicleNo,vehicle.stationCode,vehicle.model,dueDate,daysFrom(dueDate,data.today),latest?.serviceDate]) }
    : view === "history"
      ? { title: "Vehicle service history", subtitle: "Active filters applied", fileName: `fleet-service-history-${data.today}`, headers: ["Date","Vehicle","Station","Type","Workshop","Amount","Status","Next due"], rows: history.map((row) => [row.serviceDate,row.vehicleNo,row.stationCode,row.serviceType,row.vendorName,row.amount,row.status,row.nextServiceDate]) }
      : view === "non_operational"
        ? { title: "Non-operational vehicle report", subtitle: `As at ${data.today}`, fileName: `fleet-non-operational-${data.today}`, headers: ["Vehicle","Station","Source","Model","Status","Non-operational from","Expected date","Issue / comment"], rows: exceptions.map((row) => [row.vehicleNo,row.stationCode,ownershipLabel(row.ownershipType),row.model,row.statusLabel,row.nonOperationalSince,row.expectedOperationalDate,row.statusComment]) }
        : view === "daily_status"
          ? { title: "Daily station fleet status", subtitle: reportDate, fileName: `fleet-daily-status-${reportDate}`, headers: reportRows()[0].map(String), rows: reportRows().slice(1) }
          : { title: "Vehicle service payment bills", subtitle: "Active filters applied", fileName: `fleet-service-bills-${data.today}`, headers: ["Request","Station","Payment head","Amount","Status","Work date","Remarks"], rows: bills.map((row) => [row.requestNo,row.stationCode,row.head,row.amount,row.statusLabel,row.workDate,row.remarks]) };
  async function shareReport() { const body = [`DropX Fleet status · ${showDate(reportDate)}`, ...report.map((row) => `${row.station}: ${row.totalNonOperational} non-operational · ${row.adHocVans} approved ad-hoc van${row.adHocVans === 1 ? "" : "s"}`)].join("\n"); try { if (navigator.share) await navigator.share({ title: `DropX Fleet status · ${reportDate}`, text: body }); else { await navigator.clipboard.writeText(body); setMessage("Daily status copied. Paste it into WhatsApp or email."); } } catch { /* User dismissed native share. */ } }
  function changeView(next: View) { setView(next); setStatuses([]); setOwnership([]); }

  return <section className="fc-section fc-service-workspace">
    <div className="fc-section-head"><div><span className="fc-eyebrow">Maintenance &amp; availability lifecycle</span><h1>Service</h1><p>Plan service, manage vehicle downtime and publish the daily fleet status from one workspace.</p></div>{data.capabilities.canManageFleet ? <button className="fc-button primary" onClick={() => setRecording(true)} type="button"><Plus size={17} /> Record work</button> : null}</div>
    <div className="fc-service-command"><nav className="fc-view-switch compact"><button className={view === "schedule" ? "active" : ""} onClick={() => changeView("schedule")} type="button"><CalendarClock size={15} /> Schedule</button><button className={view === "history" ? "active" : ""} onClick={() => changeView("history")} type="button"><History size={15} /> Work history</button><button className={view === "non_operational" ? "active" : ""} onClick={() => changeView("non_operational")} type="button"><AlertTriangle size={15} /> Non-operational</button><button className={view === "daily_status" ? "active" : ""} onClick={() => changeView("daily_status")} type="button"><Truck size={15} /> Daily status</button><button className={view === "bills" ? "active" : ""} onClick={() => changeView("bills")} type="button"><CircleDollarSign size={15} /> Bills</button></nav><div className="fc-toolbar-actions">{view === "daily_status" ? <button className="fc-download-link" onClick={shareReport} type="button"><Share2 size={14} /> Share</button> : null}<FleetExportButtons compact report={exportReport} /></div></div>
    {message ? <div className="fc-inline-message notice">{message}</div> : null}
    <div className="fc-scope-filters fc-service-filters"><label className="fc-filter-search"><span>Search</span><div><Search size={14} /><input onChange={(event) => setSearch(event.target.value)} placeholder="Vehicle, workshop, station or issue" value={search} /></div></label><FleetMultiSelect allLabel="All stations" label="Station" onChange={setStations} options={option(data.stationOptions.map((row) => row.code))} values={stations} />{["schedule","non_operational","daily_status"].includes(view) ? <FleetMultiSelect allLabel="All vehicle types" label="Vehicle type" onChange={setOwnership} options={[{ value: "own", label: "Own" },{ value: "odcd", label: "ODCD" },{ value: "rented", label: "Rented" }]} values={ownership} /> : null}<FleetMultiSelect allLabel="All statuses" label="Status" onChange={setStatuses} options={view === "schedule" ? [{ value: "overdue", label: "Overdue" },{ value: "due_soon", label: "Due in 14 days" },{ value: "planned", label: "Planned" },{ value: "not_planned", label: "Not planned" }] : view === "non_operational" ? option(exceptions.map((row) => row.status)) : view === "daily_status" ? [{ value: "affected", label: "Affected stations only" }] : option(view === "history" ? data.serviceHistory.filter((row) => row.status !== "scheduled").map((row) => row.status) : data.payments.map((row) => row.statusLabel))} values={statuses} />{view === "daily_status" ? <label className="fc-report-date"><span>Report date</span><input max={data.today} onChange={(event) => setReportDate(event.target.value)} type="date" value={reportDate} /></label> : null}</div>
    <div className="fc-segment-cards"><article><small>Fleet vehicles</small><strong>{vehicles.filter((row) => !closedStatus(row.status)).length}</strong></article><article><small>Due / overdue</small><strong>{due}</strong></article><article><small>Non-operational</small><strong>{vehicles.filter((row) => !closedStatus(row.status) && row.status !== "active").length}</strong></article><article><small>Recorded spend</small><strong>{money(data.serviceHistory.filter((row) => row.status !== "scheduled").reduce((sum, row) => sum + row.amount, 0))}</strong></article></div>
    {view === "schedule" ? <div className="fc-table-panel"><div className="fc-table-toolbar"><span>{plans.length} vehicle service plans</span><small>{unplanned} vehicles have no next service plan.</small></div><div className="fc-table-scroll"><table><thead><tr><th>Vehicle</th><th>Source</th><th>Last work</th><th>Next service</th><th>Due state</th><th>Odometer target</th><th>Action</th></tr></thead><tbody>{plans.map(({ vehicle, latest, planned, dueDate }) => <tr key={vehicle.id}><td><strong>{vehicle.vehicleNo}</strong><small className="fc-cell-note">{vehicle.stationCode} · {vehicle.model}</small></td><td>{ownershipLabel(vehicle.ownershipType)}</td><td>{latest ? <><strong>{latest.serviceType}</strong><small className="fc-cell-note">{showDate(latest.serviceDate)}</small></> : "No history"}</td><td><strong>{showDate(dueDate)}</strong><small className="fc-cell-note">{planned?.serviceType ?? (dueDate ? "Next service" : "Date not set")}</small></td><td><DueState date={dueDate} today={data.today} /></td><td>{(planned?.nextServiceOdometerKm ?? latest?.nextServiceOdometerKm ?? vehicle.nextServiceOdometerKm)?.toLocaleString("en-IN") ?? "—"}</td><td>{data.capabilities.canManageFleet ? <button className="fc-row-action" onClick={() => setSelected(vehicle)} type="button">{dueDate ? "Update plan" : "Plan service"}</button> : "—"}</td></tr>)}</tbody></table></div></div> : null}
    {view === "history" ? <div className="fc-table-panel"><div className="fc-table-toolbar"><span>{history.length} completed or active work records</span></div><div className="fc-table-scroll"><table><thead><tr><th>Date</th><th>Vehicle</th><th>Work type</th><th>Workshop</th><th>Amount</th><th>Status</th><th>Next due</th><th>Bill</th></tr></thead><tbody>{history.map((row) => <tr key={row.id}><td>{showDate(row.serviceDate)}</td><td><strong>{row.vehicleNo}</strong><small className="fc-cell-note">{row.stationCode}</small></td><td><strong>{row.serviceType}</strong><small className="fc-cell-note">{row.description || "No note"}</small></td><td>{row.vendorName || "—"}</td><td><strong>{money(row.amount)}</strong></td><td><span className={`fc-status ${row.status === "completed" ? "good" : "warn"}`}><i />{pretty(row.status)}</span></td><td>{showDate(row.nextServiceDate)}</td><td>{row.invoiceUrl ? <a className="fc-link" href={row.invoiceUrl} rel="noreferrer" target="_blank">View <ExternalLink size={12} /></a> : "—"}</td></tr>)}</tbody></table></div>{!history.length ? <div className="fc-empty"><Wrench size={30} /><strong>No matching work history</strong><p>Record a service, repair or maintenance event to begin the vehicle timeline.</p></div> : null}</div> : null}
    {view === "non_operational" ? <div className="fc-table-panel"><div className="fc-table-toolbar"><span>{exceptions.length} vehicles needing an availability update</span><small>Keep the issue, start date and expected return current.</small></div><div className="fc-table-scroll"><table><thead><tr><th>Vehicle</th><th>Station</th><th>Source</th><th>Status</th><th>Non-operational from</th><th>Expected return</th><th>Issue / comment</th><th>Action</th></tr></thead><tbody>{exceptions.map((vehicle) => <tr key={vehicle.id}><td><strong>{vehicle.vehicleNo}</strong><small className="fc-cell-note">{vehicle.model}</small></td><td>{vehicle.stationCode}</td><td>{ownershipLabel(vehicle.ownershipType)}</td><td><span className="fc-status bad"><i />{vehicle.statusLabel}</span></td><td>{showDate(vehicle.nonOperationalSince)}</td><td>{showDate(vehicle.expectedOperationalDate)}</td><td>{vehicle.statusComment || "Update required"}</td><td>{data.capabilities.canManageFleet ? <button className="fc-row-action" onClick={() => setStatusVehicle(vehicle)} type="button">Update</button> : "—"}</td></tr>)}</tbody></table></div>{!exceptions.length ? <div className="fc-empty"><Truck size={30} /><strong>All current vehicles are operational</strong><p>No service or breakdown exception is open.</p></div> : null}</div> : null}
    {view === "daily_status" ? <div className="fc-table-panel fc-status-report"><div className="fc-table-toolbar"><span>Station fleet status · {showDate(reportDate)}</span><small>Ad-hoc count includes finally approved or settled van requests only.</small></div><div className="fc-table-scroll"><table><thead><tr><th rowSpan={2}>Station</th><th colSpan={3}>DropX Own Vehicles</th><th colSpan={3}>ODCD / Rented</th><th rowSpan={2}>Total non-operational</th><th rowSpan={2}>Approved ad-hoc vans</th></tr><tr><th>Total</th><th>Operational</th><th>Non-operational</th><th>Total</th><th>Operational</th><th>Non-operational</th></tr></thead><tbody>{report.map((row) => <tr key={row.station}><td><strong>{row.station}</strong></td><td>{row.ownTotal}</td><td>{row.ownOperational}</td><td>{row.ownNonOperational}</td><td>{row.partnerTotal}</td><td>{row.partnerOperational}</td><td>{row.partnerNonOperational}</td><td className={row.totalNonOperational ? "fc-date-risk" : ""}><strong>{row.totalNonOperational}</strong></td><td><strong>{row.adHocVans}</strong></td></tr>)}{report.length ? <tr className="fc-report-total"><td>Total</td>{(["ownTotal","ownOperational","ownNonOperational","partnerTotal","partnerOperational","partnerNonOperational","totalNonOperational","adHocVans"] as const).map((key) => <td key={key}>{report.reduce((sum, row) => sum + row[key], 0)}</td>)}</tr> : null}</tbody></table></div></div> : null}
    {view === "bills" ? <div className="fc-table-panel"><div className="fc-table-toolbar"><span>{bills.length} vehicle payment records</span><small>Approval remains in Vehicle Payments.</small></div><div className="fc-table-scroll"><table><thead><tr><th>Request</th><th>Station</th><th>Payment head</th><th>Work date</th><th>Amount</th><th>Status</th><th>Purpose</th></tr></thead><tbody>{bills.map((row) => <tr key={row.id}><td><strong>{row.requestNo}</strong><small className="fc-cell-note">{row.requestedBy}</small></td><td>{row.stationCode}</td><td>{row.head}</td><td>{showDate(row.workDate)}</td><td><strong>{money(row.amount)}</strong></td><td><span className={`fc-status ${row.statusLabel === "Approved" || row.statusLabel === "Paid" ? "good" : row.statusLabel === "Rejected" ? "bad" : "warn"}`}><i />{row.statusLabel}</span></td><td>{row.remarks}</td></tr>)}</tbody></table></div></div> : null}

    {statusVehicle ? <div className="fc-modal-backdrop"><section className="fc-modal"><button aria-label="Close" className="fc-modal-close" onClick={() => setStatusVehicle(null)} type="button">×</button><div className="fc-modal-title"><span className="fc-vehicle-big"><AlertTriangle size={22} /></span><div><small>{statusVehicle.stationCode} · {ownershipLabel(statusVehicle.ownershipType)}</small><h2>Update {statusVehicle.vehicleNo}</h2><p>Maintain the operational timeline used by the daily report.</p></div></div><form className="fc-add-form" onSubmit={saveStatus}><label><span>Operational status</span><select defaultValue={statusVehicle.status} name="status"><option value="active">Active / operational</option><option value="under_service">Under service</option><option value="breakdown">Breakdown</option><option value="inactive">Inactive</option></select></label><label><span>Non-operational from</span><input defaultValue={statusVehicle.nonOperationalSince ?? data.today} max={data.today} name="non_operational_since" type="date" /></label><label><span>Expected operational date</span><input defaultValue={statusVehicle.expectedOperationalDate ?? ""} min={data.today} name="expected_operational_date" type="date" /></label><label className="full"><span>Issue and latest comment</span><textarea defaultValue={statusVehicle.statusComment} name="status_comment" placeholder="Engine work, claim waiting for parts, expected workshop update…" required rows={3} /></label><div className="fc-form-actions"><button className="fc-button secondary" onClick={() => setStatusVehicle(null)} type="button">Cancel</button><button className="fc-button primary" disabled={saving} type="submit">{saving ? "Saving…" : "Save availability"}</button></div></form></section></div> : null}
    {selected ? <div className="fc-modal-backdrop"><section className="fc-modal"><button aria-label="Close" className="fc-modal-close" onClick={() => setSelected(null)} type="button">×</button><div className="fc-modal-title"><span className="fc-vehicle-big"><CalendarClock size={22} /></span><div><small>{selected.stationCode} · {selected.model}</small><h2>Plan {selected.vehicleNo}</h2><p>Set or revise the next scheduled service. The prior plan remains in history.</p></div></div><form className="fc-add-form" onSubmit={savePlan}><label><span>Next service date</span><input defaultValue={plannedByVehicle.get(selected.id)?.serviceDate ?? latestByVehicle.get(selected.id)?.nextServiceDate ?? ""} min={data.today} name="serviceDate" required type="date" /></label><label><span>Service type</span><select defaultValue={plannedByVehicle.get(selected.id)?.serviceType ?? "Regular Service"} name="serviceType"><option>Regular Service</option><option>Oil Change</option><option>Preventive Maintenance</option><option>Inspection</option><option>Other</option></select></label><label><span>Odometer target</span><input defaultValue={plannedByVehicle.get(selected.id)?.nextServiceOdometerKm ?? latestByVehicle.get(selected.id)?.nextServiceOdometerKm ?? ""} min="0" name="nextServiceOdometerKm" type="number" /></label><label className="full"><span>Planning note</span><input defaultValue={plannedByVehicle.get(selected.id)?.description} name="description" placeholder="Workshop booking, interval or service scope" /></label><div className="fc-form-actions"><button className="fc-button secondary" onClick={() => setSelected(null)} type="button">Cancel</button><button className="fc-button primary" disabled={saving} type="submit">{saving ? "Saving…" : "Save plan"}</button></div></form></section></div> : null}
    {recording ? <div className="fc-modal-backdrop"><section className="fc-modal wide"><button aria-label="Close" className="fc-modal-close" onClick={() => setRecording(false)} type="button">×</button><div className="fc-modal-title"><span className="fc-vehicle-big"><Wrench size={22} /></span><div><small>Vehicle work record</small><h2>Record service or maintenance</h2><p>Classify the work and link its bill, cost and next due point.</p></div></div><form className="fc-add-form" onSubmit={saveRecord}><label><span>Vehicle</span><select name="vehicleId" required><option value="">Select vehicle</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.vehicleNo} · {vehicle.stationCode}</option>)}</select></label><label><span>Work date</span><input defaultValue={data.today} name="serviceDate" required type="date" /></label><label><span>Work category</span><select name="serviceType" required><option>Regular Service</option><option>Preventive Maintenance</option><option>Repair</option><option>Breakdown Repair</option><option>Tyre Work</option><option>Oil Change</option><option>Electrical / Battery</option><option>Body / Accident Repair</option><option>Other</option></select></label><label><span>Status</span><select name="status"><option value="completed">Completed</option><option value="in_progress">In progress</option></select></label><label><span>Odometer km</span><input min="0" name="odometerKm" type="number" /></label><label><span>Amount</span><input min="0" name="amount" step="0.01" type="number" /></label><label><span>Workshop / technician</span><input name="vendorName" /></label><label><span>Workshop contact</span><input name="vendorContact" /></label><label className="full"><span>Description</span><textarea name="description" rows={2} /></label><label className="full"><span>Bill / evidence link</span><input name="invoiceUrl" placeholder="https://" type="url" /></label><label><span>Next service date</span><input name="nextServiceDate" type="date" /></label><label><span>Next service odometer</span><input min="0" name="nextServiceOdometerKm" type="number" /></label><label><span>Downtime hours</span><input min="0" name="downtimeHours" step="0.5" type="number" /></label><div className="fc-form-actions"><button className="fc-button secondary" onClick={() => setRecording(false)} type="button">Cancel</button><button className="fc-button primary" disabled={saving} type="submit">{saving ? "Saving…" : "Save work record"}</button></div></form></section></div> : null}
  </section>;
}
