'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import type {FleetControlVehicle} from '@/lib/fleet-control';
type Rent={id:string;vehicle_id:string;monthly_rent:number;effective_from:string;effective_to:string|null;reason:string;updated_at:string};
type Identity={id:string;updated_at:string;[key:string]:string|number|null};
type Invoice={document_type:string;file_name:string;download_url:string|null};
const money=(v:number)=>`₹${Number(v).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const fields=[
 ['chassis_number','Chassis number','text'],['engine_number','Engine number','text'],['registered_owner','Registered owner','text'],
 ['model','Make / model','text'],['fuel_type','Fuel type','text'],['color','Colour','text'],['rc_location','Registration office','text'],
 ['manufacture_year','Manufacture year','number'],['registration_date','Registration date','date'],['payload_capacity_kg','Payload capacity (kg)','number'],
 ['purchase_date','Purchase date','date'],['purchase_value','Purchase value (₹)','number'],['invoice_number','Invoice number','text'],['supplier_name','Supplier / dealer','text'],
] as const;
export function FleetVehicleRentMaster({vehicles,today,canEdit,canManageDocuments=false}:{vehicles:FleetControlVehicle[];today:string;canEdit:boolean;canManageDocuments?:boolean}) {
 const router=useRouter(),dialog=useRef<HTMLDialogElement>(null);
 const [rates,setRates]=useState<Rent[]>([]),[identities,setIdentities]=useState<Identity[]>([]);
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[tab,setTab]=useState<'identity'|'rent'|'invoice'>('identity');
 const [saving,setSaving]=useState(false),[reload,setReload]=useState(0),[invoices,setInvoices]=useState<Invoice[]>([]),[docsLoading,setDocsLoading]=useState(false);
 const current=(id:string)=>rates.find(r=>r.vehicle_id===id&&r.effective_from<=today&&(!r.effective_to||r.effective_to>=today));
 const vehicle=vehicles.find(v=>v.id===selected),identity=identities.find(v=>v.id===selected);
 useEffect(()=>{if(selected)dialog.current?.showModal()},[selected]);
 useEffect(()=>{const c=new AbortController();setLoading(true);fetch('/api/fleet-control/vehicle-rent',{cache:'no-store',signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load vehicle master.');setRates(d.rates);setIdentities(d.vehicles??[]);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[reload]);
 useEffect(()=>{if(!vehicle||tab!=='invoice')return;const c=new AbortController();setInvoices([]);setDocsLoading(true);fetch(`/api/fleet/documents?vehicle_no=${encodeURIComponent(vehicle.vehicleNo)}`,{signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to load invoice.');setInvoices(d.documents??[])}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!c.signal.aborted)setDocsLoading(false)});return()=>c.abort()},[vehicle?.vehicleNo,tab,reload]);
 async function save(event:FormEvent<HTMLFormElement>,kind:'identity'|'rent'|'invoice') {
  event.preventDefault();if(!vehicle||saving)return;const form=new FormData(event.currentTarget);setSaving(true);setError('');setNotice('');
  try {
   let response:Response;
   if(kind==='invoice'){form.set('vehicle_no',vehicle.vehicleNo);form.set('document_type','VEHICLE_INVOICE');response=await fetch('/api/fleet/documents',{method:'POST',body:form})}
   else response=await fetch('/api/fleet-control/vehicle-rent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(kind==='identity'?{kind,vehicleId:vehicle.id,updated_at:identity?.updated_at,details:Object.fromEntries(form)}:{vehicleId:vehicle.id,monthlyRent:form.get('amount'),effectiveFrom:form.get('from'),reason:form.get('reason')})});
   const result=await response.json();if(!response.ok)throw Error(result.error||'Save failed.');
   setNotice(`${kind==='identity'?'Vehicle details':kind==='invoice'?'Invoice':'Rent revision'} saved for ${vehicle.vehicleNo}.`);setReload(n=>n+1);router.refresh();
  }catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setSaving(false)}
 }
 const rows=vehicles.filter(v=>`${v.vehicleNo} ${v.model} ${v.stationCode}`.toLowerCase().includes(search.toLowerCase()));
 return <article className="fc-panel fc-vehicle-rent-master">
 <div className="fc-panel-head"><div><span className="fc-eyebrow">Vehicle Master</span><h2>Vehicle identity, ownership &amp; cost</h2><p>Maintain permanent vehicle details, purchase evidence and effective-dated rent. Daily deployment and availability stay in Vehicles.</p></div><input aria-label="Search vehicle master" placeholder="Search vehicle or station…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {error&&!selected&&<div className="fc-rent-message error" role="alert">{error} <button onClick={()=>setReload(n=>n+1)}>Reload</button></div>}{notice&&!selected&&<p className="fc-rent-message" role="status">{notice}</p>}
 {loading&&!identities.length?<p className="fc-rent-message">Loading vehicle master…</p>:<div className="fc-table-wrap"><table className="fc-table"><thead><tr><th>Vehicle</th><th>Station / ownership</th><th>Master details</th><th>Purchase value</th><th>Monthly rent</th><th>Action</th></tr></thead><tbody>{rows.map(v=>{const d=identities.find(i=>i.id===v.id),rate=current(v.id);return <tr key={v.id}><td><strong>{v.vehicleNo}</strong><small>{d?.model||v.model}</small></td><td>{v.stationCode}<small>{d?.ownership_type||v.ownershipType} · {v.deploymentStatus==='deployed'?'Deployed':'Not deployed'}</small></td><td>{d?.chassis_number?<span>{d.chassis_number}</span>:<span className="fc-status warn">Chassis not added</span>}<small>{d?.invoice_number?`Invoice ${d.invoice_number}`:'Invoice details not added'}</small></td><td>{d?.purchase_value==null?'—':money(Number(d.purchase_value))}</td><td>{rate?money(rate.monthly_rent):<span className="fc-status warn">{(d?.ownership_type||v.ownershipType)==='odcd'?'Through DA payout':'Rent not set'}</span>}</td><td><button className="fc-button secondary" onClick={()=>{setSelected(v.id);setTab('identity');setError('');setNotice('')}}>{canEdit?'Manage vehicle master':'View details'}</button></td></tr>})}</tbody></table>{!rows.length&&<p className="fc-rent-message">No vehicles match this search.</p>}</div>}
 {vehicle&&<dialog ref={dialog} className="fc-rent-editor fc-identity-editor" onCancel={e=>{e.preventDefault();if(!saving)setSelected(null)}} aria-label={`Vehicle master for ${vehicle.vehicleNo}`}><div className="fc-panel-head"><div><span className="fc-eyebrow">Vehicle master</span><h3>{vehicle.vehicleNo} · {vehicle.stationCode}</h3></div><button type="button" className="fc-button secondary" disabled={saving} onClick={()=>setSelected(null)}>Close</button></div>
 <nav className="fc-master-tabs" aria-label="Vehicle master sections">{(['identity','rent','invoice'] as const).map(t=><button key={t} type="button" disabled={saving} className={tab===t?'active':''} onClick={()=>{setTab(t);setError('')}}>{t==='identity'?'Vehicle details':t==='rent'?'Rental & history':'Invoice evidence'}</button>)}</nav>
 {error&&<p className="fc-rent-message error" role="alert">{error}</p>}{notice&&<p className="fc-rent-message" role="status">{notice}</p>}
 {tab==='identity'&&identity&&<form key={`${identity.id}:${identity.updated_at}`} className="fc-add-form" onSubmit={e=>save(e,'identity')}><label><span>Ownership / source</span><select name="ownership_type" disabled={!canEdit} defaultValue={String(identity.ownership_type||vehicle.ownershipType)}><option value="own">Own vehicle</option><option value="rented">Rented vehicle</option><option value="odcd">ODCD / partner vehicle</option></select></label>{fields.map(([key,label,type])=><label key={key}><span>{label}</span><input name={key} type={type} readOnly={!canEdit} required={key==='model'||key==='fuel_type'} min={type==='number'?(key==='manufacture_year'?1950:0):undefined} max={key==='manufacture_year'?2100:undefined} step={type==='number'?(key==='manufacture_year'?1:0.01):undefined} maxLength={type==='text'?160:undefined} defaultValue={identity[key]??''}/></label>)}<label className="full"><span>Master notes</span><textarea name="master_notes" readOnly={!canEdit} maxLength={2000} defaultValue={String(identity.master_notes||'')}/></label><p className="full">Purchase value is an asset record and is not charged again in CPS. Own and rented vehicles use their rental rates. ODCD vehicle pay comes through the DA payout mapping. Ownership changes apply to deployment costs from today.</p>{canEdit&&<div className="fc-form-actions"><button className="fc-button primary" disabled={saving||loading}>{saving?'Saving…':'Save vehicle details'}</button></div>}</form>}
 {tab==='rent'&&<><p className="fc-rent-message">Monthly rent is editable for each vehicle, including own vehicles. CPS accrues the rate by calendar day at the deployed station. A new effective date preserves the earlier rate. Deployed downtime continues to incur rent.</p>{canEdit&&<form key={vehicle.id} className="fc-add-form" onSubmit={e=>save(e,'rent')}><label><span>Monthly rent (₹)</span><input name="amount" type="number" step="0.01" min="0" max="9999999" required defaultValue={current(vehicle.id)?.monthly_rent??''}/></label><label><span>Effective from</span><input name="from" type="date" required defaultValue={today}/></label><label className="full"><span>Reason for this rate</span><input name="reason" required minLength={3} maxLength={500} placeholder="Agreement, revision or correction"/></label><p className="full">An existing effective date corrects that revision. A new date creates a revision. Every change is recorded.</p><div className="fc-form-actions"><button className="fc-button primary" disabled={saving}>{saving?'Saving…':'Save vehicle rent'}</button></div></form>}<div className="fc-table-wrap"><table className="fc-table"><thead><tr><th>Effective period</th><th>Monthly rent</th><th>Reason</th></tr></thead><tbody>{rates.filter(r=>r.vehicle_id===vehicle.id).map(r=><tr key={r.id}><td>{r.effective_from} → {r.effective_to||'Ongoing'}</td><td>{money(r.monthly_rent)}</td><td>{r.reason}</td></tr>)}</tbody></table></div></>}
 {tab==='invoice'&&<div className="fc-invoice-evidence">{docsLoading?<p>Loading invoice…</p>:invoices.filter(d=>d.document_type==='VEHICLE_INVOICE').length?invoices.filter(d=>d.document_type==='VEHICLE_INVOICE').map(d=><p key={d.file_name}>{d.download_url?<a className="fc-button secondary" href={d.download_url}>Download {d.file_name}</a>:d.file_name}</p>):<p>No purchase invoice attached yet.</p>}{canManageDocuments&&<form className="fc-add-form" onSubmit={e=>save(e,'invoice')}><label className="full"><span>Purchase invoice · PDF / JPG / PNG / WebP · up to 20 MB</span><input name="file" type="file" required accept="application/pdf,image/jpeg,image/png,image/webp"/></label><div className="fc-form-actions"><button className="fc-button primary" disabled={saving}>{saving?'Uploading…':'Upload invoice'}</button></div></form>}</div>}
 </dialog>}
 </article>
}
