import { createFieldExecutive, queueAmazonInvitationFromOpsPulse } from "@/app/field-executive/actions";
import { updateRecruitInterviewOutcome } from "@/app/ops-pulse/workforce-register-actions";
import { AppShell } from "@/components/app-shell";
import { PageHead } from "@/components/page-head";
import { PendingLink } from "@/components/pending-link";
import { SubmitButton } from "@/components/submit-button";
import { canOnboardDesignation } from "@/lib/designation-onboarding-access";
import { canAccessDesignationPortal } from "@/lib/designation-portal-access";
import { loadMappedDesignationIds } from "@/lib/designation-register-routing";
import { dashboardDateInputValue, formatDashboardDateTime } from "@/lib/date-format";
import { filterOnboardingLocations } from "@/lib/onboarding-location-access";
import { currentAccessSurface } from "@/lib/access-surface";
import { isCompanyOwner, requirePagePermission, type AuthorizationContext } from "@/lib/authorization";
import { requireCompanyId } from "@/lib/company-scope";
import { supabaseAdmin } from "@/lib/supabase-admin";

export type WorkForceRegisterSearchParams = { tab?: string; date?: string; mobile?: string; candidate?: string; error?: string; notice?: string };
type QueueKey = "interviews" | "dropx-id" | "amazon-id" | "da-onboarding" | "attention";
type Station = { id: string; station_code: string; station_name: string | null; hide_from_location_list?: boolean | null };
type RecruitLead = { id: string; full_name: string | null; phone: string | null; email: string | null; work_email: string | null; station_code: string | null; job_code: string | null; status: string; final_status: string | null; interview_at: string | null; final_remarks: string | null; assigned_user_id: string | null; updated_at: string };
type WorkforceRow = { id: string; full_name: string; mobile: string; mobile_country_code: string | null; email: string; location_id: string; onboarding_status: string; updated_at: string; created_at: string; recruitment_lead_id: string | null; stations: { station_code: string; station_name: string | null } | Array<{ station_code: string; station_name: string | null }> | null };
type Invitation = { id: string; workforce_id: string; station_id: string; status: string; requested_at: string; completed_at: string | null; external_reference: string | null; error_code: string | null; error_message: string | null };
type Scheduler = { id: string; full_name: string | null; mobile: string | null; mobile_country_code: string | null; email: string | null };
type RecruitmentEvent = { id: string; lead_id: string; workforce_id: string | null; event_code: string; event_at: string; actor_user_id: string | null; metadata: Record<string, unknown> | null };

const queues: Array<{ key: QueueKey; label: string; helper: string }> = [
  { key: "interviews", label: "Interviews", helper: "Recruit scheduled candidates" },
  { key: "dropx-id", label: "DropX ID pending", helper: "Registration invitations" },
  { key: "amazon-id", label: "Amazon ID", helper: "Ready to trigger" },
  { key: "da-onboarding", label: "DA in-app onboarding", helper: "Partner processing" },
  { key: "attention", label: "Need attention", helper: "Returned or failed" }
];

function queueKey(value: unknown): QueueKey { const candidate = String(value ?? "").trim().toLowerCase(); return queues.some((queue) => queue.key === candidate) ? candidate as QueueKey : "interviews"; }
function relation<T>(value: T | T[] | null | undefined) { return Array.isArray(value) ? value[0] ?? null : value ?? null; }
function text(value: unknown) { return String(value ?? "").trim(); }
function digits(value: unknown) { return text(value).replace(/\D/g, ""); }
function displayPhone(phone: string | null, countryCode: string | null = null) { const normalized = digits(phone); return normalized ? `${countryCode ? `+${digits(countryCode)} ` : ""}${normalized}` : "Contact unavailable"; }
function stationName(row: WorkforceRow) { return relation(row.stations)?.station_code || "Unassigned station"; }
function statusLabel(value: unknown) { return text(value).replace(/[_-]+/g, " ") || "Pending"; }
function validDate(value: unknown) { return /^\d{4}-\d{2}-\d{2}$/.test(text(value)); }
function boundsForDate(value: string) { const start = new Date(`${value}T00:00:00+05:30`); return { start: start.toISOString(), end: new Date(start.getTime() + 86400000).toISOString() }; }
function basePath(input: { tab: QueueKey; date?: string | null; mobile?: string | null; candidate?: string | null }) { const query = new URLSearchParams({ tab: input.tab }); if (input.date) query.set("date", input.date); if (input.mobile) query.set("mobile", input.mobile); if (input.candidate) query.set("candidate", input.candidate); return `/work-force-register?${query.toString()}`; }
function withinScope(stationCode: string | null, stationCodes: Set<string>, authorization: AuthorizationContext) { return authorization.hasAllLocationAccess || stationCodes.has(text(stationCode).toUpperCase()); }

async function loadSchedulerMap(companyId: string, leads: RecruitLead[]) {
  const ids = [...new Set(leads.map((lead) => lead.assigned_user_id).filter((id): id is string => Boolean(id)))];
  if (!ids.length || !supabaseAdmin) return new Map<string, Scheduler>();
  const result = await supabaseAdmin.from("profiles").select("id, full_name, mobile, mobile_country_code, email").eq("company_id", companyId).in("id", ids);
  return new Map((result.data ?? []).map((profile) => [profile.id, profile as Scheduler]));
}

async function loadTracker(companyId: string, mobile: string, authorization: AuthorizationContext, stationCodes: Set<string>) {
  const suffix = digits(mobile).slice(-10);
  if (suffix.length < 6 || !supabaseAdmin) return { leads: [] as RecruitLead[], workforce: [] as WorkforceRow[], events: [] as RecruitmentEvent[], actors: new Map<string, Scheduler>() };
  const [leadResult, workforceResult] = await Promise.all([
    supabaseAdmin.from("leads").select("id, full_name, phone, email, work_email, station_code, job_code, status, final_status, interview_at, final_remarks, assigned_user_id, updated_at").eq("company_id", companyId).is("archived_at", null).ilike("phone", `%${suffix}%`).limit(12),
    supabaseAdmin.from("workforce").select("id, full_name, mobile, mobile_country_code, email, location_id, onboarding_status, updated_at, created_at, recruitment_lead_id, stations(station_code, station_name)").eq("company_id", companyId).is("deleted_at", null).ilike("mobile", `%${suffix}%`).limit(12)
  ]);
  const leads = ((leadResult.data ?? []) as RecruitLead[]).filter((lead) => digits(lead.phone).endsWith(suffix)).filter((lead) => withinScope(lead.station_code, stationCodes, authorization));
  const workforce = ((workforceResult.data ?? []) as WorkforceRow[]).filter((row) => digits(row.mobile).endsWith(suffix)).filter((row) => authorization.hasAllLocationAccess || authorization.locationScopeIds.includes(row.location_id));
  const leadIds = [...new Set([...leads.map((lead) => lead.id), ...workforce.map((row) => row.recruitment_lead_id).filter((id): id is string => Boolean(id))])];
  const workforceIds = workforce.map((row) => row.id);
  const eventResult = leadIds.length || workforceIds.length ? await supabaseAdmin.from("workforce_recruitment_events").select("id, lead_id, workforce_id, event_code, event_at, actor_user_id, metadata").eq("company_id", companyId).or([leadIds.length ? `lead_id.in.(${leadIds.join(",")})` : "", workforceIds.length ? `workforce_id.in.(${workforceIds.join(",")})` : ""].filter(Boolean).join(",")).order("event_at", { ascending: true }).limit(100) : { data: [] as RecruitmentEvent[] };
  const events = (eventResult.data ?? []) as RecruitmentEvent[];
  const actorIds = [...new Set(events.map((event) => event.actor_user_id).filter((id): id is string => Boolean(id)))];
  const actorResult = actorIds.length ? await supabaseAdmin.from("profiles").select("id, full_name, mobile, mobile_country_code, email").eq("company_id", companyId).in("id", actorIds) : { data: [] as Scheduler[] };
  return { leads, workforce, events, actors: new Map((actorResult.data ?? []).map((actor) => [actor.id, actor as Scheduler])) };
}

async function loadDeskData(authorization: AuthorizationContext, tab: QueueKey, queueDate: string, candidateId?: string, mobile?: string) {
  const companyId = requireCompanyId(authorization);
  if (!supabaseAdmin) throw new Error("The Workforce Register service is unavailable.");
  const stationResult = await supabaseAdmin.from("stations").select("id, station_code, station_name, hide_from_location_list").eq("company_id", companyId).order("station_code").limit(500);
  if (stationResult.error) throw new Error(stationResult.error.message);
  const stations = filterOnboardingLocations((stationResult.data ?? []) as Station[], authorization);
  const stationCodes = new Set(stations.map((station) => text(station.station_code).toUpperCase()));
  const bounds = boundsForDate(queueDate);
  const interviewBase = () => { let query = supabaseAdmin!.from("leads").select("id, full_name, phone, email, work_email, station_code, job_code, status, final_status, interview_at, final_remarks, assigned_user_id, updated_at").eq("company_id", companyId).in("status", ["interview_scheduled", "INTERVIEW"]).is("archived_at", null).is("duplicate_of", null).or("final_status.is.null,final_status.eq.Rescheduled").gte("interview_at", bounds.start).lt("interview_at", bounds.end).order("interview_at", { ascending: true }).limit(100); if (!authorization.hasAllLocationAccess) query = query.in("station_code", [...stationCodes]); return query; };
  const workforceBase = (statuses?: string[]) => { let query = supabaseAdmin!.from("workforce").select("id, full_name, mobile, mobile_country_code, email, location_id, onboarding_status, updated_at, created_at, recruitment_lead_id, stations(station_code, station_name)").eq("company_id", companyId).is("deleted_at", null).order("updated_at", { ascending: false }).limit(120); if (statuses?.length) query = query.in("onboarding_status", statuses); if (!authorization.hasAllLocationAccess) query = query.in("location_id", authorization.locationScopeIds); return query; };
  const interviewCountBase = () => { let query = supabaseAdmin!.from("leads").select("id", { count: "exact", head: true }).eq("company_id", companyId).in("status", ["interview_scheduled", "INTERVIEW"]).is("archived_at", null).is("duplicate_of", null).or("final_status.is.null,final_status.eq.Rescheduled").gte("interview_at", bounds.start).lt("interview_at", bounds.end); if (!authorization.hasAllLocationAccess) query = query.in("station_code", [...stationCodes]); return query; };
  const workforceCountBase = (statuses: string[]) => { let query = supabaseAdmin!.from("workforce").select("id", { count: "exact", head: true }).eq("company_id", companyId).is("deleted_at", null).in("onboarding_status", statuses); if (!authorization.hasAllLocationAccess) query = query.in("location_id", authorization.locationScopeIds); return query; };
  const [interviewCount, dropxCount, amazonReadyCount, daCount, attentionCount, returnedCount] = await Promise.all([
    interviewCountBase(), workforceCountBase(["pending", "returned"]), workforceCountBase(["under_review", "approved", "active"]),
    (() => { let query = supabaseAdmin!.from("workforce_amazon_invitation_requests").select("id", { count: "exact", head: true }).eq("company_id", companyId).in("status", ["queued", "processing", "sent"]); if (!authorization.hasAllLocationAccess) query = query.in("station_id", authorization.locationScopeIds); return query; })(),
    (() => { let query = supabaseAdmin!.from("workforce_amazon_invitation_requests").select("id", { count: "exact", head: true }).eq("company_id", companyId).eq("status", "failed"); if (!authorization.hasAllLocationAccess) query = query.in("station_id", authorization.locationScopeIds); return query; })(),
    workforceCountBase(["returned"])
  ]);
  const counts = { interviews: interviewCount.count ?? 0, "dropx-id": dropxCount.count ?? 0, "amazon-id": amazonReadyCount.count ?? 0, "da-onboarding": daCount.count ?? 0, attention: (attentionCount.count ?? 0) + (returnedCount.count ?? 0) } satisfies Record<QueueKey, number>;
  let interviews: RecruitLead[] = []; let workforce: WorkforceRow[] = []; let invitations: Invitation[] = [];
  if (tab === "interviews") { const result = await interviewBase(); if (result.error) throw new Error(result.error.message); interviews = (result.data ?? []) as RecruitLead[]; }
  else if (tab === "dropx-id") { const result = await workforceBase(["pending", "returned"]); if (result.error) throw new Error(result.error.message); workforce = (result.data ?? []) as WorkforceRow[]; }
  else if (tab === "amazon-id") { const result = await workforceBase(["under_review", "approved", "active"]); if (result.error) throw new Error(result.error.message); const candidates = (result.data ?? []) as WorkforceRow[]; const requestResult = candidates.length ? await supabaseAdmin.from("workforce_amazon_invitation_requests").select("workforce_id, status").eq("company_id", companyId).in("workforce_id", candidates.map((row) => row.id)).in("status", ["queued", "processing", "sent"]) : { data: [] as Array<Pick<Invitation, "workforce_id" | "status">>, error: null }; if (requestResult.error) throw new Error(requestResult.error.message); const queued = new Set((requestResult.data ?? []).map((request) => request.workforce_id)); workforce = candidates.filter((row) => !queued.has(row.id)); }
  else { const requestResult = await supabaseAdmin.from("workforce_amazon_invitation_requests").select("id, workforce_id, station_id, status, requested_at, completed_at, external_reference, error_code, error_message").eq("company_id", companyId).in("status", tab === "attention" ? ["failed"] : ["queued", "processing", "sent"]).order("updated_at", { ascending: false }).limit(120); if (requestResult.error) throw new Error(requestResult.error.message); invitations = ((requestResult.data ?? []) as Invitation[]).filter((request) => authorization.hasAllLocationAccess || authorization.locationScopeIds.includes(request.station_id)); const ids = invitations.map((request) => request.workforce_id); if (ids.length) { const workerResult = await workforceBase().in("id", ids); if (workerResult.error) throw new Error(workerResult.error.message); workforce = (workerResult.data ?? []) as WorkforceRow[]; } if (tab === "attention") { const returned = await workforceBase(["returned"]); if (returned.error) throw new Error(returned.error.message); workforce = [...workforce, ...((returned.data ?? []) as WorkforceRow[]).filter((row) => !workforce.some((existing) => existing.id === row.id))]; } }
  const candidateResult = candidateId ? await supabaseAdmin.from("leads").select("id, full_name, phone, email, work_email, station_code, job_code, status, final_status, interview_at, final_remarks, assigned_user_id, updated_at").eq("company_id", companyId).eq("id", candidateId).eq("status", "interview_reported").is("archived_at", null).maybeSingle() : { data: null as RecruitLead | null, error: null };
  if (candidateResult.error) throw new Error(candidateResult.error.message);
  const inviteCandidate = candidateResult.data && withinScope(candidateResult.data.station_code, stationCodes, authorization) ? candidateResult.data as RecruitLead : null;
  const [schedulers, tracker] = await Promise.all([loadSchedulerMap(companyId, interviews), loadTracker(companyId, mobile ?? "", authorization, stationCodes)]);
  const mappedDesignationIds = inviteCandidate ? await loadMappedDesignationIds(companyId, "workforce") : new Set<string>();
  const designationResult = inviteCandidate ? await supabaseAdmin.from("designations").select("id, name, code, onboarding_role_ids, portal_permissions").eq("company_id", companyId).eq("is_active", true).order("name") : { data: [] as Array<{ id: string; name: string; code: string; onboarding_role_ids?: string[] | null; portal_permissions?: unknown }>, error: null };
  if (designationResult.error) throw new Error(designationResult.error.message);
  return { stations, counts, interviews, workforce, invitations, schedulers, inviteCandidate, tracker, designations: (designationResult.data ?? []).filter((designation) => mappedDesignationIds.has(designation.id)) };
}

function Notice({ error, notice }: { error?: string; notice?: string }) { return error || notice ? <section className={`panel message-panel ${error ? "error" : "success"}`}><div className="panel-body"><strong>{error ? "Action required" : "Updated"}</strong><p className="subtle">{error || notice}</p></div></section> : null; }

function InterviewQueue({ rows, schedulers, queueDate, canEdit }: { rows: RecruitLead[]; schedulers: Map<string, Scheduler>; queueDate: string; canEdit: boolean }) { return <section className="panel ops-workforce-queue"><div className="panel-head"><div><h2>Scheduled interviews</h2><p className="subtle">Only candidates scheduled for {queueDate} are shown. Rescheduled candidates leave this date and return on their new date.</p></div><span className="status-pill warn">{rows.length} today</span></div><div className="ops-workforce-list">{rows.map((lead) => { const scheduler = lead.assigned_user_id ? schedulers.get(lead.assigned_user_id) : null; return <details className="ops-workforce-row" key={lead.id}><summary><span><strong>{lead.full_name || "Unnamed candidate"}</strong><small>{lead.station_code || "Station not assigned"} · {lead.job_code || "Role pending"}</small></span><span className="ops-workforce-row-meta"><b>{formatDashboardDateTime(lead.interview_at)}</b><small title={scheduler ? `${scheduler.full_name || "Scheduler"} · ${displayPhone(scheduler.mobile, scheduler.mobile_country_code)}` : "No scheduler has been assigned"}>ⓘ {scheduler?.full_name || "Scheduler unassigned"}{scheduler?.mobile ? ` · ${displayPhone(scheduler.mobile, scheduler.mobile_country_code)}` : ""}</small></span></summary><div className="ops-workforce-row-body"><div className="ops-workforce-facts"><span>Candidate contact <b>{displayPhone(lead.phone)}</b></span><span>Email <b>{lead.work_email || lead.email || "Not supplied"}</b></span><span>Scheduled by <b>{scheduler?.full_name || "Unassigned"}</b></span></div>{canEdit ? <div className="ops-workforce-actions"><form action={updateRecruitInterviewOutcome}><input name="lead_id" type="hidden" value={lead.id}/><input name="outcome" type="hidden" value="reported"/><input name="queue_date" type="hidden" value={queueDate}/><button className="button compact">Reported → invite associate</button></form><form action={updateRecruitInterviewOutcome} className="ops-workforce-inline-form"><input name="lead_id" type="hidden" value={lead.id}/><input name="outcome" type="hidden" value="rescheduled"/><input name="queue_date" type="hidden" value={queueDate}/><label>Reschedule for<input name="rescheduled_for" required type="datetime-local"/></label><button className="button secondary compact">Reschedule</button></form><form action={updateRecruitInterviewOutcome}><input name="lead_id" type="hidden" value={lead.id}/><input name="outcome" type="hidden" value="not_interested"/><input name="queue_date" type="hidden" value={queueDate}/><button className="button danger compact">Not interested</button></form></div> : <p className="subtle">You can view this candidate but do not have permission to update the interview.</p>}</div></details>; })}{!rows.length ? <div className="empty-state">No interviews are scheduled for this date.</div> : null}</div></section>; }

function InviteCandidate({ candidate, stations, designations, canEdit }: { candidate: RecruitLead; stations: Station[]; designations: Array<{ id: string; name: string; code: string }>; canEdit: boolean }) { const mappedStation = stations.find((station) => text(station.station_code).toUpperCase() === text(candidate.station_code).toUpperCase()); const defaultMobile = digits(candidate.phone).slice(-10); return <section className="panel ops-workforce-invite"><div className="panel-head"><div><p className="eyebrow">Candidate reported</p><h2>Invite {candidate.full_name || "associate"} to DropX One</h2><p className="subtle">The candidate moves to DropX ID pending after this invitation. Registration completion moves them to Amazon ID automatically.</p></div><PendingLink className="icon-button" href="/work-force-register?tab=dropx-id" aria-label="Close invitation">×</PendingLink></div>{canEdit ? <form action={createFieldExecutive} className="form-grid three"><input name="return_path" type="hidden" value="/work-force-register"/><input name="redirect_tab" type="hidden" value="dropx-id"/><input name="recruitment_lead_id" type="hidden" value={candidate.id}/><label>Associate name<input className="field" name="full_name" required defaultValue={candidate.full_name || ""}/></label><label>Mobile number<div className="ops-workforce-phone"><input className="field" name="mobile_country_code" defaultValue="91" required/><input className="field" name="mobile" required defaultValue={defaultMobile}/></div></label><label>Station work email<input className="field" name="email" required type="email" defaultValue={candidate.work_email || candidate.email || ""}/></label><label>Date of join<input className="field" name="date_of_join" required type="date" defaultValue={dashboardDateInputValue()}/></label><label>Reported on<input className="field" name="reported_on" type="date" defaultValue={dashboardDateInputValue()}/></label><label>Station<select className="field" name="location_id" required defaultValue={mappedStation?.id || ""}><option value="" disabled>Select station</option>{stations.map((station) => <option key={station.id} value={station.id}>{station.station_code}{station.station_name ? ` · ${station.station_name}` : ""}</option>)}</select></label><label>Designation<select className="field" name="designation" required defaultValue=""><option value="" disabled>Select designation</option>{designations.map((designation) => <option key={designation.id} value={designation.name}>{designation.name}{designation.code ? ` · ${designation.code}` : ""}</option>)}</select></label><div className="form-actions span-2 align-right"><SubmitButton disabled={!mappedStation || !designations.length} disabledText={!mappedStation ? "Candidate station is not in your scope" : "No Workforce designation is configured"}>Send DropX ID invitation</SubmitButton></div></form> : <p className="subtle">You can view this candidate but do not have permission to send the invitation.</p>}</section>; }

function WorkforceRows({ rows, invitations, mode, canEdit }: { rows: WorkforceRow[]; invitations: Invitation[]; mode: Exclude<QueueKey, "interviews">; canEdit: boolean }) { const inviteByWorkforce = new Map(invitations.map((invite) => [invite.workforce_id, invite])); const title = mode === "dropx-id" ? "DropX ID pending" : mode === "amazon-id" ? "Amazon ID ready" : mode === "da-onboarding" ? "DA in-app onboarding" : "Need attention"; const helper = mode === "dropx-id" ? "Waiting for the associate to complete the DropX One registration." : mode === "amazon-id" ? "Registration is complete. Send the Amazon ID trigger when the station is ready." : mode === "da-onboarding" ? "The Amazon invitation was triggered. Follow its partner status here." : "Returned registrations and failed partner invitations that need an owner."; return <section className="panel ops-workforce-queue"><div className="panel-head"><div><h2>{title}</h2><p className="subtle">{helper}</p></div><span className="status-pill">{rows.length} shown</span></div><div className="ops-workforce-list">{rows.map((row) => { const invite = inviteByWorkforce.get(row.id); const idfi = /idfi|idfy|insufficien/i.test(`${invite?.error_code || ""} ${invite?.error_message || ""}`); return <details className="ops-workforce-row" key={row.id}><summary><span><strong>{row.full_name}</strong><small>{stationName(row)} · {displayPhone(row.mobile, row.mobile_country_code)}</small></span><span className="ops-workforce-row-meta"><b className={mode === "attention" ? "status-pill danger" : "status-pill"}>{mode === "attention" && idfi ? "IDFI insufficiency" : statusLabel(invite?.status || row.onboarding_status)}</b><small>Updated {formatDashboardDateTime(invite?.requested_at || row.updated_at)}</small></span></summary><div className="ops-workforce-row-body"><div className="ops-workforce-facts"><span>DropX ID <b>{row.onboarding_status === "pending" ? "Registration pending" : statusLabel(row.onboarding_status)}</b></span><span>Amazon status <b>{invite ? statusLabel(invite.status) : mode === "amazon-id" ? "Ready to trigger" : "Not triggered"}</b></span><span>Email <b>{row.email}</b></span></div>{mode === "amazon-id" && canEdit ? <form action={queueAmazonInvitationFromOpsPulse}><input name="workforce_id" type="hidden" value={row.id}/><input name="return_status" type="hidden" value="da-onboarding"/><button className="button compact">Send Amazon ID trigger</button></form> : null}{mode === "attention" && invite?.error_message ? <p className="ops-workforce-error"><strong>{idfi ? "IDFI insufficiency" : "Partner response"}</strong> {invite.error_message}</p> : null}{mode === "da-onboarding" && invite?.external_reference ? <p className="subtle">Partner reference: {invite.external_reference}</p> : null}</div></details>; })}{!rows.length ? <div className="empty-state">Nothing is waiting in this queue.</div> : null}</div></section>; }

function CandidateTracker({ mobile, data }: { mobile: string; data: Awaited<ReturnType<typeof loadTracker>> }) { if (!digits(mobile)) return null; const timeline = [...data.events].sort((left, right) => new Date(left.event_at).getTime() - new Date(right.event_at).getTime()); return <section className="panel ops-workforce-tracker"><div className="panel-head"><div><h2>Candidate journey</h2><p className="subtle">Matched to {displayPhone(mobile)} across Recruit and Workforce.</p></div></div>{!data.leads.length && !data.workforce.length ? <div className="empty-state">No candidate or associate matched this mobile number in your station scope.</div> : <div className="ops-workforce-tracker-grid"><div><h3>Current record</h3>{data.leads.map((lead) => <div className="ops-workforce-tracker-card" key={lead.id}><strong>{lead.full_name || "Candidate"}</strong><span>{lead.station_code || "Station pending"} · Recruit: {statusLabel(lead.status)}</span><span>{lead.final_status || "No final outcome yet"}</span></div>)}{data.workforce.map((row) => <div className="ops-workforce-tracker-card" key={row.id}><strong>{row.full_name}</strong><span>{stationName(row)} · DropX: {statusLabel(row.onboarding_status)}</span><span>Amazon: {row.onboarding_status === "pending" ? "Waiting for registration" : "Check DA in-app onboarding"}</span></div>)}</div><div><h3>Journey trail</h3>{timeline.length ? <ol className="ops-workforce-timeline">{timeline.map((event) => { const actor = event.actor_user_id ? data.actors.get(event.actor_user_id) : null; return <li key={event.id}><strong>{statusLabel(event.event_code)}</strong><span>{formatDashboardDateTime(event.event_at)} · {actor?.full_name || "System"}</span></li>; })}</ol> : <p className="subtle">The candidate is visible; operational events will appear as the interview and invitation are updated.</p>}</div></div>}</section>; }

export async function OpsWorkforceRegisterPage({ searchParams }: { searchParams?: WorkForceRegisterSearchParams }) {
  const authorization = await requirePagePermission("delivery_associates", "access"); const tab = queueKey(searchParams?.tab); const queueDate = validDate(searchParams?.date) ? String(searchParams?.date) : dashboardDateInputValue(); const permission = authorization.permissions.delivery_associates ?? { canView: false, canAdd: false, canEdit: false }; const canEdit = Boolean(permission.canEdit && !authorization.readOnly); const data = await loadDeskData(authorization, tab, queueDate, searchParams?.candidate, searchParams?.mobile); const current = queues.find((queue) => queue.key === tab)!;
  return <AppShell active="Workforce Register" pageCode="delivery_associates"><PageHead eyebrow="Workforce operations" title="Workforce Register" subtitle="A clear Recruit-to-DA journey: interview, DropX ID, Amazon ID, then in-app onboarding."/><Notice error={searchParams?.error} notice={searchParams?.notice}/><section className="ops-workforce-hero"><div><strong>Associate onboarding desk</strong><p>Recruit owns candidate data. Operations records the interview outcome and advances only the next required step.</p></div><form action="/work-force-register" className="ops-workforce-tracker-search"><input name="tab" type="hidden" value={tab}/><input name="date" type="hidden" value={queueDate}/><label>Track a candidate by mobile<input className="field" name="mobile" inputMode="numeric" placeholder="Enter mobile number" defaultValue={searchParams?.mobile || ""}/></label><button className="button secondary compact">Track journey</button></form></section><nav className="ops-workforce-tabs" aria-label="Workforce journey queues">{queues.map((queue) => <PendingLink key={queue.key} href={basePath({ tab: queue.key, date: queue.key === "interviews" ? queueDate : null })} className={queue.key === tab ? "active" : ""}><span>{queue.label}</span><strong>{data.counts[queue.key]}</strong><small>{queue.helper}</small></PendingLink>)}</nav>{tab === "interviews" ? <form action="/work-force-register" className="panel ops-workforce-date-filter"><input name="tab" type="hidden" value="interviews"/><label>Interview date<input className="field" name="date" type="date" defaultValue={queueDate}/></label><button className="button secondary compact">View date</button><span>Rescheduled candidates appear only on their selected future date.</span></form> : null}<CandidateTracker mobile={searchParams?.mobile || ""} data={data.tracker}/>{tab === "interviews" ? <InterviewQueue rows={data.interviews} schedulers={data.schedulers} queueDate={queueDate} canEdit={canEdit}/> : null}{tab === "dropx-id" && data.inviteCandidate ? <InviteCandidate candidate={data.inviteCandidate} stations={data.stations} designations={data.designations.filter((designation) => canOnboardDesignation(designation, authorization) && canAccessDesignationPortal(designation, currentAccessSurface(), "add", { isOwner: isCompanyOwner(authorization) }))} canEdit={canEdit}/> : null}{tab !== "interviews" ? <WorkforceRows rows={data.workforce} invitations={data.invitations} mode={tab} canEdit={canEdit}/> : null}<section className="ops-workforce-next"><span>Current queue</span><strong>{current.label}</strong><p>{current.helper}. Open a row only when you need its details or action.</p></section></AppShell>;
}
