'use client';
import { useEffect, useRef, useState } from 'react';
import { Search, ArrowLeft, ArrowUpRight, ChevronRight, Copy, RefreshCw, Clock3, GitBranch, History, ListFilter } from 'lucide-react';
import { sources, text, human, reference, state, waiting, age, eventTime, eventAction, eventActor, statusTone, stageSince, type TrackerRow, type Detail, type RecordData } from '@/lib/request-tracker/model';
import './request-tracker.css';
type SearchResult={rows:TrackerRow[];hasMore:boolean;warnings:{label:string;message:string}[];checkedAt:string;names:Record<string,string>};
const date=(v:string)=>{const d=new Date(v);return Number.isFinite(d.getTime())?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit',timeZone:'Asia/Kolkata'}).format(d):'Not recorded';};
const portals:Record<string,string>={People:'https://people.dropxlogistics.com',Workforce:'https://workforce.dropxlogistics.com',Recruit:'https://recruit.dropxlogistics.com',OpsPulse:'https://ops.dropxlogistics.com',Finance:'https://fin.dropxlogistics.com',Fleet:'https://fleet.dropxlogistics.com',Dashboard:'https://dashboard.dropxlogistics.com'};
function Value({value,names}:{value:unknown;names:Record<string,string>}){
 if(value===null||value===undefined||value==='')return <span className="rt-muted">Not recorded</span>;
 if(Array.isArray(value))return value.length?<details><summary>{value.length} items</summary>{value.map((v,i)=><div className="rt-nested" key={i}><Value value={v} names={names}/></div>)}</details>:<span className="rt-muted">None</span>;
 if(typeof value==='object')return <details><summary>{Object.keys(value).length} fields</summary><Fields record={value as RecordData} names={names}/></details>;
 const s=String(value);return <span className={s==='[Protected]'?'rt-muted':''}>{names[s]?<>{names[s]} <small className="rt-id">{s}</small></>:s}</span>;
}
function Fields({record,names}:{record:RecordData;names:Record<string,string>}){return <dl className="rt-fields">{Object.entries(record).map(([k,v])=><div key={k}><dt>{human(k)}</dt><dd><Value value={v} names={names}/></dd></div>)}</dl>;}
function Pill({value}:{value:string}){return <span className={`rt-pill rt-${statusTone(value)}`}>{human(value)}</span>;}
export function RequestTracker({initialType,initialId,initialQuery}:{initialType?:string;initialId?:string;initialQuery?:string}){
 const [kind,setKind]=useState(initialType??'payment');const [query,setQuery]=useState(initialQuery??'');const [status,setStatus]=useState('');
 const [filters,setFilters]=useState({type:initialType??'payment',q:initialQuery??'',status:'',offset:0,refresh:0});
 const [result,setResult]=useState<SearchResult|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const [selected,setSelected]=useState<{kind:string;id:string}|null>(initialId?{kind:initialType??'payment',id:initialId}:null);
 const [detail,setDetail]=useState<Detail|null>(null);const [detailError,setDetailError]=useState('');const [detailLoading,setDetailLoading]=useState(false);
 const [tab,setTab]=useState('timeline');const [eventFilter,setEventFilter]=useState('all');const [copied,setCopied]=useState(false);const [eventOffset,setEventOffset]=useState(0);const [refreshDetail,setRefreshDetail]=useState(0);
 const heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');const params=new URLSearchParams({type:filters.type,q:filters.q,status:filters.status,offset:String(filters.offset)});
  fetch(`/api/request-tracker?${params}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load requests.');return j;}).then(setResult).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();
 },[filters]);
 useEffect(()=>{if(!selected)return;const abort=new AbortController();setDetailLoading(true);setDetailError('');setDetail(null);
  const p=new URLSearchParams({type:selected.kind,id:selected.id,offset:String(eventOffset)});
  fetch(`/api/request-tracker?${p}`,{signal:abort.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load history.');return j;}).then(setDetail).catch(e=>{if(e.name!=='AbortError')setDetailError(e.message);}).finally(()=>{if(!abort.signal.aborted)setDetailLoading(false);});return()=>abort.abort();
 },[selected,eventOffset,refreshDetail]);
 function open(kind:string,id:string){setSelected({kind,id});setEventOffset(0);setTab('timeline');setEventFilter('all');const u=new URL(window.location.href);u.search='';u.searchParams.set('type',kind);u.searchParams.set('id',id);window.history.replaceState(null,'',u);setTimeout(()=>heading.current?.focus(),0);}
 function close(){setSelected(null);setDetail(null);window.history.replaceState(null,'','/request-tracker');}
 async function copy(){try{await navigator.clipboard.writeText(window.location.href);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setDetailError('Could not copy. You can copy this page address.');}}
 const names=result?.names??{};
 return <div className="request-tracker">
  <header className="rt-heading"><div><span className="rt-eyebrow">ADMINISTRATION</span><h1 ref={heading} tabIndex={-1}>Request Tracker</h1><p>One reference. Every connected step.</p></div><span className="rt-live"><i/> Live sources</span></header>
  {!selected?<>
   <form className="rt-search" onSubmit={e=>{e.preventDefault();setFilters({type:kind,q:query.trim(),status,offset:0,refresh:filters.refresh+1});}}>
    <label className="rt-searchbox"><Search size={19}/><span className="rt-sr">Exact request ID or reference</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Paste an exact request ID or reference" maxLength={160}/></label>
    <label><span className="rt-sr">Request type</span><select aria-label="Request type" value={kind} onChange={e=>setKind(e.target.value)}><option value="">All request types</option>{sources.map(s=><option key={s.key} value={s.key}>{s.portal} · {s.label}</option>)}</select></label>
    <button className="rt-primary" type="submit">Track request <ChevronRight size={16}/></button>
    <details className="rt-filter"><summary><ListFilter size={15}/> Filters</summary><label>Exact source status<input value={status} onChange={e=>setStatus(e.target.value)} placeholder="e.g. pending" maxLength={80}/></label><small>Select All request types to search across portals.</small></details>
   </form>
   <section className="rt-panel"><div className="rt-section-head"><div><h2>{filters.q?'Search results':'Request register'}</h2><span className="rt-muted">{sources.find(s=>s.key===filters.type)?.portal??'All portals'} · {filters.q?'Exact reference match':'Most recently updated'}</span></div><button className="rt-icon" aria-label="Refresh requests" onClick={()=>setFilters({...filters,refresh:filters.refresh+1})}><RefreshCw size={17}/></button></div>
    {loading?<div className="rt-empty" role="status">Loading request sources…</div>:error?<div className="rt-empty rt-error" role="alert">{error}<button onClick={()=>setFilters({...filters,refresh:filters.refresh+1})}>Retry</button></div>:<>
     <div className="rt-table-wrap"><table className="rt-table"><thead><tr><th>Request</th><th>Source</th><th>Current stage</th><th>Waiting on</th><th>Last updated</th><th><span className="rt-sr">Details</span></th></tr></thead><tbody>{result?.rows.map(row=>{const r=row.record;const id=text(r,'id');return <tr key={`${row.kind}:${id}`}><td><button className="rt-reference" onClick={()=>open(row.kind,id)}>{reference(r)}</button><small>{row.label}</small></td><td>{row.portal}</td><td><Pill value={state(r)}/></td><td className="rt-wait">{waiting(r,names)}</td><td><span title={date(text(r,'updated_at','created_at'))}>{age(text(r,'updated_at','created_at'))} ago</span><small>{text(r,'station_code','location_code')||names[text(r,'station_id','location_id')]||''}</small></td><td><button aria-label={`View ${reference(r)}`} className="rt-icon" onClick={()=>open(row.kind,id)}><ChevronRight size={18}/></button></td></tr>;})}</tbody></table></div>
     {!result?.rows.length?<div className="rt-empty">{result?.warnings.length?'No results from available sources. Check source availability below.':'No matching requests. Try All request types or another exact reference.'}</div>:null}
     <div className="rt-footer"><button disabled={filters.offset===0} onClick={()=>setFilters({...filters,offset:Math.max(0,filters.offset-50)})}>Previous</button><span>Page {Math.floor(filters.offset/50)+1}</span><button disabled={!result?.hasMore||filters.offset>=10000} onClick={()=>setFilters({...filters,offset:filters.offset+50})}>Next</button></div>
    </>}
   </section>
   {!!result?.warnings.length&&!loading?<details className="rt-notice"><summary>{result.warnings.length} sources unavailable <ChevronRight size={14}/></summary>{result.warnings.map(w=><p key={w.label}><strong>{w.label}</strong> — {w.message}</p>)}</details>:null}
   <p className="rt-footnote">Existing references are preserved. Historical coverage varies by source. Times are shown in IST.</p>
  </>:<>
   <div className="rt-back"><button onClick={close}><ArrowLeft size={16}/> All requests</button><div><button onClick={copy}><Copy size={15}/>{copied?'Copied':'Copy link'}</button><button aria-label="Refresh request details" onClick={()=>setRefreshDetail(x=>x+1)}><RefreshCw size={16}/></button></div></div>
   {detailLoading?<div className="rt-panel rt-empty" role="status">Loading request and history…</div>:detailError?<div className="rt-panel rt-empty rt-error" role="alert">{detailError}<button onClick={()=>setRefreshDetail(x=>x+1)}>Retry</button></div>:detail?<>
    <section className="rt-panel rt-summary"><div className="rt-summary-top"><div><span className="rt-eyebrow">{detail.portal} · {detail.label}</span><h2>{reference(detail.record)}</h2></div><Pill value={detail.deleted?'Deleted':state(detail.record)}/></div>
     <div className="rt-metrics"><div><span>Waiting on</span><strong>{detail.deleted?'Record deleted':waiting(detail.record,detail.names)}</strong></div><div><span>Requested by</span><strong>{detail.names[text(detail.record,'requested_by','claimant_user_id','created_by')]||text(detail.record,'requested_for_name','worker_name','requested_by','claimant_user_id','created_by')||'Not recorded'}</strong></div><div><span>Created</span><strong>{date(text(detail.record,'created_at','requested_at','submitted_at'))}</strong></div><div><span>Amount / total</span><strong>{text(detail.record,'amount','total_claimed','requested_amount','amount_requested','estimated_amount','net_amount')||'—'}</strong></div><div><span>Time in current stage</span><strong>{eventOffset===0&&stageSince(detail)?age(stageSince(detail)):'Not recorded'}</strong></div></div>
     <details className="rt-coverage"><summary><Clock3 size={14}/> History coverage and freshness</summary><p>Database change recording enabled {date(detail.auditSince)}. Earlier events are shown where the source retained them. A last-updated timestamp is not the time a request entered its current stage.</p><p>{sources.find(s=>s.key===detail.kind)?.coverage}</p>{detail.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>
    </section>
    <div className="rt-tabs" role="tablist" aria-label="Request detail"><button id="rt-tab-timeline" role="tab" aria-controls="rt-content" aria-selected={tab==='timeline'} onClick={()=>setTab('timeline')}><History size={16}/> Timeline</button><button id="rt-tab-linked" role="tab" aria-controls="rt-content" aria-selected={tab==='linked'} onClick={()=>setTab('linked')}><GitBranch size={16}/> Linked records <span>{detail.related.length}</span></button><button id="rt-tab-details" role="tab" aria-controls="rt-content" aria-selected={tab==='details'} onClick={()=>setTab('details')}>Request details</button></div>
    <section id="rt-content" role="tabpanel" aria-labelledby={`rt-tab-${tab}`} className="rt-panel">
     {tab==='timeline'?<><div className="rt-section-head"><h2>Event timeline</h2><select aria-label="Event type" value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="all">All events</option><option value="workflow">Workflow events</option><option value="database">Database changes</option></select></div><div className="rt-timeline">{detail.events.filter(e=>eventFilter==='all'||(eventFilter==='database')===(e.source==='Database change')).map((e,index)=>{const r=e.record;const database=e.source==='Database change';const changes=Array.isArray(r.changed_fields)?r.changed_fields as string[]:[];const before=(r.before_data??{}) as RecordData;const after=(r.after_data??{}) as RecordData;return <details className="rt-event" key={`${e.source}:${text(r,'id')}:${index}`}><summary><span className={`rt-dot ${database?'rt-dot-db':''}`}/><div className="rt-event-main"><strong>{eventAction(e)}{database&&changes.length?<span className="rt-muted"> · {changes.length} fields</span>:null}</strong><span>{eventActor(e,detail.names)} <span className="rt-muted">· {database?'Database change':'Workflow'}</span></span></div><time title={eventTime(e)}>{date(eventTime(e))}</time><ChevronRight className="rt-chevron" size={16}/></summary><div className="rt-event-body">
      {!database&&text(r,'from_status','to_status')?<p><Pill value={text(r,'from_status')||'Not recorded'}/> → <Pill value={text(r,'to_status')||'Not recorded'}/></p>:null}
      {text(r,'comments','decision_note','remarks','message','reason','summary')?<p className="rt-note">{text(r,'comments','decision_note','remarks','message','reason','summary')}</p>:null}
      {database?<><p className="rt-muted">{text(r,'actor_id')?'Authenticated actor recorded.':'Human operator was not captured by this write.'}{text(r,'recorded_actor_id')?' The row contains an actor reference; see technical details for its provenance.':''}</p><div className="rt-table-wrap"><table className="rt-table"><thead><tr><th>Field</th><th>Before</th><th>After</th></tr></thead><tbody>{changes.map(k=><tr key={k}><th>{human(k)}</th><td><Value value={before[k]} names={detail.names}/></td><td><Value value={after[k]} names={detail.names}/></td></tr>)}</tbody></table></div></>:null}
      <details className="rt-technical"><summary>Event details · {e.source}</summary><Fields record={database?Object.fromEntries(Object.entries(r).filter(([k])=>!['before_data','after_data'].includes(k))):r} names={detail.names}/></details>
     </div></details>;})}{!detail.events.length?<div className="rt-empty">No retained events for this request yet. Current record details remain available.</div>:null}</div><div className="rt-footer"><button disabled={eventOffset===0} onClick={()=>setEventOffset(Math.max(0,eventOffset-100))}>Newer events</button><span>Newest first · IST</span><button disabled={!detail.hasMore||eventOffset>=10000} onClick={()=>setEventOffset(eventOffset+100)}>Older events</button></div></>:null}
     {tab==='linked'?<><div className="rt-section-head"><h2>Connected requests</h2><span className="rt-muted">Explicit record links</span></div>{detail.related.length?<div className="rt-links">{detail.related.map(r=><button key={`${r.kind}:${r.id}`} onClick={()=>open(r.kind,r.id)}><GitBranch size={19}/><span><strong>{r.reference}</strong><small>{r.label}</small>{r.status?<Pill value={r.status}/>:null}</span><ChevronRight size={18}/></button>)}</div>:<div className="rt-empty">No explicit linked request was found.</div>}<p className="rt-footnote">Up to 21 links per source are shown. Each linked record retains its own status.</p></>:null}
     {tab==='details'?<><div className="rt-section-head"><h2>Source record</h2><a href={portals[detail.portal]} target="_blank" rel="noreferrer">Open {detail.portal} <ArrowUpRight size={15}/></a></div><div className="rt-record"><Fields record={detail.record} names={detail.names}/></div><p className="rt-footnote">Protected contact, identity, banking and file fields stay in their source portal.</p></>:null}
    </section>
   </>:null}
  </>}
 </div>;
}
