import {supabaseAdmin} from '@/lib/supabase-admin';
import {readAllRows} from '@/lib/supabase-pagination';
import {requireCompanyId} from '@/lib/company-scope';
import type {AuthorizationContext} from '@/lib/authorization';
import {SubmitButton} from './submit-button';
export async function WorkforceHoldDesk({auth,action,canEdit,reviewer,status}:{auth:AuthorizationContext;action:(form:FormData)=>Promise<void>;canEdit:boolean;reviewer:boolean;status?:string}){
  if(!supabaseAdmin)return <p role="alert">Database is unavailable.</p>;
  const company=requireCompanyId(auth),none='00000000-0000-0000-0000-000000000000';
  let peopleQuery=supabaseAdmin.from('workforce').select('id,full_name,dropx_id,location_id').eq('company_id',company).is('deleted_at',null).neq('migration_state','reclassified').order('full_name').order('id');
  let holdsQuery=supabaseAdmin.from('workforce_payment_holds').select('*').eq('company_id',company).order('requested_at',{ascending:false}).order('id');
  if(!auth.hasAllLocationAccess){const ids=auth.locationScopeIds.length?auth.locationScopeIds:[none];peopleQuery=peopleQuery.in('location_id',ids);holdsQuery=holdsQuery.in('station_id',ids);}
  if(status&&['active','release_requested','released'].includes(status))holdsQuery=holdsQuery.eq('status',status);
  const [people,holds,stations]=await Promise.all([readAllRows(peopleQuery),readAllRows(holdsQuery),readAllRows(supabaseAdmin.from('stations').select('id,station_code').eq('company_id',company).order('id'))]);
  if(people.error||holds.error||stations.error)return <p role="alert">The Workforce hold desk could not be loaded. Please retry; no changes were made.</p>;
  const workers=new Map((people.data??[]).map(row=>[row.id,row])),stationNames=new Map((stations.data??[]).map(row=>[row.id,row.station_code]));
  const actorIds=[...new Set((holds.data??[]).flatMap(row=>[row.requested_by,row.released_by]).filter(Boolean))];
  const names=new Map<string,string>();
  for(let index=0;index<actorIds.length;index+=100){const result=await supabaseAdmin.from('profiles').select('id,full_name').eq('company_id',company).in('id',actorIds.slice(index,index+100));if(!result.error)for(const row of result.data??[])names.set(row.id,row.full_name||'Authorised user');}
  const time=(date:string|null)=>date?new Date(date).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'—';
  return <><section className="panel"><div className="panel-head"><div><h2>Workforce payment holds</h2><p>A temporary payment block—not a deduction. Earned amounts remain visible. Finance processing is blocked until an independent Workforce reviewer releases the hold.</p></div></div>
    {canEdit&&!auth.readOnly?<form action={action} className="panel-body" style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:14}}><input type="hidden" name="action" value="create"/>
      <label>Associate / DropX ID<select name="workforce_id" className="field" required defaultValue=""><option value="">Choose associate</option>{(people.data??[]).map(row=><option key={row.id} value={row.id}>{row.dropx_id||'ID pending'} · {row.full_name} · {stationNames.get(row.location_id)}</option>)}</select></label>
      <label>Unpaid period starts<input name="period_start" className="field" type="date" required/></label><label>Unpaid period ends<input name="period_end" className="field" type="date" required/></label>
      <label>Unique case / approval reference<input className="field" name="reference" required minLength={3} maxLength={250}/></label>
      <label>Reason<textarea className="field" name="reason" required minLength={5} maxLength={2000}/></label>
      <div><p className="subtle">Use the approved company process. Holds cannot recall payments already sent to the bank.</p><SubmitButton pendingText="Placing hold" confirmTitle="Place payment hold?" confirmMessage="This will block payment for the selected associate and period until an independent Workforce reviewer releases it.">Place hold</SubmitButton></div>
    </form>:null}</section>
    <section className="panel"><div className="panel-head"><h2>Hold history</h2><form method="get"><label>Status<select name="status" className="field" defaultValue={status??''}><option value="">All</option><option value="active">Active</option><option value="release_requested">Release requested</option><option value="released">Released</option></select></label><button className="button secondary" type="submit">Filter</button></form></div><div className="table-wrap"><table><thead><tr><th>Associate / station</th><th>Period</th><th>Reason</th><th>Placed by</th><th>Status / history</th><th>Action</th></tr></thead><tbody>{(holds.data??[]).map(row=><tr key={row.id}><td>{workers.get(row.workforce_id)?.full_name??'Historical associate'}<br/>{workers.get(row.workforce_id)?.dropx_id??row.workforce_id}<br/>{stationNames.get(row.station_id)}</td><td>{row.period_start}<br/>{row.period_end}</td><td>{row.reason}<br/><small>{row.reference}</small></td><td>{names.get(row.requested_by)??row.requested_by}<br/><small>{time(row.requested_at)} IST</small></td><td>{row.status.replaceAll('_',' ')}{row.release_requested_at?<p>Release requested {time(row.release_requested_at)} IST</p>:null}{row.released_at?<p>Released by {names.get(row.released_by)??row.released_by} · {time(row.released_at)} IST<br/>{row.release_note}</p>:null}</td><td>{canEdit&&!auth.readOnly&&row.status!=='released'?reviewer&&row.requested_by!==auth.userId?<form action={action}><input type="hidden" name="action" value="release"/><input type="hidden" name="hold_id" value={row.id}/><input className="field" name="note" placeholder="Release decision reason" required minLength={5}/><SubmitButton pendingText="Releasing">Release hold</SubmitButton></form>:row.requested_by===auth.userId&&row.status==='active'?<form action={action}><input type="hidden" name="action" value="request_release"/><input type="hidden" name="hold_id" value={row.id}/><SubmitButton className="button secondary" pendingText="Requesting">Request release</SubmitButton></form>:'Independent Workforce review required':'—'}</td></tr>)}{!holds.data?.length?<tr><td colSpan={6}>No holds match this view.</td></tr>:null}</tbody></table></div></section></>;
}
