import Link from 'next/link';
import {AppShell} from '@/components/app-shell';
import {requirePagePermission} from '@/lib/authorization';
import {loadCpu} from '@/lib/ops-pulse/dark-store';
import type {CpsParams} from '@/lib/ops-pulse/cps';
import './style.css';
export const dynamic='force-dynamic';export const maxDuration=300;
const money=(n:number|null)=>n===null?'—':'₹'+n.toLocaleString('en-IN',{maximumFractionDigits:2});
export default async function Page({searchParams={}}:{searchParams?:CpsParams}){
 const auth=await requirePagePermission('cps_overview','access');let r;try{r=await loadCpu(auth,searchParams);}catch(e){return <AppShell active="CPU · Cost per unit" pageCode="cps_overview"><p role="alert">{e instanceof Error?e.message:'CPU is unavailable.'}</p><Link href="/cpu">Retry</Link></AppShell>;}
 return <AppShell active="CPU · Cost per unit" pageCode="cps_overview"><div className="cpu"><header><div><p>OPSPULSE · DARK STORE</p><h1>Cost per unit</h1><span>Operating expense ÷ processed units</span></div><Link href="/cpu/master">Update monthly units ↗</Link></header><form className="cpu-panel cpu-filters"><label>Period<select name="period" defaultValue={searchParams.period||'mtd'}><option value="mtd">Month to date</option><option value="monthly">Selected month</option><option value="custom">Custom range</option></select></label><label>Month<input type="month" name="month" defaultValue={r.period.from.slice(0,7)}/></label><label>From<input type="date" name="from" defaultValue={r.period.from}/></label><label>Through<input type="date" name="to" defaultValue={r.period.to}/></label><label>Store<select name="station" defaultValue={searchParams.station||''}><option value="">All my stores</option>{r.locations.map(l=><option key={l.id} value={l.station_code}>{l.station_code} · {l.station_name}</option>)}</select></label><button>Apply</button></form><p className="cpu-note">CPU uses units, never shipments. Monthly cumulative units are spread evenly over the entered days for date-range estimates. Costs use the same period. Central and regional HO allocations are shown separately in Finance P&L.</p><section className="cpu-panel cpu-scroll"><table><thead><tr><th>Store</th><th>Units</th><th>CPU</th><th>Cost details</th></tr></thead><tbody>{!r.rows.length&&<tr><td colSpan={4}>No dark stores are assigned to your access.</td></tr>}{r.rows.map(row=><tr key={row.code}><td><b>{row.code}</b><small>{row.name} · {row.category}</small></td><td>{row.units===null?'Units pending':row.units.toLocaleString('en-IN',{maximumFractionDigits:0})}</td><td><strong>{money(row.cpu)}</strong></td><td><details><summary>View breakdown</summary><p>{row.days} days · through {row.through} · Total {money(row.cost)}</p>{row.groups.map(g=><details key={g.head}><summary>{g.head} · {money(g.cpu)} / unit</summary><p>{money(g.amount)} for this period</p><table><tbody>{g.lines.map((x,i)=><tr key={i}><td>{x.date}</td><td>{x.source}</td><td>{money(x.amount)}</td></tr>)}</tbody></table></details>)}{row.notes.map(n=><p className="cpu-note" key={n}>{n}</p>)}</details></td></tr>)}</tbody></table></section><p className="cpu-note">CPU may vary when source data is updated. Individual HRMS salaries and names are private.</p></div></AppShell>;
}
