'use client';
import {useState,useEffect,useCallback} from 'react';
import styles from './associate-payouts.module.css';
type Row=Record<string,any>;
const money=(v:unknown)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v??0));
export function AssociatePayouts({accountId,profileType}:{accountId:string;profileType:string}){
 const [payouts,setPayouts]=useState<Row[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[selected,setSelected]=useState(''),[tab,setTab]=useState('summary'),[notice,setNotice]=useState('');
 const query=new URLSearchParams({accountId,profileType}).toString();
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch('/api/connect/payout-review?'+query,{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setPayouts(b.payouts);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to load.');}finally{setLoading(false);}},[query]);
 useEffect(()=>{void load();},[load]);
 async function send(e:React.FormEvent<HTMLFormElement>,p:Row,disputeId?:string){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setNotice('');try{const r=await fetch('/api/connect/payout-review?'+query,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:disputeId?'reply':'create',disputeId,publicationId:p.publicationId,category:data.get('category'),reason:data.get('reason')})}),b=await r.json();if(!r.ok)throw new Error(b.error);form.reset();setNotice('Sent to Workforce and your station team.');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to send.');}finally{setBusy(false);}}
 const p=payouts.find(x=>x.id===selected)||payouts[0];
 return <section className={styles.card}><header><h2>Payouts</h2><button onClick={()=>void load()} disabled={loading}>Refresh</button></header>
 {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 {loading?<p>Loading payouts…</p>:!p?<p>{error?'Payouts could not be loaded. Please refresh.':'No payout details published yet.'}</p>:<>
 <label className={styles.period}>Pay period<select value={p.id} onChange={e=>{setSelected(e.target.value);setTab('summary');}}>{payouts.map(x=><option key={x.id} value={x.id}>{x.from} – {x.to}</option>)}</select></label>
 <div className={styles.total}><div><small>{p.status}</small><strong>{money(p.net)}</strong></div><a href={'/api/connect/payout-slip?'+query+'&runId='+encodeURIComponent(p.id)} target="_blank" rel="noreferrer">Download PDF</a></div>
 {p.canDispute?<p className={styles.hint}>Review by {new Date(p.reviewUntil).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · Not yet paid</p>:null}
 {p.revisionPending?<p role="status">A revised calculation is being prepared. These are your last published details.</p>:null}
 <nav className={styles.tabs} aria-label="Payout details">{['summary','deductions','daily','disputes'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='disputes'?'Disputes ('+p.disputes.length+')':t[0].toUpperCase()+t.slice(1)}</button>)}</nav>
 {tab==='summary'?<><div className={styles.counts}>{[['Delivery',p.counts.delivery],['C-return',p.counts.cReturn],['MFN',p.counts.mfn],['MFN return',p.counts.mfnReturn]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div>
 <dl>{[['Base & training',p.base],['Incentives',p.incentive],['Additions',p.additions],['Deductions',-p.deductions],['Net payment',p.net]].map(([k,v])=><div key={k}><dt>{k==='Deductions'?<button onClick={()=>setTab('deductions')}>Deductions →</button>:k}</dt><dd>{money(v)}</dd></div>)}</dl>
 <p>{p.name} · {p.dropxId}<br/>{p.bankAccount} · {p.ifsc}</p><small>Provider IDs: {p.providerIds.join(', ')||'Training'}</small>{p.paymentReference?<p>Reference: {p.paymentReference} · {p.paymentDate}</p>:null}
 </>:null}
 {tab==='deductions'?<>{p.lines.filter((l:Row)=>l.adjustment<0||l.originalAmount<0).map((l:Row,i:number)=><article key={i}><header><b>{l.category.replaceAll('_',' ')}</b><strong>{money(Math.max(0,-l.adjustment))}</strong></header><p>{l.reason||'Contact Workforce for the recorded basis.'}</p><small>{l.date}{l.originalAmount!==null?' · Original deduction '+money(-l.originalAmount):''}</small><button onClick={()=>setTab('disputes')}>Dispute this deduction</button></article>)}{!p.lines.some((l:Row)=>l.adjustment<0||l.originalAmount<0)?<p>No deductions.</p>:null}</>:null}
 {tab==='daily'?<div className={styles.scroll}><table><thead><tr><th>Date / ID</th><th>Delivery</th><th>C-return</th><th>MFN</th><th>MFN return</th><th>Pay</th></tr></thead><tbody>{p.lines.map((l:Row,i:number)=><tr key={i}><td>{l.date}<small>{l.providerId||l.type} · {l.providerName||p.name}</small></td><td>{l.delivery}</td><td>{l.cReturn}</td><td>{l.mfn}</td><td>{l.mfnReturn}</td><td>{money(l.net)}</td></tr>)}</tbody></table></div>:null}
 {tab==='disputes'?<>{p.canDispute?<form onSubmit={e=>void send(e,p)} className={styles.form}><label>What needs checking?<select name="category"><option value="counts">Delivery / return counts</option><option value="training">Training payment</option><option value="loss">Loss recovery</option><option value="tds">TDS</option><option value="other">Other payout issue</option></select></label><label>Details<textarea name="reason" required minLength={10} maxLength={2000} placeholder="Date, amount or count, and what should be corrected"/></label><button disabled={busy}>{busy?'Sending…':'Raise dispute'}</button></form>:<p>This payout is confirmed. Contact support for corrections in the next open period.</p>}
 {p.disputes.map((d:Row)=><article key={d.id}><header><b>{d.category}</b><strong>{d.status.replace('_',' ')}</strong></header>{d.events.map((e:Row)=><p key={e.id}><b>{e.actor_name}</b> · {new Date(e.created_at).toLocaleString('en-IN')}<br/>{e.message}</p>)}{['open','in_review'].includes(d.status)?<form onSubmit={e=>void send(e,p,d.id)} className={styles.form}><label>Reply<textarea name="reason" required minLength={3} maxLength={2000}/></label><button disabled={busy}>Send reply</button></form>:null}</article>)}</>:null}
 </>}</section>;
}
