"use client";

import {
  ArrowLeft, ArrowRight, BadgeCheck, Check, CheckCircle2, ChevronRight, CircleAlert,
  Clock3, Copy, ExternalLink, Fingerprint, LogOut, Mail, RefreshCw, ShieldCheck, Smartphone, TriangleAlert, UserRoundCheck, X
} from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import type { AppAccount } from "./connect-profile-app";

type Stage = "overview" | "attendance" | "registration" | "amazon" | "bgc" | "account" | "activation";
type CheckState = "complete" | "action" | "in_progress" | "pending";
type BgcCheck = { code:string;label:string;status:CheckState;detail:string;owner:string;source:string;updatedAt:string|null };
type ExitReason = { id:string;label:string;description?:string;requires_note:boolean };
type Data = {
  available:boolean;pilot?:boolean;isolatedBeta?:boolean;stage:string;stageLabel:string;instruction?:string;actionOwner?:string;
  driverId?:string|null;biometricId?:string|null;amazonAccountId?:string|null;invitationEmail?:string|null;
  invitationUrl?:string|null;invitationReceivedAt?:string|null;
  invitationStatus?:string|null;registrationRequired?:boolean;registrationStatus?:string|null;registrationUpdatedAt?:string|null;
  offboardingRequested?:boolean;offboardingRequestedAt?:string|null;exitReasons?:ExitReason[];category?:string;amazonAction?:string;
  reportDate?:string|null;reportUpdatedAt?:string|null;updatedAt?:string|null;stale?:boolean;syncDelayed?:boolean;
  bgcChecks?:BgcCheck[];latestAttendance?:{date:string;inTime:string|null;outTime:string|null;status:string|null;updatedAt:string|null}|null;
};
type Milestone = { id:Exclude<Stage,"overview">;label:string;detail:string;status:CheckState;source:string };

const stateLabel:Record<CheckState,string>={complete:"Complete",action:"Action needed",in_progress:"In progress",pending:"Upcoming"};
const inbox=(email?:string|null)=>{const domain=String(email??"").split("@")[1]?.toLowerCase();if(domain?.includes("gmail"))return "https://mail.google.com/";if(domain?.includes("outlook")||domain?.includes("hotmail")||domain?.includes("live."))return "https://outlook.live.com/mail/";if(domain?.includes("yahoo"))return "https://mail.yahoo.com/";return null;};
const displayTime=(value?:string|null)=>value?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Asia/Kolkata"}).format(new Date(value)):"Not yet synced";

function milestoneState(data:Data):Milestone[]{
  const attendanceComplete=Boolean(data.latestAttendance?.inTime&&data.latestAttendance?.outTime);
  const registrationComplete=data.registrationStatus==="submitted"||!data.registrationRequired;
  const invitationComplete=data.invitationStatus==="sent"||Boolean(data.amazonAccountId);
  const bgcAction=Boolean(data.bgcChecks?.some(item=>item.status==="action"));
  const bgcComplete=Boolean(data.bgcChecks?.length)&&data.bgcChecks!.every(item=>item.status==="complete");
  const accountComplete=["scc_pending","scc_available","delivery_started"].includes(data.stage);
  return [
    {id:"attendance",label:"Biometric attendance",detail:attendanceComplete?"IN and OUT punches confirmed.":data.biometricId?"Enrol this ID and complete IN and OUT punches.":"Ask the station team for biometric enrolment.",status:attendanceComplete?"complete":"action",source:"Station biometric device"},
    {id:"registration",label:"DropX registration",detail:registrationComplete?"Submitted for Workforce confirmation.":"Confirm your details and submit the registration.",status:registrationComplete?"complete":"action",source:"DropX registration + Workforce review"},
    {id:"amazon",label:"Amazon invitation",detail:invitationComplete?"Invitation sent to the displayed work email.":"The station or Workforce team must send the invitation.",status:invitationComplete?"complete":"in_progress",source:"Amazon LSC invitation queue"},
    {id:"bgc",label:"Background verification",detail:bgcAction?`${data.bgcChecks?.filter(item=>item.status==="action").length} check(s) need attention.`:bgcComplete?"All received checks are clear.":"Verification is continuing check by check.",status:bgcAction?"action":bgcComplete?"complete":invitationComplete?"in_progress":"pending",source:"IDfy; DA In-App only as fallback"},
    {id:"account",label:"Account setup and UAN",detail:accountComplete?"Amazon account setup is complete.":"UAN and provisioning are tracked inside account setup.",status:accountComplete?"complete":data.stage==="verification_pending"?"in_progress":"pending",source:"Amazon LSC profile; DA In-App fallback"},
    {id:"activation",label:"Driver ID and first delivery",detail:data.driverId?`LSC Driver ID ${data.driverId} received.`:"Driver ID appears only after Amazon returns it.",status:data.driverId?"complete":"pending",source:"Amazon LSC / SCC + daily shipment count"}
  ];
}

function StateBadge({state}:{state:CheckState}){return <span className={`dx-beta-state ${state}`}>{state==="complete"?<Check size={13}/>:state==="action"?<CircleAlert size={13}/>:<Clock3 size={13}/>} {stateLabel[state]}</span>;}
function Soc({children,updated}:{children:string;updated?:string|null}){return <p className="dx-beta-soc"><ShieldCheck size={13}/>Source of confirmation: {children}<span>{displayTime(updated)}</span></p>;}

export function ConnectBetaOnboarding({account,onRegister}:{account:AppAccount;onRegister:()=>void}){
  const [data,setData]=useState<Data|null>(null),[view,setView]=useState<Stage>("overview"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[refreshing,setRefreshing]=useState(false),[refresh,setRefresh]=useState(0);
  const [copied,setCopied]=useState<"email"|"link"|null>(null);
  const [exitOpen,setExitOpen]=useState(false),[reasonId,setReasonId]=useState(""),[exitNote,setExitNote]=useState(""),[exitError,setExitError]=useState(""),[exitSaving,setExitSaving]=useState(false);
  const latest=useRef<Data|null>(null);
  useEffect(()=>{let disposed=false;const controller=new AbortController();const timer=window.setTimeout(()=>controller.abort(),12000);const run=async()=>{setRefreshing(Boolean(latest.current));if(!latest.current)setLoading(true);try{const query=new URLSearchParams({accountId:account.id,profileType:account.profileType});const response=await fetch(`/api/connect/workforce-joining?${query}`,{cache:"no-store",signal:controller.signal});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to load work setup.");if(!disposed){latest.current=payload;setData(payload);setError("");}}catch(reason){if(!disposed)setError(reason instanceof Error?reason.message:"Unable to load work setup.");}finally{window.clearTimeout(timer);if(!disposed){setLoading(false);setRefreshing(false);}}};void run();return()=>{disposed=true;controller.abort();window.clearTimeout(timer);};},[account.id,account.profileType,refresh]);
  useEffect(()=>{const timer=window.setInterval(()=>{if(document.visibilityState==="visible"&&navigator.onLine)setRefresh(value=>value+1);},30000);return()=>window.clearInterval(timer);},[]);

  const milestones=useMemo(()=>data?milestoneState(data).filter(item=>!(data.isolatedBeta&&item.id==="registration")):[],[data]);
  const done=milestones.filter(item=>item.status==="complete").length;
  const next=milestones.find(item=>item.status==="action")??milestones.find(item=>item.status==="in_progress")??milestones.find(item=>item.status==="pending");
  const selected=view==="overview"?null:milestones.find(item=>item.id===view)??null;

  const submitExit=async(event:FormEvent)=>{event.preventDefault();setExitError("");const reason=data?.exitReasons?.find(item=>item.id===reasonId);if(!reason){setExitError("Choose why you are not continuing.");return;}if(reason.requires_note&&exitNote.trim().length<3){setExitError("Add a short note for this reason.");return;}setExitSaving(true);try{const response=await fetch("/api/connect/workforce-joining",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:account.id,profileType:account.profileType,action:"not_continuing",reasonId,note:exitNote.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to save your decision.");setExitOpen(false);setRefresh(value=>value+1);}catch(reason){setExitError(reason instanceof Error?reason.message:"Unable to save your decision.");}finally{setExitSaving(false);}};
  const copyValue=async(kind:"email"|"link",value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(kind);window.setTimeout(()=>setCopied(current=>current===kind?null:current),1800);}catch{setError("Copy was blocked by the browser. Press and hold the value to copy it.");}};

  if(loading&&!data)return <section className="dx-main dx-beta-onboarding"><div className="dx-beta-loading" role="status"><span className="mini-spin"/>Loading your work setup…</div></section>;
  if(!data)return <section className="dx-main dx-beta-onboarding"><div className="dx-alert error">{error||"Work setup is unavailable."}<button onClick={()=>setRefresh(value=>value+1)}>Retry</button></div></section>;

  const workEmail=data.invitationEmail||account.email||"Work email not assigned";
  const mailHref=inbox(workEmail);
  const renderDetail=()=>{
    if(view==="attendance")return <><div className="dx-beta-focus"><i><Fingerprint/></i><div><small>Biometric enrolment ID</small><strong>{data.biometricId||"Ask your station team"}</strong><p>This number is only for attendance. Punch IN before work and OUT after work every day.</p></div></div><div className="dx-beta-punches"><div className={data.latestAttendance?.inTime?"done":""}><span>IN punch</span><strong>{data.latestAttendance?.inTime?"Confirmed":"Pending"}</strong></div><div className={data.latestAttendance?.outTime?"done":""}><span>OUT punch</span><strong>{data.latestAttendance?.outTime?"Confirmed":"Pending"}</strong></div></div><Soc updated={data.latestAttendance?.updatedAt}>Station biometric device</Soc></>;
    if(view==="registration")return <><div className="dx-beta-focus"><i><UserRoundCheck/></i><div><small>DropX registration</small><strong>{data.registrationStatus==="submitted"?"Submitted for review":"Complete your details"}</strong><p>The invitation creates this private registration task. There is no open public self-registration.</p></div></div>{data.registrationRequired?<button className="dx-beta-primary" type="button" onClick={onRegister}>Complete registration <ArrowRight size={16}/></button>:<div className="dx-beta-success"><CheckCircle2/>Registration submitted. Workforce can review and confirm it.</div>}<Soc updated={data.registrationUpdatedAt}>DropX registration and Workforce confirmation</Soc></>;
    if(view==="amazon")return <><div className="dx-beta-email"><Mail/><span><small>Amazon account email</small><strong>{workEmail}</strong></span><button aria-label="Copy Amazon account email" onClick={()=>void copyValue("email",workEmail)}><Copy/>{copied==="email"?"Copied":"Copy"}</button></div>{data.invitationUrl?<><div className="dx-beta-invite-ready"><CheckCircle2/><span><strong>Your Amazon invitation is ready</strong><small>Received {displayTime(data.invitationReceivedAt)}</small></span></div><div className="dx-beta-browser-safety"><TriangleAlert/><span><strong>Use the correct Amazon account</strong><small>If another Amazon account is already open, sign out first. The safer option is to copy this link and paste it into a private/incognito window.</small></span></div><div className="dx-beta-action-row"><a className="dx-beta-primary" href={data.invitationUrl} target="_blank" rel="noopener noreferrer"><ExternalLink/>Open invitation</a><button type="button" onClick={()=>void copyValue("link",data.invitationUrl!)}><Copy/>{copied==="link"?"Link copied":"Copy link"}</button></div></>:<div className="dx-beta-empty"><Clock3/><strong>Invitation link is not available yet</strong><span>This page refreshes automatically when the Amazon email arrives.</span></div>}<ol className="dx-beta-guide"><li><b>1</b><span>Sign out of any Amazon account already open in your browser, or use a private/incognito window.</span></li><li><b>2</b><span>Open the invitation and continue with <strong>{workEmail}</strong>.</span></li><li><b>3</b><span>Fill the requested details, upload documents and create the Amazon account.</span></li><li><b>4</b><span>Install the official Amazon Flex app from Google Play and sign in with the same Amazon account.</span></li><li><b>5</b><span>Return here to follow background verification, account setup and Driver ID.</span></li></ol><a className="dx-beta-store-link" href="https://play.google.com/store/apps/details?id=com.amazon.flex.rabbit" target="_blank" rel="noopener noreferrer"><Smartphone/>Get Amazon Flex on Google Play <ArrowRight/></a>{!data.isolatedBeta&&mailHref?<a className="dx-beta-secondary-link" href={mailHref} target="_blank" rel="noreferrer">Open email inbox</a>:null}<Soc updated={data.invitationReceivedAt??data.updatedAt}>Amazon invitation email received by DropX</Soc></>;
    if(view==="bgc")return <>{data.bgcChecks?.length?<div className="dx-beta-checks">{data.bgcChecks.map(item=><article key={item.code}><i className={item.status}>{item.status==="complete"?<Check/>:item.status==="action"?<CircleAlert/>:<Clock3/>}</i><span><strong>{item.label}</strong><small>{item.detail}</small><em>Owner: {item.owner}</em></span><StateBadge state={item.status}/></article>)}</div>:<div className="dx-beta-empty"><ShieldCheck/><strong>Waiting for IDfy check details</strong><span>The worker has not returned individual checks yet. DA In-App remains a fallback for the overall stage.</span></div>}<Soc updated={data.reportUpdatedAt}>IDfy candidate profile; DA In-App onboarding as fallback</Soc></>;
    if(view==="account")return <><div className="dx-beta-focus"><i><BadgeCheck/></i><div><small>Amazon account setup</small><strong>{["scc_pending","scc_available","delivery_started"].includes(data.stage)?"Provisioning complete":"Setup in progress"}</strong><p>UAN is one task inside account setup. It is not shown as a separate lifecycle milestone.</p></div></div><div className="dx-beta-checks"><article><i className="in_progress"><Clock3/></i><span><strong>UAN update</strong><small>Complete or confirm UAN when Amazon requests it.</small><em>Owner: Associate / Amazon</em></span><StateBadge state={data.stage==="scc_pending"||data.driverId?"complete":"in_progress"}/></article><article><i className="in_progress"><Clock3/></i><span><strong>Account provisioning</strong><small>{data.amazonAction||data.instruction||"Amazon is processing the operational account."}</small><em>Owner: Amazon</em></span><StateBadge state={data.driverId?"complete":"in_progress"}/></article></div><Soc updated={data.reportUpdatedAt}>Amazon LSC profile; DA In-App onboarding fallback</Soc></>;
    return <><div className="dx-beta-focus"><i><BadgeCheck/></i><div><small>LSC Driver ID</small><strong>{data.driverId||"Waiting for Amazon LSC"}</strong><p>{data.driverId?"This is your operational Driver ID. Your biometric ID remains attendance-only.":"No DropX employee ID is substituted here. The Driver ID appears only when LSC returns it."}</p></div></div><div className="dx-beta-checks"><article><i className={data.driverId?"complete":"pending"}>{data.driverId?<Check/>:<Clock3/>}</i><span><strong>Driver ID received</strong><small>{data.driverId?"Exact LSC identity connected.":"Waiting for exact LSC evidence."}</small><em>Owner: Amazon / station team</em></span><StateBadge state={data.driverId?"complete":"pending"}/></article><article><i className={data.stage==="delivery_started"?"complete":"pending"}>{data.stage==="delivery_started"?<Check/>:<Clock3/>}</i><span><strong>First delivery confirmed</strong><small>Confirmed only from Amazon daily shipment count.</small><em>Owner: System</em></span><StateBadge state={data.stage==="delivery_started"?"complete":"pending"}/></article></div><Soc updated={data.updatedAt}>Amazon LSC / SCC and Amazon daily shipment count</Soc></>;
  };

  return <section className="dx-main dx-beta-onboarding">
    <header className="dx-beta-heading"><div><small>DROPX ONE · PRIVATE BETA</small><h1>{view==="overview"?"Your work setup":selected?.label}</h1><p>{view==="overview"?"Follow one guided journey. Every milestone shows its owner, action and source of confirmation.":selected?.detail}</p></div><button aria-label="Refresh work setup" disabled={refreshing} onClick={()=>setRefresh(value=>value+1)}><RefreshCw className={refreshing?"dx-spin":""}/></button></header>
    {error?<div className="dx-joining-error" role="alert"><strong>Status refresh paused</strong><span>{error}</span></div>:null}
    {data.offboardingRequested?<div className="dx-setup-stopped"><LogOut/><div><strong>You told us you are not continuing</strong><span>Workforce can review and reactivate this beta onboarding if this was a mistake.</span></div></div>:null}
    <nav className="dx-beta-stage-nav" aria-label="Work setup milestones">{milestones.map((item,index)=><button aria-current={view===item.id?"step":undefined} className={`${item.status}${view===item.id?" active":""}`} key={item.id} onClick={()=>setView(item.id)}><b>{item.status==="complete"?<Check size={13}/>:index+1}</b><span>{item.label}</span></button>)}</nav>
    {view==="overview"?<div className="dx-beta-grid"><section className="dx-beta-card dx-beta-progress-card"><div className="dx-beta-progress-head"><span><small>Joining progress</small><strong>{done} of {milestones.length} confirmed</strong></span><b>{Math.round(done/milestones.length*100)}%</b></div><div className="dx-beta-progress"><span style={{width:`${done/milestones.length*100}%`}}/></div><div className="dx-beta-list">{milestones.map(item=><button key={item.id} onClick={()=>setView(item.id)}><i className={item.status}>{item.status==="complete"?<Check/>:item.status==="action"?<CircleAlert/>:<Clock3/>}</i><span><strong>{item.label}</strong><small>{item.detail}</small></span><StateBadge state={item.status}/><ChevronRight/></button>)}</div></section><aside className="dx-beta-side"><section className="dx-beta-card"><small>NEXT ACTION</small><h2>{next?.label||"Setup complete"}</h2><p>{next?.detail||"Your work workspace will open after activation."}</p>{next?<button className="dx-beta-primary" onClick={()=>setView(next.id)}>Open next step <ArrowRight size={16}/></button>:null}</section><section className="dx-beta-card dx-beta-identity"><small>YOUR IDENTIFIERS</small><dl><div><dt>Biometric ID</dt><dd>{data.biometricId||"Pending"}</dd></div><div><dt>Invitation email</dt><dd>{workEmail}</dd></div><div><dt>LSC Driver ID</dt><dd>{data.driverId||"Created later by Amazon"}</dd></div></dl></section></aside></div>:<section className="dx-beta-card dx-beta-detail"><button className="dx-beta-back" onClick={()=>setView("overview")}><ArrowLeft/>All milestones</button>{renderDetail()}</section>}
    {!data.isolatedBeta&&!data.offboardingRequested?<footer className="dx-beta-decision"><span><strong>Not continuing with this role?</strong><small>Tell Workforce why. Your beta onboarding can be reactivated later.</small></span><button onClick={()=>setExitOpen(true)}>I’m not continuing</button></footer>:null}
    {exitOpen?<div className="dx-exit-dialog" role="dialog" aria-modal="true" aria-labelledby="beta-exit-title"><button className="dx-exit-close" type="button" aria-label="Close" onClick={()=>setExitOpen(false)}><X/></button><form onSubmit={submitExit}><small>LEAVE ONBOARDING</small><h3 id="beta-exit-title">Tell us why you’re not continuing</h3><p>This closes only your private beta onboarding.</p><label>Reason<select required value={reasonId} onChange={event=>setReasonId(event.target.value)}><option value="">Choose a reason</option>{data.exitReasons?.map(reason=><option value={reason.id} key={reason.id}>{reason.label}</option>)}</select></label><label>Additional detail <span>optional unless requested</span><textarea value={exitNote} maxLength={1000} onChange={event=>setExitNote(event.target.value)}/></label>{exitError?<div className="dx-joining-error" role="alert">{exitError}</div>:null}<footer><button type="button" onClick={()=>setExitOpen(false)}>Go back</button><button className="danger" disabled={exitSaving||!data.exitReasons?.length}>{exitSaving?"Saving…":"Confirm I’m not continuing"}</button></footer></form></div>:null}
  </section>;
}
