'use client';
import { useEffect,useState } from 'react';
import { BookOpen,CalendarDays,CheckCircle2,ExternalLink,RefreshCw } from 'lucide-react';
import type { AppAccount } from './connect-profile-app';
import type { TrainingPublicQuestion } from '../lib/connect-training-policy';
import styles from './connect-training.module.css';
type Enrolment={id:string;programme_name:string;starts_on:string;target_completion_on:string|null;status:string};
type Milestone={id:string;enrolment_id:string;title:string;description:string|null;milestone_kind:string;due_on:string;status:string;scheduled_start:string|null;scheduled_end:string|null;meeting_mode:string|null;meeting_reference:string|null;trainer_name:string|null;completion_rule:string;pass_percent:number|null;max_attempts:number|null;questions:TrainingPublicQuestion[];material_ids:string[];effectiveness_rating:number|null};
type Payload={enrolments:Enrolment[];milestones:Milestone[];materials:{id:string;title:string;kind:string}[];attempts:{id:string;milestone_id:string;attempt_number:number;percent:number;passed:boolean}[];reviews:{id:string;enrolment_id:string;due_on:string;status:string;overall_rating:number|null;decision_note:string|null}[]};
const label=(s:string)=>s.replaceAll('_',' ');
const date=(s:string|null,time=false)=>s?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',...(time?{timeStyle:'short' as const}:{}),timeZone:'Asia/Kolkata'}).format(new Date(s.length===10?`${s}T12:00:00+05:30`:s)):'Not scheduled';
export function ConnectTraining({account}:{account:AppAccount}){
 const [data,setData]=useState<Payload|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState('open'),[refresh,setRefresh]=useState(0),[busy,setBusy]=useState(false);
 const query=new URLSearchParams({accountId:account.id,profileType:account.profileType}).toString();
 useEffect(()=>{const abort=new AbortController();setError('');fetch(`/api/connect/training?${query}`,{cache:'no-store',signal:abort.signal}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setData(p);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[query,refresh]);
 async function submit(body:Record<string,unknown>){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/connect/training',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,accountId:account.id,profileType:account.profileType})});const p=await r.json();if(!r.ok)throw new Error(p.error);setNotice(p.notice);setRefresh(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 const shown=data?.enrolments.filter(e=>filter==='all'||(filter==='completed'?e.status==='completed':!['completed','cancelled'].includes(e.status)))??[];
 return <section className={styles.root}><header className={styles.header}><div><small>My development</small><h1>Training</h1><p>Your learning, sessions and milestones.</p></div><button aria-label="Refresh training" onClick={()=>setRefresh(v=>v+1)}><RefreshCw size={18}/></button></header>
 <nav className="dx-performance-sections" aria-label="Training status">{[['open','To do'],['completed','Completed'],['all','All training']].map(([v,l])=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{l}</button>)}</nav>
 {error?<div role="alert" className="dx-alert error">{error}</div>:null}{notice?<div role="status" className="dx-alert success">{notice}</div>:null}
 {!data&&!error?<p>Loading training…</p>:null}
 {shown.map(e=>{const steps=data!.milestones.filter(m=>m.enrolment_id===e.id);const done=steps.filter(m=>['completed','waived'].includes(m.status)).length;const review=data!.reviews.find(r=>r.enrolment_id===e.id);return <article className={styles.card} key={e.id}><header><div><strong>{e.programme_name}</strong><small>Started {date(e.starts_on)} · {done}/{steps.length} complete</small></div><span className="dx-performance-status pending">{label(e.status)}</span></header><progress aria-label={`${e.programme_name} progress`} max={steps.length||1} value={done}/>
 {steps.map(m=>{const attempts=data!.attempts.filter(a=>a.milestone_id===m.id);const closed=['completed','waived','cancelled'].includes(m.status)||e.status==='cancelled';return <details className={styles.milestone} key={m.id}><summary>{closed?<CheckCircle2 size={18}/>:<BookOpen size={18}/>}<span><strong>{m.title}</strong><small>{label(m.status)} · Due {date(m.due_on)}</small></span></summary><div className={styles.content}>
 {m.description?<p>{m.description}</p>:null}<div className={styles.facts}><span><CalendarDays size={16}/> {date(m.scheduled_start,true)}</span><span>Trainer: {m.trainer_name??'To be assigned'}</span>{m.meeting_mode?<span>{label(m.meeting_mode)}</span>:null}</div>
 {m.meeting_reference?.startsWith('https://')?<a className={styles.primary} href={m.meeting_reference} target="_blank" rel="noreferrer">Join session <ExternalLink size={15}/></a>:m.meeting_reference?<p>Venue / reference: {m.meeting_reference}</p>:null}
 <div className={styles.links}>{m.material_ids.map(id=><a key={id} href={`/api/connect/training?${query}&materialId=${id}&milestoneId=${m.id}`} target="_blank" rel="noreferrer"><BookOpen size={16}/>{data!.materials.find(x=>x.id===id)?.title??'Material'}<ExternalLink size={14}/></a>)}</div>
 {attempts.length?<p>{attempts.map(a=>`Attempt ${a.attempt_number}: ${a.percent}% ${a.passed?'· Passed':''}`).join(' · ')}</p>:null}
 {!closed&&m.completion_rule==='acknowledge'&&m.milestone_kind!=='assessment'?<button className={styles.primary} disabled={busy} onClick={()=>void submit({action:'acknowledge',milestoneId:m.id})}>I have completed this learning</button>:null}
 {!closed&&m.milestone_kind==='assessment'?(m.questions.length&&!m.questions.some(q=>q.question_type==='text')&&(!m.max_attempts||attempts.length<m.max_attempts)?<form onSubmit={ev=>{ev.preventDefault();const form=new FormData(ev.currentTarget);const answers=Object.fromEntries(m.questions.map(q=>[q.id,form.getAll(q.id).map(String)]));void submit({action:'assessment',milestoneId:m.id,answers});}}><p>Pass: {m.pass_percent}% · {m.max_attempts?`${m.max_attempts-attempts.length} attempts left`:'Trainer-configured attempts'}</p>{m.questions.map(q=><fieldset className={styles.question} key={q.id}><legend>{q.prompt}</legend>{q.options.map(option=><label key={option}><input name={q.id} type={q.question_type==='multiple_choice'?'checkbox':'radio'} value={option} required={q.question_type!=='multiple_choice'}/>{option}</label>)}</fieldset>)}<button className={styles.primary} disabled={busy}>{busy?'Submitting…':'Submit test'}</button></form>:<p>Contact your trainer for this assessment.</p>):!closed&&m.completion_rule==='trainer'?<small>Completion is confirmed by your trainer.</small>:null}
 {m.effectiveness_rating?<p>Effectiveness: {m.effectiveness_rating}/5</p>:null}</div></details>;})}
 {review?<details className={styles.milestone}><summary><CalendarDays size={18}/><span><strong>Probation review</strong><small>{label(review.status)} · {date(review.due_on)}</small></span></summary><div className={styles.content}>{review.overall_rating?<p>{review.overall_rating}/5</p>:<p>Your manager will complete this review.</p>}{review.decision_note?<p>{review.decision_note}</p>:null}</div></details>:null}</article>;})}
 {data&&!shown.length?<div className="dx-performance-empty"><BookOpen/><strong>{filter==='completed'?'No completed training yet':'No training assigned'}</strong><span>Training assigned by HR will appear here.</span></div>:null}</section>;
}
