"use client";

import { FormEvent,useEffect,useRef,useState } from "react";
import { ArrowRight,BookOpen,CheckCircle2,Fingerprint,LogOut,Mail,RefreshCw,UserRoundCheck,X } from "lucide-react";
import type { AppAccount } from "./connect-profile-app";

type ExitReason={id:string;label:string;description?:string;requires_note:boolean};
type Data={pilot?:boolean;stale?:boolean;syncDelayed?:boolean;reportDate?:string;driverId?:string|null;biometricId?:string;amazonAccountId?:string|null;invitationEmail?:string|null;registrationRequired?:boolean;registrationStatus?:string|null;offboardingRequested?:boolean;offboardingRequestedAt?:string|null;exitReasons?:ExitReason[];actionOwner?:string;category?:string;amazonAction?:string;instruction?:string;reportUpdatedAt?:string|null;available:boolean;stage:string;stageLabel:string;configured:boolean;mode:string|null;firstPunch:string|null;mappingEffectiveFrom:string|null;providerStage:string|null;nextFollowUp:string|null;updatedAt:string|null;paymentHolds?:Array<{id:string;from:string;to:string;status:string;placedAt:string}>;tasks:Array<{code:string;label:string;status:string}>;training:null|{dailyRate:number|null;minimumMinutes:number;acceptedOn:string;eligibleDays:number;reviewDays:number;eligibleAmount:number|null;days:Array<{date:string;minutes:number;amount:number|null;holds:string[]}>}};

const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value);
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(new Date(`${value.slice(0,10)}T00:00:00+05:30`)):"Not yet";
const invitedInbox=(email?:string|null)=>{const domain=String(email??"").split("@")[1]?.toLowerCase();if(domain?.includes("gmail"))return {label:"Open Gmail inbox",href:"https://mail.google.com/"};if(domain?.includes("outlook")||domain?.includes("hotmail")||domain?.includes("live."))return {label:"Open Outlook inbox",href:"https://outlook.live.com/mail/"};if(domain?.includes("yahoo"))return {label:"Open Yahoo inbox",href:"https://mail.yahoo.com/"};return null;};

export function ConnectWorkforceJoining({account,compact=false,activationOnly=false,onRegister}:{account:AppAccount;compact?:boolean;activationOnly?:boolean;onRegister?:()=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(false),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[refresh,setRefresh]=useState(0);
 const [exitOpen,setExitOpen]=useState(false),[reasonId,setReasonId]=useState(""),[exitNote,setExitNote]=useState(""),[exitError,setExitError]=useState(""),[exitSaving,setExitSaving]=useState(false);
 const dataRef=useRef<Data|null>(null);
 useEffect(()=>{dataRef.current=null;setData(null);},[account.id,account.profileType]);
 useEffect(()=>{
  let disposed=false,inFlight=false,activeController:AbortController|null=null;
  const query=new URLSearchParams({accountId:account.id,profileType:account.profileType});
  const load=async(initial=false)=>{if(inFlight||disposed)return;inFlight=true;if(initial&&!dataRef.current)setLoading(true);else setRefreshing(true);const controller=new AbortController();activeController=controller;const timeout=window.setTimeout(()=>controller.abort(),12000);try{const response=await fetch(`/api/connect/workforce-joining?${query}`,{cache:"no-store",signal:controller.signal});if(!response.ok)throw new Error("Unavailable");const payload=await response.json();if(!disposed){dataRef.current=payload;setData(payload);setError(false);}}catch{if(!disposed)setError(true);}finally{window.clearTimeout(timeout);inFlight=false;if(!disposed){setLoading(false);setRefreshing(false);}}};
  void load(true);const poll=()=>{if(document.visibilityState==="visible"&&navigator.onLine)void load(false);};const timer=window.setInterval(poll,30000);document.addEventListener("visibilitychange",poll);window.addEventListener("online",poll);return()=>{disposed=true;activeController?.abort();window.clearInterval(timer);document.removeEventListener("visibilitychange",poll);window.removeEventListener("online",poll);};
 },[account.id,account.profileType,refresh]);

 const submitExit=async(event:FormEvent)=>{event.preventDefault();setExitError("");const reason=data?.exitReasons?.find(item=>item.id===reasonId);if(!reason){setExitError("Choose why you are not continuing.");return;}if(reason.requires_note&&exitNote.trim().length<3){setExitError("Add a short note for this reason.");return;}setExitSaving(true);try{const response=await fetch("/api/connect/workforce-joining",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({accountId:account.id,profileType:account.profileType,action:"not_continuing",reasonId,note:exitNote.trim()})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Unable to save your decision.");setExitOpen(false);setRefresh(value=>value+1);}catch(saveError){setExitError(saveError instanceof Error?saveError.message:"Unable to save your decision.");}finally{setExitSaving(false);}};
 const accountNeedsRegistration=["pending","returned"].includes(String(account.status??"").toLowerCase());
 const registrationRequired=Boolean(onRegister&&(data?.registrationRequired||(!data&&accountNeedsRegistration)));
 if(!loading&&!error&&!data?.available&&!registrationRequired)return null;
 const inbox=invitedInbox(data?.invitationEmail);
 const registrationDone=data?.registrationStatus==="submitted"||!registrationRequired;

 return <section className="dx-dashboard-card dx-joining-card" aria-label={activationOnly?"Work setup status":"Joining status"}>
  <header><div><small>{activationOnly?"BETA ONBOARDING":"My journey"}</small><h2>{activationOnly?"Your day-one setup":"Joining status"}</h2></div><button type="button" aria-label="Refresh joining status" disabled={refreshing} onClick={()=>setRefresh(value=>value+1)}><RefreshCw className={refreshing?"dx-spin":""} size={17}/></button></header>
  {error?<div className="dx-joining-error" role="alert"><strong>Status refresh paused</strong><span>{data?"Showing the last available update.":"Use refresh to try again."}</span></div>:null}
  {loading&&!data?<p role="status">Loading your joining status…</p>:data?.pilot?<>
   {data.offboardingRequested?<div className="dx-setup-stopped" role="status"><LogOut size={18}/><div><strong>You told us you are not continuing</strong><span>Your Workforce team can review and reactivate this onboarding if this was a mistake or you decide to return.</span></div></div>:<div className="dx-setup-current"><span>Current Amazon status</span><strong>{data.stageLabel}</strong><p>{data.instruction}</p></div>}
   <div className="dx-setup-steps" aria-label="Day-one actions">
    <article className="dx-setup-step"><header><span>1</span><small>DO TODAY</small>{data.biometricId?<CheckCircle2 size={17}/>:<Fingerprint size={17}/>}</header><div className="dx-setup-step-icon"><Fingerprint size={20}/></div><h3>Biometric attendance</h3><p>Ask your station team to enrol this ID on the biometric device.</p><strong className="dx-setup-code">{data.biometricId||"Ask station team"}</strong><p className="dx-setup-hint">Punch <b>IN</b> before work and <b>OUT</b> after work every day. This ID is only for attendance.</p></article>
    <article className="dx-setup-step"><header><span>2</span><small>DO TODAY</small>{registrationDone?<CheckCircle2 size={17}/>:<UserRoundCheck size={17}/>}</header><div className="dx-setup-step-icon"><UserRoundCheck size={20}/></div><h3>DropX registration</h3><p>Confirm your personal details and submit them for Workforce review.</p>{registrationDone?<div className="dx-setup-complete"><CheckCircle2 size={15}/> Submitted for review</div>:onRegister&&!data.offboardingRequested?<button className="dx-setup-primary" type="button" onClick={onRegister}>Complete registration <ArrowRight size={16}/></button>:null}</article>
    <article className="dx-setup-step"><header><span>3</span><small>AFTER TRAINING</small>{data.driverId?<CheckCircle2 size={17}/>:<Mail size={17}/>}</header><div className="dx-setup-step-icon"><Mail size={20}/></div><h3>Amazon Driver ID setup</h3><p>Attend training for 1–2 days. If the job suits you, open the invitation sent to:</p><strong className="dx-setup-email">{data.invitationEmail||"Your invited Amazon email"}</strong><p className="dx-setup-hint">Open this exact email account on your mobile or browser, accept the Amazon invitation, and complete the steps in Flex Pro.</p>{!data.offboardingRequested?<div className="dx-setup-actions">{inbox?<a href={inbox.href} target="_blank" rel="noreferrer"><Mail size={15}/>{inbox.label}</a>:null}<a href="/guides/amazon-da-onboarding-guide.pdf" target="_blank" rel="noreferrer"><BookOpen size={15}/>Open step-by-step guide</a></div>:null}<div className="dx-driver-result"><span>LSC Driver ID</span><strong>{data.driverId||"Created after Amazon setup"}</strong><small>{data.driverId?"Received from LSC / SCC":"This will appear automatically after Amazon setup is completed and LSC returns it."}</small></div></article>
   </div>
   {!data.offboardingRequested?<div className="dx-setup-decision"><div><strong>Does this role work for you?</strong><span>Complete Amazon setup if you want to continue. If you do not want the job, tell Workforce here.</span></div><button type="button" onClick={()=>setExitOpen(true)}>I’m not continuing</button></div>:null}
   {exitOpen?<div className="dx-exit-dialog" role="dialog" aria-modal="true" aria-labelledby="exit-title"><button className="dx-exit-close" type="button" aria-label="Close" onClick={()=>setExitOpen(false)}><X size={17}/></button><form onSubmit={submitExit}><small>LEAVE ONBOARDING</small><h3 id="exit-title">Tell us why you’re not continuing</h3><p>This closes only your beta onboarding. Workforce can reactivate it later.</p><label>Reason<select required value={reasonId} onChange={event=>setReasonId(event.target.value)}><option value="">Choose a reason</option>{data.exitReasons?.map(reason=><option value={reason.id} key={reason.id}>{reason.label}</option>)}</select></label><label>Additional detail <span>optional unless requested</span><textarea value={exitNote} maxLength={1000} onChange={event=>setExitNote(event.target.value)} placeholder="Add a short note for Workforce"/></label>{exitError?<div className="dx-joining-error" role="alert">{exitError}</div>:null}<footer><button type="button" onClick={()=>setExitOpen(false)}>Go back</button><button className="danger" disabled={exitSaving||!data.exitReasons?.length}>{exitSaving?"Saving…":"Confirm I’m not continuing"}</button></footer>{!data.exitReasons?.length?<p className="dx-exit-unavailable">Workforce has not configured exit reasons yet. Contact your station team.</p>:null}</form></div>:null}
   {data.stale||data.syncDelayed?<p role="status" className="dx-joining-note">The partner report sync is delayed. Your invitation and registration details above remain available.</p>:null}
  </>:data?<>
   <div className="dx-joining-status"><strong>{data.stageLabel}</strong><span>{data.instruction||(data.mappingEffectiveFrom?`Work assignment effective ${date(data.mappingEffectiveFrom)}`:data.configured?"Partner ID or commercial terms pending":"Your station team will confirm your joining plan.")}</span></div>
   {registrationRequired?<button className="dx-registration-cta" type="button" onClick={onRegister}><span><strong>Complete DropX registration</strong><small>Confirm your details and submit them for Workforce review.</small></span><ArrowRight size={18}/></button>:null}
   {!activationOnly&&data.paymentHolds?.length?<div role="status" className="dx-joining-note"><strong>Payment on hold</strong><p>Your earnings are retained—not deducted. Contact your station team for review.</p><ul>{data.paymentHolds.map(hold=><li key={hold.id}>{date(hold.from)} – {date(hold.to)} · {hold.status==='release_requested'?'Release awaiting review':'Active hold'}</li>)}</ul></div>:null}
   {!activationOnly&&data.training?<><div className="dx-joining-metrics"><div><small>Eligible training days</small><strong>{data.training.eligibleDays}</strong></div><div><small>Days needing review</small><strong>{data.training.reviewDays}</strong></div>{data.training.eligibleAmount!==null?<div><small>Training estimate · to date</small><strong>{money(data.training.eligibleAmount)}</strong></div>:null}</div><p>{data.training.dailyRate!==null?`${money(data.training.dailyRate)} / eligible day · `:""}{data.training.minimumMinutes} minimum biometric minutes · terms accepted {date(data.training.acceptedOn)}.</p>{!compact?<details><summary>Training attendance and review reasons</summary>{data.training.days.length?<ul className="dx-joining-days">{data.training.days.map(day=><li key={day.date}><div><strong>{date(day.date)}</strong><span>{day.minutes} minutes · {day.holds.length?"Review required":"Eligible for payroll review"}{day.amount!==null?` · ${money(day.amount)}`:""}</span></div>{day.holds.length?<ul>{day.holds.map(reason=><li key={reason}>{reason}</li>)}</ul>:null}</li>)}</ul>:<p>No training attendance recorded yet.</p>}</details>:null}</>:!activationOnly&&data.mode==="direct"?<p>Regular earnings start under your effective provider and rate mapping.</p>:null}
   {data.tasks.length&&!['active','offboarded','closed'].includes(data.stage)?<details><summary>DA In-App checklist</summary><ul className="dx-joining-tasks">{data.tasks.map(task=><li key={task.code}><span>{task.label}</span><strong>{task.status}</strong></li>)}</ul></details>:null}
  </>:registrationRequired?<button className="dx-registration-cta" type="button" onClick={onRegister}><span><strong>Complete DropX registration</strong><small>Confirm your details and submit them for Workforce review.</small></span><ArrowRight size={18}/></button>:null}
 </section>;
}
