"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";

type Account = { id: string; name: string | null; email: string | null; reference: string | null; companyName: string };
type ExitCase = { id: string; caseNumber: string; scenario: string; status: string; stage: string; reason: string; comments: string; requestedLastWorkingDate: string | null; approvedLastWorkingDate: string | null; submittedAt: string; settlementStatus: string; tasks: Array<{ id: string; category: string; name: string; due_date: string | null; status: string; is_required: boolean }>; documents: Array<{ id: string; type: string; name: string; status: string; generatedAt: string; downloadUrl: string }> };
type Payload = { policy: { resignation_notice_days: number; withdrawal_allowed: boolean }; reasons: Array<{ id: string; name: string; comment_required: boolean }>; exitCase: ExitCase | null };

export function ConnectExitManagement({ account, onBack }: { account: Account; onBack: () => void }) {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [pending, setPending] = useState(false);
  const load = useCallback(async () => { setPending(true); setError(""); try { const response = await fetch(`/api/connect/exit?employeeId=${encodeURIComponent(account.id)}`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to load exit management."); setData(body); } catch (problem) { setError(problem instanceof Error ? problem.message : "Unable to load exit management."); } finally { setPending(false); } }, [account.id]);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); setNotice(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/connect/exit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ employeeId: account.id, action: "submit", reasonId: form.get("reason_id"), comments: form.get("comments"), requestedLastWorkingDate: form.get("requested_last_working_date"), personalEmail: form.get("personal_email"), personalMobile: form.get("personal_mobile") }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to submit resignation."); setNotice(body.notice); await load(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Unable to submit resignation."); } finally { setPending(false); } }
  async function withdraw() { if (!window.confirm("Send a request to HR to withdraw this resignation?")) return; setPending(true); setError(""); try { const response = await fetch("/api/connect/exit", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ employeeId: account.id, action: "withdraw" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to request withdrawal."); setNotice(body.notice); await load(); } catch (problem) { setError(problem instanceof Error ? problem.message : "Unable to request withdrawal."); } finally { setPending(false); } }
  const exitCase = data?.exitCase; const canStart = !exitCase || ["rejected","withdrawn","cancelled"].includes(exitCase.status); const canWithdraw = Boolean(exitCase && data?.policy.withdrawal_allowed && !["withdrawal_requested","documents_ready","closed","rejected","withdrawn","cancelled"].includes(exitCase.status));
  const minDate = new Date().toISOString().slice(0, 10); const suggested = new Date(); suggested.setDate(suggested.getDate() + (data?.policy.resignation_notice_days ?? 30));
  return <section className="connect-exit-page">
    <div className="connect-section-heading"><button className="connect-back-button" onClick={onBack} type="button">←</button><div><p>Employee self-service</p><h2>Exit management</h2></div></div>
    {error ? <div className="connect-alert error">{error}</div> : null}{notice ? <div className="connect-alert success">{notice}</div> : null}
    {pending && !data ? <div className="connect-exit-card"><p className="connect-help">Loading exit details...</p></div> : null}
    {canStart && data ? <form className="connect-exit-card" onSubmit={submit}><div><span className="connect-exit-eyebrow">Resignation request</span><h3>Tell us about your planned exit</h3><p>Your request will go to the configured reporting manager and HR workflow.</p></div>
      <label>Reason *<select name="reason_id" required defaultValue=""><option value="" disabled>Select a reason</option>{data.reasons.map((reason) => <option key={reason.id} value={reason.id}>{reason.name}</option>)}</select></label>
      <label>Requested last working date *<input name="requested_last_working_date" type="date" min={minDate} max={new Date(Date.now() + 365 * 86400000).toISOString().slice(0,10)} defaultValue={suggested.toISOString().slice(0,10)} required /><small>Policy notice period: {data.policy.resignation_notice_days} days</small></label>
      <label>Comments<textarea name="comments" placeholder="Share any details HR should know" /></label><label>Personal email<input name="personal_email" type="email" defaultValue={account.email ?? ""} placeholder="For exit communication" /></label><label>Personal mobile<input name="personal_mobile" inputMode="tel" placeholder="For exit communication" /></label>
      <div className="connect-exit-warning"><strong>Before you submit</strong><span>The request starts an approval workflow. Your last working date is final only after HR approval.</span></div><button className="connect-primary" disabled={pending || !data.reasons.length} type="submit">{pending ? "Submitting..." : "Submit resignation"}</button>
    </form> : null}
    {exitCase && !canStart ? <div className="connect-exit-stack"><article className="connect-exit-card status-card"><div className="connect-exit-status-head"><div><span className="connect-exit-eyebrow">{exitCase.caseNumber}</span><h3>{exitCase.status.replaceAll("_", " ")}</h3></div><span className={`connect-status-badge ${exitCase.status}`}>{exitCase.stage.replaceAll("_", " ")}</span></div><div className="connect-exit-facts"><div><span>Reason</span><strong>{exitCase.reason}</strong></div><div><span>Requested last day</span><strong>{exitCase.requestedLastWorkingDate ?? "-"}</strong></div><div><span>Approved last day</span><strong>{exitCase.approvedLastWorkingDate ?? "Pending"}</strong></div><div><span>Settlement</span><strong>{exitCase.settlementStatus.replaceAll("_", " ")}</strong></div></div>{canWithdraw ? <button className="connect-secondary danger" disabled={pending} onClick={withdraw} type="button">Request withdrawal</button> : null}</article>
      <article className="connect-exit-card"><div><span className="connect-exit-eyebrow">Checklist</span><h3>Handover and clearance</h3></div><div className="connect-exit-list">{exitCase.tasks.map((task) => <div key={task.id}><span className={`connect-task-dot ${task.status}`} /><div><strong>{task.name}</strong><small>{task.category} · due {task.due_date ?? "not set"}</small></div><em>{task.status.replaceAll("_", " ")}</em></div>)}</div></article>
      <article className="connect-exit-card"><div><span className="connect-exit-eyebrow">Documents</span><h3>Your exit documents</h3><p>HRMS generates these automatically after all required steps are complete.</p></div>{exitCase.documents.length ? <div className="connect-document-list">{exitCase.documents.map((document) => <a href={document.downloadUrl || undefined} key={document.id} target="_blank" rel="noreferrer"><span>PDF</span><div><strong>{document.name}</strong><small>{document.type.replaceAll("_", " ")}</small></div><b>Download</b></a>)}</div> : <p className="connect-empty-note">No documents are ready yet.</p>}</article>
    </div> : null}
  </section>;
}
