export type CompactReport={headers:string[];rows:(string|number|null|undefined)[][];widths:number[];notes:string[]};
type Line={text:string;x:number;y:number;bold?:boolean;size:number;color:string};
type Rect={x:number;y:number;width:number;height:number;color:string};
export type CompactPage={width:number;height:number;lines:Line[];rects:Rect[]};
const text=(v:unknown)=>String(v??'—').replace(/\s+/g,' ').trim();
function wrap(v:unknown,chars:number){const value=text(v);if(!value)return['—'];const result:string[]=[];let rest=value;while(rest.length>chars){let cut=rest.lastIndexOf(' ',chars);if(cut<chars/3)cut=chars;result.push(rest.slice(0,cut));rest=rest.slice(cut).trimStart();}result.push(rest);return result;}
// One logical layout feeds PNG and vector PDF. Long notes wrap; no rows are silently dropped.
export function compactPages(title:string,subtitle:string,report:CompactReport):CompactPage[]{
 const width=900,edge=18,usable=864,lineHeight=21,maxHeight=1230;
 const total=report.widths.reduce((n,v)=>n+v,0),cols=report.widths.map(w=>w/total*usable);
 const pages:CompactPage[]=[];let page:CompactPage,y=0;
 function start(){page={width,height:0,lines:[],rects:[]};pages.push(page);y=edge;page.rects.push({x:edge,y,width:usable,height:62,color:'#152d3b'});page.lines.push({text:title,x:30,y:y+25,bold:true,size:21,color:'#ffffff'});page.lines.push({text:'DROPX FLEET',x:30,y:y+47,bold:true,size:11,color:'#8de0d3'});y+=74;for(const line of wrap(subtitle,110)){page.lines.push({text:line,x:edge,y:y+14,size:13,color:'#486575'});y+=18;}for(const note of report.notes){for(const line of wrap(note,115)){page.lines.push({text:line,x:edge,y:y+13,size:12,color:'#486575'});y+=17;}}y+=8;const labels=report.headers.map((h,i)=>wrap(h,Math.floor((cols[i]-14)/8)));const h=Math.max(...labels.map(l=>l.length))*20+14;page.rects.push({x:edge,y,width:usable,height:h,color:'#dceeea'});let x=edge;labels.forEach((ls,i)=>{ls.forEach((s,j)=>page.lines.push({text:s,x:x+7,y:y+21+j*20,bold:true,size:14,color:'#153d40'}));x+=cols[i];});y+=h;}
 function finish(){page.lines.push({text:`DropX Fleet · ${pages.length} · ${report.rows.length} rows in this report`,x:edge,y:y+23,size:11,color:'#647583'});page.height=y+42;}
 start();
 report.rows.forEach((row,index)=>{
 const cells=report.headers.map((_,i)=>wrap(row[i],Math.max(8,Math.floor((cols[i]-14)/9.4))));let offset=0,maxLines=Math.max(...cells.map(v=>v.length));
 while(offset<maxLines){if(y+lineHeight+16>maxHeight){finish();start();}const take=Math.min(maxLines-offset,Math.max(1,Math.floor((maxHeight-y-16)/lineHeight)));const h=take*lineHeight+14;const isTotal=text(row[0]).toLowerCase()==='total';page.rects.push({x:edge,y,width:usable,height:h,color:isTotal?'#fff0d1':index%2?'#f0f5f7':'#ffffff'});page.rects.push({x:edge,y:y+h-1,width:usable,height:1,color:'#d9e3e8'});let x=edge;cells.forEach((ls,i)=>{ls.slice(offset,offset+take).forEach((s,j)=>page.lines.push({text:s,x:x+7,y:y+22+j*lineHeight,size:15,bold:isTotal||i===0,color:'#223642'}));x+=cols[i];});y+=h;offset+=take;if(offset<maxLines){finish();start();}}
 });finish();return pages;
}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export async function downloadCompactImages(title:string,subtitle:string,fileName:string,report:CompactReport){const pages=compactPages(title,subtitle,report),images:Blob[]=[];for(let i=0;i<pages.length;i++){const p=pages[i],canvas=document.createElement('canvas');canvas.width=p.width;canvas.height=p.height;const c=canvas.getContext('2d');if(!c)throw Error('Canvas unavailable');c.fillStyle='#ffffff';c.fillRect(0,0,p.width,p.height);for(const r of p.rects){c.fillStyle=r.color;c.fillRect(r.x,r.y,r.width,r.height);}for(const l of p.lines){c.fillStyle=l.color;c.font=`${l.bold?700:400} ${l.size}px Arial`;c.fillText(l.text,l.x,l.y);}const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image unavailable')),'image/png'));images.push(blob);}if(images.length===1)download(images[0],`${fileName}.png`);else{const JSZip=(await import('jszip')).default,zip=new JSZip();for(let i=0;i<images.length;i++)zip.file(`${fileName}-${i+1}.png`,images[i]);download(await zip.generateAsync({type:'blob'}),`${fileName}-images.zip`);}}
export async function compactPdf(title:string,subtitle:string,report:CompactReport){const {PDFDocument,StandardFonts,rgb}=await import('pdf-lib'),doc=await PDFDocument.create();doc.setTitle(title);doc.setAuthor('DropX Fleet');const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const color=(hex:string)=>rgb(parseInt(hex.slice(1,3),16)/255,parseInt(hex.slice(3,5),16)/255,parseInt(hex.slice(5,7),16)/255);for(const p of compactPages(title,subtitle,report)){const scale=595/p.width,height=Math.max(300,p.height*scale),page=doc.addPage([595,height]);for(const r of p.rects)page.drawRectangle({x:r.x*scale,y:height-(r.y+r.height)*scale,width:r.width*scale,height:r.height*scale,color:color(r.color)});for(const l of p.lines)page.drawText(l.text.replaceAll('₹','Rs ').replaceAll('—','-').replaceAll('·','|').replace(/[^\x20-\x7e]/g,' '),{x:l.x*scale,y:height-l.y*scale,size:l.size*scale,font:l.bold?bold:regular,color:color(l.color)});}return doc.save();}
