export type FleetDailyStatusVehicle = {
  vehicle_no: string;
  station_code: string;
  model: string;
  ownership_type: string | null;
  status: string | null;
  non_operational_since: string | null;
  expected_operational_date: string | null;
  status_comment: string | null;
  status_reason_key: string | null;
};

export type FleetDailyStatusSummary = {
  station: string;
  ownTotal: number;
  ownOperational: number;
  ownNonOperational: number;
  partnerTotal: number;
  partnerOperational: number;
  partnerNonOperational: number;
  totalNonOperational: number;
  adHocVans: number;
};

export type FleetDailyStatusTotals = {
  totalVehicles: number;
  operational: number;
  nonOperational: number;
  adHoc: number;
  adHocPending: number;
  stationCount: number;
};

export type FleetDailyStatusAdHocSummary = {
  station: string;
  type: "Van" | "Driver";
  todayCount: number;
  todayAmount: number;
  todayPendingCount: number;
  todayPendingAmount: number;
  pendingCount: number;
  pendingAmount: number;
  mtdCount: number;
  mtdAmount: number;
};

export type FleetDailyStatusEmailConfig = {
  title: string;
  subjectPrefix: string;
  headerLabel: string;
  intro: string;
  footer: string;
  primaryColor: string;
  accentColor: string;
  alertColor: string;
  includeSummary: boolean;
  includeStationTable: boolean;
  includeNonOperationalTable: boolean;
  includeAdHoc: boolean;
  includeMappedOperations: boolean;
  includeAllLocationOperations: boolean;
  includeStationMailboxes: boolean;
  monthlyThread: boolean;
  excludeAmazonNow: boolean;
  excludedStationCodes: string[];
};

export const defaultFleetDailyStatusEmailConfig: FleetDailyStatusEmailConfig = {
  title: "DropX Daily Fleet Update",
  subjectPrefix: "DropX Daily Fleet Update",
  headerLabel: "Availability · Exceptions · Ad Hoc Support",
  intro: "Stations requiring attention are ranked first. Red values need an availability update.",
  footer: "Generated by DropX Fleet. Ad hoc figures distinguish approved usage from pending approvals.",
  primaryColor: "#111a2f",
  accentColor: "#d92d67",
  alertColor: "#c52a42",
  includeSummary: true,
  includeStationTable: true,
  includeNonOperationalTable: true,
  includeAdHoc: true,
  includeMappedOperations: true,
  includeAllLocationOperations: true,
  includeStationMailboxes: true,
  monthlyThread: true,
  excludeAmazonNow: true,
  excludedStationCodes: []
};

const color = (value: unknown, fallback: string) => /^#[0-9a-f]{6}$/i.test(clean(value)) ? clean(value) : fallback;
export function normalizeFleetDailyStatusEmailConfig(value: unknown): FleetDailyStatusEmailConfig {
  const input = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
  const bool = (key: keyof FleetDailyStatusEmailConfig) => typeof input[key] === "boolean" ? Boolean(input[key]) : defaultFleetDailyStatusEmailConfig[key] as boolean;
  const words = (key: keyof FleetDailyStatusEmailConfig) => clean(input[key]) || defaultFleetDailyStatusEmailConfig[key] as string;
  return {
    title: words("title"), subjectPrefix: words("subjectPrefix"), headerLabel: words("headerLabel"), intro: words("intro"), footer: words("footer"),
    primaryColor: color(input.primaryColor, defaultFleetDailyStatusEmailConfig.primaryColor), accentColor: color(input.accentColor, defaultFleetDailyStatusEmailConfig.accentColor), alertColor: color(input.alertColor, defaultFleetDailyStatusEmailConfig.alertColor),
    includeSummary: bool("includeSummary"), includeStationTable: bool("includeStationTable"), includeNonOperationalTable: bool("includeNonOperationalTable"), includeAdHoc: bool("includeAdHoc"), includeMappedOperations: bool("includeMappedOperations"), includeAllLocationOperations: bool("includeAllLocationOperations"), includeStationMailboxes: bool("includeStationMailboxes"), monthlyThread: bool("monthlyThread"), excludeAmazonNow: bool("excludeAmazonNow"),
    excludedStationCodes: Array.isArray(input.excludedStationCodes) ? [...new Set(input.excludedStationCodes.map((item) => clean(item).toUpperCase()).filter(Boolean))] : []
  };
}

const clean = (value: unknown) => String(value ?? "").trim();
const esc = (value: unknown) => clean(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const owned = (type: unknown) => !["odcd", "rented", "leased"].includes(clean(type).toLowerCase());
const cell = (value: unknown, extra = "") => `<td style="padding:11px 9px;border-bottom:1px solid #e7ebef;text-align:center;color:#273142;${extra}">${esc(value)}</td>`;
const dateLabel = (value: string | null) => {
  if (!value) return "Update required";
  const parsed = new Date(`${value.slice(0, 10)}T12:00:00+05:30`);
  return Number.isNaN(parsed.valueOf()) ? clean(value) : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(parsed);
};
const dayDifference = (from: string | null, to: string) => from
  ? Math.max(0, Math.round((Date.parse(`${to.slice(0, 10)}T00:00:00Z`) - Date.parse(`${from.slice(0, 10)}T00:00:00Z`)) / 86_400_000))
  : null;

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
function fleetTable(rows: FleetDailyStatusSummary[]) {
  const totals = (key: keyof Omit<FleetDailyStatusSummary, "station">) => rows.reduce((sum, row) => sum + row[key], 0);
  const body = rows.map((row) => {
    const alert = row.totalNonOperational > 0;
    return `<tr style="background:${alert ? "#fff9f5" : "#ffffff"}">${cell(row.station, "font-weight:800;text-align:left;color:#111a2f")}${cell(row.ownTotal)}${cell(row.ownOperational, "color:#167a57;font-weight:700")}${cell(row.ownNonOperational, row.ownNonOperational ? "color:#c52a42;font-weight:800" : "color:#7d8794")}${cell(row.partnerTotal)}${cell(row.partnerOperational, "color:#167a57;font-weight:700")}${cell(row.partnerNonOperational, row.partnerNonOperational ? "color:#c52a42;font-weight:800" : "color:#7d8794")}${cell(row.totalNonOperational, row.totalNonOperational ? "background:#fff0f2;color:#c52a42;font-weight:900" : "color:#7d8794")}</tr>`;
  }).join("");
  const totalRowValues: Array<string | number> = ["Total", totals("ownTotal"), totals("ownOperational"), totals("ownNonOperational"), totals("partnerTotal"), totals("partnerOperational"), totals("partnerNonOperational"), totals("totalNonOperational")];
  const totalRow = totalRowValues
    .map((value, index) => cell(value, `font-weight:900;${index === 0 ? "text-align:left;" : ""}background:#111a2f;color:#ffffff;border-bottom:0`)).join("");
  return `<div style="overflow-x:auto;border:1px solid #dfe4e8;border-radius:14px;background:#ffffff"><table role="presentation" style="border-collapse:separate;border-spacing:0;width:100%;min-width:760px;font:12px Arial,sans-serif"><thead><tr><th rowspan="2" style="padding:12px 9px;background:#111a2f;color:#fff;text-align:left;border-radius:13px 0 0 0">Station</th><th colspan="3" style="padding:9px;background:#1f7a70;color:#fff;border-left:1px solid #ffffff33">DropX owned</th><th colspan="3" style="padding:9px;background:#3265a8;color:#fff;border-left:1px solid #ffffff33">ODCD / rented</th><th rowspan="2" style="padding:9px;background:#c52a42;color:#fff;border-left:1px solid #ffffff33;border-radius:0 13px 0 0">Non-operational</th></tr><tr style="background:#edf1f4;color:#3a4655"><th style="padding:8px">Total</th><th>Operational</th><th>Down</th><th>Total</th><th>Operational</th><th>Down</th></tr></thead><tbody>${body}<tr>${totalRow}</tr></tbody></table></div>`;
}

type AdHocPeriod = "today" | "mtd" | "pending";
function adHocMetric(rows: FleetDailyStatusAdHocSummary[], type: "Van" | "Driver", period: AdHocPeriod) {
  return rows.filter((row) => row.type === type).reduce((total, row) => {
    if (period === "today") {
      total.count += row.todayCount + row.todayPendingCount;
      total.amount += row.todayAmount + row.todayPendingAmount;
      total.pending += row.todayPendingCount;
    } else if (period === "mtd") {
      total.count += row.mtdCount;
      total.amount += row.mtdAmount;
    } else {
      total.count += row.pendingCount;
      total.amount += row.pendingAmount;
      total.pending += row.pendingCount;
    }
    return total;
  }, { count: 0, amount: 0, pending: 0 });
}

function adHocPeriodCell(rows: FleetDailyStatusAdHocSummary[], period: AdHocPeriod, total = false) {
  const values = (["Van", "Driver"] as const).map((type) => ({ type, ...adHocMetric(rows, type, period) }));
  if (!values.some((value) => value.count > 0)) return `<span style="color:${total ? "#c7d1e2" : "#98a2b3"}">—</span>`;
  return values.map((value) => value.count > 0
    ? `<div style="white-space:nowrap;margin:${value.type === "Driver" ? "5px" : "0"} 0 0;font-weight:800;color:${total ? "#ffffff" : value.type === "Van" ? "#176b61" : "#8a5b00"}">${value.type}: ${value.count} · ${esc(money(value.amount))}${period === "today" && value.pending > 0 ? ` <span style="font-size:10px;color:${total ? "#ffd18a" : "#a65300"}">(${value.pending} pending)</span>` : ""}</div>`
    : `<div style="white-space:nowrap;margin:${value.type === "Driver" ? "5px" : "0"} 0 0;color:${total ? "#c7d1e2" : "#98a2b3"}">${value.type}: 0 · ${esc(money(0))}</div>`).join("");
}

function adHocTable(rows: FleetDailyStatusAdHocSummary[]) {
  const stations = [...new Set(rows.map((row) => row.station))].map((station) => {
    const stationRows = rows.filter((row) => row.station === station);
    const today = (["Van", "Driver"] as const).reduce((sum, type) => sum + adHocMetric(stationRows, type, "today").count, 0);
    const pending = (["Van", "Driver"] as const).reduce((sum, type) => sum + adHocMetric(stationRows, type, "pending").count, 0);
    const mtd = (["Van", "Driver"] as const).reduce((sum, type) => sum + adHocMetric(stationRows, type, "mtd").count, 0);
    return { station, rows: stationRows, today, pending, mtd };
  }).filter((item) => item.today || item.pending || item.mtd)
    .sort((a, b) => b.pending - a.pending || b.today - a.today || b.mtd - a.mtd || a.station.localeCompare(b.station));
  if (!stations.length) return `<div style="padding:18px;text-align:center;border:1px solid #dfe4e8;background:#f8fafb;border-radius:14px;color:#667085;font:700 12px Arial,sans-serif">No ad hoc usage or open approvals.</div>`;
  const periodCell = (stationRows: FleetDailyStatusAdHocSummary[], period: AdHocPeriod, background = "") => `<td style="padding:10px 9px;border-bottom:1px solid #e7ebef;text-align:left;${background}">${adHocPeriodCell(stationRows, period)}</td>`;
  const body = stations.map(({ station, rows: stationRows, pending }) => `<tr style="background:${pending ? "#fffbf3" : "#ffffff"}">${cell(station, "font-weight:800;text-align:left;color:#111a2f")}${periodCell(stationRows, "today")}${periodCell(stationRows, "mtd")}${periodCell(stationRows, "pending", pending ? "background:#fff3dd" : "")}</tr>`).join("");
  const totalCell = (period: AdHocPeriod) => `<td style="padding:10px 9px;background:#111a2f;border-bottom:0;text-align:left">${adHocPeriodCell(rows, period, true)}</td>`;
  return `<div style="overflow-x:auto;border:1px solid #dfe4e8;border-radius:14px;background:#ffffff"><table role="presentation" style="border-collapse:separate;border-spacing:0;width:100%;min-width:720px;font:12px Arial,sans-serif"><thead><tr><th style="padding:11px 9px;background:#111a2f;color:#fff;text-align:left;border-radius:13px 0 0 0">Station</th><th style="padding:11px 9px;background:#1f7a70;color:#fff;text-align:left">Today<br><span style="font-size:10px;font-weight:500">Approved + awaiting approval</span></th><th style="padding:11px 9px;background:#3265a8;color:#fff;text-align:left">MTD approved<br><span style="font-size:10px;font-weight:500">Used this month</span></th><th style="padding:11px 9px;background:#d97818;color:#fff;text-align:left;border-radius:0 13px 0 0">Open pending<br><span style="font-size:10px;font-weight:500">Needs approval</span></th></tr></thead><tbody>${body}<tr><td style="padding:10px 9px;background:#111a2f;color:#fff;font-weight:900">Total</td>${totalCell("today")}${totalCell("mtd")}${totalCell("pending")}</tr></tbody></table></div>`;
}

function exceptionTable(rows: FleetDailyStatusVehicle[], reportDate: string) {
  if (!rows.length) return `<div style="padding:22px;text-align:center;border:1px solid #cfe9df;background:#f0fbf6;border-radius:14px;color:#167a57;font-weight:700">No non-operational vehicles in the selected stations.</div>`;
  const body = rows.map((row) => {
    const status = clean(row.status).replaceAll("_", " ") || "Non-operational";
    const reason = clean(row.status_reason_key).replaceAll("_", " ");
    const downDays = dayDifference(row.non_operational_since, reportDate);
    const expectedDays = row.expected_operational_date ? dayDifference(row.expected_operational_date, reportDate) : null;
    const overdue = Boolean(row.expected_operational_date && row.expected_operational_date < reportDate);
    const expected = overdue ? `<strong style="color:#c52a42">Overdue ${expectedDays}d</strong><br><span style="font-size:11px;color:#8b3a49">Update expected date</span>` : row.expected_operational_date ? esc(dateLabel(row.expected_operational_date)) : `<strong style="color:#c52a42">Date required</strong>`;
    return `<tr style="background:${overdue || !row.expected_operational_date ? "#fff9fa" : "#fff"}"><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><strong style="color:#111a2f">${esc(row.vehicle_no)}</strong><br><span style="color:#7d8794;font-size:11px">${esc(row.model)}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><span style="display:inline-block;padding:4px 8px;border-radius:999px;background:#e9f4f1;color:#176b61;font-weight:700">${esc(row.station_code)}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${owned(row.ownership_type) ? "DropX owned" : esc(clean(row.ownership_type).toUpperCase())}</td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><span style="display:inline-block;padding:4px 8px;border-radius:999px;background:#fff0f2;color:#c52a42;font-weight:700;text-transform:capitalize">${esc(status)}</span>${reason ? `<br><strong style="display:inline-block;margin-top:6px;color:#263649;text-transform:capitalize">${esc(reason)}</strong>` : ""}<br><span style="display:inline-block;margin-top:3px;color:#4b5868">${esc(row.status_comment || "No latest comment")}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${esc(dateLabel(row.non_operational_since))}</td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;text-align:center"><strong style="display:inline-block;padding:5px 9px;border-radius:999px;background:#fff0f2;color:#c52a42">${downDays == null ? "Start date required" : `${downDays} day${downDays === 1 ? "" : "s"}`}</strong></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${expected}</td></tr>`;
  }).join("");
  return `<div style="overflow-x:auto;border:1px solid #dfe4e8;border-radius:14px;background:#fff"><table role="presentation" style="border-collapse:collapse;width:100%;min-width:820px;font:12px Arial,sans-serif"><thead><tr style="background:#fff3e8;color:#8c4b11">${["Vehicle", "Station", "Source", "Issue and status", "Down since", "Days down", "Expected back"].map((value) => `<th style="padding:10px;text-align:left;border-bottom:1px solid #f0d8c4">${value}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table></div>`;
}

function kpi(label: string, value: number, color: string, background: string, note = "") {
  return `<td class="kpi" width="20%" style="padding:5px"><div style="padding:14px 12px;border-radius:12px;background:${background};border:1px solid ${color}22"><div style="font:700 10px Arial,sans-serif;letter-spacing:.7px;text-transform:uppercase;color:#667085">${esc(label)}</div><div style="margin-top:5px;font:900 24px Arial,sans-serif;color:${color}">${value}</div>${note ? `<div style="margin-top:4px;font:800 11px Arial,sans-serif;color:#a65300">${esc(note)}</div>` : ""}</div></td>`;
}

export function buildFleetDailyStatusEmail(input: { companyName?: string | null; date: string; rows: FleetDailyStatusSummary[]; exceptions: FleetDailyStatusVehicle[]; adHocRows?: FleetDailyStatusAdHocSummary[]; totals?: FleetDailyStatusTotals; config?: Partial<FleetDailyStatusEmailConfig> | null }) {
  const config = normalizeFleetDailyStatusEmailConfig(input.config);
  const adHocRows = input.adHocRows ?? [];
  const adHocCount = (station: string) => adHocRows.filter((row) => row.station === station).reduce((sum, row) => sum + row.todayCount + row.pendingCount, 0);
  const rows = [...input.rows].sort((a, b) => b.totalNonOperational - a.totalNonOperational || adHocCount(b.station) - adHocCount(a.station) || a.station.localeCompare(b.station));
  const exceptions = [...input.exceptions].sort((a, b) => (a.non_operational_since || input.date).localeCompare(b.non_operational_since || input.date));
  const total = (key: keyof Omit<FleetDailyStatusSummary, "station">) => rows.reduce((sum, row) => sum + row[key], 0);
  const totalVehicles = input.totals?.totalVehicles ?? total("ownTotal") + total("partnerTotal");
  const operational = input.totals?.operational ?? total("ownOperational") + total("partnerOperational");
  const nonOperational = input.totals?.nonOperational ?? total("totalNonOperational");
  const adHoc = input.totals?.adHoc ?? (adHocRows.reduce((sum,row)=>sum+row.todayCount,0) || total("adHocVans"));
  const adHocPending = input.totals?.adHocPending ?? adHocRows.reduce((sum,row)=>sum+row.pendingCount,0);
  const stationCount = input.totals?.stationCount ?? rows.length;
  const reportDate = dateLabel(input.date);
  const kpis = config.includeSummary ? `<tr><td class="pad" style="padding:8px 19px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr>${kpi("Vehicles", totalVehicles, config.primaryColor, "#f4f6f8")}${kpi("Operational", operational, "#167a57", "#effaf5")}${kpi("Non-operational", nonOperational, config.alertColor, "#fff1f3")}${config.includeAdHoc ? kpi("Ad hoc approved", adHoc, "#b36b00", "#fff8e6", `${adHocPending} open pending approval${adHocPending === 1 ? "" : "s"}`) : ""}${kpi("Stations", stationCount, "#3265a8", "#eff5ff")}</tr></table></td></tr>` : "";
  const stationSection = config.includeStationTable ? `<tr><td class="pad" style="padding:8px 24px 22px"><div style="margin-bottom:10px;font:900 16px Arial,sans-serif;color:${config.primaryColor}">1. Daily station status</div>${fleetTable(rows)}</td></tr>` : "";
  const adHocSectionNumber = config.includeStationTable ? 2 : 1;
  const adHocSection = config.includeAdHoc ? `<tr><td class="pad" style="padding:0 24px 22px"><div style="margin-bottom:4px;font:900 16px Arial,sans-serif;color:${config.primaryColor}">${adHocSectionNumber}. Ad hoc usage and approvals</div><div style="margin-bottom:10px;font:12px Arial,sans-serif;color:#667085">Today includes approved and awaiting-approval requests for the report date. MTD contains approved usage. Open pending contains every unresolved request.</div>${adHocTable(adHocRows)}</td></tr>` : "";
  const exceptionSectionNumber = 1 + Number(config.includeStationTable) + Number(config.includeAdHoc);
  const exceptionSection = config.includeNonOperationalTable ? `<tr><td class="pad" style="padding:0 24px 22px"><div style="margin-bottom:4px;font:900 16px Arial,sans-serif;color:${config.primaryColor}">${exceptionSectionNumber}. Non-operational vehicle actions</div><div style="margin-bottom:10px;font:12px Arial,sans-serif;color:#667085">Days down are calculated from the recorded non-operational date. Overdue expected returns require an update.</div>${exceptionTable(exceptions, input.date)}</td></tr>` : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:680px){.shell{width:100%!important}.pad{padding:16px!important}.kpi{display:inline-block!important;width:45%!important}}</style></head><body style="margin:0;background:#f2f5f6;color:#202633"><div style="display:none;max-height:0;overflow:hidden">${esc(reportDate)}: ${totalVehicles} vehicles, ${nonOperational} non-operational${config.includeAdHoc ? `, ${adHoc} approved and ${adHocPending} pending ad hoc requests` : ""}.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f5f6"><tr><td align="center" style="padding:24px 10px"><table class="shell" role="presentation" width="920" cellspacing="0" cellpadding="0" style="width:920px;max-width:100%;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 8px 30px #111a2f12"><tr><td class="pad" style="padding:24px 28px;background:${config.primaryColor};border-left:7px solid ${config.accentColor}"><table role="presentation" width="100%"><tr><td><div style="font:900 22px Arial,sans-serif;color:#fff"><span style="display:inline-block;width:28px;height:28px;line-height:28px;text-align:center;border-radius:9px;background:${config.accentColor};margin-right:8px">F</span>${esc(config.title)}</div><div style="margin-top:7px;font:700 11px Arial,sans-serif;letter-spacing:1.4px;color:#f5c04f">${esc(config.headerLabel).toUpperCase()}</div></td><td align="right" style="font:700 13px Arial,sans-serif;color:#fff"><div>${esc(reportDate)}</div><div style="margin-top:5px;color:#c7d1e2;font-weight:400">${esc(input.companyName || "DropX Logistics")}</div></td></tr></table></td></tr><tr><td class="pad" style="padding:22px 24px 8px"><div style="font:900 24px Arial,sans-serif;color:${config.primaryColor}">Today’s fleet position</div><div style="margin-top:6px;font:13px Arial,sans-serif;color:#667085">${esc(config.intro)}</div></td></tr>${kpis}${stationSection}${adHocSection}${exceptionSection}<tr><td align="center" style="padding:8px 24px 28px"><div style="font:11px Arial,sans-serif;color:#8a94a3">${esc(config.footer)}</div></td></tr></table></td></tr></table></body></html>`;
  const text = [`${config.title} - ${reportDate}`, `${totalVehicles} vehicles | ${operational} operational | ${nonOperational} non-operational${config.includeAdHoc ? ` | ${adHoc} approved ad hoc usages | ${adHocPending} pending approvals` : ""}`, `${stationCount} stations`, config.footer].join("\n");
  return { html, text };
}
