export type FleetDailyStatusVehicle = {
  vehicle_no: string;
  station_code: string;
  model: string;
  ownership_type: string | null;
  status: string | null;
  non_operational_since: string | null;
  expected_operational_date: string | null;
  status_comment: string | null;
  status_reason_key: string | null;
};

export type FleetDailyStatusSummary = {
  station: string;
  ownTotal: number;
  ownOperational: number;
  ownNonOperational: number;
  partnerTotal: number;
  partnerOperational: number;
  partnerNonOperational: number;
  totalNonOperational: number;
  adHocVans: number;
};

export type FleetDailyStatusTotals = {
  totalVehicles: number;
  operational: number;
  nonOperational: number;
  adHoc: number;
  stationCount: number;
};

export type FleetDailyStatusAdHocSummary = {
  station: string;
  type: "Van" | "Driver";
  todayCount: number;
  todayAmount: number;
  mtdCount: number;
  mtdAmount: number;
};

export type FleetDailyStatusEmailConfig = {
  title: string;
  subjectPrefix: string;
  headerLabel: string;
  intro: string;
  footer: string;
  primaryColor: string;
  accentColor: string;
  alertColor: string;
  includeSummary: boolean;
  includeStationTable: boolean;
  includeNonOperationalTable: boolean;
  includeAdHoc: boolean;
  includeMappedOperations: boolean;
  includeAllLocationOperations: boolean;
  includeStationMailboxes: boolean;
  monthlyThread: boolean;
  excludeAmazonNow: boolean;
  excludedStationCodes: string[];
};

export const defaultFleetDailyStatusEmailConfig: FleetDailyStatusEmailConfig = {
  title: "DropX Daily Fleet Update",
  subjectPrefix: "DropX Daily Fleet Update",
  headerLabel: "Availability · Exceptions · Ad Hoc Support",
  intro: "Stations requiring attention are ranked first. Red values need an availability update.",
  footer: "Generated by DropX Fleet. Ad hoc figures include approved Van and Driver usage.",
  primaryColor: "#111a2f",
  accentColor: "#d92d67",
  alertColor: "#c52a42",
  includeSummary: true,
  includeStationTable: true,
  includeNonOperationalTable: true,
  includeAdHoc: true,
  includeMappedOperations: true,
  includeAllLocationOperations: true,
  includeStationMailboxes: true,
  monthlyThread: true,
  excludeAmazonNow: true,
  excludedStationCodes: []
};

const color = (value: unknown, fallback: string) => /^#[0-9a-f]{6}$/i.test(clean(value)) ? clean(value) : fallback;
export function normalizeFleetDailyStatusEmailConfig(value: unknown): FleetDailyStatusEmailConfig {
  const input = value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
  const bool = (key: keyof FleetDailyStatusEmailConfig) => typeof input[key] === "boolean" ? Boolean(input[key]) : defaultFleetDailyStatusEmailConfig[key] as boolean;
  const words = (key: keyof FleetDailyStatusEmailConfig) => clean(input[key]) || defaultFleetDailyStatusEmailConfig[key] as string;
  return {
    title: words("title"), subjectPrefix: words("subjectPrefix"), headerLabel: words("headerLabel"), intro: words("intro"), footer: words("footer"),
    primaryColor: color(input.primaryColor, defaultFleetDailyStatusEmailConfig.primaryColor), accentColor: color(input.accentColor, defaultFleetDailyStatusEmailConfig.accentColor), alertColor: color(input.alertColor, defaultFleetDailyStatusEmailConfig.alertColor),
    includeSummary: bool("includeSummary"), includeStationTable: bool("includeStationTable"), includeNonOperationalTable: bool("includeNonOperationalTable"), includeAdHoc: bool("includeAdHoc"), includeMappedOperations: bool("includeMappedOperations"), includeAllLocationOperations: bool("includeAllLocationOperations"), includeStationMailboxes: bool("includeStationMailboxes"), monthlyThread: bool("monthlyThread"), excludeAmazonNow: bool("excludeAmazonNow"),
    excludedStationCodes: Array.isArray(input.excludedStationCodes) ? [...new Set(input.excludedStationCodes.map((item) => clean(item).toUpperCase()).filter(Boolean))] : []
  };
}

const clean = (value: unknown) => String(value ?? "").trim();
const esc = (value: unknown) => clean(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const owned = (type: unknown) => !["odcd", "rented", "leased"].includes(clean(type).toLowerCase());
const cell = (value: unknown, extra = "") => `<td style="padding:11px 9px;border-bottom:1px solid #e7ebef;text-align:center;color:#273142;${extra}">${esc(value)}</td>`;
const dateLabel = (value: string | null) => {
  if (!value) return "Update required";
  const parsed = new Date(`${value.slice(0, 10)}T12:00:00+05:30`);
  return Number.isNaN(parsed.valueOf()) ? clean(value) : new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Kolkata" }).format(parsed);
};
const dayDifference = (from: string | null, to: string) => from
  ? Math.max(0, Math.round((Date.parse(`${to.slice(0, 10)}T00:00:00Z`) - Date.parse(`${from.slice(0, 10)}T00:00:00Z`)) / 86_400_000))
  : null;

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);
function compactAdHocCell(rows: FleetDailyStatusAdHocSummary[], period: "today" | "mtd") {
  if (!rows.length) return `<span style="color:#98a2b3">—</span>`;
  return rows.map((row) => {
    const count = period === "today" ? row.todayCount : row.mtdCount;
    const amount = period === "today" ? row.todayAmount : row.mtdAmount;
    return `<span style="display:inline-block;white-space:nowrap;margin:1px 3px 1px 0;padding:3px 6px;border-radius:999px;background:${row.type === "Van" ? "#e9f7f4;color:#176b61" : "#fff5e6;color:#9c6300"};font-weight:800">${row.type === "Van" ? "V" : "D"} ${count} · ${esc(money(amount))}</span>`;
  }).join("<br>");
}

function fleetTable(rows: FleetDailyStatusSummary[], adHocRows: FleetDailyStatusAdHocSummary[], includeAdHoc: boolean) {
  const totals = (key: keyof Omit<FleetDailyStatusSummary, "station">) => rows.reduce((sum, row) => sum + row[key], 0);
  const body = rows.map((row) => {
    const alert = row.totalNonOperational > 0;
    const stationAdHoc = adHocRows.filter((item) => item.station === row.station);
    const adHocCells = includeAdHoc ? `<td style="padding:8px 6px;border-bottom:1px solid #e7ebef;text-align:center">${compactAdHocCell(stationAdHoc, "today")}</td><td style="padding:8px 6px;border-bottom:1px solid #e7ebef;text-align:center">${compactAdHocCell(stationAdHoc, "mtd")}</td>` : "";
    return `<tr style="background:${alert ? "#fff9f5" : "#ffffff"}">${cell(row.station, "font-weight:800;text-align:left;color:#111a2f")}${cell(row.ownTotal)}${cell(row.ownOperational, "color:#167a57;font-weight:700")}${cell(row.ownNonOperational, row.ownNonOperational ? "color:#c52a42;font-weight:800" : "color:#7d8794")}${cell(row.partnerTotal)}${cell(row.partnerOperational, "color:#167a57;font-weight:700")}${cell(row.partnerNonOperational, row.partnerNonOperational ? "color:#c52a42;font-weight:800" : "color:#7d8794")}${cell(row.totalNonOperational, row.totalNonOperational ? "background:#fff0f2;color:#c52a42;font-weight:900" : "color:#7d8794")}${adHocCells}</tr>`;
  }).join("");
  const totalAdHoc = (period: "today" | "mtd") => compactAdHocCell(["Van", "Driver"].map((type) => ({
    station: "TOTAL", type: type as "Van" | "Driver",
    todayCount: adHocRows.filter((row) => row.type === type).reduce((sum, row) => sum + row.todayCount, 0),
    todayAmount: adHocRows.filter((row) => row.type === type).reduce((sum, row) => sum + row.todayAmount, 0),
    mtdCount: adHocRows.filter((row) => row.type === type).reduce((sum, row) => sum + row.mtdCount, 0),
    mtdAmount: adHocRows.filter((row) => row.type === type).reduce((sum, row) => sum + row.mtdAmount, 0)
  })).filter((row) => period === "today" ? row.todayCount > 0 : row.mtdCount > 0), period);
  const totalRowValues: Array<string | number> = ["Total", totals("ownTotal"), totals("ownOperational"), totals("ownNonOperational"), totals("partnerTotal"), totals("partnerOperational"), totals("partnerNonOperational"), totals("totalNonOperational")];
  const totalRow = totalRowValues
    .map((value, index) => cell(value, `font-weight:900;${index === 0 ? "text-align:left;" : ""}background:#111a2f;color:#ffffff;border-bottom:0`)).join("");
  const adHocHeaders = includeAdHoc ? `<th rowspan="2" style="padding:9px;background:#d97818;color:#fff;border-left:1px solid #ffffff33">Ad hoc today<br><span style="font-size:10px;font-weight:500">V / D · amount</span></th><th rowspan="2" style="padding:9px;background:#b76313;color:#fff;border-left:1px solid #ffffff33;border-radius:0 13px 0 0">Ad hoc MTD<br><span style="font-size:10px;font-weight:500">V / D · amount</span></th>` : "";
  const adHocTotals = includeAdHoc ? `<td style="padding:8px 6px;background:#111a2f;text-align:center">${totalAdHoc("today")}</td><td style="padding:8px 6px;background:#111a2f;text-align:center">${totalAdHoc("mtd")}</td>` : "";
  return `<div style="overflow-x:auto;border:1px solid #dfe4e8;border-radius:14px;background:#ffffff"><table role="presentation" style="border-collapse:separate;border-spacing:0;width:100%;min-width:${includeAdHoc ? "980" : "760"}px;font:12px Arial,sans-serif"><thead><tr><th rowspan="2" style="padding:12px 9px;background:#111a2f;color:#fff;text-align:left;border-radius:13px 0 0 0">Station</th><th colspan="3" style="padding:9px;background:#1f7a70;color:#fff;border-left:1px solid #ffffff33">DropX owned</th><th colspan="3" style="padding:9px;background:#3265a8;color:#fff;border-left:1px solid #ffffff33">ODCD / rented</th><th rowspan="2" style="padding:9px;background:#c52a42;color:#fff;border-left:1px solid #ffffff33${includeAdHoc ? "" : ";border-radius:0 13px 0 0"}">Non-operational</th>${adHocHeaders}</tr><tr style="background:#edf1f4;color:#3a4655"><th style="padding:8px">Total</th><th>Operational</th><th>Down</th><th>Total</th><th>Operational</th><th>Down</th></tr></thead><tbody>${body}<tr>${totalRow}${adHocTotals}</tr></tbody></table></div>`;
}

function exceptionTable(rows: FleetDailyStatusVehicle[], reportDate: string) {
  if (!rows.length) return `<div style="padding:22px;text-align:center;border:1px solid #cfe9df;background:#f0fbf6;border-radius:14px;color:#167a57;font-weight:700">No non-operational vehicles in the selected stations.</div>`;
  const body = rows.map((row) => {
    const status = clean(row.status).replaceAll("_", " ") || "Non-operational";
    const reason = clean(row.status_reason_key).replaceAll("_", " ");
    const downDays = dayDifference(row.non_operational_since, reportDate);
    const expectedDays = row.expected_operational_date ? dayDifference(row.expected_operational_date, reportDate) : null;
    const overdue = Boolean(row.expected_operational_date && row.expected_operational_date < reportDate);
    const expected = overdue ? `<strong style="color:#c52a42">Overdue ${expectedDays}d</strong><br><span style="font-size:11px;color:#8b3a49">Update expected date</span>` : row.expected_operational_date ? esc(dateLabel(row.expected_operational_date)) : `<strong style="color:#c52a42">Date required</strong>`;
    return `<tr style="background:${overdue || !row.expected_operational_date ? "#fff9fa" : "#fff"}"><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><strong style="color:#111a2f">${esc(row.vehicle_no)}</strong><br><span style="color:#7d8794;font-size:11px">${esc(row.model)}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><span style="display:inline-block;padding:4px 8px;border-radius:999px;background:#e9f4f1;color:#176b61;font-weight:700">${esc(row.station_code)}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${owned(row.ownership_type) ? "DropX owned" : esc(clean(row.ownership_type).toUpperCase())}</td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef"><span style="display:inline-block;padding:4px 8px;border-radius:999px;background:#fff0f2;color:#c52a42;font-weight:700;text-transform:capitalize">${esc(status)}</span>${reason ? `<br><strong style="display:inline-block;margin-top:6px;color:#263649;text-transform:capitalize">${esc(reason)}</strong>` : ""}<br><span style="display:inline-block;margin-top:3px;color:#4b5868">${esc(row.status_comment || "No latest comment")}</span></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${esc(dateLabel(row.non_operational_since))}</td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;text-align:center"><strong style="display:inline-block;padding:5px 9px;border-radius:999px;background:#fff0f2;color:#c52a42">${downDays == null ? "Start date required" : `${downDays} day${downDays === 1 ? "" : "s"}`}</strong></td><td style="padding:12px 10px;border-bottom:1px solid #e7ebef;color:#4b5868">${expected}</td></tr>`;
  }).join("");
  return `<div style="overflow-x:auto;border:1px solid #dfe4e8;border-radius:14px;background:#fff"><table role="presentation" style="border-collapse:collapse;width:100%;min-width:820px;font:12px Arial,sans-serif"><thead><tr style="background:#fff3e8;color:#8c4b11">${["Vehicle", "Station", "Source", "Issue and status", "Down since", "Days down", "Expected back"].map((value) => `<th style="padding:10px;text-align:left;border-bottom:1px solid #f0d8c4">${value}</th>`).join("")}</tr></thead><tbody>${body}</tbody></table></div>`;
}

function kpi(label: string, value: number, color: string, background: string) {
  return `<td class="kpi" width="20%" style="padding:5px"><div style="padding:14px 12px;border-radius:12px;background:${background};border:1px solid ${color}22"><div style="font:700 10px Arial,sans-serif;letter-spacing:.7px;text-transform:uppercase;color:#667085">${esc(label)}</div><div style="margin-top:5px;font:900 24px Arial,sans-serif;color:${color}">${value}</div></div></td>`;
}

export function buildFleetDailyStatusEmail(input: { companyName?: string | null; date: string; rows: FleetDailyStatusSummary[]; exceptions: FleetDailyStatusVehicle[]; adHocRows?: FleetDailyStatusAdHocSummary[]; totals?: FleetDailyStatusTotals; config?: Partial<FleetDailyStatusEmailConfig> | null }) {
  const config = normalizeFleetDailyStatusEmailConfig(input.config);
  const adHocRows = input.adHocRows ?? [];
  const adHocCount = (station: string) => adHocRows.filter((row) => row.station === station).reduce((sum, row) => sum + row.todayCount, 0);
  const rows = [...input.rows].sort((a, b) => b.totalNonOperational - a.totalNonOperational || adHocCount(b.station) - adHocCount(a.station) || a.station.localeCompare(b.station));
  const exceptions = [...input.exceptions].sort((a, b) => (a.non_operational_since || input.date).localeCompare(b.non_operational_since || input.date));
  const total = (key: keyof Omit<FleetDailyStatusSummary, "station">) => rows.reduce((sum, row) => sum + row[key], 0);
  const totalVehicles = input.totals?.totalVehicles ?? total("ownTotal") + total("partnerTotal");
  const operational = input.totals?.operational ?? total("ownOperational") + total("partnerOperational");
  const nonOperational = input.totals?.nonOperational ?? total("totalNonOperational");
  const adHoc = input.totals?.adHoc ?? (adHocRows.reduce((sum,row)=>sum+row.todayCount,0) || total("adHocVans"));
  const stationCount = input.totals?.stationCount ?? rows.length;
  const reportDate = dateLabel(input.date);
  const kpis = config.includeSummary ? `<tr><td class="pad" style="padding:8px 19px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr>${kpi("Vehicles", totalVehicles, config.primaryColor, "#f4f6f8")}${kpi("Operational", operational, "#167a57", "#effaf5")}${kpi("Non-operational", nonOperational, config.alertColor, "#fff1f3")}${config.includeAdHoc ? kpi("Ad hoc usage", adHoc, "#b36b00", "#fff8e6") : ""}${kpi("Stations", stationCount, "#3265a8", "#eff5ff")}</tr></table></td></tr>` : "";
  const stationSection = config.includeStationTable ? `<tr><td class="pad" style="padding:8px 24px 22px"><div style="margin-bottom:4px;font:900 16px Arial,sans-serif;color:${config.primaryColor}">1. Daily station status</div>${config.includeAdHoc ? `<div style="margin-bottom:10px;font:12px Arial,sans-serif;color:#667085">Ad hoc cells show approved Van (V) and Driver (D) count · amount. Stations without today’s ad hoc usage show a dash.</div>` : ""}${fleetTable(rows, adHocRows, config.includeAdHoc)}</td></tr>` : "";
  const exceptionSection = config.includeNonOperationalTable ? `<tr><td class="pad" style="padding:0 24px 22px"><div style="margin-bottom:4px;font:900 16px Arial,sans-serif;color:${config.primaryColor}">${config.includeStationTable ? "2" : "1"}. Non-operational vehicle actions</div><div style="margin-bottom:10px;font:12px Arial,sans-serif;color:#667085">Days down are calculated from the recorded non-operational date. Overdue expected returns require an update.</div>${exceptionTable(exceptions, input.date)}</td></tr>` : "";
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media(max-width:680px){.shell{width:100%!important}.pad{padding:16px!important}.kpi{display:inline-block!important;width:45%!important}}</style></head><body style="margin:0;background:#f2f5f6;color:#202633"><div style="display:none;max-height:0;overflow:hidden">${esc(reportDate)}: ${totalVehicles} vehicles, ${nonOperational} non-operational${config.includeAdHoc ? ` and ${adHoc} approved ad hoc requests` : ""}.</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background:#f2f5f6"><tr><td align="center" style="padding:24px 10px"><table class="shell" role="presentation" width="920" cellspacing="0" cellpadding="0" style="width:920px;max-width:100%;background:#fff;border-radius:18px;overflow:hidden;box-shadow:0 8px 30px #111a2f12"><tr><td class="pad" style="padding:24px 28px;background:${config.primaryColor};border-left:7px solid ${config.accentColor}"><table role="presentation" width="100%"><tr><td><div style="font:900 22px Arial,sans-serif;color:#fff"><span style="display:inline-block;width:28px;height:28px;line-height:28px;text-align:center;border-radius:9px;background:${config.accentColor};margin-right:8px">F</span>${esc(config.title)}</div><div style="margin-top:7px;font:700 11px Arial,sans-serif;letter-spacing:1.4px;color:#f5c04f">${esc(config.headerLabel).toUpperCase()}</div></td><td align="right" style="font:700 13px Arial,sans-serif;color:#fff"><div>${esc(reportDate)}</div><div style="margin-top:5px;color:#c7d1e2;font-weight:400">${esc(input.companyName || "DropX Logistics")}</div></td></tr></table></td></tr><tr><td class="pad" style="padding:22px 24px 8px"><div style="font:900 24px Arial,sans-serif;color:${config.primaryColor}">Today’s fleet position</div><div style="margin-top:6px;font:13px Arial,sans-serif;color:#667085">${esc(config.intro)}</div></td></tr>${kpis}${stationSection}${exceptionSection}<tr><td align="center" style="padding:8px 24px 28px"><div style="font:11px Arial,sans-serif;color:#8a94a3">${esc(config.footer)}</div></td></tr></table></td></tr></table></body></html>`;
  const text = [`${config.title} - ${reportDate}`, `${totalVehicles} vehicles | ${operational} operational | ${nonOperational} non-operational${config.includeAdHoc ? ` | ${adHoc} approved ad hoc Van/Driver usages` : ""}`, `${stationCount} stations`, config.footer].join("\n");
  return { html, text };
}
