import test from "node:test";
import assert from "node:assert/strict";
import ts from "typescript";
import {readFileSync} from "node:fs";
function compile(file,mocks={}){const m={exports:{}};new Function("require","module","exports",ts.transpileModule(readFileSync(new URL(file,import.meta.url),"utf8"),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(name=>{if(name in mocks)return mocks[name];throw Error(name);},m,m.exports);return m.exports;}
const {mapAdvertising,advertisingCosts}=compile("./advertising.ts");
const row=(date="2026-09-01",spend=100)=>({account_id:"act_123",spend_date:date,ad_id:"99",ad_name:"Hire DA",campaign_name:"Recruit",spend,currency:"INR",synced_at:"2026-10-01T00:00:00Z"});
test("one ad/day is mapped once; paused/duplicate ads do not multiply spend",()=>{const rows=mapAdvertising([row()],[],[{meta_ad_id:"99",station_code:"A"},{meta_ad_id:"99",station_code:"A"}]);assert.equal(rows.length,1);assert.equal(rows[0].station_code,"A");assert.equal(rows[0].spend,100);});
test("ambiguous mappings remain unresolved; explicit monthly overrides preserve other months",()=>{const ads=[{meta_ad_id:"99",station_code:"A"},{meta_ad_id:"99",station_code:"B"}];const map=[{ad_id:"99",station_code:"C",effective_from:"2026-09-01",effective_to:"2026-09-30"}];const rows=mapAdvertising([row(),row("2026-10-01")],map,ads);assert.equal(rows[0].station_code,"C");assert.equal(rows[1].station_code,"");});
test("cost rows honor date and station scope, use actual daily costs, and flag missing sync",()=>{const costs=advertisingCosts({rows:[{...row(),station_code:"A"},{...row("2026-09-02",50),station_code:"A"},{...row(),station_code:"B"}],months:[{month:"2026-09-01",through_date:"2026-09-01",synced_at:"2026-10-01",last_error:null}],codes:["A"],from:"2026-09-01",to:"2026-09-02",start:"2026-03-01",label:"Acquisition",enabled:true,refreshMinutes:60,now:Date.parse("2026-10-01")});assert.equal(costs.breakup.reduce((n,r)=>n+r.amount,0),150);assert.equal(costs.breakup[1].amount,50);assert.equal(costs.breakup[0].sub_head,"Acquisition");assert.equal(costs.gaps.length,1);assert.equal(costs.gaps[0].first_date,"2026-09-02");});
test("success with zero spend is zero, never confused with missing data",()=>{const costs=advertisingCosts({rows:[],months:[{month:"2026-09-01",through_date:"2026-09-30",synced_at:"2026-10-01",last_error:null}],codes:["A"],from:"2026-09-01",to:"2026-09-30",start:"2026-03-01",label:"Meta",enabled:true,refreshMinutes:60,now:Date.parse("2026-10-01")});assert.deepEqual(costs.breakup,[]);assert.deepEqual(costs.gaps,[]);});
const sync=compile("./advertising-sync.ts",{"server-only":{},"@/lib/supabase-admin":{},"./cps":{},"./cod":{}});
const info={currency:"INR",timezone_name:"Asia/Kolkata"};
const insight={ad_id:"99",date_start:"2026-09-01",date_stop:"2026-09-01",spend:"100.12",account_currency:"INR"};
const params={token:"secret",account:"act_123",version:"v25.0",from:"2026-09-01",to:"2026-09-30"};
test("Meta pagination uses daily grain, auth header and all pages without following arbitrary URLs",async()=>{const requests=[];global.fetch=async(url,opts)=>{requests.push([url,opts]);const n=requests.length;return Response.json(n===1?info:n===2?{data:[insight],paging:{next:"https://untrusted.test",cursors:{after:"next-page"}}}:{data:[{...insight,date_start:"2026-09-02",date_stop:"2026-09-02",spend:"20.05"}]});};const rows=await sync.fetchDailyMetaSpend(params);assert.equal(rows.length,2);assert.equal(rows.reduce((n,r)=>n+r.spend,0),120.17);assert.ok(requests[1][0].includes("time_increment=1"));assert.ok(requests.every(([u,o])=>u.startsWith("https://graph.facebook.com/")&&!u.includes("secret")&&o.headers.Authorization==="Bearer secret"));assert.ok(requests[2][0].includes("after=next-page"));});
test("partial pagination, duplicate grain and non-INR data fail before persistence",async()=>{for(const payload of [{data:[insight],paging:{next:"yes"}},{data:[insight,insight]},{data:[{...insight,account_currency:"USD"}]}]){let n=0;global.fetch=async()=>Response.json(++n===1?info:payload);await assert.rejects(sync.fetchDailyMetaSpend(params));}});

test("confirmed Meta cashbook payments are excluded once, with other expenses and history preserved",()=>{const {excludeAdvertisingSettlements}=compile("./advertising.ts");const line={station_code:"A",work_date:"2026-09-01",head:"Other",sub_head:"Advertising Charges",source:"Cashbook",amount:325};const base={daily:[],generated_at:"",breakup:[line,{...line,sub_head:"Local posters"},{...line,work_date:"2026-06-01"}],expense_periods:[]};const rules=[{source:"Cashbook",cost_label:"Advertising Charges",effective_from:"2026-07-01",is_active:true}];assert.equal(excludeAdvertisingSettlements(base,rules).breakup.length,2);assert.equal(base.breakup.length,3);assert.equal(excludeAdvertisingSettlements(base,[{...rules[0],is_active:false}]).breakup.length,3);});

test("current Recruit routing overrides stale legacy locations; unresolved current ads cannot inherit a stale location",async()=>{
 const tables={recruitment_ads:[{meta_ad_id:"1",location_id:"rA",ad_name:"Current"},{meta_ad_id:"2",location_id:null}],lead_ads:[{meta_ad_id:"1",station_code:"OLD"},{meta_ad_id:"2",station_code:"OLD"},{meta_ad_id:"3",station_code:"B"}],recruitment_locations:[{id:"rA",station_id:"sA",code:"OLD"}],stations:[{id:"sA",station_code:"A"},{id:"sB",station_code:"B"}]};
 const db={from(name){const query={select(){return query},eq(k,v){assert.equal(k,"company_id");assert.equal(v,"company");return query},order(){return query},then(fn){return Promise.resolve(fn({data:tables[name],error:null}));}};return query;}};
 const data=compile("./advertising-data.ts",{"server-only":{},"@/lib/supabase-admin":{supabaseAdmin:db},"@/lib/supabase-pagination":{readAllRows:async q=>await q},"./advertising":{}});
 const result=await data.loadAdvertisingAdMappings("company");assert.equal(result.data.find(a=>a.meta_ad_id==="1").station_code,"A");assert.equal(result.data.find(a=>a.meta_ad_id==="2").station_code,null);assert.equal(result.data.find(a=>a.meta_ad_id==="3").station_code,"B");
});
