-- Initial agreed values are editable master data; no rates are embedded in application code.
insert into finance_business_master(company_id,kind,key,label,data)
select c.id,'now_rate',v.key,v.label,v.data::jsonb from companies c cross join (values
('ufc.chennai.2026-10','UFC · Chennai','{"category": "UFC", "city": "Chennai", "monthly_mg": "977413", "monthly_incentive": "40875", "mg_upd": 2700, "slabs": [{"above": 2700, "upto": 4950, "base": "1.9", "incentive": "0.5"}, {"above": 4950, "upto": 8100, "base": "1.8", "incentive": "0.5"}, {"above": 8100, "upto": 12600, "base": "1.7", "incentive": "0.5"}, {"above": 12600, "upto": 18000, "base": "1.6", "incentive": "0.5"}, {"above": 22500, "upto": null, "base": "1.6", "incentive": "0.5"}], "slab_mode": "progressive", "effective_from": "2026-10-01", "effective_to": null, "source": "UFC_RateCard_DROPX_LOGISTICS.pdf; progressive excess confirmed by user"}'),
('ufc.hyderabad.2026-10','UFC · Hyderabad','{"category": "UFC", "city": "Hyderabad", "monthly_mg": "1091668", "monthly_incentive": "40875", "mg_upd": 2700, "slabs": [{"above": 2700, "upto": 4950, "base": "2.1", "incentive": "0.7"}, {"above": 4950, "upto": 8100, "base": "2", "incentive": "0.7"}, {"above": 8100, "upto": 12600, "base": "1.9", "incentive": "0.7"}, {"above": 12600, "upto": 18000, "base": "1.8", "incentive": "0.7"}, {"above": 22500, "upto": null, "base": "1.7", "incentive": "0.7"}], "slab_mode": "progressive", "effective_from": "2026-10-01", "effective_to": null, "source": "UFC_RateCard_DROPX_LOGISTICS.pdf; progressive excess confirmed by user"}'),
('mfc.chennai.2026-10','MFC · Chennai','{"category": "MFC", "city": "Chennai", "monthly_mg": "675194", "monthly_incentive": "32700", "mg_upd": 2500, "slabs": [{"above": 2500, "upto": 4500, "base": "1.7", "incentive": "0.5"}, {"above": 4500, "upto": 7500, "base": "1.6", "incentive": "0.5"}, {"above": 7500, "upto": 12500, "base": "1.5", "incentive": "0.5"}, {"above": 12500, "upto": 18000, "base": "1.4", "incentive": "0.5"}, {"above": 18000, "upto": null, "base": "1.3", "incentive": "0.5"}], "slab_mode": "progressive", "effective_from": "2026-10-01", "effective_to": null, "source": "MFC_RateCard_DROPX_LOGISTICS.pdf; progressive excess confirmed by user"}'),
('mfc.hyderabad.2026-10','MFC · Hyderabad','{"category": "MFC", "city": "Hyderabad", "monthly_mg": "732401", "monthly_incentive": "32700", "mg_upd": 2500, "slabs": [{"above": 2500, "upto": 4500, "base": "1.9", "incentive": "0.6"}, {"above": 4500, "upto": 7500, "base": "1.8", "incentive": "0.6"}, {"above": 7500, "upto": 12500, "base": "1.7", "incentive": "0.6"}, {"above": 12500, "upto": 18000, "base": "1.6", "incentive": "0.6"}, {"above": 18000, "upto": null, "base": "1.5", "incentive": "0.6"}], "slab_mode": "progressive", "effective_from": "2026-10-01", "effective_to": null, "source": "MFC_RateCard_DROPX_LOGISTICS.pdf; progressive excess confirmed by user"}'),
('mfc.kanpur.2026-10','MFC · Kanpur','{"category": "MFC", "city": "Kanpur", "monthly_mg": "685794", "monthly_incentive": "32700", "mg_upd": 2500, "slabs": [{"above": 2500, "upto": 4500, "base": "1.8", "incentive": "0.5"}, {"above": 4500, "upto": 7500, "base": "1.7", "incentive": "0.5"}, {"above": 7500, "upto": 12500, "base": "1.6", "incentive": "0.5"}, {"above": 12500, "upto": 18000, "base": "1.5", "incentive": "0.5"}, {"above": 18000, "upto": null, "base": "1.4", "incentive": "0.5"}], "slab_mode": "progressive", "effective_from": "2026-10-01", "effective_to": null, "source": "MFC_RateCard_DROPX_LOGISTICS.pdf; progressive excess confirmed by user"}'))v(key,label,data) where c.name='DROPX LOGISTICS' on conflict(company_id,kind,key) do nothing;

insert into finance_business_master(company_id,kind,key,label,data)
select s.company_id,'now_store',lower(s.station_code)||'.2026-10',s.station_code||' · '||case when s.station_code in ('TCD4','TTG9') then 'UFC' else 'MFC' end,
jsonb_build_object('station_code',s.station_code,'category',case when s.station_code in ('TCD4','TTG9') then 'UFC' else 'MFC' end,'city',s.city,
'rate_key',case when s.station_code in ('TCD4','TTG9') then 'ufc' else 'mfc' end||'.'||lower(s.city)||'.2026-10','effective_from','2026-10-01','effective_to',null,'monthly_mg_override',null)
from stations s join companies c on c.id=s.company_id and c.name='DROPX LOGISTICS' join location_models m on m.id=s.location_model_id and upper(m.code)='NOW'
where s.is_active and s.city in ('Chennai','Hyderabad','Kanpur') on conflict(company_id,kind,key) do nothing;
insert into finance_business_master(company_id,kind,key,label,data)
select c.id,'cost_head',v.key,v.label,jsonb_build_object('description',v.label||' outsourced service') from companies c cross join(values('security','Security guards'),('housekeeping','Housekeeping'),('pest-control','Pest control'))v(key,label)
where c.name='DROPX LOGISTICS' on conflict(company_id,kind,key)do nothing;
insert into finance_business_master(company_id,kind,key,label,data)
select h.company_id,'overhead',lower(h.station_code)||'.2026-10',h.station_code||' allocation',jsonb_build_object('station_code',h.station_code,'mode',case when h.station_code in ('HO_CLT','HO_MJR') then 'corporate' else 'regional' end,'effective_from','2026-10-01','effective_to',null,'recipient_codes',case when h.station_code in ('HO_CLT','HO_MJR') then '[]'::jsonb else coalesce((select jsonb_agg(s.station_code order by s.station_code)from stations s join location_models m on m.id=s.location_model_id where s.company_id=h.company_id and s.is_active and not s.is_ho and not coalesce(s.hide_from_location_list,false) and s.state=h.state and (h.station_code not in ('HO_TN','HO_TS','HO_UP') or upper(m.code)='NOW')),'[]'::jsonb)end)
from stations h join companies c on c.id=h.company_id and c.name='DROPX LOGISTICS' where h.is_ho and h.is_active
on conflict(company_id,kind,key)do nothing;
