-- Make the Fleet daily status email content, audience and presentation configurable.

alter table public.fleet_control_settings
  add column if not exists daily_status_email_config jsonb not null default jsonb_build_object(
    'title', 'DropX Daily Fleet Update',
    'subjectPrefix', 'DropX Daily Fleet Update',
    'headerLabel', 'Availability · Exceptions · Ad Hoc Support',
    'intro', 'Stations requiring attention are ranked first. Red values need an availability update.',
    'footer', 'Generated by DropX Fleet. Approved ad hoc van usage only.',
    'primaryColor', '#111a2f',
    'accentColor', '#d92d67',
    'alertColor', '#c52a42',
    'includeSummary', true,
    'includeStationTable', true,
    'includeNonOperationalTable', true,
    'includeAdHoc', true,
    'includeMappedOperations', true,
    'includeAllLocationOperations', true,
    'includeStationMailboxes', true,
    'monthlyThread', true,
    'excludeAmazonNow', true,
    'excludedStationCodes', jsonb_build_array()
  );

comment on column public.fleet_control_settings.daily_status_email_config is
  'Editable Fleet daily email copy, colors, sections, audience sources, exclusions and thread mode.';
