alter table public.fleet_audit_checklist_items add column if not exists response_config jsonb;
alter table public.fleet_audits add column if not exists draft jsonb not null default '{}'::jsonb;
alter table public.fleet_audit_findings add column if not exists checklist_item_id uuid references public.fleet_audit_checklist_items(id);
alter table public.fleet_audit_findings add column if not exists resolution_note text;
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"good","label":"Good","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"average","label":"Average","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"poor","label":"Poor","issue":true,"severity":"high","followUp":"planned","photos":1,"remarks":true,"days":7},{"value":"needs_immediate_replacement","label":"Needs immediate replacement","issue":true,"severity":"critical","followUp":"immediate","photos":1,"remarks":true,"days":7},{"value":"unable_to_inspect","label":"Unable to inspect","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (category='Tyres');
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"available_and_valid","label":"Available and valid","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"expired","label":"Expired","issue":true,"severity":"high","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"missing","label":"Missing","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unable_to_verify","label":"Unable to verify","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (category='Documents');
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"normal","label":"Normal","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"concern_noticed","label":"Concern noticed","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unsafe_inspection_required","label":"Unsafe — inspection required","issue":true,"severity":"critical","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"not_tested","label":"Not tested","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (label in ('Brakes and parking brake respond correctly','No fluid leak, abnormal noise or dashboard warning'));
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"working","label":"Working","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"partly_working","label":"Partly working","issue":true,"severity":"medium","followUp":"planned","photos":1,"remarks":true,"days":7},{"value":"not_working","label":"Not working","issue":true,"severity":"high","followUp":"immediate","photos":1,"remarks":true,"days":7},{"value":"not_tested","label":"Not tested","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (label in ('Lights and indicators work','Horn and both mirrors work'));
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"good","label":"Good","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"average","label":"Average","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"poor","label":"Poor","issue":true,"severity":"high","followUp":"planned","photos":1,"remarks":true,"days":7},{"value":"needs_immediate_replacement","label":"Needs immediate replacement","issue":true,"severity":"critical","followUp":"immediate","photos":1,"remarks":true,"days":7},{"value":"unable_to_inspect","label":"Unable to inspect","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (category in ('Condition','Battery'));
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"satisfactory","label":"Satisfactory","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"coaching_needed","label":"Coaching needed","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unsafe_behaviour_observed","label":"Unsafe behaviour observed","issue":true,"severity":"critical","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"not_observed","label":"Not observed","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (category='Driver & driving' and response_type in ('pass_fail','yes_no'));
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"available_and_valid","label":"Available and valid","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"expired","label":"Expired","issue":true,"severity":"high","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"missing","label":"Missing","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unable_to_verify","label":"Unable to verify","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and response_config is null and (label='Is the driving licence available and valid?');
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"available_and_valid","label":"Available and valid","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"expired","label":"Expired","issue":true,"severity":"high","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"missing","label":"Missing","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unable_to_verify","label":"Unable to verify","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Is the driving licence available and valid?';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{documentType}','"FLEET_REGISTRATION"'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='RC copy is available and valid';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{documentType}','"FLEET_INSURANCE"'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Insurance is valid and expiry date is recorded';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{documentType}','"FLEET_PUC"'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='PUC is valid and expiry date is recorded';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{documentType}','"FLEET_FITNESS"'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Fitness and permit are valid';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{documentType}','"FLEET_TAX"'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Road tax is valid';
update public.fleet_audit_checklist_items set response_config=jsonb_set(response_config,'{fuels}','["Diesel","Petrol","CNG"]'::jsonb) where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='PUC is valid and expiry date is recorded';
update public.fleet_audit_checklist_items set is_active=false,updated_at=now() where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label in ('Service book is available and updated','Vehicle inspection photo set','Walk-around audit video','Additional findings and required action','Recent speeding, harsh braking, accident or traffic violation observations');
insert into public.fleet_audit_checklist_items(company_id,template_id,category,label,guidance,audit_mode,sort_order,response_type,response_config,is_required) select t.company_id,t.id,'Safety','Steering response','Check steering response during a safe physical inspection. Record any play, pull or unusual noise.','physical',175,'text','{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"normal","label":"Normal","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"concern_noticed","label":"Concern noticed","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"unsafe_inspection_required","label":"Unsafe — inspection required","issue":true,"severity":"critical","followUp":"immediate","photos":0,"remarks":true,"days":7},{"value":"not_tested","label":"Not tested","issue":true,"severity":"high","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,true from public.fleet_audit_templates t where t.company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and t.is_default and t.is_active and not exists(select 1 from public.fleet_audit_checklist_items i where i.template_id=t.id and i.label='Steering response');
insert into public.fleet_audit_checklist_items(company_id,template_id,category,label,guidance,audit_mode,sort_order,response_type,response_config,is_required) select t.company_id,t.id,'Safety','Wipers and windscreen visibility','Check clear visibility and wiper operation.','both',185,'text','{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"working","label":"Working","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"partly_working","label":"Partly working","issue":true,"severity":"medium","followUp":"planned","photos":1,"remarks":true,"days":7},{"value":"not_working","label":"Not working","issue":true,"severity":"high","followUp":"immediate","photos":1,"remarks":true,"days":7},{"value":"not_tested","label":"Not tested","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,true from public.fleet_audit_templates t where t.company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and t.is_default and t.is_active and not exists(select 1 from public.fleet_audit_checklist_items i where i.template_id=t.id and i.label='Wipers and windscreen visibility');
insert into public.fleet_audit_checklist_items(company_id,template_id,category,label,guidance,audit_mode,sort_order,response_type,response_config,is_required) select t.company_id,t.id,'EV readiness','Charging port, cable and dashboard warnings','Inspect visible condition only. Do not open high-voltage components.','both',155,'text','{"kind":"choice","fuels":["EV"],"documentType":"","unit":"","options":[{"value":"good","label":"Good","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"average","label":"Average","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"poor","label":"Poor","issue":true,"severity":"high","followUp":"planned","photos":1,"remarks":true,"days":7},{"value":"needs_immediate_replacement","label":"Needs immediate replacement","issue":true,"severity":"critical","followUp":"immediate","photos":1,"remarks":true,"days":7},{"value":"unable_to_inspect","label":"Unable to inspect","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7}]}'::jsonb,true from public.fleet_audit_templates t where t.company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and t.is_default and t.is_active and not exists(select 1 from public.fleet_audit_checklist_items i where i.template_id=t.id and i.label='Charging port, cable and dashboard warnings');
insert into public.fleet_audit_checklist_items(company_id,template_id,category,label,guidance,audit_mode,sort_order,response_type,response_config,is_required) select t.company_id,t.id,'Delivery readiness','Readiness for the next delivery route','Consider open defects and the inspection results before recording readiness.','both',400,'text','{"kind":"choice","fuels":[],"documentType":"","unit":"","options":[{"value":"ready","label":"Ready","issue":false,"severity":"medium","followUp":"none","photos":0,"remarks":false,"days":7},{"value":"ready_with_follow_up","label":"Ready with follow-up","issue":true,"severity":"medium","followUp":"planned","photos":0,"remarks":true,"days":7},{"value":"not_ready_for_delivery","label":"Not ready for delivery","issue":true,"severity":"critical","followUp":"immediate","photos":0,"remarks":true,"days":7}]}'::jsonb,true from public.fleet_audit_templates t where t.company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and t.is_default and t.is_active and not exists(select 1 from public.fleet_audit_checklist_items i where i.template_id=t.id and i.label='Readiness for the next delivery route');
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","options":[{"value":"matches","label":"Matches","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"does_not_match","label":"Does not match","issue":true,"followUp":"immediate","severity":"high","photos":1,"remarks":true,"days":7},{"value":"plate_unreadable","label":"Plate unreadable","issue":true,"followUp":"planned","severity":"high","photos":1,"remarks":true,"days":7}],"fuels":[],"unit":"","documentType":""}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Registration number matches the vehicle and master';
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","options":[{"value":"present_and_usable","label":"Present and usable","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"needs_repair","label":"Needs repair","issue":true,"followUp":"planned","severity":"medium","photos":1,"remarks":true,"days":7},{"value":"missing","label":"Missing","issue":true,"followUp":"planned","severity":"high","photos":0,"remarks":true,"days":7}],"fuels":[],"unit":"","documentType":""}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Spare tyre is present and serviceable';
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","options":[{"value":"complete","label":"Complete","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"items_missing","label":"Items missing","issue":true,"followUp":"planned","severity":"medium","photos":1,"remarks":true,"days":7},{"value":"not_available","label":"Not available","issue":true,"followUp":"planned","severity":"high","photos":0,"remarks":true,"days":7}],"fuels":[],"unit":"","documentType":""}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='First-aid kit and warning equipment are present';
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","options":[{"value":"service_up_to_date","label":"Service up to date","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"service_booked","label":"Service booked","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"service_overdue","label":"Service overdue","issue":true,"followUp":"planned","severity":"high","photos":0,"remarks":true,"days":7},{"value":"service_record_missing","label":"Service record missing","issue":true,"followUp":"planned","severity":"medium","photos":0,"remarks":true,"days":7}],"fuels":[],"unit":"","documentType":""}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Next service due date or odometer is recorded';
update public.fleet_audit_checklist_items set response_config='{"kind":"choice","options":[{"value":"starts_normally","label":"Starts normally","issue":false,"followUp":"none","severity":"medium","photos":0,"remarks":false,"days":7},{"value":"slow_starting","label":"Slow starting","issue":true,"followUp":"planned","severity":"medium","photos":0,"remarks":true,"days":7},{"value":"fails_to_start","label":"Fails to start","issue":true,"followUp":"immediate","severity":"high","photos":0,"remarks":true,"days":7}],"fuels":["Diesel","Petrol","CNG"],"unit":"","documentType":""}'::jsonb where company_id='43866344-b550-4e8a-9a2d-9d23f3d8a997' and label='Battery is properly charged';
-- Only the authenticated server action can call this function; all records are scoped
-- and validated in that action. Row lock makes repeated/concurrent submission atomic.
create or replace function public.fleet_complete_audit_v2(p_company uuid,p_audit uuid,p_user uuid,p_data jsonb)
returns void language plpgsql security invoker set search_path = public as $$
declare a public.fleet_audits; r jsonb;
begin
 select * into a from public.fleet_audits where id=p_audit and company_id=p_company for update;
 if not found or a.status not in ('scheduled','in_progress') then raise exception 'Only an open audit can be completed'; end if;
 for r in select * from jsonb_array_elements(p_data->'responses') loop
  insert into public.fleet_audit_responses(company_id,audit_id,checklist_item_id,response_value,passed,comments,responded_by)
  values(p_company,p_audit,(r->>'itemId')::uuid,r->'snapshot',(r->>'passed')::boolean,r->>'comments',p_user)
  on conflict(audit_id,checklist_item_id) do update set response_value=excluded.response_value,passed=excluded.passed,comments=excluded.comments,responded_by=p_user,responded_at=now();
 end loop;
 for r in select * from jsonb_array_elements(p_data->'evidence') loop
  insert into public.fleet_audit_evidence(company_id,audit_id,checklist_item_id,media_type,media_url,caption,uploaded_by)
  values(p_company,p_audit,nullif(r->>'itemId','')::uuid,r->>'type',r->>'url',r->>'caption',p_user);
 end loop;
 for r in select * from jsonb_array_elements(p_data->'findings') loop
  insert into public.fleet_audit_findings(company_id,audit_id,checklist_item_id,category,finding,severity,action_required,expected_completion_date,owner_user_id)
  values(p_company,p_audit,nullif(r->>'itemId','')::uuid,r->>'category',r->>'finding',r->>'severity',r->>'actionRequired',nullif(r->>'expectedCompletionDate','')::date,p_user);
 end loop;
 update public.fleet_audits set status=p_data->>'status',score=(p_data->>'score')::numeric,summary=p_data->>'summary',odometer_km=(p_data->>'odometerKm')::numeric,completed_at=now(),completed_by=p_user,updated_at=now(),draft='{}',email_status='not_sent' where id=p_audit and company_id=p_company;
end $$;
revoke all on function public.fleet_complete_audit_v2(uuid,uuid,uuid,jsonb) from public,anon,authenticated;
grant execute on function public.fleet_complete_audit_v2(uuid,uuid,uuid,jsonb) to service_role;
