-- The daily Fleet email now consolidates approved Van and Driver usage.
-- Only replace the previous seeded wording; preserve any custom footer.
update public.fleet_control_settings
set daily_status_email_config = jsonb_set(
      coalesce(daily_status_email_config, '{}'::jsonb),
      '{footer}',
      to_jsonb('Generated by DropX Fleet. Ad hoc figures include approved Van and Driver usage.'::text),
      true
    ),
    updated_at = now()
where daily_status_email_config->>'footer' = 'Generated by DropX Fleet. Approved ad hoc van usage only.';
