"use client";
import { useEffect,useState } from "react";
import { AdvertisingBreakdown } from "@/components/advertising-breakdown";
import type { AdvertisingDetail,AdvertisingMapping,AdvertisingMonth } from "@/lib/ops-pulse/advertising";
type Data={settlements:{id:string;source:string;cost_label:string;effective_from:string;is_active:boolean}[];settings:{start_date:string;refresh_minutes:number;cost_label:string;is_enabled:boolean}|null;history:AdvertisingMonth[];rows:AdvertisingDetail[];ads:{meta_ad_id:string;ad_name:string;station_code:string}[];mappings:AdvertisingMapping[];stations:{code:string;name:string}[];canEdit:boolean;canConfigure:boolean};
export function AdvertisingMaster(){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7)),[data,setData]=useState<Data|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const response=await fetch(`/api/ops-pulse/advertising?month=${month}`);const result=await response.json();if(!response.ok)throw Error(result.error);setData(result);}
 useEffect(()=>{let alive=true;setData(null);fetch(`/api/ops-pulse/advertising?month=${month}`).then(async r=>{const p=await r.json();if(!r.ok)throw Error(p.error);if(alive)setData(p);}).catch(e=>{if(alive)setMessage(e.message);});return()=>{alive=false;};},[month]);
 async function save(payload:Record<string,unknown>){setBusy(true);setMessage("");try{const r=await fetch("/api/ops-pulse/advertising",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const p=await r.json();if(!r.ok)throw Error(p.error);setMessage(p.message);await load();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false);}}
 const box={background:"white",border:"1px solid #e2e8f0",borderRadius:14,padding:20,marginBlock:16};
 const unmapped=data?.rows.filter(r=>!r.station_code).reduce((s,r)=>s+r.spend,0)??0;
 const history=data?.history.find(h=>h.month===month+"-01");
 const ads=new Map((data?.ads??[]).map(a=>[a.meta_ad_id,{id:a.meta_ad_id,name:a.ad_name}]));
 for(const row of data?.rows??[])ads.set(row.ad_id,{id:row.ad_id,name:row.ad_name});
 return <div style={{maxWidth:1400,margin:"auto"}}>{message&&<p role="status" style={box}>{message}</p>}<section style={box}><div style={{display:"flex",gap:12,flexWrap:"wrap",alignItems:"center"}}><label>Spend month <input type="month" disabled={busy} value={month} max={new Date().toISOString().slice(0,7)} onChange={e=>setMonth(e.target.value)}/></label>{data?.canConfigure&&<button className="button primary" disabled={busy} onClick={()=>save({action:"sync",month})}>{busy?"Refreshing…":"Refresh Meta spend"}</button>}<a href="https://recruit.dropxlogistics.com/">Recruit ad mappings ↗</a></div><p>Checks every 30 minutes use the refresh interval below. Recent months and older history are refreshed automatically. Paused ads retain their historical costs. Mapping overrides apply only to the chosen month.</p><p>Through: {history?.through_date??"Not synced"} · Last successful refresh: {history?.synced_at?new Date(history.synced_at).toLocaleString("en-IN"):"Never"}</p>{history?.last_error&&<p role="alert">{history.last_error}</p>}{unmapped>0&&<p role="alert">₹{unmapped.toLocaleString("en-IN")} has no unique station mapping. It is retained here and excluded from station CPS/P&L until mapped.</p>}</section>
 {data?.canConfigure&&<details style={box}><summary>Sync settings</summary><form key={JSON.stringify(data.settings)} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);save({action:"settings",start_date:form.get("start")+"-01",refresh_minutes:Number(form.get("minutes")),cost_label:form.get("label"),is_enabled:form.get("enabled")==="on"});}} style={{display:"flex",gap:14,flexWrap:"wrap",marginTop:16}}><label>History starts <input name="start" type="month" required defaultValue={data.settings?.start_date.slice(0,7)??month}/></label><label>Refresh minutes <input name="minutes" type="number" min={30} max={1440} required defaultValue={data.settings?.refresh_minutes??60}/></label><label>Cost label <input name="label" required maxLength={120} defaultValue={data.settings?.cost_label??"Meta advertising"}/></label><label><input name="enabled" type="checkbox" defaultChecked={data.settings?.is_enabled??true}/> Automatic sync enabled</label><button disabled={busy}>Save settings</button></form></details>}
 {data?.canConfigure&&<details style={box}><summary>Meta payment settlements — prevent double counting</summary><p>These source entries pay for Meta spend already included above. They stay in Cashbook / payments but are excluded from CPS and P&amp;L. Other local advertising remains an expense.</p><ul>{data.settlements.map(r=><li key={r.id}>{r.source}: {r.cost_label} · from {r.effective_from} · {r.is_active?"Excluded as Meta settlement":"Included as separate expense"} <button disabled={busy} onClick={()=>save({action:"settlement",...r,is_active:!r.is_active})}>{r.is_active?"Disable exclusion":"Enable exclusion"}</button></li>)}</ul><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:"settlement",source:f.get("source"),cost_label:f.get("label"),effective_from:f.get("start")+"-01",is_active:true});}} style={{display:"flex",gap:12,flexWrap:"wrap"}}><label>Source <select name="source"><option>Cashbook</option><option>Approved payment requests</option></select></label><label>Exact cost label <input required maxLength={120} name="label"/></label><label>From month <input required type="month" name="start" defaultValue={month}/></label><button disabled={busy}>Add settlement rule</button></form></details>}
 {data&&<section style={box}><AdvertisingBreakdown rows={data.rows}/></section>}
 {data?.canEdit&&<details style={box}><summary>Station mapping — add, edit or remove a monthly override</summary><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({action:f.get("action"),ad_id:f.get("ad_id"),station_code:f.get("station"),effective_from:month+"-01"});}} style={{display:"flex",gap:12,flexWrap:"wrap",marginTop:16}}><label>Ad <select required name="ad_id"><option value="">Select ad</option>{[...ads.values()].map(a=><option key={a.id} value={a.id}>{a.name} · {a.id}</option>)}</select></label><label>Station <select required name="station"><option value="">Select station</option>{data.canConfigure&&<option value="@corporate">Corporate / HO (not allocated to stations)</option>}{data.stations.map(s=><option key={s.code} value={s.code}>{s.code} · {s.name}</option>)}</select></label><label>Action <select name="action"><option value="mapping">Save override for {month}</option><option value="delete_mapping">Remove override; use Recruit mapping</option></select></label><button disabled={busy}>Apply mapping</button></form><p>Default station mapping comes from Recruit’s Ads master. Amounts always come from Meta. No station is inferred from an ad name.</p><ul>{data.mappings.filter(m=>m.effective_from===month+"-01").map(m=><li key={m.id}>{m.ad_id} → {m.station_code}</li>)}</ul></details>}
 </div>;
}
